### ISSUE TITLE
building Azurite on linux: npm ci getting repo1.uhc.com problem

### ISSUE THREAD

**Issue by zitro3** [Azure/Azurite#1014]
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension) I am new. I just git cloned and trying to build it.
npm = 7.21.0

### What's the Node.js version?
node=v16.7.0
### What problem was encountered?
npm ci <- returning error below
### Steps to reproduce the issue?
>npm ci

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated core-js@2.6.9: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code EBUSY
npm ERR! syscall getaddrinfo
npm ERR! errno EBUSY
npm ERR! request to https://repo1.uhc.com:443/artifactory/api/npm/npm-virtual/ts-mockito/-/ts-mockito-2.6.1.tgz failed, reason: getaddrinfo EBUSY repo1.uhc.com

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/testuser/.npm/_logs/2021-08-21T01_29_19_369Z-debug.log

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No. I like to participate but having problem on 1st step of the build process. I appreciate any guidelines.

**Comment by zitro3** [comment]
Kindly nevermind. I need to do below about ts-mockito.

> npm install ts-mockito --save-dev

**Comment by ninthspace** [comment]
This should be reopened because of this error, either when installing directly, or installing `ts-mockito` as suggested above.

`npm ERR! network request to https://repo1.uhc.com:443/artifactory/api/npm/npm-virtual/ts-mockito/-/ts-mockito-2.6.1.tgz failed, reason: getaddrinfo ENOTFOUND repo1.uhc.com`

**Comment by blueww** [comment]
@ninthspace 
I can't repro the issue.
I can run "npm install ts-mockito --save-dev" successfully on Linux machine.
And latest version is just 2.6.1 in https://www.npmjs.com/package/ts-mockito .

Would you please check if the issue still repro and the network on your machine?
If still not work, it looks should be npm problem instead of Azurite issue.

**Comment by zitro3** [comment]
I tried to git clone fresh copy of the main to my windows machine and got the same error. But doing the ts-mockito above and rerunning the npm ci again removes the problem.

C:\Users\20273\Desktop\VICE\Azurite>**npm ci**
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
...
...
npm WARN deprecated core-js@2.6.9: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm notice
npm notice New minor version of npm available! 7.20.6 -> 7.23.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.23.0
npm notice Run npm install -g npm@7.23.0 to update!
npm notice
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
**npm ERR! network request to https://repo1.uhc.com:443/artifactory/api/npm/npm-virtual/ts-mockito/-/ts-mockito-2.6.1.tgz failed, reason: getaddrinfo ENOTFOUND repo1.uhc.com**
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\20273\AppData\Local\npm-cache\_logs\2021-09-13T14_40_40_583Z-debug.log

C:\Users\20273\Desktop\VICE\Azurite>**npm install ts-mockito --save-dev**
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
....
....
npm WARN deprecated core-js@2.6.9: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 1017 packages, and audited 1018 packages in 40s

42 packages are looking for funding
  run `npm fund` for details

16 vulnerabilities (5 low, 6 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Users\20273\Desktop\VICE\Azurite>**npm ci**
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
....
...
**> azurite@3.14.2 prepare
> npm run build


> azurite@3.14.2 build
> tsc**


added 1017 packages, and audited 1018 packages in 1m

42 packages are looking for funding
  run `npm fund` for details

16 vulnerabilities (5 low, 6 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Users\20273\Desktop\VICE\Azurite>
