### ISSUE TITLE
Connect via SAS connection string

### ISSUE THREAD

**Issue by subesokun** [Azure/Azurite#104]
Hi, I'd like to know if it's possible to generate a SAS connection string via Azurite? So far I've been able to generate a SAS token but when using it within a connection string (e.g. `SharedAccessSignature=<SAS>;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;`) I always get the error that the connection string is malformed. Any ideas? Thanks a lot :)

**Comment by edwin-huber** [comment]
Hi,
are you starting with the "-a" for auth option?
Are you just using curl, or are you using an SDK?

It would help if you could provide more detailed steps to reproduce the errors that you see.
Thanks,
Edwin

**Comment by subesokun** [comment]
We're using the (latest) Python SDK for connecting to the storage account and starting the dockerized Azurite server with its default settings. The README didn't mention this `-accountAuth` flag but if there is such a flag, how can we set it in the Docker container?

Also just noticed in the README https://github.com/Azure/Azurite#blob-storage---api-implementation-status `Account SAS Support [TODO]` :/ Are there any indications when this feature will be available?

**Comment by edwin-huber** [comment]
If you are using the standard Docker Image that is linked in the documentation, AFAIK this is not yet updated with the latest release, and you need to build your own image.

SAS auth should be working... I'm just checking on some of the last kinks. 

Regarding the -accountAuth option, you need to just override the default CMD used in the dockerfile:
[https://docs.docker.com/engine/reference/run/#overriding-dockerfile-image-defaults](https://docs.docker.com/engine/reference/run/#overriding-dockerfile-image-defaults)

But if you build it yourself, you can just modify the CMD command with the options that you need.

**Comment by edwin-huber** [comment]
SAS support added in v3
