### ISSUE TITLE
bad query result when using a boolean clause with parenthesis

### ISSUE THREAD

**Issue by Xaxetrov** [Azure/Azurite#1051]
### Which service(blob, file, queue, table) does this issue concern?

table

### Which version of the Azurite was used?

3.14.2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

npm

### What's the Node.js version?

14.17.6

### What problem was encountered?

Azurite does not give correct query results (it finds none) when a query contains a clause of this kind:
`(MyBooleanField eq true)`
On the contrary, the deprecated azure storage emulator and actual azure storage table service give results when using this clause.

However, this clause works (Notice the space before closing the parenthesis):
`(MyBooleanField eq true )`

### Steps to reproduce the issue?

- Have a table with several fields, at least one bool.
- Fill this table with a few entities.
- Open a storage explorer, or have a small application that queries the service (e.g. Azure Cosmos Table client library for .Net)
- Execute a query with a filtering clause on the boolean field. It should give results.
- Execute the same query with parenthesis around the boolean clause. It gives no result.
- Add a space before closing the parenthesis. It gives results.

Example anonymized log attached (I replace results when I got some by a filler text, line 15) : [example.log](https://github.com/Azure/Azurite/files/7178900/example.log)

### Have you found a mitigation/solution?

Not for now, a lot of libraries do not let you manipulate the query string directly.

**Comment by edwin-huber** [comment]
Thanks for raising this, I shall take a look.
