### ISSUE TITLE
Snapshot details are not included in blob list if "Snapshots" is used instead of "snapshots"

### ISSUE THREAD

**Issue by rmja** [Azure/Azurite#1053]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.14.2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.1.0

### What problem was encountered?
When requesting a list of blobs from a container the snapshot details are not included if the request url has "Snapshots" instead of "snapshots".

For example this request correctly returns snapshots:

```
http://127.0.0.1:10000/devstoreaccount1/images?restype=container&comp=list&prefix=hello&include=snapshots
```

However, this one does not:

```
http://127.0.0.1:10000/devstoreaccount1/images?restype=container&comp=list&prefix=hello&include=Snapshots
```

It seems to have something to do with the case-sensitive test here (repeated multiple times in file):
https://github.com/Azure/Azurite/blob/f62ebd5eff8a143853e35fad3ee07a57a8f8d2ee/src/blob/handlers/ContainerHandler.ts#L539

The `Azure.Storage.Blobs` .net client adds the include list directly from the enum text values which happen to be "Snapshot" (see https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/Generated/ContainerRestClient.cs#L1146)

"Snapshots" worked in "Azure Storage Emulator" and works on the Azure hosted blob storage.

### Steps to reproduce the issue?

Start a new C# app and include `Azure.Storage.Blobs`. Create a blob client and list the blobs as:

```
var blobItems = blobClient.GetBlobsAsync(states: BlobStates.Snapshots, prefix: "test"));
```

Observe that the Snapshot property on each blob item is not populated. One can observe the request with fiddler and see that the request is sent with capital 'S'. One see that the reason that the snapshots are not returned is because the following test fails:
https://github.com/Azure/Azurite/blob/f62ebd5eff8a143853e35fad3ee07a57a8f8d2ee/src/blob/handlers/ContainerHandler.ts#L539

Note that this is probably not only related to snapshots, but all the possible "include" request values.

### Have you found a mitigation/solution?

I guess the best way is to make the ".includes()" string comparisons in https://github.com/Azure/Azurite/blob/f62ebd5eff8a143853e35fad3ee07a57a8f8d2ee/src/blob/handlers/ContainerHandler.ts case insensitive, or maybe normalize the include array to all lowercase somewhere earlier.

**Comment by blueww** [comment]
Fix PR https://github.com/Azure/Azurite/pull/1063/files is already merged. 
The issue will be fixed in the next Azurite release.
