### ISSUE TITLE
Table query with parentheses does not find rows.

### ISSUE THREAD

**Issue by Burgyn** [Azure/Azurite#1084]
### Which service(blob, file, queue, table) does this issue concern?

Table

### Which version of the Azurite was used?

`3.14.2`

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What's the Node.js version?

I'm not sure I use Docker image.

### What problem was encountered?

Table query with parentheses e.g.:  `(PartitionKey eq '1') and (AppId eq 1000002L)` does not find rows.

### Steps to reproduce the issue?

1. In Storage Explorer, insert entity
![image](https://user-images.githubusercontent.com/5930822/136383155-d2aaaea3-a3dc-4414-929c-04da0c143969.png)

2. In Storage Explorer, use query tool to create a query that includes parentheses
No rows found.

![image](https://user-images.githubusercontent.com/5930822/136383314-431b1351-df15-44c7-ae87-f222813bd8f6.png)

3. In Storage Explorer, use the same query but without parentheses
Records were found.
![image](https://user-images.githubusercontent.com/5930822/136383654-4496f9fd-ed57-4fb3-9689-bf8f633caf72.png)

---

We use `Microsoft.Azure.Cosmos.Table` SDK that wraps the conditions with parentheses.

**Comment by XiaoningLiu** [comment]
Hi @edwin-huber, can you help a quick check if it's a missing in #778?

**Comment by Burgyn** [comment]
😊
The problem seems to be in method `tokenizeQuery`. The original condition did not take into account `int64` with `L` suffix.
Original:

```ts
if (i !== 0 && query[i - 1].match(/\d/) !== null)
```

my "naive, without refactor, but functional" implementation looks like this:

```ts
if (
  (i !== 0 && query[i - 1].match(/\d/) !== null) ||
  (i - tokenStart > 0 &&
    query.substring(tokenStart, i).match(/\b[0-9]+L\b/g) != null)
)
```

---

I had a problem running the tests. `ERROR: --compilers is DEPRECATED and no longer supported.` I'm not NodeJs guy 🙄.

**Comment by edwin-huber** [comment]
Issue should be resolved in main branch since Nov 3.
