### ISSUE TITLE
Support for Blob Tags

### ISSUE THREAD

**Issue by omeryesil** [Azure/Azurite#1085]
### Summary
I was wondering if the 'blob tags' support is in the near future roadmap. We want to use Azurite for our CI (contunious integration pipeline), however not having the Tags support makes it a deal breaker. 

We could use the actual Azure Storage Account, however all of our deployments are automated, including the storage account creation, and getting its connection strings through Azure Key Vault, and these processes run only in the CD (continuous deployment).  

### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
Docker image: azurite:3.14.2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Docker Hub

### What problem was encountered?
We get 400 error when we call the tags related methods. 

### Steps to reproduce the issue?

In C#, any call to tags, example:
`
...
blobClient.SetTags(resourceInfo.Tags);
...
`

### Have you found a mitigation/solution?
Not implemented yet, but we will probably do not use Azurite, but use Azure Blob Storage instead, and manually pass connection strings to the test runs (by using Azure DevOps Env variables)

**Comment by blueww** [comment]
Close this issue, as we already have an issue to track blob tag.
