### ISSUE TITLE
Problems using rscd and filename with spaces

### ISSUE THREAD

**Issue by elangelo** [Azure/Azurite#1095]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.14.0, 3.14.2
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Docker
### What's the Node.js version?
whatever is on the container
### What problem was encountered?
When trying to download a file with a space and using content-disposition the azurite service always returns 'forbidden'
Creating the sas url the same way with a real azure blob container service returns success.

### Steps to reproduce the issue?
Our uri's contain a rscd parameter to enforce proper filenames on the downloaded files
The sas uri generated might look like:

http://host.docker.internal:10000/devstoreaccount1/container/Cygnus%20Visual%20colors.jpg?sv=2019-07-07&sr=b&sig=PvUPhg1QJlvK9lom7%2F%2BebI8Hig5ml5KfIvUfjduQMWw%3D&st=2021-10-07T11%3A00%3A00Z&se=2021-10-21T12%3A00%3A00Z&sp=r&rscd=attachment%3B%20filename%3D%22Cygnus%2520Visual%2520colors.jpg%22%3B%20filename*%3DUTF-8%27%27Cygnus%2520Visual%2520colors.jpg

we create the signature like this: (C# code)

            ```
var encodedFileName = Uri.EscapeDataString(fileName);

            SharedAccessBlobHeaders headers = new SharedAccessBlobHeaders()
            {
                ContentDisposition = $"attachment; filename=\"{encodedFileName}\"; filename*=UTF-8''{encodedFileName}"
            };

            var startTime = DateTime.Parse("2021-10-07T08:00Z");
            var endTime = DateTime.Parse("2021-10-21T08:00Z");

            SharedAccessBlobPolicy policy = new SharedAccessBlobPolicy()
            {
                Permissions = SharedAccessBlobPermissions.Read,
                SharedAccessStartTime = startTime,
                SharedAccessExpiryTime = endTime
            };

            return blob.GetSharedAccessSignature(policy, headers);
```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

_I'll do this later_

### Have you found a mitigation/solution?
no

**Comment by blueww** [comment]
@elangelo 
Thanks for reporting this issue!
Please attach the debug log. We will look into it deeper with debug log.
