### ISSUE TITLE
Connect with Storage Explorer

### ISSUE THREAD

**Issue by dsarfati** [Azure/Azurite#11]
I already looked into the previous issue related to storage explorer. Is it possible to connect when running on Mac OSX? I tried to connect using the connection string provided in the Readme (below) but I get an unhelpful error from explorer. 

`DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1; `

<img width="1008" alt="screen shot 2018-03-26 at 12 30 26 am" src="https://user-images.githubusercontent.com/7310169/37892546-0403c3ce-308d-11e8-8ee4-4df949a23a0a.png">

**Comment by seguler** [comment]
Can we close this ? It works with the latest Storage Explorer.
