### ISSUE TITLE
Missing response header

### ISSUE THREAD

**Issue by janbernloehr** [Azure/Azurite#1101]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.14.2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VSCode Extension

### What's the Node.js version?
VSCode 1.60.2

### What problem was encountered?

The response does not contain the headers `x-ms-default-encryption-scope` and `x-ms-deny-encryption-scope-override` which the azure-storage-sdk-for-cpp assumes to be there, hence crashing the application - see https://github.com/Azure/azure-sdk-for-cpp/issues/2961.

### Steps to reproduce the issue?

Perform any http request against a container in the dev storage, e.g.
```
http://127.0.0.1:10000/devstoreaccount1/aztest?restype=container
```

and check the response headers.

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by yshahin** [comment]
@blueww  in the swagger ETag is required and is not returned in the azurite headers.
Would you reopen the ticket and fix this issue?
Thanks

**Comment by blueww** [comment]
@[yshahin](https://github.com/yshahin)
As this issue is for  `x-ms-default-encryption-scope` and `x-ms-deny-encryption-scope-override ` header, would you please open a new issue for better track?

Please indicate the impact of missing Etag in the new issue.
