### ISSUE TITLE
Wrong data retrieved from table for TableEntity with property of type double

### ISSUE THREAD

**Issue by bragma** [Azure/Azurite#1119]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
3.14.2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
v14.17.6

### What problem was encountered?
Retrieving data with ExecuteQuerySegmentedAsync (C#) on a class inherited from TableEntity and double properties retrieves 0 as value instead of 1.

### Steps to reproduce the issue?
Please see the test repository [here](https://github.com/bragma/AzuriteTableTest). Start Azurite docker image and run the program. Data will be correctly written to the table (check with Storage Explorer), but query will retrieve value 0 instead of 1.
Notice that changing property type from double to int will instead return the correct result.

### Have you found a mitigation/solution?
No

**Comment by edwin-huber** [comment]
Hi,
I have been testing your repro.
In the current main branch, this is working, as are the tests which I created using Azure data-tables package.
Could you please confirm?
Thanks!

**Comment by edwin-huber** [comment]
I should also add that the WindowsAzure.Storage Package that you are using has been deprecated.
Please check out Azure.Data.Tables as a replacement.
https://github.com/Azure/azure-sdk-for-net/blob/Azure.Data.Tables_12.2.1/sdk/tables/Azure.Data.Tables/README.md

**Comment by bragma** [comment]
> I should also add that the WindowsAzure.Storage Package that you are using has been deprecated.

I know, thanks for reminiding me. I'm using that package specifically because it's the one we are using in production and may take some time for us to migrate.

**Comment by bragma** [comment]
> Hi, I have been testing your repro. In the current main branch, this is working, as are the tests which I created using Azure data-tables package. Could you please confirm? Thanks!

I'll try. As I specified in the original report, I've been using the image from dockerhub (docker on windows WSL). I'm not sure if this may make a difference. Maybe the problem is with the dockerhub image.
In any case, I'll try to run from main locally and let you know. Thanks!

**Comment by edwin-huber** [comment]
Ah, yes, the DockerHub image is not in parity with the latest PRs.

**Comment by bragma** [comment]
> Ah, yes, the DockerHub image is not in parity with the latest PRs.

I suggest to use imege tags properly instead of "latest"

**Comment by edwin-huber** [comment]
> I suggest to use imege tags properly instead of "latest"

Sorry for the confusion. 
To be more precise: in my response "latest" meant most recent and did not refer to the Docker image tag.  
There are usually a couple of "recent" PRs which have not yet been "released" with a version number.

**Comment by bragma** [comment]
Just tested with main branch, same problem. I'm using 3.14.3, while the dockerhub image was using 3.14.2
I did:
git clone
npm ci
npm run build
cd dist/src
node azurite.js

The I run the executable from my test repository.

Not sure it is meaningful, node is 10.16.3

**Comment by bragma** [comment]
I just checked this [PR](https://github.com/Azure/Azurite/pull/1155)  but it does not cover my case. The bug happens when an integer value (ex: 1) is read with a double value. If there is any decimal digit, it works correctly. I didn't run the tests with the PR, but I am expecting that 54.321 will work.

**Comment by edwin-huber** [comment]
Many thanks for the follow up and clarification.
I shall adjust the tests accordingly and check what is going on in your case, if it is down to the old SDK, or the way the query parser is working.

**Comment by edwin-huber** [comment]
If I look at the old SDK, the value is inserted as a string:
```json
 "properties": {
            "PartitionKey": "PARTITION",
            "RowKey": "ROW",
            "Value": "1.1",
            "Value@odata.type": "Edm.Double",
            "Timestamp": "2021-11-08T19:59:19.1870000Z",
            "Timestamp@odata.type": "Edm.DateTime"
          },
```
When using the new Data-Tables SDK, the values are inserted as numbers:
```json
 "properties": {
            "PartitionKey": "double163640168151205689",
            "RowKey": "row163640168159008630",
            "int32Field": 54321,
            "int64Field": "12345",
            "doubleField": 5,
            "doubleField@odata.type": "Edm.Double",
```

I need to check if this is something we can still address.
Please bear with me.

**Comment by edwin-huber** [comment]
Hi,
we found the issue and have a solution for backwards compatibility.
Will hopefully make it into the next release, pending PR review and merge.

**Comment by bragma** [comment]
> Hi, we found the issue and have a solution for backwards compatibility. Will hopefully make it into the next release, pending PR review and merge.

Great, thanks a lot!

**Comment by edwin-huber** [comment]
Issue should be resolved.
