### ISSUE TITLE
Unable to execute Azurite

### ISSUE THREAD

**Issue by stephenllai** [Azure/Azurite#112]
I use the following command to install Azurite.
`sudo npm install -g azurite`
("sudo" is needed, otherwise I cannot install Azurite successfully.)

When I try to execute Azurite with the following command
`azurite -l /home/stephen/azurite/workspace`
I get the following error
`/usr/bin/env: 'node\r': No such file or directory`

**Comment by edwin-huber** [comment]
cross platform support now in v3, pipeline tests also validating this.
