### ISSUE TITLE
Can't validate credentials for Azurite on Apache Spark 3.1.2 (Scala)

### ISSUE THREAD

**Issue by luizrego** [Azure/Azurite#1138]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
v3.14.3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio Code Extension

### What's the Node.js version?
N/A

### What problem was encountered?
```
Caused by: org.apache.hadoop.fs.azure.AzureException: No credentials found for account 127.0.0.1:10000 in the configuration, and its container test-container is not accessible using anonymous credentials. Please check if the container exists first. If it is not publicly available, you have to provide account credentials.
```
### Steps to reproduce the issue?
```
    val spark_session = SparkSession.builder.master("local[1]").getOrCreate()
    val conf = spark_session.sparkContext.hadoopConfiguration
    spark_session.conf.set("spark.hadoop.fs.wasbs.impl", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")
    spark_session.conf.set("fs.azure.account.key.127.0.0.1:10000/devstoreaccount1", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")

    val df = spark_session.read.csv("http://127.0.0.1:10000/devstoreaccount1/test-container/me.csv")

    df.show()
```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
@luizrego 

For Azurite debug log, if you run in VS extension, you can get from Ourput console, and choose "Azurite Blob Debug", like following picture.

![image](https://user-images.githubusercontent.com/6926193/139619214-210d1513-1200-4aa4-a963-88e8623c8538.png)

I am not so familiar with java SDK, would you please share what these 2 lines means?
```
    spark_session.conf.set("fs.azure.account.key.127.0.0.1:10000/devstoreaccount1", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")

    val df = spark_session.read.csv("wasb://127.0.0.1:10000/devstoreaccount1/test-container/me.csv")
```

From the log, it looks the error happens in request : 
```
127.0.0.1 - - [29/Oct/2021:08:02:25 +0000] "HEAD /$root?restype=container HTTP/1.1" 400 -
```
Would you please share which credential you use to head the container? And have you enabled public access on the container?

**Comment by luizrego** [comment]
Hi @blueww 

Those 2 lines are basically what I need to provide to the Spark session since it's an Azure FileSystem and then create a dataframe based on the CSV file. Just to show you an example how it works when I try to connect to a real blob storage on Azure:

```
    /* Azurite */
  spark_session.conf.set("fs.azure", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")
  spark_session.conf.set("fs.azure.account.key.<storage_account_name>", <storage_account_key>)
  val df = spark_session.read.csv("wasb://lego-data@<storage_account_name>/themes.csv")

  /* Blob Storage Azure WORKS */
  spark_session.conf.set("fs.azure.account.key.<storage_account_name>.blob.core.windows.net", <storage_account_key>)
  val df = spark_session.read.format("csv").option("header","True").load(f"wasbs://lego-data@<storage_account_name>.blob.core.windows.net/landing/$ts_date%s_themes.csv.gz")
```
So that's why I was expecting the same behaviour. Regarding the credential, here they are:
`AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;`

Finally I guess the permissions on the container are correct, right?

![image](https://user-images.githubusercontent.com/20259512/139674734-948e53da-b5be-4032-8e2a-fd0ba2e7e225.png)

**Comment by blueww** [comment]
@luizrego 
I see you have enabled public access to the container. So you can read the container with anonymous access.
Do you still meet the failure? If so, please share the debug log for Azurite.

**Comment by luizrego** [comment]
@blueww sorry for the delayed reply, it worked now. Thank you for your time and the issue can be marked as resolved.

**Comment by blueww** [comment]
Thanks @luizrego  for the confirm!
Close the issue as it's already resolved.

**Comment by ronfulkerson** [comment]
@luizrego can you provide an example of how you got it to work?
