### ISSUE TITLE
Blob storage returns 403 when trying to ready from secondary on v3.14.2+

### ISSUE THREAD

**Issue by vikene** [Azure/Azurite#1142]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
3.14.2
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
NPM
### What's the Node.js version?
14.17.4
### What problem was encountered?
When we try to access secondary location of blob storage, it returns 403 - forbidden error. 
### Steps to reproduce the issue?
Attaching debug log and project to replicate this issue. 
Extract the project and give following commands in order to replicate this issue.
    1) Dotnet build 
    2) Dotnet run
[blobstorage.zip](https://github.com/Azure/Azurite/files/7454811/blobstorage.zip)

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:
Attaching debug log as a file.
[debug.log](https://github.com/Azure/Azurite/files/7454804/debug.log)

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
Fall back to 3.14.0

**Comment by vigneashs** [comment]
Created a pull request for this issue - https://github.com/Azure/Azurite/pull/1145

**Comment by blueww** [comment]
The issue has been fixed in Azurite 3.15.0.
