### ISSUE TITLE
Unable to use Node.js Durable Functions with Azurite

### ISSUE THREAD

**Issue by SpicySyntax** [Azure/Azurite#115]
I am working on a project that uses Typescript + Node.js + Azure Durable Functions. I started using Azurite and love its simplicity, however my Durable Function orchestrations never work when I use Azurite over the Azure Storage Emulator.

**Comment by MaximRouiller** [comment]
cc : @cgillum @kashimiz @jeffhollan

**Comment by cgillum** [comment]
I suspect this is the same issue as this: https://github.com/Azure/Azurite/issues/37

**Comment by XiaoningLiu** [comment]
Did Azurite run in durable function?

**Comment by SpicySyntax** [comment]
> Did Azurite run in durable function?
I'm not sure I understand your question.
I am using the 'npm-run-all' package to run the Azure Functions locally in parallel with Azurite. This has been working fine as a storage emulator for everything except for my Durable Function Orchestration.

**Comment by SpicySyntax** [comment]
@cgillum @XiaoningLiu when can we expect a new npm package with this fix? It is holding back our ability to develop locally

**Comment by TsuyoshiUshio** [comment]
Hi.  You can use old version of Azurite. V3 doesn't support Storage Table. Durable Functions requires Storage Table.  This is v2 link that support Storage table. 
https://github.com/Azure/Azurite/tree/legacy-master

**Comment by mouadbroos** [comment]
> Hi. You can use old version of Azurite. V3 doesn't support Storage Table. Durable Functions requires Storage Table. This is v2 link that support Storage table.
> https://github.com/Azure/Azurite/tree/legacy-master

I confirm that this works. You can directly install the legacy version from Npm :  > npm install azurite@2.7.1 -g

**Comment by priyaananthasankar** [comment]
@mouadbroos Did you try starting the orchestration with Azurite v2? The webhook returns back with "One of more inputs are incorrect" and just changing it to cloud storage worked.

**Comment by terurou** [comment]
Durable Entities doesn't work with Azurite v2.6.7.

* Microsoft.Azure.WebJobs.Extensions.DurableTask 2.1.1
* npm durable-functions 1.3.1
* Node.js 10.18.1

**Comment by mouadbroos** [comment]
@priyaananthasankar sorry for the delayed response, I ran into a lot of problems trying to get azurite to work so I switched to using a VM running windows 10 with the official azure storage emulator!

**Comment by edwin-huber** [comment]
This is now resolved with support for durable functions.
