### ISSUE TITLE
Call to get tags (?comp=tags) returns content instead of tags

### ISSUE THREAD

**Issue by bamancio-futura** [Azure/Azurite#1151]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
When I call `GET /devstoreaccount1/testcontainer/dummyfile.txt?comp=tags HTTP/1.1` from the docker image I get  the content of the blob in the response, instead of the tags structure. When I call the same from an Azure Storage Account I get the expected structure, which are the tags.

### Steps to reproduce the issue?

Call `GET /devstoreaccount1/testcontainer/dummyfile.txt?comp=tags HTTP/1.1`

### Have you found a mitigation/solution?
 Call a real Azure Storage Account. I get the expected structure in the response.

**Comment by blueww** [comment]
@bamancio-futura 
Blob tag is still not supported by Azurite. We already have other issue to track it, like https://github.com/Azure/Azurite/issues/647

However, do you want to make this API fail with 500 in Azurite, since it's not implemented.

**Comment by bamancio-futura** [comment]
I'll wait for the support in #647. Thanks.
