### ISSUE TITLE
AZURITE_ACCOUNTS: No valid combination of account information found

### ISSUE THREAD

**Issue by Cogax** [Azure/Azurite#1166]
When I set an account via `AZURITE_ACCOUNTS` environment variable, I get an error `No valid combination of account information found`. It works when I remove `AZURITE_ACCOUNTS` environment variable and log in via `devstoreaccount1` account.

This issue was observed in `3.14.3` (docker tag).
**Workaround**: It works as expected with `3.13.1` (docker tag).

_Originally posted by @Cogax in https://github.com/Azure/Azurite/issues/837#issuecomment-967212068_

**Comment by blueww** [comment]
@Cogax 
Is the error is from SDK or from Azurite?
We will need more inforamtion to investigate this.
Would you please the Azurite debug log on this?

**Comment by jangaehler** [comment]
@blueww I have the same problem. It is as described in https://github.com/Azure/Azurite/issues/837 . 

Most importantly, there is no documentation showing step by step how to set up and use AZURITE_ACCOUNTS (incl. docker-compose, connection string examples). This would be super helpful for users and would save tons of time.

**Comment by blueww** [comment]
@jangaehler 
"No valid combination of account information found" looks a client side error. 
It looks should not related with the Azurite version.

Would you please share the connection string you used to repro this issue? (hide the credential like key)

**Comment by blueww** [comment]
Close this issue as it looks has been resolved on customer side.
