### ISSUE TITLE
Failing to open a new Azurite table in Storage Explorer

### ISSUE THREAD

**Issue by seniorquico** [Azure/Azurite#117]
I have Node.js 10.13.0 installed via nvm. I started Azurite 2.7.0 by running the following:

```sh
$ node --version
v10.13.0
$ mkdir empty
$ cd empty
$ npx azurite
...
```

Azurite started normally. I then used Storage Explorer 1.5.0 to create a new table named "Example". The operation completed successfully, and I saw the "Example" table in the navigation tree. However, selecting the table to open it resulted in the following error:

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>EntityNotFound</Code><Message>The specified entity does not exist.</Message></Error>
```

I found the following in the console log (no other errors or anything that looked too relevent):

```
POST /devstoreaccount1/Tables 204 2.419 ms - -
GET /devstoreaccount1/Example?%24top=1000 404 0.866 ms - 135
```

This is a simple reproduction of a more general issue we've encountered creating and reading tables in Azurite. Working with tables no longer appears to be working from our .NET Core application.

**Comment by seniorquico** [comment]
Azurite is returning a 404 Not Found/EntityNotFound error when the table _exists_ but contains no entities. However, Azure Storage is returning a 200 OK with a "minimalmetadata" body. (This is my first step into Azurite and the implementation details of Azure Storage... I just got a dev environment running, and I'm comparing Fiddler captures of Azurite and Azure Storage using the Azure Storage Explorer as a client.)

This issue appears to stem from an empty search result in [TableStorageManager.queryEntities](https://github.com/Azure/Azurite/blob/3a089ae6a9fb6c28bd63ba9d4f9c2f47b8257626/lib/core/table/TableStorageManager.js#L148-L150) that was introduced in [#80](https://github.com/Azure/Azurite/pull/80).

**Comment by seniorquico** [comment]
Based on discussions, #80 appears to have resolved an issue related to point queries (see #19). It was suggested that a point query should return a 404 Not Found if the entity does not exist. Example API query:

```
/Events(PartitionKey='foo',RowKey='SS-HEAD')
```

However, the Azure Storage Explorer tests I'm running appear to make queries using the `$filter` argument:

```
/Events?%24select=&%24filter=PartitionKey%20eq%20%27foo%27%20and%20RowKey%20eq%20%27SS-HEAD%27&%24top=1000
```

For queries using the `$filter` argument, it looks like I can confirm Azure Storage responds with a 200 OK result and something like the following:

```
{"odata.metadata":".../$metadata#Events","value":[]}
```

Of note, this was the behavior prior to #80.

**Comment by macux** [comment]
Is there any update to this? I've tried downgrading to 2.6.5 and 2.5.1 but they both have some flavour of not found errors, either when deleting or querying tables.

**Comment by XiaoningLiu** [comment]
ping @edwin-huber

**Comment by edwin-huber** [comment]
following the initial steps outlined by @seniorquico in the current legacy-dev branch, I am unable to reproduce the issue.
I am able to create a table, and create a new entry in the table:

```
POST /devstoreaccount1/Tables 204 2.786 ms - -
GET /devstoreaccount1/example?%24top=1000 200 0.913 ms - 89
POST /devstoreaccount1/example 204 1.407 ms - -
GET /devstoreaccount1/example?%24top=1000 200 1.242 ms - 201
```

Here we get the expected behavior with HTTP Status of 200.  
I'm just validating the query logic and issue presented later in this thread, and adding that to a test case if we need it.

Queries from the storage explorer's latest version are still using the filter logic, as is the FSharp test that I have:

```
GET /devstoreaccount1/example?%24select=&%24filter=PartitionKey%20eq%20%27foo%27%20and%20RowKey%20eq%20%27SS-HEAD%27&%24top=1000 200 0.541 ms - 89
```

I'm setting up a project with the latest Cosmos package according to:
https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-develop-table-dotnet

@XiaoningLiu It might be as simple as we need to push a release out from the legacy dev branch to update Nuget and Docker versions based on legacy / 2.0 arch

**Comment by edwin-huber** [comment]
@XiaoningLiu  We need to push out a release.

I am unable to repro with the current version, and the tables behavior in the legacy-dev branch is the same as the service:
When I use the query Syntax

```
http://localhost:10002/devstoreaccount1/demoe1391(PartitionKey='Foo',RowKey='Walter')
```
It returns 404 not found  
<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>EntityNotFound</Code>
    <Message>The specified entity does not exist.</Message>
</Error>


This is "almost" the same behavior that I get from the service, we can argue whether we need to update the Code to ResourceNotFound...:
HTTP Status 404
<?xml version="1.0" encoding="utf-8"?>
<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
    <code>ResourceNotFound</code>
    <message xml:lang="en-US">The specified resource does not exist.
RequestId:85ab86e5-e002-0000-5ec9-389910000000
Time:2019-07-12T15:52:36.2226820Z</message>
</error>


When I use a filter:
```
%24select=&%24filter=PartitionKey%20eq%20%27foo%27%20and%20RowKey%20eq%20%27SS-HEAD%27&%24top=1000
```
I get an empty list:
HTTP Status 200
{
    "value": []
}

The service provides a little more, but essentially also the empty list:
<?xml version="1.0" encoding="utf-8"?>
<feed xml:base="https://azuritetesting.table.core.windows.net/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
    <id>https://azuritetesting.table.core.windows.net/testtable</id>
    <title type="text">testtable</title>
    <updated>2019-07-12T15:54:50Z</updated>
    <link rel="self" title="testtable" href="testtable" />
    <author>
        <name />
    </author>
</feed>

We could change our response format to match the XML response from the service... but the responses are working with my sample app and queries submitted by the Cosmos Table API, so I think a release should be enough.

**Comment by XiaoningLiu** [comment]
@edwin-huber Sounds good. Anything others we need to do for the legacy branch release? Like changelog etc.

**Comment by edwin-huber** [comment]
released version and new release in Azurite v3 also addresses this issue.
