### ISSUE TITLE
azurite blob storage events

### ISSUE THREAD

**Issue by kuba-lilz** [Azure/Azurite#1174]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.14.3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
N/A?

### What problem was encountered?
Can azurite create blob storage events (https://docs.microsoft.com/en-us/azure/event-grid/event-schema-blob-storage?tabs=event-grid-event-schema)? If so, is there any way to specify where should they be published?

I'm trying to recreate
```
azure storage -> (sends blob created events) -> azure event grid -> (sends events to queue) -> azure storage queue
```
setup on local environment for development, and as part of that would need a way to publish blob created events.

### Have you found a mitigation/solution?
Nope

**Comment by blueww** [comment]
@kuba-lilz 
Azurite is an open source Azure Storage API compatible server. It only support accept/responds storage API now. It currently not aimed to support event grid.

**Comment by blueww** [comment]
@kuba-lilz 
I will close this issue as Azurite doesn't support event grid.

Feel free to contact us again if need any further assistance on Azurite.

**Comment by blueww** [comment]
@SeanFeldman 

In the ReadMe.MD, the introduction said "Azurite is an open source Azure Storage API compatible server (emulator)." So it only support storage features, not support other Azure features like event grid. As there are so many other azure features not supported by Azurite, would you please give some hint why we need mention Event grid in ReadMe.Md?

**Comment by SeanFeldman** [comment]
Event Grid is in underlying service and can be configured to emit Storage related events. Hence it could be confusing to read that just from the sentence you've quoted. I've seen first hand devs going in the route of building their testing strategy based on Azurite to find out they can't test anything events related. Hence the ask for a clarification to avoid those mistakes.

**Comment by blueww** [comment]
@SeanFeldman 

Thanks for the reply!

Just looked deeper into Event Grid, it looks Event grid can use storage in 2 ways:
1. Get Event from some storage blob/datalakegen2 operations, like delete blob, create blob, set tier ...
2. Use storage Queue as event handler to receive event.

So would you please share more details for your scenarios? Will your scenario need use above function #1, #2 or both?
What's the detail request for Azurite, do you need Azurite to simulate #1 or #2 with event grid in public Azure, or you need Azurite to simulate both without event grid in public Azure?

However, ReadMe.md has said Azurite is "Azure Storage API compatible server", which means will support storage API simulation, but not cover other functions like backend communication with other service.
And there are other Azure service has communication with storage, like compute, networking ... 
So it's still looks a little odd to me to add event grid not support to Azurite Readme.md.

**Comment by PuchatekwSzortach** [comment]
Using Azure dashboard, Azure Storage Events are configured from within Azure Storage service page, not Even Grid page - so from the interaction standpoint it indeed does look to user as if events were a feature of Azure Storage, not an external service that can be connected to it.

Screenshot from
https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-event-grid-manual

<img width="1048" alt="Screen Shot 2022-12-10 at 21 08 01" src="https://user-images.githubusercontent.com/13689310/206854376-19013d27-be43-4717-89d9-3634afa081b1.png">

**Comment by PuchatekwSzortach** [comment]
Storage events is feature that is incredibly useful in building background processes reacting to events, and you already provide all the other pieces of the puzzle (queues to push events to). If Azurite's mission is to enable developers build Azure Storage-based solutions, thus driving growth of Azure when they deploy these solutions in production, then I think adding storage events fits that goal very well, as it allows developers to work easily on a new class of Azure Storage applications.

The logic to implement isn't complex, and even getting the bare bones (Blob Created events sent to storage queue in the same Azurite installation/docker container) would add a significant new value to Azurite that it's missing compared to Azure Storage.

**Comment by SeanFeldman** [comment]
@blueww that'd be #1. @PuchatekwSzortach has demonstrated the possible confusion I'm talking about. EventGrid is an underlying service, enabling other Azure services, such as Storage, emit events.

My intent is not to convince the Azurite team to emulate those events. Rather, clearly indicate it's currently not provided so save developers time figuring it out.

Should you decide to support storage events, you'd need to figure out how that will work as event handlers can be various services, not just Storage Queues.

**Comment by kuba-lilz** [comment]
The workaround reading Azurite log that ultimately creates blob events on storage queue would be solve the problem I created this issue for :) And even if someone wants to send that storage even outside of azurite queue, having it in the queue makes that task simpler than current setup.

From my standpoint "eventType" and "subject" are the most critical parts of the message - they let me know what event happened and on which blob.

And small thought from someone who once implemented an in-house solution akin to what you described above - I imagine the script that listens on logs would be running in different process and thus creating storage events would be asynchronous w.r.t. when blobs were actually created. During development and testing it's useful to be able to make this step synchronous at times so we don't e.g. wait arbitrary amount of time in tests that expect storage events to be available on the queue.
Our in-house emulator contains a simple endpoint that makes operation synchronous. This endpoint guarantees that after it returns storage events for all blobs uploaded before endpoint call are already created.

**Comment by blueww** [comment]
@justinmchase 

Thanks for your suggestion!

Azurite is an open source Azure Storage API compatible server. It only aim to support accept/responds storage API. 
And we don't aimed to support other service / platform like event grid or kafka. 

However, Azurite debug log contains almost all info that Event grid could support. So you might can write your own script/program to read Azurite debug log and create a message send to kafka for every request. 
This should not be a part of Azurite, but can be an external program/script.

**Comment by dsaad68** [comment]
@blueww As a developer who works daily with Azure Storage Account, I believe that supporting Event Grid events should be considered one of the main features of Azurite. 

When I hear the definition you stated above for Azurite, I think Azurite supports this suggested feature out of the box.

If it is possible to add this feature, it would greatly help many developers working with Azure Storage Account.

**Comment by blueww** [comment]
@dsaad68 
Azurite is a Azure Storage API compatible server (emulator). 
However, Event Grid is not a part of Azure Storage, it's another service in Azure. 
We don't aimed to support other service / platform like event grid in Azurite.

However, if you really want it, you might can : 
1. Raise a [help ticket](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header) in Azure Portal, to ask event grid team provide such an emulator. 
2. Develop your own open source event grid emulator and make it can work with Azurite.  However, you need to own the develop/test/release/maintenance by you own.

**Comment by vincentfenet** [comment]
as i was interested in PUT event in azurite blob storage, i've made a small proxy software that can emulate different kind of events like `event grid` ones here: https://github.com/vincentfenet/blob-storage-notify-proxy
