### ISSUE TITLE
Cannot retrieve a value of type double w/o fraction. Zero is returned instead.

### ISSUE THREAD

**Issue by Benny56** [Azure/Azurite#1180]
### Which service(blob, file, queue, table) does this issue concern?

table

### Which version of the Azurite was used?

3.12.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Visual Studio 2022. I have both channels installed Preview and Current.

### What's the Node.js version?

v10.19.0

### What problem was encountered?

A value of type double is stored as Int32 when no fraction is provided.
The Int32 value is not converted back to double instead zeo is returned.

### Steps to reproduce the issue?

1. Create a table using Microsoft Azure Storage Explorer
2. Create a row with PartitionKey, RowKey and a double value with fraction. Example: pk, rk, 5.7
3. Create a second row with a double value w/o fracktion: pk, rk, 5
4. Retrieve 1st row. Result: 5.7
5. Retrieve 2nd row. Result: 0.0

### Have you found a mitigation/solution?

I have temporarily suspended Azurite and returned to Azure Storage Emulator.

**Comment by edwin-huber** [comment]
Thanks for raising.
We shall take a look and address this.

**Comment by edwin-huber** [comment]
Hi,
This issue appears resolved, feel free to reopen if not.

If I double click in storage explorer, I see the expected double values (5.7,5).

Please ensure that you are using a recent and supported version of NodeJs (14+), and that you are using the most recent version of Azurite.

![image](https://user-images.githubusercontent.com/11886843/165456693-ed6f4d83-1a1b-4341-b1e5-7efff93542c3.png)

**Comment by Benny56** [comment]
See issue #1796 for more precise reproduction steps
