### ISSUE TITLE
Emulated table service does not return RestError for invalid filter option

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#1185]
### Which service(blob, file, queue, table) does this issue concern?
Table
### Which version of the Azurite was used?
3.14.3
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
4.14.7
### What problem was encountered?
The  table service does not return with a RestError for invalid queries.
### Steps to reproduce the issue?
Run the following code in Node:
```js
const { TableClient } = require("@azure/data-tables");
const connectionString = "<DEV_CONNECTION_STRING>";
(async () => {
    const client = TableClient.fromConnectionString(connectionString, "test01", { allowInsecureConnection: true });
    try {
        await client.createTable();
        const result = await client.listEntities({ queryOptions: { filter: "1" } }).byPage();
        console.log(result.next(), null, 2);
    } catch (error) {
        console.error(error);
    }
})();
```

If the connection string used is for a dev account (emulator), the `console.log` statement is run, which is unexpected.

If you swap the connection string for a real Azure table service, the `console.error` statement is run, printing out the message "The $filter expression must evaluate to a single boolean value."

### Have you found a mitigation/solution?
No

**Comment by edwin-huber** [comment]
Thanks for raising.
We need to respond with a 400.

**Comment by craxal** [comment]
@edwin-huber Is there any news on this issue?

**Comment by edwin-huber** [comment]
Hi @craxal, 
We're working our way through the issues.
We've made considerable progress on the backlog.
Should be done soon!
