### ISSUE TITLE
Add Tray Icon ability to Azurite

### ISSUE THREAD

**Issue by OzBob** [Azure/Azurite#1186]
AzureStorageEmulator ran in the Tray and didn't have a 'blocking' console window
As a developer I used to have a 'on startup/login task':

```
START "AzureStorageEmulator" "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
```

As Azureite is 'blocking' and remains in the Console I can't do this and everytime I start a VS solution that depends on 'development=true' storage emulation, I have to remember to start azureite.

Add Tray Icon ability to Azurite

**Comment by blueww** [comment]
@OzBob 
Azurite still doesn't support Tray Icon, and we don't see that request before.
If you would like to start Azurite when start computer, there should be other ways, like you can setup a service with it.

**Comment by OzBob** [comment]
Azurite can now be started via Storage Explorer: https://github.com/microsoft/AzureStorageExplorer/issues/3229
