### ISSUE TITLE
Table queries with backticks in a $filter argument fail

### ISSUE THREAD

**Issue by seniorquico** [Azure/Azurite#120]
A popular storage provider for Microsoft Orleans sends table storage queries like the following:

```
GET /devstoreaccount1/OrleansReminders?$filter=((PartitionKey gt 'dev_') and (PartitionKey le 'dev`')) and ((PartitionKey gt 'dev_CC26AB93') and (PartitionKey le 'dev_E80BF780'))&timeout=3
```

Note how the second filter test includes a backtick. This fails on Azurite as it gets translated into the following, which throws a `SyntaxError` when `eval`'d:

```
... ( item.partitionKey <= `dev`` ) ...
```

**Comment by edwin-huber** [comment]
Resolved with #807 pending PR
