### ISSUE TITLE
Azurite table fails in pipeline (500 server error)

### ISSUE THREAD

**Issue by Redcloves** [Azure/Azurite#1204]
### Which service(blob, file, queue, table) does this issue concern?
table
### Which version of the Azurite was used?
2.7.1
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What problem was encountered?
Azurite works locally, but fails to build in the pipeline.
### Steps to reproduce the issue?
As it builds fine locally, I believe the issue is with the yaml file. I tried by trial and error with different tasks suggested online for the pipeline to build, but nothing works so far. Yaml file attached below.
![yaml](https://user-images.githubusercontent.com/66646780/145285393-29f8c435-dd2c-467f-bac0-ccb05465975a.jpg)
![pipeline](https://user-images.githubusercontent.com/66646780/145285375-70822542-0807-403e-9d8e-d7880b698476.jpg)

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"

```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
For now, I'm using the cloud version, but for testing I'd prefer to use Azurite.

**Comment by edwin-huber** [comment]
Hi, 
you are referencing the outdated version of Azurite (2.x) in your pipeline... please switch to version 3.x

Thanks,
Edwin

**Comment by Redcloves** [comment]
Hi,
But there’s no support for tables in version 3, that’s why I installed the 2.  

Anna

**Comment by edwin-huber** [comment]
Hi Anna,  
Table Support for v3 is in preview, and generally, v3's API support is more up-to-date than v2.
We are getting quite close to GA support for Tables now.
If you still have issues with v3, please let us know, and we will work to help you fix those.
Kind regards,
Edwin

**Comment by Redcloves** [comment]
Hi,
Thanks, changing to version 3 worked on the pipeline. 

Kind regards,
Anna
