### ISSUE TITLE
Calling azurite from a Linux docker container

### ISSUE THREAD

**Issue by DrEight** [Azure/Azurite#1206]
I have azurite installed on Windows with the https endpoints enabled. 
I have 2 services that are calling azurite: the first is on the local machine the second is inside a linux docker container.
Since the docker service can not call 127.0.0.1, but it has to call 'host.docker.internal' the SSL certificate is not valid. I tried to generate a self-signed certificate with subject name 'host.docker.internal' and the IP 127.0.0.1 without success.
I tried also localhost & host.docker.internal: no luck.
With 'http' everything work, but I can not use 'http', I have to use 'https'.

**Comment by blueww** [comment]
@DrEight 

Would you please share what's the detail error you have get?

And if the server and client are on different machine, has the root cert that used to sign the Azurite cert , been added to trust root of the client machine?

**Comment by DrEight** [comment]
@blueww 
It seems that azurite works if there is only the dns=127.0.0.1  specified.
For example if I generate a certificate with: mkcert 127.0.0.1 host.docker.internal, it does not even works on the local machine.
I tried also to generate a certificate with: 'mkcert localhost' and it does not work locally. ( I changed the connection string accordingly ) .
For reference to register the certificate as trusted I use:
Windows/Linux :  certutil -addstore -enterprise -f "Root" .\127.0.0.1+1.pem

**Comment by blueww** [comment]
@DrEight 

For "host.docker.internal" on local machine, you can generated cert with "mkcert host.docker.internal", then start Azurite with parameter "--cert host.docker.internal.pem --key host.docker.internal-key.pem". 
(The cert should have "Subject Alternative Name" like "DNS Name=host.docker.internal")

To add the root cert to another machine, please add the root cert of the generated *.pem file to the trust root of the client machine.

**Comment by DrEight** [comment]
@blueww 
My problem is that, the certificate does not work on the local machine. I'm searching for a certificate that works in both scenarios

**Comment by blueww** [comment]
The cert works on my machine with above step.
If the cert still not work, please share the step you set up Azurite, which include command to 
1. mkcert
2. start Azurite
3. connection String
4. host file 
Please hide any credentail.

**Comment by DrEight** [comment]
So these are the steps I did :
- I created the certificate with the command: mkcert host.docker.internal
- I added the certificate to the root store : certutil -addstore -enterprise -f "Root" .\host.docker.internal.pem
- I started azurite with the command :  azurite --cert c:\azurite\host.docker.internal.pem --key c:\azurite\host.docker.internal-key.pem --oauth basic --silent
- I started the Azure Storage Explorer and I added the certificate host.docker.internal.pem then I restarted the Explorer. 
- I've tried to connect to Azurite with the connection string: DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://127.0.0.1:10010/devstoreaccount1;QueueEndpoint=https://127.0.0.1:10001/devstoreaccount1

I received the exception : Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://127.0.0.1:10010/devstoreaccount1?comp=list&include=metadata failed, reason: connect ECONNREFUSED 127.0.0.1:10010",
  "stack": "FetchError: request to https://127.0.0.1:10010/devstoreaccount1?comp=list&include=metadata failed, reason: connect ECONNREFUSED 127.0.0.1:10010\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}


I didn't test the certificate inside docker, but I suppose it would work, but remember that I'm looking for a certificate that works in both scenarios.

**Comment by blueww** [comment]
@DrEight

The connection string you use will connect to Azurite with "127.0.0.1" as "BlobEndpoint=https://127.0.0.1:10000/devstoreaccount1"

But the cert is on DNS name "host.docker.internal"

So the cert DNS name is not aligned with the Uri you use to connect to Azurite. this will make the connection fail.

**Comment by DrEight** [comment]
I've already tried what you suggest. The problem I've seen is that when you map 'host.docker.internal' to 127.0.0.1 the docker container inherit the setting from the host machine and it stop to call externally.

**Comment by blueww** [comment]
@DrEight 
Do you map 'host.docker.internal' to 127.0.0.1 in host file?
Normally you don't need to change host file manually for that. 
When you start azurite with docker, you should already can use the host.docker.internal hostname to connect to your Docker host from inside a Docker container.
See more details in https://docs.docker.com/desktop/windows/networking/

**Comment by DrEight** [comment]
@blueww 
the hosts is already mapped to 'my ip' -> host.docker.internal by default. This setting is added by the docker setup.
it is not mapped 127.0.0.1 -> host.docker.internal.
I guess that this is done for a good reason and I can not force who will use my container to introduce this change on the host machine.

**Comment by blueww** [comment]
@DrEight 
If you still fail, would you please check:
1. you can connect Azurite in docker with "http" successfully with "BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1"
2. the cert is on DNS name "host.docker.internal"
2. you connect to Azurite on same machine, and use "BlobEndpoint=https://host.docker.internal:10000/devstoreaccount1"
3. The cert  root (not the cert itself) if in trust root  of the client machine.
And please also share the command you use to start azurite (you should have updated it with my sample).

If still fail, would you please share the failure error message (hide credential if any)
The before failure reason should already fixed if you follow my sample.

**Comment by blueww** [comment]
@DrEight 
I will close the issue as not get any responds from you for a long time.
Feel free to contact us again if need any further support on Azurite.
