### ISSUE TITLE
Question: Silent mode by environmet variable

### ISSUE THREAD

**Issue by Burgyn** [Azure/Azurite#1208]
Hi,

I have a question.
Is there a way to turn off the logging feature when this docker image is used in a docker compose file?

Thanks a lot.

**Comment by blueww** [comment]
@Burgyn 
Have you tried "-s", see detail in https://github.com/Azure/Azurite#access-log-configuration?
With this parameter, Azurite will not display access log in console. (However, still have some log for start/stop Azurite).

**Comment by Burgyn** [comment]
Hi @blueww,

thank you for your response. Yes, I know this parameter. But I want to use this image in **compose docker** and I don't know how to do it 😔.

**Comment by blueww** [comment]
@Burgyn 

For run Azurite with least log, "-s" should be the option.

If the question is for how to run azurite in compose docker, it looks like out of Azurite scope. And we don't have a config ready for Azurite in compose docker.
However, we see a compose docker file in the before issue. You might can reference it.
https://github.com/Azure/Azurite/issues/837#issuecomment-867176178

**Comment by Burgyn** [comment]
Hi,

thanks a lot.
