### ISSUE TITLE
Blob copy does not allow custom hostname

### ISSUE THREAD

**Issue by wiruzman** [Azure/Azurite#1245]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.15.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub/npm
### What's the Node.js version?
v14.15.4
### What problem was encountered?
`startCopyFromURL` and `copyFromURL` does not respect `disableProductStyleUrl` option and therefore I cannot use an url to copy a blob locally.
Example of url: `http://mystorage.mydomain.com:10000/devstoreaccount1/container/blob`
### Steps to reproduce the issue?
- Start Azurite with: `azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --disableProductStyleUrl`
- Use .Net library to copy a blob with `StartCopyFromUriAsync` method.

### Have you found a mitigation/solution?
Using 127.0.0.1 as host solves the problem, but we want to use a proper hostname. Or using version 3.14.0.

**Comment by blueww** [comment]
@wiruzman 
Thanks for reporting this issue!
We will look into it.

**Comment by blueww** [comment]
A PR is raised to fix this issue: https://github.com/Azure/Azurite/pull/1252

**Comment by wiruzman** [comment]
When will this be released?

**Comment by blueww** [comment]
@wiruzman 

Normally we will release it together with the next API version upgrade. Should be in about 1-2 month. Not sure if it can meet your requirement?

Before we release, you can also clone the code and start Azurite with the fix by:
https://github.com/Azure/Azurite#github

**Comment by wiruzman** [comment]
We are heavily depending on the docker image as we use it for automation and using table storage. Right now we are depending on Azurite for automation and Microsoft Storage Emulator for table storage. Is it possible to release as a patch?

**Comment by blueww** [comment]
@wiruzman 

We might will have the next release in the mid of next month. 
Will that work for you ?

Before we release, you can also clone the code and build your own npm package:
1. clone the main branch to local
2. npm ci
3. npm run build
4. npm pack
5. npm install -g <lcoalpckname>

**Comment by wiruzman** [comment]
If there is no fast track for bugs then we have no other options.

As I mentioned, we rely on docker images as we have over 50 engineers using the setup. We cannot change the setup and change back later which will be inconvenient in the long run. I could test it locally and verify if it works, but we can only roll it out to over 50 engineers when we have a docker image.

**Comment by blueww** [comment]
The fix is released in Azurite 3.16.0.
