### ISSUE TITLE
Error thrown when trying to delete entity with empty partition/row key

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#1264]
### Which service (blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.14.3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.13.1

### What problem was encountered?
Azurite returns an error when attempting to delete an entity with empty strings for partition/row keys.

### Steps to reproduce the issue?

1. Using @azure/data-tables, add the following entity object to an emulator table:
   ```js
   {
      partitionKey: "",
      rowKey: ""
   }
   ```
2. Attempt to delete the entity.

### Have you found a mitigation/solution?
No. The same procedure is accepted by Azure proper. Empty partition or row keys are valid keys.

**Comment by bhugot** [comment]
Hello I think it's come from a string empty rowkey bug that is corrected but not released yet as the change log is not correct.

**Comment by bhugot** [comment]
Hello @blueww would it be possible to have a new release of azurite to have the fix for this?

**Comment by MatthewSteeples** [comment]
Looks like the release is coming soon... #1334

**Comment by edwin-huber** [comment]
Hi,
This is waiting on PR #1157 
I added a test to ```table.entity.tests.azure.data-tables.ts``` to confirm desired behavior.
I'm hoping we'll be merging the PR very soon.

**Comment by edwin-huber** [comment]
Changes merged, pending next release.

**Comment by edwin-huber** [comment]
Fix released
