### ISSUE TITLE
Table query with parenthesis needs operators enclosed in spaces

### ISSUE THREAD

**Issue by pvones** [Azure/Azurite#1282]
### Which service(blob, file, queue, table) does this issue concern?
table
### Which version of the Azurite was used?
3.14.1
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio Professional 2022
### What's the Node.js version?
16.13.2
### What problem was encountered?
Table query with parenthesis and operators without spaces in between returns HTTP 400 error. It works with both real Azure storage and the deprecated Azure Storage Emulator v5.10
### Steps to reproduce the issue?
Let's have a table with field BoolField of type Boolean.
Following query does not work with Azurite: `(PartitionKey eq '')or(BoolField eq false)`
### Have you found a mitigation/solution?
The query operator must be enclosed in spaces: `(PartitionKey eq '') or (BoolField eq false)`

**Comment by edwin-huber** [comment]
Thanks for reporting, I'm taking a look

**Comment by edwin-huber** [comment]
Changes merged, pending next release.
