### ISSUE TITLE
ETag doesn't change when entity updated in Table service

### ISSUE THREAD

**Issue by haochenghuang** [Azure/Azurite#1286]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
3.15.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
unknown

### What problem was encountered?
ETag doesn't change when entity updated in Table service. ETag in table service use timestamp by default. And seems smallest unit of timestamp in table service is 0.001s. If 2 write operations executed fast in a small period of time. ETag may not update properly.

### Steps to reproduce the issue?
```
await _table.InsertAsync(new DemoEntity("partionKey", "rowKey"), Token);
var e1 = await _table.RetrieveAsync("partionKey", "rowKey", Token);
var e2 = await _table.RetrieveAsync("partionKey", "rowKey", Token);
e2.XXX = "xxx";  // update some value in entity
var result = await _table.MergeAsync(e2, Token);
Assert.AreEqual((int)HttpStatusCode.NoContent, result.HttpStatusCode);  // will pass
var e3 = await _table.RetrieveAsync("partionKey", "rowKey", Token);
Assert.AreEqual("xxx", e3.XXX);  // will pass
Assert.AreNotEqual(e1.ETag, e3.ETag);  // will fail
```
Error message:
```
[INFO] [93]   Error Message:
[INFO] [94]      Expected: not equal to "W/"datetime'2022-01-17T05%3A27%3A10.6390000Z'""
[INFO] [95]   But was:  "W/"datetime'2022-01-17T05%3A27%3A10.6390000Z'""
```

Actually, ETag value will be like `"ETag":"W/\"datetime'2022-01-17T08%3A29%3A47.5220000Z'\"`, part of ETag value is timestamp. However, the accuracy of the timestamp is not enough, is only millisecond level.

### Have you found a mitigation/solution?
This case may pass occasionally, but most time it will fail.
If I sleep some time, for example 1 second, then this case can always pass.

**Comment by edwin-huber** [comment]
Thanks for raising this.
We shall take a look.
