### ISSUE TITLE
Feature request: issue a warning about a port being unavailable when starting Azurite

### ISSUE THREAD

**Issue by hhubik** [Azure/Azurite#1294]
Just spent a few hours getting Azurite to work.  The problem was that another application on my system uses the IP/port `127.0.0.1:10000`, which took a while to figure out.  Everything works perfectly once I specified `127.0.0.1:10003` as the Azurite blob endpoint.

If possible, please check for port conflicts and issue a clear warning to the user if a conflict is detected when an attempt is made to start Azurite services.

**Comment by blueww** [comment]
@hhubik 

Azurite already have code the check port conflict, like when start Azurite with npm, when blob endpoint is occupied, we get following failure:
```
D:\>azurite
Azurite Blob service is starting at http://127.0.0.1:10000
Exit due to unhandled error: listen EADDRINUSE: address already in use 127.0.0.1:10000
```

Would you please follow up the issue template , and give the details of how the issue is repro? Then we can investigate it.

**Comment by hhubik** [comment]
@blueww 
Thanks for the message.  This behavior is fine if Azurite is started from the command line. 
Before installing Azurite through npm,  I had installed the Azurite VS Code extension.  At that time, I could not start Azurite and did not see any error message similar to the one above that would help me solve the problem.  It is however possible that I missed it.

I cannot install the Azurite extension at the moment.  If it is easy for you to verify that the Azurite extension also reports a port conflict that would be great.

**Comment by blueww** [comment]
@hhubik 

I tested to start blob service in VS extension, with the port is occupied. I will see an error message, and when I click the update arrow of the error message to expand it, will see the error as following picture:

![image](https://user-images.githubusercontent.com/6926193/150901488-eb1fbb3b-7d11-457d-94ad-8d73877974c4.png)

**Comment by hhubik** [comment]
That's perfect.  Not being familiar with Azurite, I must have missed it.
