### ISSUE TITLE
How to reset all content from command line?

### ISSUE THREAD

**Issue by sergiojrdotnet** [Azure/Azurite#1295]
### Which service(blob, file, queue, table) does this issue concern?
All of them

### Which version of the Azurite was used?
3.14.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)`
Visual Studio Code Extension

I would like to know if is possible to reset all content by any parameter on initialization of azurite.exe inside Visual Studio extensions folder.

**Comment by blueww** [comment]
@sergiojrdotnet 

For "reset", do you mean clean all storage data in Azurite?
If so, we already have an issue to track it: https://github.com/Azure/Azurite/issues/588

**Comment by sergiojrdotnet** [comment]
Yes, that's it

**Comment by blueww** [comment]
@sergiojrdotnet 
I will close this issue as it's dup with #588.

I have provided a script to clean up Azurite storage data. You can see it in #588.

Feel free to contact us again if you need any further assistance on Azurite.
