### ISSUE TITLE
The average performance of Azurite

### ISSUE THREAD

**Issue by henryfang1989** [Azure/Azurite#131]
Does anyone know the speed of uploading and downloading the blobs? I was running Azurite on a server machine. It turns out the upload speed is around 55MB/s and download speed is around 70MB/s. Since client and server are running on the same machine, why the speed is kinda of slow? Thanks.

**Comment by XiaoningLiu** [comment]
Does your sever use a SSD or HDD?

**Comment by henryfang1989** [comment]
Server uses the SSD

**Comment by XiaoningLiu** [comment]
Hi @henryfang1989 

You may want to have a test for your disk I/O bandwidth. Azurite will persistent the uploaded blob into your local disk. The speed will be limited to the disk I/O.

**Comment by XiaoningLiu** [comment]
Will close this as it's expected.

In recently released Azurite 3.3.0-preview. It supports external SQL based metadata storage, based on that, you can initialize multi Azurite instances with process manager like pm2 to load balance requests to Azurite.

https://github.com/Azure/Azurite/issues/136
