### ISSUE TITLE
Invalid storage account + Nginx reverse proxy + Docker

### ISSUE THREAD

**Issue by Nefcanto** [Azure/Azurite#1313]
**Please know that I have already read many issues, including #1039 and #476, but none of them solved my problem.**

### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
I have no clue, I just use this image:
`mcr.microsoft.com/azure-storage/azurite:latest`

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
I run it inside docker

### What's the Node.js version?
Again, I have no clue, I'm using your official image
`mcr.microsoft.com/azure-storage/azurite:latest`

### What problem was encountered?
I use this `docker-compose.yml` to run a container for Azurite:

```
version: "3.9"
services:
  azure:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: ProjectStorage
    ports:
      - 57017:10000
    volumes:
      - /Temp/Project/Storage:/data
```

Then I use `mkcert` to create a local development certificate for `https://storage.project.local`.

Then I use Nginx to create a reverse proxy to forward requests. Here's my Nginx config:

```
server {
    listen 80;
    server_name storage.project.local;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name storage.project.local;

    ssl_certificate /Temp/Project/Storage/Certificate.pem;
    ssl_certificate_key /Temp/Project/Storage/Key.pem;

    location / {
        proxy_pass http://localhost:57017;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
```

### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

To be honest, I can't figure out how to configure Azurite inside docker from your docs. I don't know how to provide those parameters to the Azurite. Should I add them as environment variables to my docker instance? Should I create a `Dockerfile` and set them in `CMD` command?

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?

No, not yet. I'm still searching and performing trial and error techniques.

**Comment by immigres** [comment]
I have the exact same issue, using the latest azurite docker image. I just switched to an older image (15 months old, I'm not sure about the exact version) and everything works as expected.

**Comment by blueww** [comment]
@Nefcanto , @immigres 

I am not so familiar with Nginx, please make sure Azurite can get the request.

If so, would you please share:
1. The detail failure: the failure message, or it hangs or crash?
2. The command you use to start Azurite with docker
3. The connection string you use to connect to Azurite
4. the Azurite debug log 
To get Debug log , see following command will start azurite with docker , and map "d:/azurite" on local machine to "/data", then save the debug log in "/data/debug.log", so you will get the debug log on local machine "D:\azurite\debug.log"
`docker run  -p 10000:10000 -p 10001:10001 -v d:/azurite:/data mcr.microsoft.com/azure-storage/azurite azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 -d /data/debug.log`

**Comment by blueww** [comment]
@Nefcanto , @immigres
I will close the issue since not get responds from you for a long time.
Feel free to contact us again if need any further assistance.

**Comment by 1k-off** [comment]
@Nefcanto Hey! I'm not sure if this still actual for you, but I did some research and found a solution.
So, let me explain as I understand this.

I have azurite as a windows service (setup with nssm). It can be docker also. Debug log enabled.
The first thing I did - az cli request using http and IP:
```
az storage blob upload -f D:\work\file.tgz --container-name deployments --name test/file.tgz --connection-string "DefaultEndpointsProtocol=http;AccountName=account;AccountKey=cGFzc3dvcmRwYXNzd29yZDEyM3Bhc3N3b3JkCg==;BlobEndpoint=http://192.168.0.17:14000/account;QueueEndpoint=http://192.168.0.17:14001/account;"
```

Works fine. In logs I see the next:
```
info: BlobStorageContextMiddleware: Account=account Container=deployments Blob=test/file.tgz
```

Then I'm setting up nginx with your config and do az cli request using https and fqdns:
```
az storage blob upload -f D:\work\file.tgz --container-name deployments --name test/file.tgz --connection-string "DefaultEndpointsProtocol=https;AccountName=account;AccountKey=cGFzc3dvcmRwYXNzd29yZDEyM3Bhc3N3b3JkCg==;BlobEndpoint=https://blob.domain.tld/account;QueueEndpoint=https://blob.domain.tld/account;"
```

Logs shows error, but interesting is the next:
```
info: BlobStorageContextMiddleware: Account=blob Container=account Blob=deployments/test/file.tgz
```

We can see, we have wrong account and blob. As I can understand, if you want to use URLs - you need to use them as azure do. Like account.blob.domain.tld. So, with the next command and nginx config everything works:
```
az storage blob upload -f D:\work\file.tgz --container-name deployments --name test/file.tgz --connection-string "DefaultEndpointsProtocol=https;AccountName=account;AccountKey=cGFzc3dvcmRwYXNzd29yZDEyM3Bhc3N3b3JkCg==;BlobEndpoint=https://account.blob.domain.tld;QueueEndpoint=https://account.blob-queue.domain.tld;"
```

```
server {
    listen 443 ssl http2;
    server_name blob.domain.tld *.blob.domain.tld;
    ssl_certificate /etc/letsencrypt/live/blob.domain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blob.domain.tld/privkey.pem;
    location / {
        proxy_pass http://192.168.0.17:14000;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
server {
    listen 443 ssl http2;
    server_name blob-queue.domain.tld *.blob-queue.domain.tld;
    ssl_certificate /etc/letsencrypt/live/domain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blob.domain.tld/privkey.pem;
    location / {
        proxy_pass http://192.168.0.17:14001;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
```
