### ISSUE TITLE
VS Code Extension v3.15.0 doesn't support relative directories.

### ISSUE THREAD

**Issue by johnrom** [Azure/Azurite#1316]
### Which service(blob, file, queue, table) does this issue concern?

Applies to all services, in the VS Code Extension.

### Which version of the Azurite was used?

v3.15.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

npm + Visual Studio Code Extension

### What's the Node.js version?

8.16.0

### What problem was encountered?

There was a PR to support relative directories to the current VSCode workspace folder, but it doesn't appear to have made it into the Extension. I'm not seeing the changes in Azurite v3.15.0, even though it appears in the release notes. Did these changes land?

PR with relative path changes:

https://github.com/Azure/Azurite/pull/1153

Release notes including relative directory change:

https://github.com/Azure/Azurite/releases/tag/v3.15.0

> - Fixed an issue in Visual Studio Code extension, by changing the Location with relative path, from base on Visual Studio Code installation path, to base on the current opened workspace folder.

### Steps to reproduce the issue?

- Open VS Code w/ Azurite v3.15.0 Extension.
- Open settings, go to `azurite.location`
  - Note that it is missing the description change from the PR. The author appears to have changed it: 
    https://github.com/Azure/Azurite/pull/1153/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L203-R205
- Enter a relative directory, like:
  - `.azurite`
  - `azurite`
  - `./.azurite`
  - `./azurite`
  - `.\.azurite`
  - `.\azurite`
- Check the output log for a message like the following:
  > Azurite Blob Service starts failed with error: ENOENT: no such file or directory, access 'C:\Program Files\Microsoft VS Code\.azurite' Error: ENOENT: no such file or directory, access 'C:\Program Files\Microsoft VS Code\.azurite'

### Have you found a mitigation/solution?

Keep polluting the project root directory with these files.

**Comment by blueww** [comment]
@johnrom 

Thanks for raising the issue!
Will need some time to look deeper into it.

**Comment by blueww** [comment]
@johnrom

3.15.0 is released on Dec 7, 2021.
But the PR you mentioned is merged on Dec 14, 2021. So it's not in 3.15.0.
It will be in the next Azurite release.

**Comment by blueww** [comment]
The fix https://github.com/Azure/Azurite/pull/1153 is already released in Azurite 3.16.0.
