### ISSUE TITLE
Create table doesn’t work 

### ISSUE THREAD

**Issue by jchannon** [Azure/Azurite#132]
Please see attached image that shows the code connecting to the docker container executed as shown in the readme. The container reports a 501 response creating a table. 

![4405f3d9-1198-4edf-b811-f2f0d5742217](https://user-images.githubusercontent.com/105126/49466070-06ed5500-f7f7-11e8-8c64-2e9a21c023dd.jpeg)

The account key is the same as the sample in the readme. Have also mapped the ports to the same 10000 range but same issue

**Comment by edwin-huber** [comment]
issue should be resolved in latest version of Azurite
