### ISSUE TITLE
Incorrect OData Metadata for single entity response

### ISSUE THREAD

**Issue by gpatryk** [Azure/Azurite#133]
When metadata are requested Azurite always returns odata.metadata = `http://127.0.0.1:10002/devstoreaccount1/$metadata#TableName`. For single entity result is should be `http://127.0.0.1:10002/devstoreaccount1/$metadata#TableName/@Entity`.

**Comment by edwin-huber** [comment]
Need to validate this behavior against the new release

**Comment by edwin-huber** [comment]
Issue still persists in current version.

**Comment by edwin-huber** [comment]
According to Docs: https://docs.microsoft.com/en-us/rest/api/storageservices/insert-entity
odata.metadata will contain:
```json
"odata.metadata":"https://myaccount.table.core.windows.net/Customer/$metadata#Customers/@Element"
```
Updating with this logic
