### ISSUE TITLE
Improve Table Service Performance

### ISSUE THREAD

**Issue by edwin-huber** [Azure/Azurite#1331]
I am actively looking at options to improve performance.
The best option I have found until we check in a change for this is to change the the constructor for LokiTableMetadataStore in  ```src\table\persistence\LokiTableMetadataStore.ts```

You have 2 options.

Turn off persistence:

```typescript
  public constructor(public readonly lokiDBPath: string) {
       this.db = new Loki(lokiDBPath, {
    });
  }
```

Enable the lfsa adapter, which creates files per partition:

```typescript
  public constructor(public readonly lokiDBPath: string) {
    const lfsa = require("../../../node_modules/lokijs/src/loki-fs-structured-adapter.js");
    const lfsaAdapter = new lfsa();
    this.db = new Loki(lokiDBPath, {
      autosave: true,
      adapter: lfsaAdapter
      autosaveInterval: 5000
    });
  }
```

Addresses #1198

**Comment by edwin-huber** [comment]
Dependency on #1061

**Comment by joelverhagen** [comment]
@edwin-huber, from my testing Table didn't get faster in-memory. The slow path for blob and queue was writing extents which is not done at all in tables. LokiJS does not persist immediately upon write so Loki + Table doesn't have disk in the request context, just in a background persist every 5 seconds. Perhaps I am misunderstanding the original issue however.

**Comment by joelverhagen** [comment]
I wrote a blog about my change which describes the perf change: https://www.joelverhagen.com/blog/2023/11/azurite-in-memory

**Comment by edwin-huber** [comment]
> a background persist every 5 seconds. 

It was exactly this IO causing systems to hang, writing large amounts of table data to disk...

**Comment by joelverhagen** [comment]
Makes sense, thanks for clarifying this for me !
