### ISSUE TITLE
Emulator doesn't throw error when creating tables with same name but different casing

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#1355]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
3.15.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.13.1

### What problem was encountered?
The emulator does not respond with an error when creating a table using an existing name with different casing.

For example, if a table named "table01" exists, I expect an error to be returned by the emulator if I try to create a table named "TABLE01".

According to the [Azure documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#table-names), table names are supposed to be case-insensitive.

### Steps to reproduce the issue?

1. Install and run Azurite.
2. Use the Azure SDK for JavaScript to create a table named "table01":
   ```js
   const client1 = TableClient.fromConnectionString("<DEV CONNECTION STRING>", "table01", { allowInsecureConnection: true });
   await client1.createTable();
   ```
3. Use the Azure SDK for JavaScript to create a table named "TABLE01":
   ```js
   const client2 = TableClient.fromConnectionString("<DEV CONNECTION STRING>", "TABLE01", { allowInsecureConnection: true });
   await client2.createTable();
   ```

### Have you found a mitigation/solution?
No

**Comment by edwin-huber** [comment]
Have written tests to cover all these cases.
Should have a PR soon.
