### ISSUE TITLE
Emulator allows forbidden characters in partition and row keys

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#1371]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.16.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.13.1

### What problem was encountered?
The table service allows forbidden characters, such as "#" in partition and row keys, which are explicitly forbidden as detailed in the [Azure documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#characters-disallowed-in-key-fields)

### Steps to reproduce the issue?
Run the following code in Node:
```js
const { TableClient } = require("@azure/data-tables");
const connectionString = "<DEV_CONNECTION_STRING>";
(async () => {
    const client = TableClient.fromConnectionString(connectionString, "test01", { allowInsecureConnection: true });
    try {
        await client.createTable();
        await client.createEntity({ partitionKey: "A", rowKey: "b#" });
    } catch (error) {
        console.error(error);
    }
})();
```

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Thanks @craxal, marked as missing feature for Table support.
