### ISSUE TITLE
Error thrown when trying to delete entity with ' or % characters in partition/row key

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#1377]
### Which service (blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.14.3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.13.1

### What problem was encountered?
Azurite returns an error when attempting to delete an entity with ' or % characters in the partition/row key.

### Steps to reproduce the issue

1. Using @azure/data-tables, add the following entity object to an emulator table:
   ```js
   {
      partitionKey: "test1234'test",
      rowKey: "test1234"
   }
   ```
2. Attempt to delete the entity.

### Have you found a mitigation/solution?
No. The same procedure is accepted by Azure proper. The ' and % characters are valid characters in partition or row keys.

**Comment by XiaoningLiu** [comment]
Thanks @craxal for reporting! This seems a bug to Azurite. We are occupied with other items on hand for now, and will check this later.
