### ISSUE TITLE
No error when creating a table named "tables"

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#1379]
### Which service (blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.14.3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.13.1

### What problem was encountered?
Azurite does not return an error when attempting to create a table named "tables".

### Steps to reproduce the issue

1. Start Azurite
2. Using @azure/data-tables, create a client object connecting to the local emulator.
3. Use the client to create a table named "tables".

### Have you found a mitigation/solution?
No. Azure proper returns an error response. The [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#table-names) also clearly states that "tables" is a reserved table name.

**Comment by XiaoningLiu** [comment]
Service alignment issue.
