### ISSUE TITLE
Connect over https to Azurite fails with RemoteCertificateNameMismatch

### ISSUE THREAD

**Issue by njannink** [Azure/Azurite#1399]
OS: Windows 11
Azurite version: 3.16.0
Env: AspNetCore 6.0

When trying to connect to Azurite which is hosted on https with a dev-cert (pfx) I get the following error:

`The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch`

I have followed the steps from: https://github.com/Azure/Azurite/blob/main/README.md#https-setup but I can't get it to work.

The connection string I use for the `var client = new BlobServiceClient(connectionString);` is

`DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=https://127.0.0.1:10001/devstoreaccount1;TableEndpoint=https://127.0.0.1:10002/devstoreaccount1`

Any idea what is going wrong?

**Comment by njannink** [comment]
If I try to connect using a pem certificate with a key file I get the following connection error:

`"The remote certificate is invalid because of errors in the certificate chain: PartialChain"`

**Comment by blueww** [comment]
@njannink 

For the error "RemoteCertificateNameMismatch", this error occurs when a client system is making a request to the server (i.e. "[https://myserver.com:443/someaction](https://myserver.com/someaction)") and will expect either the Common Name, or one of the values in the Subject Alternative Name field, to look like "myserver.com"

How do you start Azurite？ with npm / docker / VS extension or other ways?
Do you connect to Azurite really with Uri like : https://127.0.0.1/.......
And do you generate the cert with command "mkcert 127.0.0.1"? Does the cert has Common Name or one of the values in the Subject Alternative Name field as "127.0.0.1"?

**Comment by njannink** [comment]
I start azurite from the command line, because thats the same way I would start it in the Azure DevOps integration tests step.

```
azurite --cert .\127.0.0.1.pem --key .\127.0.0.1-key.pem
Azurite Blob service is starting at https://127.0.0.1:10000
Azurite Blob service is successfully listening at https://127.0.0.1:10000
Azurite Queue service is starting at https://127.0.0.1:10001
Azurite Queue service is successfully listening at https://127.0.0.1:10001
Azurite Table service is starting at https://127.0.0.1:10002
Azurite Table service is successfully listening at https://127.0.0.1:10002
```

I generated the certificate using `mkcert 127.0.0.1`

**Comment by njannink** [comment]
I found how to get the certificate working I still needed to run the command `mkcert -install`

**Comment by blueww** [comment]
@njannink 
Good to you the scenarios has worked for you.
Would you please help to close this issue?

Free free to contact us if need any further assistance on azurite.

**Comment by blueww** [comment]
Please make sure the cert is valid, its Common Name, or one of the values in the Subject Alternative Name field, is aligned with the Uri you call Azurite, and the cert root is trusted by the client.
