### ISSUE TITLE
[Question] Have a plan to support NFS support to Blob service?

### ISSUE THREAD

**Issue by kuzukawa** [Azure/Azurite#1434]
We are using Azurite for local development as NFS mounted Azure Blob Storage. However, I suppose Azurite does not have NFS support for now. Do you have a plan for it? 

Thanks.

**Comment by blueww** [comment]
@kuzukawa 
For "NFS mounted Azure Blob Storage", do you mean datalake gen2?
If so, this is already tracked in https://github.com/Azure/Azurite/issues/553.

**Comment by kuzukawa** [comment]
@blueww 
Thanks for your reply. This was about NFS3.0 protocol support for Blob storage on Azurite. I found [this issue](https://github.com/Azure/azure-storage-fuse/issues/240) and [this comment(https://github.com/Azure/azure-storage-fuse/issues/240#issuecomment-439478634).I'll consider plan B. 

Thanks.
