### ISSUE TITLE
Batch Delete Failing

### ISSUE THREAD

**Issue by mattwiz** [Azure/Azurite#1439]
### Which service(blob, file, queue, table) does this issue concern?
table
### Which version of the Azurite was used?
3.16.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
16.14.2
### What problem was encountered?
Trying to delete multiple rows using the batch operation. Same operation works fine with actual table storage. It also worked with Azure Storage Emulator.

### Steps to reproduce the issue?

Code:
```
TableBatchOperation batch = new();
TableQuerySegment<TableData> tableData = await cloudTable.ExecuteQuerySegmentedAsync(rangeQuery, null);

foreach (TableData entity in tableData)
{
    batch.Delete(entity);

    if (batch.Count == 100) // cutoff at 100 to not exceed batch limits
    {
        await cloudTable.ExecuteBatchAsync(batch);
        batch.Clear();
    }
}

if (batch.Any())
{
    await cloudTable.ExecuteBatchAsync(batch); // <- error thrown here
}
```
Log output:
```
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:03.71]     Function.TestCleanup [FAIL]
  Failed Function.TestCleanup [43 ms]
  Error Message:
   Microsoft.Azure.Cosmos.Table.StorageException : Element 0 in the batch returned an unexpected response code.
  Stack Trace:
     at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken callerCancellationToken)
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No

**Comment by mattwiz** [comment]
I have to add here that it seems to work under Windows with the Azure.Cosmos.Table library but not under Ubuntu.

**Comment by edwin-huber** [comment]
Are you running the same version of NodeJs on both?

**Comment by mattwiz** [comment]
Yes, v16.14.2. I'm using the default Microsoft-hosted agents that are offered through Azure DevOps.

**Comment by MatthewSteeples** [comment]
I think we're getting a similar problem. I've managed to get to the stack trace of it, and it appears that there's an empty line (null) returned in the response where one isn't expected

![image](https://user-images.githubusercontent.com/255971/165944090-a5c9ce36-6bcf-4b4a-b2c3-8a33a00cf6b3.png)

**Comment by MatthewSteeples** [comment]
Actually, I've just realised that this may not be the same issue for us. Ours is new with 3.17 (and 3.17.1). If the above doesn't help I can create a new issue
