### ISSUE TITLE
close() method of AzuriteBlob, AzuriteQueue and AzuriteTable won't wait for resolution

### ISSUE THREAD

**Issue by poveden** [Azure/Azurite#144]
Currently, the `close()` methods for `AzuriteBlob`, `AzuriteQueue` and `AzuriteTable`, although they return a `Promise`, the code within the promise won't await for the methods called within it:

https://github.com/Azure/Azurite/blob/f3dccf71dae73d1af8bc355e39c215515a322d4f/lib/AzuriteBlob.js#L86-L92

https://github.com/Azure/Azurite/blob/f3dccf71dae73d1af8bc355e39c215515a322d4f/lib/AzuriteQueue.js#L58-L62

https://github.com/Azure/Azurite/blob/f3dccf71dae73d1af8bc355e39c215515a322d4f/lib/AzuriteTable.js#L65-L71

Issues:

- `this.server.close()` expects a callback that will be called on completion. It should be promisified.
- Both `storageManager.flush()` and `tableStorageManager.flush()` return the promise of `db.saveDatabaseAsync()`, but is not awaited for.
- Both `storageManager.close()` and `tableStorageManager.close()` return the results of `db.close()`, but it should really return the results of `db.closeAsync()`.

Finally, where more than 1 method is called, they should be wrapped with `BbPromise.all()`.

If I'm not missing anything, then I could prepare a PR for you.

**Comment by XiaoningLiu** [comment]
@poveden A PR is welcome!

**Comment by XiaoningLiu** [comment]
Will close this issue as PR solved. And please try with latest Azurite V3.
