### ISSUE TITLE
Allow server instances to run on OS-assigned unused ports

### ISSUE THREAD

**Issue by poveden** [Azure/Azurite#145]
Node.js' [`Server.listen()`](https://nodejs.org/dist/latest-v10.x/docs/api/net.html#net_server_listen_port_host_backlog_callback) allows passing `0` as a port number, so the operating system assigns an arbitrary unused port. However, the current `env.init()` implementation won't allow it as `0` is "falsy":

https://github.com/Azure/Azurite/blob/f3dccf71dae73d1af8bc355e39c215515a322d4f/lib/core/env.js#L40-L42

Allowing a `0` to be passed and used would allow scenarios where fixed port number availability is not known, or where multiple, parallelized instances are being run (e.g. test suites).

A possible solution would be creating a helper function:

```js
function normalizePort(port, defaultPort) {
  if (port === 0) {
    return port;
  }

  return defaultPort;
}
```

and change the above lines to:

```js
this.blobStoragePort = normalizePort(options.p || options.blobPort, 10000);
this.queueStoragePort = normalizePort(options.q || options.queuePort, 10001);
this.tableStoragePort = normalizePort(options.t || options.tablePort, 10002);
```

**Comment by XiaoningLiu** [comment]
That sounds good, can you make a PR?

**Comment by kfarmer-msft** [comment]
Out of curiosity, how would a client discover the port number for use in a test?

**Comment by XiaoningLiu** [comment]
@kfarmer-msft  Default ports will be used without specified configurations when starting Azurite.

**Comment by poveden** [comment]
> Out of curiosity, how would a client discover the port number for use in a test?

@kfarmer-msft While running from the command line, the output will tell you the assigned ports:

```shell
$ azurite -p 0 -q 0 -t 0

 _______                   _
(_______)                 (_)  _
 _______ _____ _   _  ____ _ _| |_ _____
|  ___  (___  ) | | |/ ___) (_   _) ___ |
| |   | |/ __/| |_| | |   | | | |_| ____|
|_|   |_(_____)____/|_|   |_| \__)_____)

Azurite, Version 2.7.0
A lightweight server clone of Azure Storage

Azure Table Storage Emulator listening on port 55292
Azure Queue Storage Emulator listening on port 55293
Azure Blob Storage Emulator listening on port 55294
```

If started programmatically, calling Node.js' [`Server.address()`](https://nodejs.org/docs/latest/api/net.html#net_server_address) will give you the bound endpoint:

```js
const queue = new AzuriteQueue();
await queue.init({ queuePort: 0 });
const port = queue.server.address().port;
```

**Comment by kfarmer-msft** [comment]
For the sake of non-NodeJS callers (eg, test harnesses for C++, C#, Java, Python, ...), I might suggest a command-line argument to report the version and endpoints in a more machine-readable structure such as JSON or XML, rather than the current output format.  Parsing unstructured output can be problematic.

**Comment by XiaoningLiu** [comment]
Azurite V3 support OS-assigned unused ports when 0 passed as `blobPort` parameter value. @kfarmer-msft    thanks for suggestion!

**Comment by edwin-huber** [comment]
closing resolved issue
