### ISSUE TITLE
Version 3.17 won't allow a comma in a table's RowKey

### ISSUE THREAD

**Issue by danielearwicker** [Azure/Azurite#1458]
### Which service(blob, file, queue, table) does this issue concern?

Table

### Which version of the Azurite was used?

3.17

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

https://hub.docker.com/_/microsoft-azure-storage-azurite

### What's the Node.js version?

As in docker image

### What problem was encountered?

Inserting a row where the RowKey has a comma produces InvalidInput error

### Steps to reproduce the issue?

Using Storage Explorer, try adding a row to a table with a comma in the RowKey (nb. this issue is not specific to using Storage Explorer as client).

### Have you found a mitigation/solution?

Pinning to 3.16 for now, which is fine. (Note that real storage accounts are also fine with comma in RowKey.)

**Comment by edwin-huber** [comment]
Thanks for raising this, I am looking into it.
