### ISSUE TITLE
ResourceAlreadyExistException when creating a new table with a name that's a substring of another table

### ISSUE THREAD

**Issue by jpcrs** [Azure/Azurite#1484]
### Which service(blob, file, queue, table) does this issue concern?
- Table

### Which version of the Azurite was used?
- 3.17 / 3.17.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
- npm

### What problem was encountered?
- I get a ResourceAlreadyExistException when creating the second table that the name is a substring of an already existing table

### Steps to reproduce the issue?
1. Create a table, ex: `MyTable`
2. Create a second table with a substring of an already existing table, ex: `My`

### Have you found a mitigation/solution?
Maybe related to the regex check if the table name already is being used, as introduced in this change:
https://github.com/Azure/Azurite/blob/124ed540cffc72564f5cf44d07f693fba936d439/src/table/persistence/LokiTableMetadataStore.ts#L131

It should be:
```
table: { $regex: [String.raw`\b${tableModel.table}\b`, "i"] }
```

### Code snippet to replicate on Loki Sandbox
https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm
```javascript
var oldTableName = "MyTable";
var newTableName = "My";
//Init collection
var db = new loki('sandbox.db');
var items = db.addCollection('tables');
items.insert({ name : oldTableName });

//Query
var currentQuery = items.findOne({'name': { '$regex': [newTableName, 'i'] }});
var newQuery = items.findOne({'name': { '$regex': [String.raw`\b${newTableName}\b`, "i"] }});
var newQuery2 = items.findOne({'name': { '$regex': [String.raw`\b${oldTableName}\b`, "i"] }});

//Log
logText('Current Query')
logObject(currentQuery);
logText('New Query')
logObject(newQuery)
logText('New Query with old table anem')
logObject(newQuery2)
inspectObject(db);
```

**Comment by edwin-huber** [comment]
Thanks for catching this.
I shall correct ASAP
