### ISSUE TITLE
"FeatureNotSupported" error on BlockBlobClient.exists() using emulator

### ISSUE THREAD

**Issue by nina03-ops** [Azure/Azurite#1486]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.17.1
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
14.10.1
### What problem was encountered?
Trying to create a test that uses azurite emulator. The test checks for BlockBlobClient.exists(). At this point I get "errorCode": "FeatureNotSupported". 
### Steps to reproduce the issue?
1. call BlockBlobClient.exists()
2. see error with the following details:
 "details": {
        "errorCode": "FeatureNotSupported",
        "connection": "keep-alive",
        "date": "Mon, 09 May 2022 11:49:01 GMT",
        "keep-alive": "timeout=5",
        "server": "Azurite-Blob/3.17.1",
        "x-ms-request-id": "..."
      },
If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
@[nina03-ops](https://github.com/nina03-ops)

I can't repro this issue on Azurite 3.17.1 with Azure.Storage.Blobs 12.11.0, by call BlockBlobClient.exists().
Would you please attach the debug log of Azurite for this issue?

**Comment by nina03-ops** [comment]
> @[nina03-ops](https://github.com/nina03-ops)
> 
> I can't repro this issue on Azurite 3.17.1 with Azure.Storage.Blobs 12.11.0, by call BlockBlobClient.exists(). Would you please attach the debug log of Azurite for this issue?
[debug.log](https://github.com/Azure/Azurite/files/8653052/debug.log)

**Comment by blueww** [comment]
@nina03-ops 

From the debug log, you can see 
> x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter "--loose" or Visual Studio Code configuration "Loose".

The error is caused by "x-ms-encryption-algorithm" is not supported by Azurite, you can start Azurite with --loose to workaround it.

BTW, this is a known issue tracked by https://github.com/Azure/Azurite/issues/676.

**Comment by nina03-ops** [comment]
it works with --loose, thank you
