### ISSUE TITLE
ListBlobsHierarchySegment Returns Incorrect Results

### ISSUE THREAD

**Issue by emarnadi-instabase** [Azure/Azurite#1491]
### Which service(blob, file, queue, table) does this issue concern?
Blob Service
### Which version of the Azurite was used?
1.16.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio Code extension and Docker
### What's the Node.js version?
6.14.6
### What problem was encountered?
ListBlobsHierarchySegment returns the incorrect number of results and the wrong marker with nested structures
### Steps to reproduce the issue?
Set up a directory structure like the following: 
- root/dir1/
- root/dir2/
- root/dir3/
- root/dir4/
- root/dir1/subdir1/
- root/dir1/subdir2/
- root/dir1/subdir3/
- root/dir1/subdir4/
If you call ListBlobsHierarchySegment with a prefix "root/", delimiter "/", and maxResults of 4, we would expect the list of {dir1/,dir2/,dir3/,dir4/}. However, dir1's subdirectories are included in the count, so only dir1/ would be returned.

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No

**Comment by avoltz** [comment]
I ran into this as well and submitted a fix. You may want to try building the image from main branch.

The fix was here: https://github.com/Azure/Azurite/pull/1488

**Comment by blueww** [comment]
Close this issue as the fix PR is already merged.
