### ISSUE TITLE
Table Service: Replace operation for non-existent entity with wildcard ETag returning 204 instead of 404

### ISSUE THREAD

**Issue by ReubenBond** [Azure/Azurite#1493]
### Which service(blob, file, queue, table) does this issue concern?

Table

### Which version of the Azurite was used?

Azurite-Table 3.17.1, according to the response headers.

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Microsoft Container Registry (mcr.microsoft.com/azure-storage/azurite:latest)

### What's the Node.js version?

Unsure, it's whatever is in that container.

### What problem was encountered?

A discrepancy between Azure Table Storage and Azurite: when using the Azure SDK for .NET and attempting to replace or merge an entity which was never inserted into the table, like so:

``` C#
// NOTE: Merge yields the same erroneous behavior as Replace
var opResult = await Table.UpdateEntityAsync(entity, new ETag("*"), TableUpdateMode.Replace);
```

We are observing that Azurite returns a 204 (inserting the value), but Azure Table Service fails with a 404 as expected (the data is being replaced but is not present to begin with).

### Steps to reproduce the issue?

Something like this, perhaps. If there is a way to enable debug logs for the container, I can do that and report back with them.

```
POST http://127.0.0.1:10002/devstoreaccount1/UnitTestAzureData(PartitionKey='PK-AzureTableDataManagerTests-0655f5a6-0b98-411a-9f87-1904e68719f2',RowKey='RK-003bfce3-5032-4ece-a77a-15822871c500')?$format=application%2Fjson%3Bodata%3Dminimalmetadata HTTP/1.1
x-ms-version: 2019-02-02
DataServiceVersion: 3.0
If-Match: *
Accept: application/json
Content-Type: application/json

{"Data":null,"StringData":"JustData","PartitionKey":"PK-AzureTableDataManagerTests-0655f5a6-0b98-411a-9f87-1904e68719f2","RowKey":"RK-003bfce3-5032-4ece-a77a-15822871c500"}
```

We have a test case which fails on Azurite but not Azure Table Service here: https://github.com/dotnet/orleans/blob/4570a2a5a8a7ca65b13031010fc994bcfede484f/test/Extensions/TesterAzureUtils/AzureTableDataManagerTests.cs#L77

### Have you found a mitigation/solution?

We can disable these tests when Azurite is being used.

**Comment by edwin-huber** [comment]
Hi,
are you sure that this is the root cause of the error?
Looking at the request your code is making, it is an insert.
Insert (POST) is expected to succeed if the entity is not there.
https://docs.microsoft.com/en-us/rest/api/storageservices/insert-entity
I have quite a bit on my plate, but I'll try the same request against the service and validate the behavior.
We are aiming for service parity, but this request should succeed based on the information you share above.
