### ISSUE TITLE
No Bad Request when using invalid characters in key fields

### ISSUE THREAD

**Issue by Vivelin** [Azure/Azurite#150]
According to [Understanding the Table Service Data Model](https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-the-Table-Service-Data-Model#characters-disallowed-in-key-fields), there are a couple of characters that are not allowed in the PartitionKey or RowKey. Doing so will cause a `Bad Request - Error in query syntax` error to be returned on Table operations. 

However, in my local development testing with Azurite, this never occurred. I had been using Base64-encoded hashes as key fields, but these may contain the disallowed `/` character. I didn't see my mistake until this was published to Azure. I believe Azurite should behave the same way and issue a 400 response when disallowed characters are used in either key field.

Please note that I have not investigated the other, similar requirements on table names and property names.

**Comment by edwin-huber** [comment]
This behavior needs to be validated against the new api

**Comment by edwin-huber** [comment]
New Table API version filters / rejects invalid characters in row and partition keys.
see: tests\table\apis\table.entity.rest.test.ts
