### ISSUE TITLE
Azurite fails to return / store correct MD5 when data is uploaded in blocks with leasing turned on

### ISSUE THREAD

**Issue by vigneashs** [Azure/Azurite#1511]
### Which service(blob, file, queue, table) does this issue concern?
Blob service fails to respond with valid MD5 content header.
### Which version of the Azurite was used?
V3.17.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual studio code extension / NuGet (we package executables)
### What's the Node.js version?
v10.24.1

### What problem was encountered?

Operations performed:
1) Create an empty file in a container
2) Acquire lease for this file
3) Upload files in a blocks in either a multi-thread or single thread
4) Set the block list sequence 
5) Try downloading the file, it would fail - due to an invalid checksum (MD5) on the file. Even though the file is intact and has no integrity issues.
 
### Steps to reproduce the issue?

Attaching an example to reproduce this issue.
[blob-v11.zip](https://github.com/Azure/Azurite/files/8765419/blob-v11.zip)

### Have you found a mitigation/solution?
We found that we can disable MD5 validation, but there is a problem here. How will we validate the integrity of the file ?

**Comment by blueww** [comment]
@[vigneashs](https://github.com/vigneashs)

I can repro the MD5 error on both Azurite and public Azure with your program. 
And differ from you, I can even repo it with or without blob lease.

And the Blob contentMD5 is set from client side, instead generate on server.  (see network trace below)
It looks client set a wrong contentMD5 in putblocklist (it looks always set "1B2M2Y8AsgTpgAmY7PhCfg==")
But I see you use deprecated blob SDK (Microsoft.Azure.Storage.Blob, Version=11.2.3.0). 
Would you like to migrate to new SDK https://www.nuget.org/packages/Azure.Storage.Blobs/, and see if the issue still repro? (old and new SDK has breaking change)

Following is network trace for the putblocklist request to set contentMd5:

```
PUT [https://***.blob.core.windows.net/quickstartblobsb23aafe2-9677-4bd5-bd02-244d4739c769/QuickStart_376424de-bd65-4336-9d0a-f5fe4ea4e649.txt?comp=blocklist](https://%2A%2A%2A.blob.core.windows.net/quickstartblobsb23aafe2-9677-4bd5-bd02-244d4739c769/QuickStart_376424de-bd65-4336-9d0a-f5fe4ea4e649.txt?comp=blocklist) HTTP/1.1
Host: weirp1.blob.core.windows.net
x-ms-blob-content-md5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-ms-lease-id: c03180ee-b8cb-4933-946d-fe856d7591b9
x-ms-client-request-id: 34eabe74-7bc0-4ba8-84c9-cdcd4dc2bee0
User-Agent: Azure-Storage/11.2.3 (.NET Core; Win32NT 10.0.19044.0)
x-ms-version: 2019-07-07
x-ms-date: Wed, 01 Jun 2022 03:33:24 GMT
Authorization: SharedKey ***
Content-Length: 1240

<?xml version="1.0" encoding="utf-8"?><BlockList><Latest>T2Zmc2V0XzAwMDAwMDAwMDAwMDAwMA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDAwNDE5NDMwNA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDAwODM4ODYwOA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDAxMjU4MjkxMg==</Latest><Latest>T2Zmc2V0XzAwMDAwMDAxNjc3NzIxNg==</Latest><Latest>T2Zmc2V0XzAwMDAwMDAyMDk3MTUyMA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDAyNTE2NTgyNA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDAyOTM2MDEyOA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDAzMzU1NDQzMg==</Latest><Latest>T2Zmc2V0XzAwMDAwMDAzNzc0ODczNg==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA0MTk0MzA0MA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA0NjEzNzM0NA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA1MDMzMTY0OA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA1NDUyNTk1Mg==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA1ODcyMDI1Ng==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA2MjkxNDU2MA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA2NzEwODg2NA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA3MTMwMzE2OA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA3NTQ5NzQ3Mg==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA3OTY5MTc3Ng==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA4Mzg4NjA4MA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA4ODA4MDM4NA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA5MjI3NDY4OA==</Latest><Latest>T2Zmc2V0XzAwMDAwMDA5NjQ2ODk5Mg==</Latest></BlockList>
HTTP/1.1 201 Created
Content-Length: 0
Last-Modified: Wed, 01 Jun 2022 03:34:17 GMT
ETag: "0x8DA437F9B9FD431"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 94bb4fed-401e-001a-5c68-75bb1d000000
x-ms-client-request-id: 34eabe74-7bc0-4ba8-84c9-cdcd4dc2bee0
x-ms-version: 2019-07-07
x-ms-content-crc64: 2nlKlje2C2U=
x-ms-request-server-encrypted: true
Date: Wed, 01 Jun 2022 03:34:17 GMT



```

**Comment by vigneashs** [comment]
@blueww , thanks for your findings. 

I was able to replica the same problem with my end.  .Net 11 SDK has a bug with MD5 caching when using UploadFromByteArray API, it doesn't clear off MD5 on subsequent block blob operations resulting in this bug. 

Since .Net 11 SDK is deprecated, I am closing this issue and we have found a mitigation which is by disabling MD5 validation on the client.
