### ISSUE TITLE
contentMd5 is missing while downloading the file

### ISSUE THREAD

**Issue by abhishekkrm** [Azure/Azurite#152]
I have uploaded a blob(CONTENTS) with md5 sum in Azurite docker emulator 

While downloading the file md5sum is missing.
bash-4.4# az storage blob download -c flamebox --file CONTENTS --name 21m/1Pi92g3YC90OKpT3fGrPKRjFryPd_ZrTTcEz-09yoAM/3e43c5aa-34a9-e344-94b5-3e92f8c36416/CONTENTS
Finished[#############################################################]  100.0000%
{
  "content": null,
  "deleted": false,
  "metadata": {},
  "name": "21m/1Pi92g3YC90OKpT3fGrPKRjFryPd_ZrTTcEz-09yoAM/3e43c5aa-34a9-e344-94b5-3e92f8c36416/local/snapshot_1/CONTENTS",
  "properties": {
    "appendBlobCommittedBlockCount": null,
    "blobTier": null,
    "blobTierChangeTime": null,
    "blobTierInferred": false,
    "blobType": "BlockBlob",
    "contentLength": 469,
    "contentRange": "bytes 0-468/469",
    "contentSettings": {
      "cacheControl": null,
      "contentDisposition": null,
      "contentEncoding": null,
      "contentLanguage": null,
      **"contentMd5": "undefined",**
      "contentType": "application/octet-stream"
    },
    "copy": {
      "completionTime": null,
      "id": null,
      "progress": null,
      "source": null,
      "status": null,
      "statusDescription": null
    },
    "creationTime": null,
    "deletedTime": null,
    "etag": "\"YDjZvBfopF412O8H2a3GqP4uynQ\"",
    "lastModified": "2019-02-14T00:07:55+00:00",
    "lease": {
      "duration": null,
      "state": null,
      "status": null
    },
    "pageBlobSequenceNumber": null,
    "remainingRetentionDays": null,
    "serverEncrypted": null
  },
  "snapshot": null
}

However if i list the file using prefix listing, i can see the proper md5sum
bash-4.4# az storage blob list -c flamebox --prefix 21m
[
  {
    "content": null,
    "deleted": false,
    "metadata": null,
    "name": "21m/1Pi92g3YC90OKpT3fGrPKRjFryPd_ZrTTcEz-09yoAM/3e43c5aa-34a9-e344-94b5-3e92f8c36416/CONTENTS",
    "properties": {
      "appendBlobCommittedBlockCount": null,
      "blobTier": null,
      "blobTierChangeTime": null,
      "blobTierInferred": false,
      "blobType": "BlockBlob",
      "contentLength": 469,
      "contentRange": null,
      "contentSettings": {
        "cacheControl": null,
        "contentDisposition": null,
        "contentEncoding": null,
        "contentLanguage": null,
        "contentMd5": "eaWQrsAaPwEGZMam7njcPA==",
        "contentType": "application/octet-stream"
      },
      "copy": {
        "completionTime": null,
        "id": null,
        "progress": null,
        "source": null,
        "status": null,
        "statusDescription": null
      },
      "creationTime": null,
      "deletedTime": null,
      "etag": "YDjZvBfopF412O8H2a3GqP4uynQ",
      "lastModified": "2019-02-14T00:07:55+00:00",
      "lease": {
        "duration": null,
        "state": "available",
        "status": "unlocked"
      },
      "pageBlobSequenceNumber": null,
      "remainingRetentionDays": null,
      "sequenceNumber": null,
      "serverEncrypted": false
    },
    "snapshot": null
  }
]

Any suggestion why i am facing this weird behavior ???

**Comment by rodgarcialima** [comment]
And I'm getting this:

```
BlobResult {
  container: 'fingerprints',
  name: '1009',
  lastModified: 'Tue, 19 Mar 2019 17:04:15 GMT',
  etag: '"nRr1nsiyidbjHcJ/1Rfoyw6hBJA"',
  contentLength: '0',
  requestId: '065d4c70-4a69-11e9-9c5c-3dfa17b06e3d' 
}
```

**Comment by XiaoningLiu** [comment]
Hi @abhishekkrm  @rodgarcialima  We recently release latest V3 preview, please have a try :)

**Comment by XiaoningLiu** [comment]
Please try with Azurite V3 which has this feature support. Will close this issue.
