### ISSUE TITLE
BlobClient.query_blob(...)  & BlockBlobClient.Query(...) result in "Bad Request"

### ISSUE THREAD

**Issue by DonnyWhoLovedBowling** [Azure/Azurite#1535]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
17.1
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
tried both Visual Studio 2022 & npm
### What's the Node.js version?
16.15.1
### What problem was encountered?
When querying a blob, you get a "bad request" from Azurite, in Python:
blobClient.query_blob("SELECT * FROM BlobStorage")
In C#:
blockBlobClient.Query("SELECT * FROM BlobStorage");

I tried this in both Python and in C#, with different .csv files including one from https://www.stats.govt.nz/large-datasets/csv-files-for-download/

### Steps to reproduce the issue?

I can provide full (Python/C#) +data code that reproduces this problem. For me it happened with every possible way in creating a blobClient and executing query_blob. 

### Have you found a mitigation/solution?
No.

**Comment by blueww** [comment]
@DonnyWhoLovedBowling 

Blob Query is still not supported by Azurite, see https://github.com/Azure/Azurite#support-matrix

**Comment by DonnyWhoLovedBowling** [comment]
Oh, thanks for pointing this out! I searched the whole Internet for
something like this,  but somehow overlooked this matrix.

Op do 9 jun. 2022 18:16 schreef Wei Wei ***@***.***>:
