### ISSUE TITLE
Could you provide an ARM build of the Docker images?

### ISSUE THREAD

**Issue by kdambekalns** [Azure/Azurite#1556]
It builds just fine with Docker Desktop for Mac on an M1, but it would be more convenient to be able to simply pull it from Docker Hub. 😎

**Comment by bpossolo** [comment]
+1 would love to get a native arm build for our apple silicon!

<img width="358" alt="Screen Shot 2022-06-25 at 6 56 35 PM" src="https://user-images.githubusercontent.com/984705/175796126-cfdbb11c-252e-44dd-bbe5-0c76793e124e.png">
.

**Comment by as206em** [comment]
Yup it will be great if you push native ARM build image

**Comment by blueww** [comment]
@kdambekalns , @as206em 
I have released ARM64 docker image from 3.19.0.
