### ISSUE TITLE
Azure.RequestFailedException: 'Service request failed. Status: 500 (Internal Server Error)  Headers: Server: Azurite-Blob/3.17.1

### ISSUE THREAD

**Issue by mciprijanovic** [Azure/Azurite#1557]
I have Azurite shipped with Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 2.0
The behavior is  the  following: when I start Visual studio which has the project that contains the reference to BLOB storage emulated locally, I see in the output console the message that Azurite started successfully and that it is listening on appropriate ports. Great. Now when I run my project, I get the following exception in the class that I don't even know where it is (can't be located by Vsual Studio shortcut CTRL+[+s):

_Azure.RequestFailedException: 'Service request failed.
Status: 500 (Internal Server Error)
Headers:
Server: Azurite-Blob/3.17.1_

Looks like Azurite is not accessible. But, if I start Azurite by command from cmd prompt before running the VS2022, then, when I start VS2022, the output console says that Azurite can not start on the default ports (which is OK since I already started Azurite which is now holding those ports) but then I do not get exception, and all works OK.

I have node version: v14.17.0

So, steps to reproduce the issue are:
1. Start VS2022
2. Run the project
3. Exception occurs

But if you run Azurite before VS2022, no exception.

The class and the method where exception occurs is:

`namespace Microsoft.Azure.WebJobs.Host.Config
{
    /// <summary>
    /// Context object passed to <see cref="IExtensionConfigProvider"/> instances when
    /// they are initialized.
    /// </summary>
    public class ExtensionConfigContext : FluentConverterRules<Attribute, ExtensionConfigContext>
    {

        // List of actions to flush from the fluent configuration. 
        private List<Action> _updates = new List<Action>();

        // Map of tyepof(TAttribute) --> FluentBindingRule<TAttribute>
        private readonly Dictionary<Type, object> _rules = new Dictionary<Type, object>();
        private readonly IConfiguration _configuration;
        private readonly IConverterManager _converterManager;
        private readonly IWebHookProvider _webHookProvider;
        private readonly IExtensionRegistry _extensionRegistry;
        private readonly INameResolver _nameResolver;

        public ExtensionConfigContext(IConfiguration configuration, INameResolver nameResolver, IConverterManager converterManager, IWebHookProvider webHookProvider, IExtensionRegistry extensionRegistry)
        {
            _configuration = configuration;
            _converterManager = converterManager;
            _webHookProvider = webHookProvider;
            _extensionRegistry = extensionRegistry;
            _nameResolver = nameResolver;
        }

        internal IExtensionConfigProvider Current { get; set; }

        internal override ConverterManager ConverterManager => (ConverterManager)_converterManager;

        /// <summary>
        /// Get a fully qualified URL that the host will resolve to this extension 
        /// </summary>
        /// <returns>null if http handlers are not supported in this environment</returns>
        /// $$$ Shouldn't be here
        [Obsolete("preview")]
        public Uri GetWebhookHandler()
        {
            if (_webHookProvider == null)
            {
                return null;
            }
            return _webHookProvider.GetUrl(this.Current);
        }`

This last method crashes. which: shouldn't be here :)

**Comment by blueww** [comment]
@[mciprijanovic](https://github.com/mciprijanovic)

Would you please share the Azurite debug log, or we don't know why the 500 error return?
You can avoid start Azurite in VS, and start it by run the Azurite executable in VS (The executable's location is `[VS 2022 dir]\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe`)
 You can run it by the following command to get debug log: `azurite.exe --skipApiVersionCheck --debug [log file location]`
If the issue can repro, please share the debug log.

Besides that, would you please share the detail error code and error message of the error besides the status code 500?

**Comment by blueww** [comment]
@[mciprijanovic](https://github.com/mciprijanovic)

I will close this issue as not get further responds form you.
Feel free to contact us again if need further assistance on Azurite.
