### ISSUE TITLE
Documentation for AZURITE_ACCOUNTS environment variable doesn't state that storage account key needs to be Base64-encoded

### ISSUE THREAD

**Issue by pcgeek86** [Azure/Azurite#1568]
### Which version of the Azurite was used?

Latest 

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Docker Hub

### What problem was encountered?

Documentation for AZURITE_ACCOUNTS environment variable doesn't state that storage account key needs to be Base64-encoded

### Steps to reproduce the issue?

This fails:

```
docker run --publish 10000:10000 --env AZURITE_ACCOUNTS="trevor:mykey" --rm -it mcr.microsoft.com/azure-storage/azurite
```

This works:

```
docker run --publish 10000:10000 --env AZURITE_ACCOUNTS="trevor:bXlrZXkK" --rm -it mcr.microsoft.com/azure-storage/azurite
```

### Have you found a mitigation/solution?

Yes, use Base64 encoding for the `AZURITE_ACCOUNTS` environment variable. It just needs to be documented.

**Comment by blueww** [comment]
@[pcgeek86](https://github.com/pcgeek86)

I have raised PR https://github.com/Azure/Azurite/pull/1570 to add the info to Azurite readme doc.
Please help to review it.

**Comment by blueww** [comment]
@[pcgeek86](https://github.com/pcgeek86)

Thanks for raising the issue!
The fix PR is already merged.

Feel free to contact us again if need any further assistance on Azurite.
