### ISSUE TITLE
Better document usage of `disableProductStyleUrl` for the docker setup

### ISSUE THREAD

**Issue by gsouf** [Azure/Azurite#1583]
### Which service(blob, file, queue, table) does this issue concern?

Blob

### Which version of the Azurite was used?

Docker / Tag 3.18.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

mcr.microsoft.com

### What's the Node.js version?

The one in the provided docker container

### What problem was encountered?

I can use the docker version of azurite using the host machine, but not when using a container from the stack.
It will reach the azurite server but it will return an http 400 with no error message.

### Steps to reproduce the issue?

With the following docker-compose file:

```
version: "3.5"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - service.azurite
    volumes:
      - ./:/test:cached
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.18.0
    volumes:
      - ./volumes/azurite-data:/data
```

run `docker-compose up`, it will output

```
service.azurite_1  | Azurite Blob service is starting at http://0.0.0.0:10000
service.azurite_1  | Azurite Blob service is successfully listening at http://0.0.0.0:10000
service.azurite_1  | Azurite Queue service is starting at http://0.0.0.0:10001
service.azurite_1  | Azurite Queue service is successfully listening at http://0.0.0.0:10001
service.azurite_1  | Azurite Table service is starting at http://0.0.0.0:10002
service.azurite_1  | Azurite Table service is successfully listening at http://0.0.0.0:10002
```

use the following js file in the main container:

```
const { Aborter, ServiceURL, StorageURL, SharedKeyCredential, ContainerURL } = require('@azure/storage-blob');

const account = 'devstoreaccount1';
const accountKey = 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==';
const serviceBaseURL = 'http://service.azurite:10000/devstoreaccount1';
const sharedKeyCredential = new SharedKeyCredential(account, accountKey);
const pipeline = StorageURL.newPipeline(sharedKeyCredential);

const serviceURL = new ServiceURL(serviceBaseURL, pipeline);

serviceURL
  .listContainersSegment(Aborter.none)
  .then(r => console.log(r))
  .catch(e => console.log('error:', e));
```

Run this js code in the `test` container using nodejs.

In the azurite docker logs we can see that the server has a hit:

```
service.azurite_1   | 172.19.0.5 - - [04/Jul/2022:19:39:46 +0000] "GET /devstoreaccount1?comp=list HTTP/1.1" 400 -
```

But the js outputs the following error:

```
error: RestError
    at new RestError (/test/node_modules/@azure/ms-rest-js/dist/msRest.node.js:2480:28)
    at /test/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3687:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: undefined,
  statusCode: 400,
  request: WebResource {
    streamResponseBody: false,
    url: 'http://service.azurite:10000/devstoreaccount1?comp=list',
    method: 'GET',
    headers: HttpHeaders { _headersMap: [Object] },
    body: undefined,
    query: undefined,
    formData: undefined,
    withCredentials: false,
    abortSignal: Aborter {
      onabort: null,
      _aborted: false,
      children: [],
      abortEventListeners: [],
      parent: undefined,
      key: undefined,
      value: undefined
    },
    timeout: 0,
    onUploadProgress: undefined,
    onDownloadProgress: undefined,
    proxySettings: undefined,
    keepAlive: true,
    agentSettings: undefined,
    redirectLimit: undefined,
    operationSpec: {
      httpMethod: 'GET',
      urlParameters: [Array],
      queryParameters: [Array],
      headerParameters: [Array],
      responses: [Object],
      isXML: true,
      serializer: [Serializer]
    }
  },
  response: {
    body: '',
    headers: HttpHeaders { _headersMap: [Object] },
    status: 400
  },
  body: undefined
}

```

### Have you found a mitigation/solution?

No.

It works when I expose port 10000 and run the same script for the docker host machine using the url `http://localhost:10000/devstoreaccount1` but this is not what I'm looking for as I need to run it from an other container.

Thanks

**Comment by gsouf** [comment]
Found that #1362 had the same issue.

Using the cli option `--disableProductStyleUrl` worked.

I'm leaving this ticket open as I believe that should be documented more explicitly alongside the docker setup. That might save people time in the future (even reading the doc now that I know it's not easy to figure out why it's failing).

**Comment by blueww** [comment]
@gsouf 

In https://github.com/Azure/Azurite#differences-between-azurite-and-azure-storage, we have documented:

> Note. When use Production-style URL to access Azurite, by default the account name should be the host name in FQDN, like "http://devstoreaccount1.blob.localhost:10000/container". To use Production-style URL with account name in URL path, like "http://foo.bar.com:10000/devstoreaccount1/container", please start Azurite with --disableProductStyleUrl.

Azurite need to get account name from the Request Uri. 

- If the request Uri has FQDN with mutiple section, like "http://devstoreaccount1.blob.localhost:10000/container", will get account name "devstoreaccount1" from FQDN hostname.
- If the request Uri is with IP or hostname, like "http://127.0.0.1:10000/devstoreaccount1",  "http://localhost:10000/devstoreaccount1", will get account name from the path "devstoreaccount1"

So by default for request Uri like "http://foo.bar.com:10000/devstoreaccount1/container", Azurite will get account name as "foo" (and take "devstoreaccount1" as container name), then the account can't be found and report 400.

To resolve this Azurite add a new parameter `--disableProductStyleUrl` force parsing storage account name from request Uri path.

As we have already documented it in the Azurite Readme file, The request Uri style related section, do you have any suggest how to better document it?

Azurite welcome contribution!
It would be great if you could raise a PR to add your preferred azurite documentation change!

**Comment by gsouf** [comment]
@blueww thanks for your answer. The last time I tried to contribute to azure documentation, no one dared to even give an answer. 

The thing with azurite documentation is that I find it easy to install following this:

> https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio

but the page is so vast that it took me forever to figure out how to create accounts, or even the default account `devstoreaccount1`. There is also no mention of how works the url (and `disableProductStyleUrl`).

I was expecting to find all this in this article rather than on github.

There is then the page "use Azurite to run automated tests" here 
> https://docs.microsoft.com/en-us/azure/storage/blobs/use-azurite-to-run-automated-tests
it demonstrates the usage of the default account, but without a single word about it.

**Comment by blueww** [comment]
@[gsouf](https://github.com/gsouf)
The above docs are owned by documentation team, (not owned by Azurite team).
I have written mail to documentation team for the request.

**Comment by blueww** [comment]
@[gsouf](https://github.com/gsouf)

The doc update is done.
You can find it [here ](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#disable-production-style-url)in the 1st doc.
And there's a link from the second article to the 1st one

**Comment by gsouf** [comment]
Great! Thank you
