### ISSUE TITLE
Azurite not starting with Visual Studio

### ISSUE THREAD

**Issue by MattHartz** [Azure/Azurite#1587]
### Which service(blob, file, queue, table) does this issue concern?
All

### Which version of the Azurite was used?
3.17.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio

### What's the Node.js version?
No idea

### What problem was encountered?
Azurite is not starting on Visual Studio start up (can't find any means of forcing it)

### Steps to reproduce the issue?
Not sure, I rebooted my PC today and since then Azurite isn't starting up normally. Even upgraded my Visual studio to the latest and restarted my PC

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
@[MattHartz](https://github.com/MattHartz)

How do you know Azurite is not started with VS? Is the Azurite process not exist, or you can't connect to Azurite?
If you just run Azurite executable manually, will it work?  (The executable's location is `[VS 2022 dir]\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe`)

BTW, it's VS code to start Azurite in VS, you might should contact VS team to see why Azurite is not started in VS. 
This doc has the details on how to report a VS feedback issue : [https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fide%2Fhow-to-report-a-problem-with-visual-studio%3Fview%3Dvs-2022&data=05%7C01%7Cweiwei%40microsoft.com%7C018bab47753441a4efbc08da37aa53e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883501988809333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O8MtF%2Ft%2B5s7xXFJPiRAQzI7qYU9B3lWj0rXclmmUvXE%3D&reserved=0)

**Comment by blueww** [comment]
@[MattHartz](https://github.com/MattHartz)

I will close the issue since not receive your responds for a long time.
Feel free to contact us again if need any further assistance on Azurite.

**Comment by MattHartz** [comment]
Therre was another report someone found that if you have multiple start up projects that that caused issues. Then after a while i also started noticing i had another SLN that had a docker image for azurite which also sometimes caused issues.

I think there's been a fix somewhat recently that addressed the former issue.
