### ISSUE TITLE
Question: Does Azurite blob storage support range download?

### ISSUE THREAD

**Issue by evanxg852000** [Azure/Azurite#1602]
### Which service(blob, file, queue, table) does this issue concern?
Blob Storage

### Which version of the Azurite was used?
Docker latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
When trying to download a byte range from Azurite, a `FeatureNotSupported` error is reported as follows.
Also, the integration test does not include range download, adding one fails with the same error.
```
Err(Error { context: Full(Custom { kind: HttpResponse { status: InternalServerError, error_code: Some("FeatureNotSupported") }, error: HttpError { status: InternalServerError, error_code: Some("FeatureNotSupported"), headers: {"x-ms-error-code": "FeatureNotSupported", "connection": "keep-alive", "server": "Azurite-Blob/3.18.0", "transfer-encoding": "chunked", "keep-alive": "timeout=5", "x-ms-request-id": "b7846c1d-1b22-482e-a7a6-c8e5ed157758", "date": "Thu, 14 Jul 2022 14:27:15 GMT", "content-type": "application/xml"}, body: b"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>FeatureNotSupported</Code>\n  <Message>x-ms-range-get-content-crc64 header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter \"--loose\" or Visual Studio Code configuration \"Loose\". Please vote your wanted features to https://github.com/azure/azurite/issues\nRequestId:b7846c1d-1b22-482e-a7a6-c8e5ed157758\nTime:2022-07-14T14:27:15.672Z</Message>\n</Error>" } }, "server returned error status which will not be retried") })
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?

No

**Comment by blueww** [comment]
@[evanxg852000](https://github.com/evanxg852000)

Latest Azurite support blob range download.
But Azurite doesn't support CRC64
From the error message, you can also find the root cause. 
Do you want to retry with loose mode?

> <Message>x-ms-range-get-content-crc64 header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter \"--loose\" or Visual Studio Code configuration \"Loose\".

**Comment by evanxg852000** [comment]
Thanks a lot. it's now working with `--loose` flag

**Comment by evanxg852000** [comment]
Thanks a lot. it's now working with `--loose` flag
