### ISSUE TITLE
Getting connection refused when passing --silent argument in docker

### ISSUE THREAD

**Issue by gaurav137** [Azure/Azurite#1606]
If I run the command "docker run mcr.microsoft.com/azure-storage/azurite azurite --silent" then I get the output as below but not able to connect to the emulator endpoint either via Azure Storage Explorer of the Azure Storage SDKs.

Azurite Blob service is starting at http://127.0.0.1:10000
Azurite Blob service is successfully listening at http://127.0.0.1:10000
Azurite Queue service is starting at http://127.0.0.1:10001
Azurite Queue service is successfully listening at http://127.0.0.1:10001
Azurite Table service is starting at http://127.0.0.1:10002
Azurite Table service is successfully listening at http://127.0.0.1:10002

But access fails with:
![image](https://user-images.githubusercontent.com/39692417/179506335-b62dc380-7320-4d79-8028-d5168b237509.png)

If I run without the --silent option ie "docker run mcr.microsoft.com/azure-storage/azurite" then I'm able to connect fine with both the Azure Storage SDKs and Azure Storage Explorer. 

Is this a bug or I'm passing the argument incorrectly? I want to run the emulator in silent mode.

**Comment by blueww** [comment]
@gaurav137 

Please refer Azurite Readme to see how to run Azurite with docker: https://github.com/Azure/Azurite#dockerhub


- `--blobHost 0.0.0.0` will be required for blob service when you use any customized azurite paramters like '--silent' (same for Queue/Table)
- You might also need to expose blob service's default listening port "-p 10000:10000" (same for Queue/Table)

Following command works in my side:
 `docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite azurite --silent --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0`

**Comment by gaurav137** [comment]
Thanks for the clarification. I missed this detail when going over the readme.
________________________________

**Comment by blueww** [comment]
@gaurav137

I will close this issue as it's already resolved  on your side.
Feel free to contact us again if need any further assistance on Azurite.

**Comment by macingo-technologies** [comment]
Hi @blueww I have other services on default port 10000.. so I changed my configuration running the command with the argument `-p 7777:10000`. And I receive a connection refused. Any idea please?

**Comment by blueww** [comment]
@macingo-technologies 

Would you please share the detail command you use to start Azurite with docker? And how you connect to Azurite (which SDK/tools, connection string?), please hide credential if any.

BTW, there's a known .net SDK issue , when connect to Azurite with not default port: https://github.com/Azure/azure-sdk-for-net/issues/32809
