### ISSUE TITLE
DeleteEntityInBatch and Commit Deletes but throws Exception

### ISSUE THREAD

**Issue by danieloh1** [Azure/Azurite#1608]
### Which service(blob, file, queue, table) does this issue concern?
table
### Which version of the Azurite was used?
3.18.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
16.16.0
### What problem was encountered?
Batch delete and commit is deleting the entity from CloudTable from Microsoft.Azure.Cosmos.Table v1.0.8, but after deletion happens, a StorageError is thrown with message: "The specified resource does not exist". I checked in Azure Storage Explorer that the table and entity exist and that the entity is getting deleted. However, this exception is getting thrown and preventing the tear down of our unit tests from completing. 
### Steps to reproduce the issue?
Start Azurite and run/debug unit test
Code:
```
public virtual void DeleteRawEntity(StorageTableEntity entity)
{
    if (entity == null)
    {
        throw new ArgumentNullException("entity");
    }

    DynamicTableEntity dynamicTableEntity = ToDynamicTableEntity(entity);

    if (entity.GetSecondaryIndexes() != null)
    {
        // The Entity has secondary Indexes. So delete them in a batch transparently to the application.
        TableBatchOperation batch = new TableBatchOperation();
        this.DeleteEntityInBatch(entity, batch);
        this.Commit(this.table, batch);
        return;
    }

```
The exception occurs at Commit, but when checking the table prior to deletion, the table and entity exist and after refreshing the table after DeleteEntityInBatch and Commit, the entity is deleted from the table.
Error Message and Stack Trace:
```
Message: 
  TearDown : Microsoft.WindowsAzure.Storage.StorageException : 0:The specified resource does not exist.
  RequestId:2f72bd18-ede0-4119-8d57-d4da66a9a526
  Time:2022-07-18T18:19:02.944Z
Stack Trace: 
  --TearDown
  Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
  CloudTable.ExecuteBatch(TableBatchOperation batch, TableRequestOptions requestOptions, OperationContext operationContext)
  XStoreStorageTable`1.Commit(CloudTable table, TableBatchOperation batchOperation) line 1186
  XStoreStorageTable`1.DeleteRawEntity(StorageTableEntity entity) line 695
```
Attaching screenshots of the data in the table and entity to be deleted.
GatewayManagerInventoryTable data:
![image](https://user-images.githubusercontent.com/105062615/179791672-b33d1542-9fd8-4455-9cb9-bfe9517ed7d8.png)

PartitionKey and RowKey for entity:
![image](https://user-images.githubusercontent.com/105062615/179792106-c46b932d-213a-4fbf-9562-f595a9713b25.png)

Exception thrown:
![image](https://user-images.githubusercontent.com/105062615/179792699-623370c7-5afd-4582-b4b1-ad45a410cc43.png)

Data deleted from GatewayManagerInventoryTable:
![image](https://user-images.githubusercontent.com/105062615/179792842-f6906d1e-ec8b-4363-92c0-6377e4f8ca6f.png)

[debug.log](https://github.com/Azure/Azurite/files/9142676/debug.log)

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No solution. We are unable to switch from Microsoft.Azure.Cosmos.Table to Azure.Data.Tables package at this time as it require a lot of work. Many of our unit tests are failing due to this issue, but able to manually delete the rest of the data in the table.

**Comment by edwin-huber** [comment]
From the debug log provided separately, I see that the entity is deleted twice.
The first batch operation succeeds, the second fails with 404 status.
This would imply that the client code did not recognize the success.
This looks related to the SDK in use.

I'll take another look tomorrow, but this might be solved by inserting / removing the additional CRLF based on a specific API version.
I need to follow up with @XiaoningLiu , and once we have properly confirmed the correct behavior, I can code the fix to replicate this, and be rid of this issue in batch delete, regardless of the SDK.

**Comment by edwin-huber** [comment]
Same root  cause as #1439

**Comment by edwin-huber** [comment]
Related #1002 and #1079

**Comment by edwin-huber** [comment]
This should now be resolved.
