### ISSUE TITLE
Possible to generate a Queue upon upload of a Blob in Azurite?

### ISSUE THREAD

**Issue by SeaDude** [Azure/Azurite#1617]
I have an Azure Function triggered by Queue messages in Azure Storage. Queues are generated by an Event Grid topic subscription on the Blob Container. For each blob uploaded, a new Queue message is generated. 

I'm having trouble testing this locally using Azurite. Is it possible to generate a Queue upon upload of a Blob in Azurite? Or do I just need to manually generate the message for testing?

Thank you

### Which service(blob, file, queue, table) does this issue concern?
Blob, Queue
### Which version of the Azurite was used?
3.18.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS Code Extension
### What's the Node.js version?
N/A
### What problem was encountered?
N/A
### Steps to reproduce the issue?
N/A
If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
@[SeaDude](https://github.com/SeaDude)

For "I'm having trouble testing this locally using Azurite." What's the trouble do you meet? 
Do you mean Azurite can't generate a queue message like Event Grid?
Azurite is an Azure Storage API Emulator; we currently don't support Event Grid.

If you really need a queue message be generated when a blob upload, a workaround might be adding some client code to monitor the blob and trigger the queue message generation with blob uploaded.

**Comment by SeaDude** [comment]
That's a good idea. Thank you for the suggestion.

**Comment by user3472g** [comment]
@blueww 

I am attempting to do this same thing. I'd like to send a CloudEvent to a local testing queue in azurite when a file is uploaded to a testing blob in Azurite. Can you provide example of generating the event and publishing to queue? preferred sdk language is python

I have a python Blob Trigger function running in azure functions.

**Comment by SeaDude** [comment]
@user3472g, what I do is: 
1. Start the Azurite extension in VS Code (Blob, Table and Queue)
2. Open Azure Storage Explorer
3. Under `Emulated & Attached` expand the `Emulator) account and wait it for initialize
4. Right click on `Queues` and create a new queue
    - Be sure to put this queue name in your Function's `function.json`
    - Hint: Name this queue the same as the queue in your Azure Storage account and you won't have to adjust it
5. Once you have the Queue setup **and** `"AzureWebJobsStorage": "UseDevelopmentStorage=true"` set in `local.settings.json`, start the Function locally with `func start`.
6. Once it initialized, back in Azure Storage Explorer, select the Queue and click `Add Message`. 
7. Paste in a Sample `CloudEvent` schema

The local Function should trigger and you can watch it execute.
