### ISSUE TITLE
Azurite does not start automatically in Visual Studio when multiple startup projects are selected

### ISSUE THREAD

**Issue by giggio** [Azure/Azurite#1634]
### Which service(blob, file, queue, table) does this issue concern?
N/A, the issue is related to Visual Studio tooling.

### Which version of the Azurite was used?
The one that comes with VS 2022: `3.18.0`. VS is version `17.3.0`.

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS

### What's the Node.js version?
`18.6.0`

### What problem was encountered?
When multiple startup projects are selected Azurite does not auto start.

### Steps to reproduce the issue?

1. Set two startup projects in VS (see [docs](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-set-multiple-startup-projects?view=vs-2022)).
1. Debug

If you restart VS Azurite will also not start on project load. It will auto start if only one project is selected.

### Have you found a mitigation/solution?

Start only one project.

**Comment by blueww** [comment]
@giggio 

This is an issue for Visual Studio. 
Would you like to contact VS team to see for this issue?
This doc has the details on how to report a VS feedback issue : [https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fide%2Fhow-to-report-a-problem-with-visual-studio%3Fview%3Dvs-2022&data=05%7C01%7Cweiwei%40microsoft.com%7C018bab47753441a4efbc08da37aa53e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883501988809333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O8MtF%2Ft%2B5s7xXFJPiRAQzI7qYU9B3lWj0rXclmmUvXE%3D&reserved=0)

**Comment by giggio** [comment]
@blueww Done:
https://developercommunity.visualstudio.com/t/Azurite-does-not-start-automatically-in/10118195?port=1025&fsid=547bf176-5025-4c3c-9a76-0f3615d3b99a&entry=problem
Thanks for the help!
