### ISSUE TITLE
AzureStorageExplorer not connecting to Azurite in Docker

### ISSUE THREAD

**Issue by winseros** [Azure/Azurite#1648]
### Which service(blob, file, queue, table) does this issue concern?
All

### Which version of the Azurite was used?
3.18.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub, via [DockerCompose](https://github.com/Azure/Azurite#docker-compose)

### What's the Node.js version?
n/a

### What problem was encountered?
Azure storage emulator refuses to connect to Azurite in Docker

### Steps to reproduce the issue?
1. Use the [Dockefile](https://github.com/Azure/Azurite#docker-compose)
2. Run the `docker-compose up`
3. Ensure it is up and running
    ```
    [+] Running 1/1
     - Container azurite  Recreated                                                                                                                        2.0s
    Attaching to azurite
    azurite  | Azurite Blob service is starting at http://0.0.0.0:10000
    azurite  | Azurite Blob service is successfully listening at http://0.0.0.0:10000
    azurite  | Azurite Queue service is starting at http://0.0.0.0:10001
    azurite  | Azurite Queue service is successfully listening at http://0.0.0.0:10001
    azurite  | Azurite Table service is starting at http://0.0.0.0:10002
    azurite  | Azurite Table service is successfully listening at http://0.0.0.0:10002
    ```
4. Ensure ports `10000`, `10001`, `10002` are listening at `127.0.0.1` (i.e. `telnet 127.0.0.1 10000`)
5. Try connecting via the storage explorer
    ![image](https://user-images.githubusercontent.com/6763540/186644578-08b89507-49c2-47c8-b695-40384d50d741.png)
6. See the error:
    ![image](https://user-images.githubusercontent.com/6763540/186644765-d6f683a9-9c6e-4a56-89a0-08e486fa8115.png)

### Have you found a mitigation/solution?
Use the "Storage Emulator" instead of Azurite.

**Comment by blueww** [comment]
@winseros 

I can't repro the issue. 
By following the steps of you, I can connect Storage Explorer successfully to Azurite.

Have you done any change to the Docker Compose file?
Would you please share the Docker Compose file you are using?

**Comment by winseros** [comment]
Hi, the issue disappeared as unexpectedly as it rose. After ininstalling/installing everything and rebooting several times in the process it started working. No idea what was it. 

Sorry for bothering

**Comment by blueww** [comment]
@winseros 

Good to know the issue disappear on your side.
I will close this issue.

Feel free to contact us again if need any further assistance on Azurite.
