### ISSUE TITLE
Missing tags on docker hub

### ISSUE THREAD

**Issue by viktor-gustafsson** [Azure/Azurite#173]
The latest tag in docker hub is 2.6.5, can you please make the latest releases available on docker hub as well?

**Comment by KasperPurunen** [comment]
This is really annoying since the github readme says docker hub has the latest version of the image. As a workaround we would need to build it ourselves and host it in our own repo. Please fix this. Thank you.

**Comment by XiaoningLiu** [comment]
Azurite V3 has officaly docker hub page updated, will close this issue.

https://hub.docker.com/_/microsoft-azure-storage-azurite
