### ISSUE TITLE
Copying between storage accounts within same instance fails

### ISSUE THREAD

**Issue by kimsey0** [Azure/Azurite#1731]
### Which service (blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.20.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
N/A

### What problem was encountered?
When copying files between storage accounts within the same Azurite instance, I get an error that:
```
The specified blob does not exist.
RequestId:9078173b-3037-4c64-b03f-a499c852c918
Time:2022-10-26T13:59:49.995Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound

Content:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>BlobNotFound</Code>
  <Message>The specified blob does not exist.
RequestId:9078173b-3037-4c64-b03f-a499c852c918
Time:2022-10-26T13:59:49.995Z</Message>
</Error>

Headers:
Server: Azurite-Blob/3.20.1
x-ms-error-code: BlobNotFound
x-ms-request-id: 9078173b-3037-4c64-b03f-a499c852c918
Date: Wed, 26 Oct 2022 13:59:49 GMT
Connection: keep-alive
Keep-Alive: REDACTED
Transfer-Encoding: chunked
Content-Type: application/xml
```

I expect this to work, since the support matrix specifies that `Copy Blob From URL` works within the same Azurite instance.

### Steps to reproduce the issue?
First, start Azurite with multiple storage accounts, like:
```pwsh
docker run -p 10000:10000 -v c:/azurite:/workspace -e "AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;devstoreaccount2:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==" mcr.microsoft.com/azure-storage/azurite azurite-blob -d /workspace/debug.log --blobHost 0.0.0.0
```

Then, create a container in each storage account, upload a non-empty file to one of them, then start a copy to the other one:
```csharp
var sourceBlobServiceClient = new BlobServiceClient("DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;");
var sourceContainer = sourceBlobServiceClient.GetBlobContainerClient("test");
await sourceContainer.CreateAsync();
var sourceBlob = sourceContainer.GetBlobClient("test.txt");
await sourceBlob.UploadAsync(BinaryData.FromString("Lorem ipsum dolor sit amet..."));

var sourceBlobSasUri = sourceBlob.GenerateSasUri(BlobSasPermissions.All, DateTimeOffset.UtcNow.AddDays(1));

var destinationBlobServiceClient = new BlobServiceClient("DefaultEndpointsProtocol=http;AccountName=devstoreaccount2;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount2;");
var destinationContainer = destinationBlobServiceClient.GetBlobContainerClient("test");
await destinationContainer.CreateAsync();
var destinationBlob = destinationContainer.GetBlobClient("test.txt");
await destinationBlob.SyncCopyFromUriAsync(sourceBlobSasUri);
```

See [debug.log](https://github.com/Azure/Azurite/files/9870257/debug.log).

### Have you found a mitigation/solution?
No, other than avoiding the use of the copy function and instead downloading an uploading files.

**Comment by kimsey0** [comment]
On a related note, AzCopy also fails when copying blobs between storage accounts in the same Azurite instance, but in a different manner: it creates empty (zero byte size) destination files. To reproduce, start Azurite as above, then add the path to `azcopy.exe` and run:

```csharp
var sourceBlobServiceClient = new BlobServiceClient("DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;");
var sourceContainer = sourceBlobServiceClient.GetBlobContainerClient("test");
await sourceContainer.CreateIfNotExistsAsync();
var sourceBlob = sourceContainer.GetBlobClient("test.txt");
await sourceBlob.UploadAsync(BinaryData.FromString("Lorem ipsum dolor sit amet..."));
var sourceBlobServiceSasUri = sourceBlobServiceClient.GenerateAccountSasUri(AccountSasPermissions.All, DateTimeOffset.UtcNow.AddDays(1), AccountSasResourceTypes.All);

var destinationBlobServiceClient = new BlobServiceClient("DefaultEndpointsProtocol=http;AccountName=devstoreaccount2;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount2;");
var destinationBlobServiceSasUri = destinationBlobServiceClient.GenerateAccountSasUri(AccountSasPermissions.All, DateTimeOffset.UtcNow.AddDays(1), AccountSasResourceTypes.All);
var process = Process.Start(new ProcessStartInfo
{
    FileName = @"C:\Path\To\azcopy.exe",
    Arguments = $"copy \"{sourceBlobServiceSasUri}\" \"{destinationBlobServiceSasUri}\" --recursive --from-to=BlobBlob",
    UseShellExecute = false,
    RedirectStandardOutput = true
});
var output = await process.StandardOutput.ReadToEndAsync();
Console.WriteLine(output);
```

This produces output:
```
INFO: Scanning...
INFO: NOTE: HTTP is in use for one or more location(s). The use of HTTP is not recommended due to security concerns.
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job b2f9e782-8dfb-e94b-7c9a-f21e1c2f5d53 has started
Log file is located at: C:\Path\To\b2f9e782-8dfb-e94b-7c9a-f21e1c2f5d53.log

0.0 %, 0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 0.0001


Job b2f9e782-8dfb-e94b-7c9a-f21e1c2f5d53 summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 0
Number of Transfers Failed: 1
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed
```

as well as [b2f9e782-8dfb-e94b-7c9a-f21e1c2f5d53.log](https://github.com/Azure/Azurite/files/9870449/b2f9e782-8dfb-e94b-7c9a-f21e1c2f5d53.log) and [debug.log](https://github.com/Azure/Azurite/files/9870451/debug.log).

Running this for storage accounts with a larger number of files (> 1000), I've seen that some of them are successfully copied while others fail with `destination length does not match source length. When S2S Length check.` message in the log. Rerunning AzCopy consistently succeeds and fails for the same files respectively. I don't know why copying sometimes works from AzCopy when it never seems to work when triggering individual copies manually.

**Comment by kimsey0** [comment]
This is the same error message as #767, but unlike that issue, I'm copying between storage accounts in the same Azurite instance, not from an external URI.

**Comment by blueww** [comment]
@kimsey0 

Thanks for reporting this issue!
Will looks into it and update you later.

**Comment by blueww** [comment]
@kimsey0 

From the debug log you shared, I see the request you use to copy blob has header `"x-ms-blob-type":"BlockBlob"`, so you use request [Put Blob From URL](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url) , which is not supported by Azurite, see [details](https://github.com/Azure/Azurite#support-matrix).
For [Copy Blob From URL](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url), it should not have the header `"x-ms-blob-type":"BlockBlob"`.

Besides that, "Copy Blob From URL" also not support cross account copy in Azurite currently. We will consider to add the support in recent release.

**Comment by kimsey0** [comment]
@blueww: Thanks for debugging and creating a pull request with a fix. 🎉 

I believe it's only in [the second log file](https://github.com/Azure/Azurite/issues/1731#issuecomment-1292145250) generated when using AzCopy that the copy request has the `"x-ms-blob-type":"BlockBlob"` header and thus uses the Put Blob From URL functionality. In [the first log file](https://github.com/Azure/Azurite/issues/1731#issue-1424104825) generated when using `SyncCopyFromUriAsync` from `Azure.Storage.Blobs`, no such header seems to be present. Thus, I believe it'll use the Copy Blob From URL functionality which I expect https://github.com/Azure/Azurite/pull/1742 to fix. 😄

I'm happy enough if we can copy files between accounts using `Azure.Storage.Blobs`, but it would also be nice if Azurite handled usages of Put Blob From URL where the source URI is within the same instance, since AzCopy is a useful tool for copying containers around, migrating storage accounts, etc.

**Comment by blueww** [comment]
@kimsey0 

Look at [the first log file](https://github.com/Azure/Azurite/issues/1731#issue-1424104825), and I believe https://github.com/Azure/Azurite/pull/1742 can fix the 404 error of "Operation=Blob_CopyFromURL" in this log.

For "Put Blob From URL", we currently is working on other high priority features, will consider it in the future.

**Comment by kimsey0** [comment]
Good to hear. That's also how we see it.

If we'd like to look into and discuss the effort required to get Put Blob From URL working, should we do that under #767?

**Comment by blueww** [comment]
@kimsey0 
It looks #767 is more on the copy from external source to Azurite, but not on "Put Blob From URL".

**Comment by blueww** [comment]
@kimsey0 

We already has other issues to track Put Blob From Uri like https://github.com/Azure/Azurite/issues/852
So we can close this issue when the PR #1742 is merged. And use other issue to track Put Blob from Uri.

**Comment by blueww** [comment]
The fix is already released in https://github.com/Azure/Azurite/releases/tag/v3.21.0
