### ISSUE TITLE
Escaped chars in query do not work

### ISSUE THREAD

**Issue by Kafkamorph** [Azure/Azurite#174]
According to the Azure docs:

> Query String Encoding
> The following characters must be encoded if they are to be used in a query string:
> 
> Forward slash (/)
> Question mark (?)
> Colon (:)
> 'At' symbol (@)
> Ampersand (&)
> Equals sign (=)
> Plus sign (+)
> Comma (,)
> Dollar sign ($)

However, a query by email (x@y.z), when escaped with %40 replacing the @, does not work.
Also, using the @ itself also does not work (expected).
So there is **no way** to actually execute the query successfully.

**Comment by edwin-huber** [comment]
needs validation against new api

**Comment by edwin-huber** [comment]
resolved in upcoming PR for v3

**Comment by MatthewSteeples** [comment]
I think we're still seeing this problem for `/` characters

**Comment by edwin-huber** [comment]
Hi @MatthewSteeples thanks for the info.
Will check the tests and open a new issue if needed.
