### ISSUE TITLE
Unable to use DefaultAzureCredential for local development with Azurite Emulator

### ISSUE THREAD

**Issue by amroczeK** [Azure/Azurite#1750]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.20.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Tried npm and Vidusal Studio Code Extension

### What's the Node.js version?
v18.2.0

### What is my OS?
macOS Ventura v13.0

### What problem was encountered?
Unable use BlobServiceClient instantiated using documented [](https://github.com/Azure/Azurite#azure-blob-storage)
```
...
// With container url and DefaultAzureCredential
var endpoint = new Uri("https://127.0.0.1:10000/devstoreaccount1/accountid-1");
_containerClient = new BlobContainerClient(endpoint, new DefaultAzureCredential());
...
```

```
...
_containerClient.GetBlobsAsync(cancellationToken: cancellationToken)
...
```

Results in following error (trying to avoid the entire stack trace because it's not entirely helpful):
```
"Exception": "Azure.Identity.CredentialUnavailableException: DefaultAzureCredential failed to retrieve a token from the included credentials...
...
Azure.Identity.CredentialUnavailableException: Stored credentials not found. Need to authenticate user in VSCode Azure Account.
```

Based on the documentation I have done the following:
1.  [Generated a certificate and key with mkcert](https://github.com/Azure/Azurite#generate-certificate-and-key-with-mkcert)
```
choco install mkcert
mkcert -install
mkcert 127.0.0.1
```
2. [Configured the following environment variables](https://github.com/Azure/Azurite#default-storage-account):
```
set AZURITE_ACCOUNTS="devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
export AZURITE_ACCOUNTS="devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
```
3. [Started azurite using the generated certs, key and oauth basic](https://github.com/Azure/Azurite#azure-sdks)
```
azurite --oauth basic --cert 127.0.0.1.pem --key 127.0.0.1-key.pem
Azurite Blob service is starting at https://127.0.0.1:10000
Azurite Blob service is successfully listening at https://127.0.0.1:10000
Azurite Queue service is starting at https://127.0.0.1:10001
Azurite Queue service is successfully listening at https://127.0.0.1:10001
Azurite Table service is starting at https://127.0.0.1:10002
Azurite Table service is successfully listening at https://127.0.0.1:10002
```

Can someone please explain what steps I am missing to achieve connecting to storage account in local development using Azurite Emulator.

**Comment by amroczeK** [comment]
> @amroczeK Thanks for raising this issue! This issue looks more like an SDK usage issue than Azurite issue. From the error, it looks the failure happens when SDK try to generate a token, before send any request to server. So it looks the error happen before any request reach Azurite.
> 
> With default credential, many credential types if enabled will be tried, in order. It might caused by no credential type of your client can success fully retrieve a token for send storage request. See more details in https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet.
> 
> Can you run the same program to access real Azure server? If not, it can also confirm this is not azurite issue.

@blueww thank you for your feedback, I will review that documentation you linked. The application is deployed to an AKS and the pod has no issues establishing a connection to the storage account and pulling blob data.

Pod/Managed identities is configured for the resource and the MSI has role assignments to the storage account and key vault.

To use DefaultAzureCredential locally against a storage account hosted by the azurite emulator, do I need any additional settings/configurations like environment variables that I may have missed?

**Comment by blueww** [comment]
@amroczeK 

Do you mean you can access real storage account by run the same problem on same machine? (the only different of the program to access Azurite and storage tenant are the Endpoint)? 
From the error message, it looks the error happens when generate a token, before send request to server. So it looks should also fail on real storage.

Besides that, would you like to get the debug log of Azurite by adding parameter like `-d c:\azurite\debug.log` when start Azurite, and we can get more necessary information to trouble shooting.

**Comment by amroczeK** [comment]
@blueww 

Yes I am able to successfully access and query against my Azure Storage account from the same local machine using my application. To achieve this I just perform an `az login` in terminal, or by using the Azure extension in VSCode, logging in and adding my tenant.

...and you know what? DefaultAzureCredential() locally against Azurite Emulator storage account has just randomly started working after restarting my laptop... :/
