### ISSUE TITLE
The Azurie emulator not working correctly in Azure DevOps image Windows-latest

### ISSUE THREAD

**Issue by jessejiang0214** [Azure/Azurite#1761]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
The version come with VS2022, more detail check this https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Come with VS2022, I also tested with npm

### What's the Node.js version?
16.18.1
### What problem was encountered?
The emulator can be connected with Blob, but not with Table.

### Steps to reproduce the issue?

Create a simple Table write code and run in the DevOps. I tested all good from my local, but not working in DevOps image.

### Have you found a mitigation/solution?
N/A

**Comment by blueww** [comment]
@jessejiang0214 

Would you please give more details?
1. What's the Azurite version
2. How do you connect to Table, what's the connection string or table Uri you are using?
3. Azurite debug log

**Comment by blueww** [comment]
@jessejiang0214
I will close this issue as not hear from you for a long time.
Feel free to contact us again if need any further assistance on Azurite.

**Comment by jessejiang0214** [comment]
Hold on. I just busy in these days. Can you try this from your end? It's quite simple to reproduce, using debug connect string, and deploy to DevOps.

**Comment by blueww** [comment]
@jessejiang0214 
It looks I can't repro on my side. It might be related with some configuration on your machine.
So we need more information from you to continue the investigation.

**Comment by jessejiang0214** [comment]
Hi @blueww , It's not on my machine as I already said, it happens on Azure DevOps windows-latest image.

**Comment by blueww** [comment]
@jessejiang0214 
For "your machine", I mean the machine run Azurite and the client code on your side.
I might so be so familiar with Dev ops. And this issue not repro on my local machine.

So we still need more info from you to investigate this issue.
(Or if you can give a detail step by step way to setup the repro environment and repro this issue, I can try to repro it.)

**Comment by edwin-huber** [comment]
Hi,
It looks like this image is installing the **Azure CosmosDb Emulator**, which might be causing a conflict on the ports.
We don't own that **github action** or **VM image** creation, or the usage of these.
I would suggest that you open a request with the team that own the creation of those actions, as they would be the correct ones to help correct or prescribe a path to resolution using them in your pipelines:
https://github.com/actions/runner-images

**Comment by jessejiang0214** [comment]
Hi Edwin, 

That's my feeling. I know some application occupy the port but don't know which one. I have request support ticket to DevOps team, but they redirect to here.  It doesn't look like they want to resolve the problem. 

I will raise issue on that repo. Thanks for your help.

Regards,
Jesse

**Comment by jessejiang0214** [comment]
I just found the solution. 
Using this script in Azure DevOps or Github Action will launch the Table services before testing.
```
- script: start /B "" "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe"
  displayName: 'Start azurite'
```

**Comment by edwin-huber** [comment]
Nice, thanks for sharing :smile:
