### ISSUE TITLE
CORS matching not honoring while card domains.

### ISSUE THREAD

**Issue by esumerfd** [Azure/Azurite#1762]
### Which service(blob, file, queue, table) does this issue concern?

Blob

### Which version of the Azurite was used?

Latest

    repository: mcr.microsoft.com/azure-storage/azurite
    tag: latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

MCR

### What's the Node.js version?

In the container.

### What problem was encountered?

In a CI environment we want to store https://*.our-domain.com as the CORS Accepts-Origin but the wildcards are not honored by Azureite

### Steps to reproduce the issue?

With a CORS setup like this:

            <AllowedOrigins>https://*.our-domain.com</AllowedOrigins>
            <AllowedMethods>GET</AllowedMethods>
            <ExposedHeaders>*</ExposedHeaders>
            <AllowedHeaders>*</AllowedHeaders>

This does not work:

curl -i  -H "Origin: https://branch-env-1.our-domain.com" https://branch-env-1.our-domain.com/f5ac4a3c-4504-4b30-869e-7f58195750cf.jpg

But this does work, so we are presuming the code is doing exact matching on the CORS strings instead of wild-card matching.

curl -i  -H "Origin: https://*.our-domain.com" https://branch-env-1.our-domain.com/f5ac4a3c-4504-4b30-869e-7f58195750cf.jpg

### Have you found a mitigation/solution?

No.

**Comment by esumerfield** [comment]
We found this code. Looks like it's not implemented. 
`
const allowedOriginArray = allowedOrigin.split(",");
    for (const corsOrigin of allowedOriginArray) {
      if (origin.trim().toLowerCase() === corsOrigin.trim().toLowerCase()) {
        return true;
      }
    }
`

The doc seems to indicate that the real service would support it:
https://learn.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services#enabling-cors-for-azure-storage

**Comment by esumerfd** [comment]
The great @dotariel submitted a PR to fix this:
> https://github.com/Azure/Azurite/pull/1764

**Comment by blueww** [comment]
@esumerfd
Thanks  for the checking!
Many of the team members are on sick leave currently. We might will need a little more time to review and evaluate this PR.
Thanks for you understanding!

**Comment by blueww** [comment]
Close this issue as the fix PR is merged and released on Azurite 3.21.0.
Feel free to contact us again if need any further assistance on Azurite.
