### ISSUE TITLE
Dependency jsonwebtoken has insecure input validation in jwt.verify function

### ISSUE THREAD

**Issue by musakacmaz** [Azure/Azurite#1789]
### Which version of the Azurite was used?
v3.20.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v14.18.0

### What problem was encountered?
An older version of dependency jsonwebtoken causes vulnerability. More details can be found [here](https://github.com/advisories/GHSA-27h2-hvpr-p74q).

### Steps to reproduce the issue?
Running `npm audit` in any project that is dependant to Azurite.

### Have you found a mitigation/solution?
Seems like dependabot app has already opened PR #1777 in order to fix this but ignored.

**Comment by blueww** [comment]
@musakacmaz 

I have reopened the PR. 
However, the change will cause a lot of test failure. We need time to resolve the failures before merge the PR.

**Comment by kurtwaldowski-echelon** [comment]
@blueww Thanks! Let us know once merged, appreciate the fast response here

**Comment by blueww** [comment]
@EmmaZhu  will help to follow up this issue/PR, and fix the test error.
Thanks Emma!

**Comment by udiNaveh** [comment]
hi @blueww @EmmaZhu is there an ETA for this fix? we're using Azurite in an official image in mcr (https://hub.docker.com/_/microsoft-azure-cognitive-services-textanalytics-healthcare)
and have been getting alerts on this vulnerability.
thanks!

**Comment by EmmaZhu** [comment]
I'm looking into this, and trying to upgrade to a later version.  Will update here with any progress.

**Comment by blueww** [comment]
Close the issue as jsonwebtoken is aleady upgraded to 9.0.0 in Azurite code with  PR https://github.com/Azure/Azurite/pull/1777 merged.
