### ISSUE TITLE
Cannot retrieve a value of type double w/o fraction. Zero is returned instead (Reopened #1180)

### ISSUE THREAD

**Issue by Benny56** [Azure/Azurite#1796]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
3.19.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio Pro 2022 17.4.4

### What problem was encountered?
A value of type double is stored as Int32 when no fraction is provided.
The Int32 value is not converted back to double instead zeo is returned.

### Steps to reproduce the issue?

1. Start Azurite
2. Create a test project and run the test below

`using Microsoft.Azure.Cosmos.Table;
namespace IntegrationTests;

public class Entity : TableEntity
{
    public double Value { get; set; }
}

public class LocalStorageIntegrationTests
{
    private CloudTableClient _client;

    public LocalStorageIntegrationTests()
    {
        // Get connection to local local storage emulator 
        var localStorageAccount = CloudStorageAccount.DevelopmentStorageAccount;
        _client = localStorageAccount.CreateCloudTableClient();
    }

    [Theory]
    [InlineData(5.8d)]
    [InlineData(5d)]
    public async void Stored_and_retrieved_value_shoulö_be_equal(double value)
    {
        // Get reference to the test table
        var table = _client.GetTableReference("tblTest");

        // Recreate test table
        _ = table.DeleteIfExists();
        await table.CreateAsync();

        // Create entity
        var entity = new Entity
        {
            PartitionKey = "key1",
            RowKey = "key2",
            Value = value
        };

        // Insert entity
        _ = await table.ExecuteAsync(TableOperation.Insert(entity));

        // Get entity back
        var result = await table.ExecuteAsync(TableOperation.Retrieve<Entity>(entity.PartitionKey, entity.RowKey));
        var retrieved = (Entity)result.Result;

        // Assert
        Assert.Equal(value, retrieved.Value);
    }
}
`
Running the above test twice with the values 5 and 5.8 will fail for 5, but succeed for 5.8. See Test-Explorer of Visual Studio.

![Test-Explorer](https://user-images.githubusercontent.com/34538233/214019141-572aea97-be0e-4ed3-89c8-b60c721096e4.jpg)

The reason is that the value 5 is stored as Int32 instead of double and it is not correctly converted back when retrieving. See Microsoft Azure Storage Explorer:

![Storage-Explorer](https://user-images.githubusercontent.com/34538233/214020187-9953c4e1-c59e-4a56-8c72-dfc73f26af46.jpg)

When you manually change the type from Int32 to Double using the Storage Explorer the value will be retrieved correctly again.

### Have you found a mitigation/solution?
I cannot exclude that the TableClient (Microsoft.Azure.Cosmos.Table) might cause the problem. But it works in the production environment with Azure Functions and also when Microsoft Azure Storage Emulator is used locally.

Currently I have to use the outdated version 1.0.8 of Microsoft.Azure.Cosmos.Table. Later I will give Azure.Data.Tables a new trial. But I'm afraid I'll get the same result.

### Workaround
I have to use the outdated Microsoft Azure Storage Emulator for my current project.

**Comment by Benny56** [comment]
I have added PR #1797 to reproduce this issue.

**Comment by blueww** [comment]
@Benny56 

The SDK "Microsoft.Azure.Cosmos.Table" is already deprecated. You can see the deprecation message in nuget: https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table/2.0.0-preview

The Suggested Alternatives is [Azure.Data.Tables](https://www.nuget.org/packages/Azure.Data.Tables/). 
With [Azure.Data.Tables], I don't repro this issue. 

Following is my test code:
```c#
using Azure;
using Azure.Data.Tables;
using System;

namespace IntegrationTests
{
    internal class Program
    {
        static void Main(string[] args)
        {
            const string connectionString = [connectionstring];

            TableServiceClient _client = new TableServiceClient(connectionString);

            // Get reference to the test table
            var tableClient = _client.GetTableClient("tblTest");

            // Recreate test table
            _ = tableClient.Delete();
            tableClient.Create();

            // Create entity
            var partitionKey = "key1";
            var rowKey = "key2";
            var entity1 = new TableEntity(partitionKey, rowKey)
            {
                { "Value", 5d },
                { "Value2", 5.8d }
            };

            // Insert entity
            _ = tableClient.AddEntity(entity1);

            // Get entity back
            Pageable<TableEntity> entities = tableClient.Query<TableEntity>(filter: $"PartitionKey eq '{partitionKey}'");

            foreach (TableEntity entity in entities)
            {
                Console.WriteLine($"{entity.GetDouble("Value").Value == 5d}");
                Console.WriteLine($"{entity.GetDouble("Value2").Value == 5.8d}");
            }
        }
    }
}
```

**Comment by Benny56** [comment]
Thank you. Good hint. I will test it.
