### ISSUE TITLE
[BUG] query with property that has and underscore ('_') fails in version >= 3.21.0

### ISSUE THREAD

**Issue by tmcgannon** [Azure/Azurite#1806]
### Which service(blob, file, queue, table) does this issue concern?

Tablee

### Which version of the Azurite was used?

3.21.0 & 3.22.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

nom

### What's the Node.js version?

18.13.0

### What problem was encountered?

When executing any query with a property that has an underscore (e.g. "_foo eq bar"), an error is returned.

### Steps to reproduce the issue?

Using Azure Storage Explorer
![image](https://user-images.githubusercontent.com/2172012/219122804-5b064495-d189-4075-a215-93ed9d0d8cea.png)

1. Create a table and an entity with an underscore (the entity doesn't matter, error occurs even if you have no entities).
![image](https://user-images.githubusercontent.com/2172012/219122967-68fcc260-f2a8-4705-851e-771da23c0deb.png)

2. Query with underscore
![image](https://user-images.githubusercontent.com/2172012/219123253-146ab3b3-bad9-47fe-9aec-f5052f6f28a6.png)

3. See error
4. Query with NO underscore succeeds
![image](https://user-images.githubusercontent.com/2172012/219123535-02ee76e2-d9c8-4eb6-a9c7-b4a3a71694da.png)

### Have you found a mitigation/solution?

Revert to 3.20.1

**Comment by edwin-huber** [comment]
Issue is in ```src\table\persistence\QueryTranscriber\QPState.ts``` line 312 isIdentifier is not matching on underscore.
I'm validating the full list of allowed chars and will then submit a PR.

**Comment by edwin-huber** [comment]
We're only missing the underscore... fix will be quick

**Comment by tmcgannon** [comment]
@edwin-huber When will this be included in a npm release?

**Comment by blueww** [comment]
The next Azurite release should be out in 1-2 months.
