### ISSUE TITLE
stackoverflow visibility

### ISSUE THREAD

**Issue by IamADav** [Azure/Azurite#181]
Hi guys,

Could you create an azurite-storage-emulator tag in stackoverflow?
There is more and more question and they are all tagged azure-storage or azure-storage-emulator.

Thx for  your work
David

**Comment by XiaoningLiu** [comment]
@IamADav That's really a good idea! If a question already tagged with "azure-storage-emulator", then the tag is already created.

https://meta.stackexchange.com/questions/103676/how-to-add-a-new-tag-on-stack-overflow

**Comment by IamADav** [comment]
I would have done it myself but I have not enough reputation on stackoverflow. If someone reading that could do it it would be for the better.

**Comment by XiaoningLiu** [comment]
You are right.  I don't have enough reputation either.

**Comment by edwin-huber** [comment]
```azurite``` tag is available in stackoverflow see:  
https://stackoverflow.com/questions/tagged/azurite
