### ISSUE TITLE
GetAccountInformation doesn't return x-ms-is-hns-enabled

### ISSUE THREAD

**Issue by Vaiz** [Azure/Azurite#1810]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.21

### What problem was encountered?
In my application, I use 'GetAccountInformation' method to check the storage account type.
I found that Azurite doesn't return 'x-ms-is-hns-enabled' header.
Could it be fixed in future versions?

### REST Documentation
https://learn.microsoft.com/en-us/rest/api/storageservices/get-account-information

**Comment by blueww** [comment]
@EmmaZhu 
This change will need swagger update.
Would you please help to look?
