### ISSUE TITLE
Docker Azurite for Windows Containers failure on docker pull command.

### ISSUE THREAD

**Issue by Caamarth** [Azure/Azurite#1813]
### Which service(blob, file, queue, table) does this issue concern?
Docker repository

### Which version of the Azurite was used?
latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
'docker pull' command can't retrieve manifest for windows/amd64, resulting in a failure.
In addition, DockerHub page returns a 404 error: [https://hub.docker.com/_/microsoft-azure-storage-azurite](https://hub.docker.com/_/microsoft-azure-storage-azurite)

### Steps to reproduce the issue?
- Run Docker for Windows with 'windows containers'
- In Powershell or CMD, type: 'docker pull mcr.microsoft.com/azure-storage/azurite'

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Using default tag: latest
latest: Pulling from azure-storage/azurite
no matching manifest for windows/amd64 10.0.19044 in the manifest list entries

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No.

**Comment by blueww** [comment]
@Caamarth 

I can't repro your issue, following is the result on my machine:
```
D:\>docker pull mcr.microsoft.com/azure-storage/azurite
Using default tag: latest
latest: Pulling from azure-storage/azurite
396c31837116: Already exists
9e7b0c9574dd: Already exists
ec07c04a8d4c: Already exists
c1eb01e62785: Already exists
52ad56578b6f: Pull complete
e5cc006e2953: Pull complete
c51dd1331480: Pull complete
9eeb7762e9fd: Pull complete
Digest: sha256:f7d8c2250b282ef1e7179eef5473ecabfd1d9ea3ade2c2b35eea5150dfe44c90
Status: Downloaded newer image for mcr.microsoft.com/azure-storage/azurite:latest
mcr.microsoft.com/azure-storage/azurite:latest
```

What's the OS of your machine?
Currently Azurite support both docker image on AMD64 and ARM64, and will download the specific image per your machine architecture.

If you want to pull the AMD64 image, could you try to following command:
`docker pull mcr.microsoft.com/azure-storage/azurite:3.22.0-amd64`

**Comment by Caamarth** [comment]
I'm using Windows 10 and Docker Desktop 4.15.0 with Engine 20.10.21 with Windows Containers, but this can be reproduced on the Azure DevOps build pipeline with windows-latest vmImage, if that helps reproduce it. As of this morning (11:10 ETC) the issue still persists.

**Comment by blueww** [comment]
@Caamarth 
Can you pull the following image successfully?
`docker pull mcr.microsoft.com/azure-storage/azurite:3.22.0-amd64`

**Comment by Caamarth** [comment]
No, I get this message from Docker Desktop:

> PS C:\WINDOWS\system32> docker pull mcr.microsoft.com/azure-storage/azurite:3.22.0-amd64
> 3.22.0-amd64: Pulling from azure-storage/azurite
> image operating system "linux" cannot be used on this platform

**Comment by blueww** [comment]
@Caamarth 

It looks the error happens since the docker in your machine is using Windows container, but Azurite docker image is Linux based.
To resolve this, you can switch the container mode to Linux, or set `"experimental": true` in Docker Engine.
See more details in: 
https://stackoverflow.com/questions/48066994/docker-no-matching-manifest-for-windows-amd64-in-the-manifest-list-entries

**Comment by Caamarth** [comment]
I assumed since there was no mention in the Learn site or the Docker hub that it's a Linux based container, that it can run on windows containers as well. In that case, my issue is resolved as it runs on Linux container just fine. Thank you.

**Comment by vaibhavPH** [comment]
I still often this error randomly. On running tests again generally they pass. Surprisingly only azulite testcontainer tests are flacky but all other tests like rabbitmq, postgres and other docker images always are passing without even a single failure.

**Comment by blueww** [comment]
@vaibhavPH 

What's the detail error you meet? 
What's the docker config on your machine? (Windows or Linux?)
As this issue is already closed (it's not a random issue). Your issue might be different from this. Would you like to Open a new issue with the details?
