### ISSUE TITLE
VS 2022 17.5 does not ship up-to-date Azurite version

### ISSUE THREAD

**Issue by drauch** [Azure/Azurite#1819]
I've installed VS 2022 17.5 and Azurite is still on 3.20.1, is there a way to install 3.22.0? I can't use the newest SDK version as of now due to the following errors:

> Status: 400 (The API version 2021-12-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. )
ErrorCode: InvalidHeaderValue

Best regards,
D.R.

**Comment by blueww** [comment]
@drauch 

This issue more like a question for VS team.
You can contact VS team for this question.
This doc has the details on how to report a VS feedback issue : [https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fide%2Fhow-to-report-a-problem-with-visual-studio%3Fview%3Dvs-2022&data=05%7C01%7Cweiwei%40microsoft.com%7C018bab47753441a4efbc08da37aa53e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883501988809333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O8MtF%2Ft%2B5s7xXFJPiRAQzI7qYU9B3lWj0rXclmmUvXE%3D&reserved=0)

**Comment by drauch** [comment]
Okay, that's unfortunate.

For everybody else, I've created: https://developercommunity.visualstudio.com/t/Visual-Studio-2022-175-does-not-ship-wi/10289485

**Comment by blueww** [comment]
@drauch 

I will close this issue, as the this is VS issue, and you have already reported the VS feedback.

Feel free to contact us again if you need any further assistance on Azurite.
