### ISSUE TITLE
filters not working as expected on GUID containing column

### ISSUE THREAD

**Issue by PrasantJillella** [Azure/Azurite#1827]
### Which service(blob, file, queue, table) does this issue concern?
Table
### Which version of the Azurite was used?
3.22.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v18.14.2
### What problem was encountered?
Filter on GuidProperty does not work for filters "ne", "ge", "gt".
**Entire filter used in my scenario are as below**:
"filter":"GuidProp gt guid'22222222-2222-2222-2222-222222222222'"
"filter":"GuidProp ne guid'22222222-2222-2222-2222-222222222222'"
"filter":"GuidProp ge guid'22222222-2222-2222-2222-222222222222'"

### Steps to reproduce the issue?
Create a table which has a column named GuidProp with Guid values in it.
Create three such records with 3 distinct GUID values, say
11111111-1111-1111-1111-111111111111
22222222-2222-2222-2222-222222222222
33333333-3333-3333-3333-333333333333

Only apply filter on GuidProp column with either of gt, ne or ge. It is observed that all three
records are returned instead of 
gt returning record with GUID value = 33333333-3333-3333-3333-333333333333 record
ne returning records with GUID values =11111111-1111-1111-1111-111111111111, 33333333-3333-3333-3333-333333333333 records
ge returning records with GUID values =22222222-2222-2222-2222-222222222222, 33333333-3333-3333-3333-333333333333 records.

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
**Log for query ran:**
 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"format":"application/json;odata=minimalmetadata","top":20,"filter":"GuidProp ge guid'22222222-2222-2222-2222-222222222222'"},"requestId":"4029d7ef-5f22-43f8-9b61-4613f4b5fb96","dataServiceVersion":"3.0"},"version":"2020-12-06"}

**Log for response returned:**
 debug: TableHandler:queryEntities() Raw response string is "{\"odata.metadata\":\"http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element\",\"value\":[{\"odata.etag\":\"W/\\\"datetime'2023-03-07T08%3A57%3A32.7098638Z'\\\"\",\"PartitionKey\":\"Part1\",\"RowKey\":\"Row1\",\"BinaryProp@odata.type\":\"Edm.Binary\",\"BinaryProp\":\"AQEB\",\"DateTimeProp@odata.type\":\"Edm.DateTime\",\"DateTimeProp\":\"2023-03-06T00:00:00.0000000Z\",\"DoubleProp\":1000.0,\"GuidProp@odata.type\":\"Edm.Guid\",\"GuidProp\":\"11111111-1111-1111-1111-111111111111\",\"IntProp\":1,\"LongProp@odata.type\":\"Edm.Int64\",\"LongProp\":\"10\",\"StringProp\":\"AAA\",\"Timestamp\":\"2023-03-07T08:57:32.7098638Z\"},{\"odata.etag\":\"W/\\\"datetime'2023-03-07T08%3A57%3A32.7489048Z'\\\"\",\"PartitionKey\":\"Part2\",\"RowKey\":\"Row2\",\"BinaryProp@odata.type\":\"Edm.Binary\",\"BinaryProp\":\"AgIC\",\"DateTimeProp@odata.type\":\"Edm.DateTime\",\"DateTimeProp\":\"2023-03-07T00:00:00.0000000Z\",\"DoubleProp\":2000.0,\"GuidProp@odata.type\":\"Edm.Guid\",\"GuidProp\":\"22222222-2222-2222-2222-222222222222\",\"IntProp\":2,\"LongProp@odata.type\":\"Edm.Int64\",\"LongProp\":\"20\",\"StringProp\":\"BBB\",\"Timestamp\":\"2023-03-07T08:57:32.7489048Z\"},{\"odata.etag\":\"W/\\\"datetime'2023-03-07T08%3A57%3A32.7549085Z'\\\"\",\"PartitionKey\":\"Part3\",\"RowKey\":\"Row3\",\"BinaryProp@odata.type\":\"Edm.Binary\",\"BinaryProp\":\"AwMD\",\"DateTimeProp@odata.type\":\"Edm.DateTime\",\"DateTimeProp\":\"2023-03-08T00:00:00.0000000Z\",\"DoubleProp\":3000.0,\"GuidProp@odata.type\":\"Edm.Guid\",\"GuidProp\":\"33333333-3333-3333-3333-333333333333\",\"IntProp\":3,\"LongProp@odata.type\":\"Edm.Int64\",\"LongProp\":\"30\",\"StringProp\":\"CCC\",\"Timestamp\":\"2023-03-07T08:57:32.7549085Z\"}]}"

```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No.

**Comment by PrasantJillella** [comment]
Hi
Checking to see if anyone can take a look into this.
Thank you.

**Comment by edwin-huber** [comment]
I am taking a look

**Comment by edwin-huber** [comment]
We have the problem that we support backward compatible schema for querying Guids (in GuidPredicate.ts).

https://github.com/azure/azurite/blob/7625366fa3d1b7080a3c1c442016bfd4cc2e1f1e/src/table/persistence/QueryTranscriber/PredicateModel/GuidPredicate.ts#L26

This means that we find a guid in string format, or encoded format to enable service parity.

In order to support other operators on GUIDs, we need to drop the backwards compatibility, as we turn a GUID predicate into 2 predicates when looking for GUIDs in this backwards compatible format.

But we cannot have a valid comparison on greater than / less than predicates, as we have 2 different strings.

We are discussing internally before I push a fix.

**Comment by PrasantJillella** [comment]
I don't think I completely understand the backward compatibility scenario (maybe an example can help better understand). 
But yes you can get back once you check with your team.

Thank you.

**Comment by PrasantJillella** [comment]
Hi 
Checking back to see if there was any update on this.
Thank you.

**Comment by edwin-huber** [comment]
PR is submitted

**Comment by PrasantJillella** [comment]
> PR is submitted

Thank you really appreciate it. please update here once the changes are pushed.
