### ISSUE TITLE
Empty RowKey is not supported in Retrieve table operation.

### ISSUE THREAD

**Issue by AleF83** [Azure/Azurite#183]
Formally, RowKey with empty string as value is legal.
Actually when RowKey is passed as empty string the Entity Retrieve operation is handled as Query Entities operation and despite the PartitionKey is passed the response is an array.

**Comment by edwin-huber** [comment]
resolved in the latest version of the v3 api

**Comment by edwin-huber** [comment]
(this is used by Azure Functions)
