### ISSUE TITLE
Security vulnerability in xml2js. Need to upgrade to 0.5.0

### ISSUE THREAD

**Issue by viswanr** [Azure/Azurite#1907]
### What problem was encountered?
There is a security vulnerability in 0.4.x versions of xml2js which azurite uses. Need to update to 0.5. If the major version of a dependency is 0, npm caret (^) rules don't apply to update minor versions. Please update manually. 
### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
@viswanr 

Thanks for raising this issue!

However, many Azurite test cases will fail with the upgrade, so we might need more time to look into the failure and fix them before upgrade xml2js.

@EmmaZhu ,

As I see, most of the failures are in Cors related cases, and failed in "@azure\storage-blob".
Would you please help to see how to fix the failure?
https://dev.azure.com/azure/Azurite/_build/results?buildId=57685&view=logs&j=a423c0c5-489d-5c33-c960-603efb6a5600&t=6241a3eb-2205-5763-b4f2-362515ea0306

> 6) Blob Cors requests test
>        OPTIONS request should work with matching rule containing Origion * @loki @sql:
>      
>   RestError
>       at handleErrorResponse (node_modules\@azure\storage-blob\node_modules\@azure\core-http\src\policies\deserializationPolicy.ts:274:17)
>       at D:\a\1\s\node_modules\@azure\storage-blob\node_modules\@azure\core-http\src\policies\deserializationPolicy.ts:179:47
>       at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by blueww** [comment]
@EmmaZhu 

Never mind.
I have raised a new PR to upgrade the dependency and fix the failures : https://github.com/Azure/Azurite/pull/1911

**Comment by blueww** [comment]
Close as the fix PR is already merged: https://github.com/Azure/Azurite/pull/1911
