### ISSUE TITLE
sequelize is vulnerable to SQL injection. Needs to be updated to 6.29.0

### ISSUE THREAD

**Issue by viswanr** [Azure/Azurite#1915]
### What problem was encountered?
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Sequelize - Default support for “raw attributes” when using  │
│               │ parentheses                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sequelize                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=6.29.0                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ azurite                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ azurite > sequelize                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1091149                     │
└───────────────┴──────────────────────────────────────────────────────────────┘

───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Sequelize vulnerable to SQL Injection via replacements       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sequelize                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=6.19.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ azurite                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ azurite > sequelize                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1091121                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
@viswanr 

I have reopen the PR to upgrade it: https://github.com/Azure/Azurite/pull/1903
But with the upgrade, Azurite build will fail.
So we still need more time to investigate how to fix the build.

**Comment by blueww** [comment]
Fix Pr has already raised and pass review/ PR check: https://github.com/Azure/Azurite/pull/1925

**Comment by blueww** [comment]
Close as the fix PR is already merged. 
Normally should be included in the next Azurite release.
