### ISSUE TITLE
Azurite Doesn't Handle Empty Table Fields Correctly When Quering With Not Equals

### ISSUE THREAD

**Issue by garrettbaski** [Azure/Azurite#1929]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.23.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
NPM

### What's the Node.js version?
v18.15.0

### What problem was encountered?
When querying tables, if you have an entity with a missing field and then query using something like ; 
```field != '' ```
That field will be returned in Azurite. However, from Azure Storage RP, it will not be returned.
Eg) If you add the two following items

Item 1 : {
PartitionKey : 1,
Row : 1,
Foo: "hi"
}

Item 2: {
PartitionKey: 1,
Row: 2
}

And then do a query for 
```Foo ne '' ```
You will get back both values in azurite but only the first value from storage. Aziure Storage seems to remove any entities where the field is not set when doing a query which removes it from being a viable candidate for these kinds of queries. 

### Steps to reproduce the issue?

Link to a test that will fail for Azurite but succeed for real Azure Storage can be found here : https://github.com/Azure/Azurite/pull/1930/files#diff-e0ef70376f6f826126897df2e43d8ab9fa613d813a176d0a443085500eb89734

### Have you found a mitigation/solution?
Yes, I have a PR, but the code is not great. But its at least an idea of how to fix it. PR Link here https://github.com/Azure/Azurite/pull/1930:

**Comment by garrettbaski** [comment]
> @edwin-huber
> 
> I can repro this issue with storage explorer, do you have any idea how to fix it? Following is the Azurite debug log . (An entity without property "foo" can be query out with `foo ne ''`, in product Azure it won't be query out.)
> 
> ```
> 2023-05-04T09:13:47.976Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/issue1947()?$select=&$filter=foo%20ne%20%27%27 RequestHeaders:{"accept":"application/json;odata=minimalmetadata","x-ms-version":"2019-02-02","dataserviceversion":"3.0","accept-encoding":"gzip,deflate","user-agent":"Microsoft Azure Storage Explorer/1.28.0 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v16.17.1 OS/(ia32-Windows_NT-10.0.19045)","x-ms-client-request-id":"9b2ec0b7-4604-4fb6-9659-7efa083da0f3","x-ms-date":"Thu, 04 May 2023 09:13:47 GMT","authorization":"SharedKeyLite devstoreaccount1:TY09ih0Jb5NauxK+YKJ9/s2zTLoRiLUOuuuh8iDGRGc=","host":"127.0.0.1:10002","connection":"keep-alive"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
> 2023-05-04T09:13:47.977Z b504217a-6ce9-42d2-bf88-5310c03d9601 debug: tableStorageContextMiddleware: Dispatch pattern string: /issue1947()
> 2023-05-04T09:13:47.977Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=issue1947
> 2023-05-04T09:13:47.977Z b504217a-6ce9-42d2-bf88-5310c03d9601 verbose: DispatchMiddleware: Dispatching request...
> 2023-05-04T09:13:47.978Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: DispatchMiddleware: Operation=Table_QueryEntities
> 2023-05-04T09:13:47.978Z b504217a-6ce9-42d2-bf88-5310c03d9601 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
> 2023-05-04T09:13:47.978Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
> 2023-05-04T09:13:47.979Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Thu, 04 May 2023 09:13:47 GMT\n/devstoreaccount1/devstoreaccount1/issue1947()"
> 2023-05-04T09:13:47.979Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:TY09ih0Jb5NauxK+YKJ9/s2zTLoRiLUOuuuh8iDGRGc=
> 2023-05-04T09:13:47.979Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
> 2023-05-04T09:13:47.980Z b504217a-6ce9-42d2-bf88-5310c03d9601 verbose: DeserializerMiddleware: Start deserializing...
> 2023-05-04T09:13:47.981Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"select":"","filter":"foo ne ''"},"requestId":"9b2ec0b7-4604-4fb6-9659-7efa083da0f3","dataServiceVersion":"3.0"},"version":"2019-02-02"}
> 2023-05-04T09:13:50.142Z b504217a-6ce9-42d2-bf88-5310c03d9601 debug: TableHandler:queryEntities() Raw response string is "{\"odata.metadata\":\"http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element\",\"value\":[{\"odata.etag\":\"W/\\\"datetime'2023-05-04T08%3A49%3A38.7396153Z'\\\"\",\"PartitionKey\":\"a8\",\"RowKey\":\"b8\",\"Value\":true,\"Timestamp\":\"2023-05-04T08:49:38.7396153Z\"},{\"odata.etag\":\"W/\\\"datetime'2023-05-04T09%3A03%3A39.7095859Z'\\\"\",\"PartitionKey\":\"b\",\"RowKey\":\"c\",\"foo\":\"123\",\"Timestamp\":\"2023-05-04T09:03:39.7095859Z\"}]}"
> 2023-05-04T09:13:50.144Z b504217a-6ce9-42d2-bf88-5310c03d9601 verbose: SerializerMiddleware: Start serializing...
> 2023-05-04T09:13:50.144Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: Serializer: Start returning stream body.
> 2023-05-04T09:13:50.146Z b504217a-6ce9-42d2-bf88-5310c03d9601 info: EndMiddleware: End response. TotalTimeInMS=2170 StatusCode=200 StatusMessage=OK Headers={"server":"Azurite-Table/3.23.0","content-type":"application/json;odata=minimalmetadata","x-ms-client-request-id":"9b2ec0b7-4604-4fb6-9659-7efa083da0f3","x-ms-request-id":"b504217a-6ce9-42d2-bf88-5310c03d9601","x-ms-version":"2022-11-02","date":"Thu, 04 May 2023 09:13:47 GMT"}
> ```

The PR I have addresses it. Not that the code is great and it feels shoehorned, but its at least one way to handle it

**Comment by blueww** [comment]
The issue should already been fixed with PR https://github.com/Azure/Azurite/pull/1975.
The fix should be released in the next Azurite release.
