### ISSUE TITLE
[Table] Filter condition fails if the query contains a backtick `

### ISSUE THREAD

**Issue by garrettbaski** [Azure/Azurite#1972]
Which service(blob, file, queue, table) does this issue concern?
Table

Which version of the Azurite was used?
3.23.0

Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
NPM

What's the Node.js version?
v18.15.0

What problem was encountered?
If your query has a backtick, it will return a 500 saying "The query condition specified in the request is invalid". It looks like in the string predicate the code says : 

```     
     taggedToken.token =
        "`" +
        // need to convert double apostrope to single
        this.replaceDoubleApostrophes(
          taggedToken.token.substring(1, taggedToken.token.length - 1)
        ) +
        "`";
```

Because of this, it looks like having a backtick in the query basically escapes the query. 

Adding the test below to the table.entity.query.tests.ts reproduces this

``` 
  it("20. should work when getting special characters, @loki", async () => {
    const tableClient = createAzureDataTablesClient(
      testLocalAzuriteInstance,
      getUniqueName("specialcharactercheck")
    );

    await tableClient.createTable();

    const partitionKey = createUniquePartitionKey("");

    // Foo has some special characters
    const result1 = await tableClient.createEntity({
      partitionKey: partitionKey,
      rowKey: `1`,
      foo: "TestVal`",
    });
    assert.notStrictEqual(result1.etag, undefined);

    const maxPageSize = 5;
    const entities = tableClient.listEntities<TableEntity<{ foo: string }>>({
      queryOptions: {
        filter: `PartitionKey eq '${partitionKey}' and foo eq 'TestVal\`'`
      }
    });
    let all: TableEntity<{ foo: string }>[] = [];
    for await (const entity of entities.byPage({
      maxPageSize
    })) {
      all = [...all, ...entity];
    }
    assert.strictEqual(all.length, 1);

    await tableClient.deleteTable();
  });
```

Have you found a mitigation/solution?
Not yet not

**Comment by blueww** [comment]
@edwin-huber 

It looks the failure is realted with the code change from your commit https://github.com/Azure/Azurite/commit/7dd63170230c034ce01116185decc122748fd74c

Would you please help to look?

**Comment by blueww** [comment]
As #1973 is merged, the fix will be out in next Azurite release.
