### ISSUE TITLE
Visual Studio 2022 17.6.2 vs. newest SDK version

### ISSUE THREAD

**Issue by drauch** [Azure/Azurite#1992]
I've installed the newest VS 2022 update (17.6.2) and I'm using the newest Azure SDK for .NET (Azure.Storage.Blobs 12.16.0). Trying to perform any operation always returns:

> Azure.RequestFailedException : The API version 2022-11-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 
>
> Status: 400

The exception message hurts, because I already have the latest patch installed. What else do I need to do?

### Which service(blob, file, queue, table) does this issue concern?

All

### Which version of the Azurite was used?

Visual Studio 2022 17.6.2 version

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

VS

### What's the Node.js version?

-

### What problem was encountered?

> Azure.RequestFailedException : The API version 2022-11-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry.

### Steps to reproduce the issue?

Trying to add a blob to the Azurite blob storage

### Have you found a mitigation/solution?

No.

**Comment by drauch** [comment]
azurite.exe versions:

```
File version: 14.20.0.0
Product version: 3.22.0
```

**Comment by drauch** [comment]
Workaround is to use the `--skipApiVersionCheck` flag, but it would be great to have Azurite support the newest Blob storage SDK version in the newest VS version. Also the error message is misleading.

**Comment by drauch** [comment]
Oh, looks like this is fixed with 3.23.0 -> why does VS not feature the newest Azurite version?

**Comment by blueww** [comment]
@drauch 

This looks more like an ask for Visual Studio team. (We can't fix it in Azurite code.)
Would you like to contact VS team for this issue?
This doc has the details on how to report a VS feedback issue : [https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fide%2Fhow-to-report-a-problem-with-visual-studio%3Fview%3Dvs-2022&data=05%7C01%7Cweiwei%40microsoft.com%7C018bab47753441a4efbc08da37aa53e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883501988809333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O8MtF%2Ft%2B5s7xXFJPiRAQzI7qYU9B3lWj0rXclmmUvXE%3D&reserved=0)

**Comment by drauch** [comment]
Sorry, I don't have the time at the moment to go through the hoops of creating a Visual Studio ticket and talk to multiple people before reaching out to someone who can actually do something.

I think the Azurite team should take responsibility for the full Azurite experience, a big part of it being developers using Visual Studio and the newest Azure SDK NuGet packages - something which doesn't work at the moment. If you're not responsible, then please contact them via internal communication channels.

For anybody else chiming in: we're using the --skipApiVersionCheck workaround for now.

Best regards,
D.R.

**Comment by blueww** [comment]
@drauch

We actually have discussed this issue with Visual team, and they agreed to add "--skipApiVersionCheck" in start Azurite in the future.
However, if Visual studio team receive more customer feedback on this, it might can help them better prioritize this ask.
