### ISSUE TITLE
Table operation errors

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#20]
I’ve been playing with Azurite some, and there appears there may be a problem with it’s tables implementation. Regardless of platform, I get errors when trying to add entities, delete entities, and delete tables. Some details:
- We use [azure-storage-node](https://github.com/Azure/azure-storage-node) for sending requests.
- We expect a certain result object when adding entities succeeds. However, we are getting an empty result object. This result object is supposed to provide information about the new entity, such as an etag.
- When attempting to delete entities or tables, we get errors like the following (may be related to #17, #19):
```
POST /devstoreaccount1/test01 204 2.216 ms - -
GET /devstoreaccount1/test01?%24top=1000 200 1.560 ms - 575
GET /devstoreaccount1/test01?%24top=1000 200 0.747 ms - 575
POST /devstoreaccount1/$batch 500 1.124 ms - 45
**PANIC** Something unexpected happened! Table Storage Emulator may be in an inconsistent state!
TypeError: Cannot read property 'tableName' of undefined
    at BbPromise.try (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\lib\middleware\table\validation.js:24:48)
    at tryCatcher (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\method.js:39:29)
    at module.exports (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\lib\middleware\table\validation.js:18:18)
    at Layer.handle [as handle_request] (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\body-parser\lib\read.js:130:5
    at invokeCallback (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\raw-body\index.js:273:7)
    at emitNone (events.js:106:13)
   at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
GET /devstoreaccount1/test01?%24top=1000 200 0.869 ms - 575
```

**Comment by edwin-huber** [comment]
PANIC errors on unimplemented features should now be addressed by https://github.com/Azure/Azurite/commit/4db55209598fde2b41323a28014becbea0cf6455 until we have implemented all table features.

**Comment by edwin-huber** [comment]
our table API needs quite a bit of work to return the correct values, in the  same format as Azure.
I'm working on getting it straightened out.
Thanks for your patience!

**Comment by alexey-belous** [comment]
Hi,
I have the same issue.

**Comment by MosesTroyer** [comment]
I'm additionally seeing this issue both in testing (specifically CloudTable.DeleteIfExistsAsync) and when using Azure Storage Explorer on OSX- it returns a 404 and fails to delete the table.

**Comment by hope4555** [comment]
Trying to import data using Azure storage explorer, Same error

**Comment by jimmy-dg** [comment]
@craxal @edwin-huber 
Any updates on this? I am getting the same error as well on batch insert operations.

Thanks.

**Comment by edwin-huber** [comment]
I'm working through the backlog, but we are moving support of table storage to the Cosmos Emulator, currently only on Windows and Windows Docker Container, but should eventually be made cross platform.  
We have a release pending in which addresses most of the issues in this thread.

**Comment by atrauzzi** [comment]
Hopefully Microsoft updates all their guidance pointing people to this tool for a cross platform emulator. Otherwise it's going to create frustration to be told "go here" and this project is telling them to go back to a Windows only emulator...

**Comment by edwin-huber** [comment]
We are doing our best to maintain the Azurite Table API until there is an official cross platform emulator for Table and Cosmos.  
The release process has started for 2.7.1.

**Comment by atrauzzi** [comment]
It's worth noting that Windows docker containers can't run on Linux.

**Comment by IdeaHunter** [comment]
@edwin-huber 
FIY: Development of Storage Emulator is being discontinued, Azurite is the way foward for us.
https://github.com/Azure/azure-sdk-for-net/issues/7208#issuecomment-520122952

So no official emulator is ever going to happen

**Comment by atrauzzi** [comment]
@IdeaHunter - This is only pertaining to table storage.

Although I'm kind of tempted to ask at this point why table storage would go to the cosmos emulator when tables are part of storage?  This just seems like a weird way to divide things.

**Comment by IdeaHunter** [comment]
because cosmos table costs x7 more $$ that azure tables

**Comment by IdeaHunter** [comment]
(btw im not a microsot worker in a any way)

**Comment by edwin-huber** [comment]
Hi,  
I think there might be some crossed wires here.  
Don’t panic... we have your back!  😇  
Azurite is the emulator going forward for Blob and Queue storage, and has been rearchitected to make it easier to support long term; for both the community and us.

Tables are however engineered by a different team.  
There is currently no cross platform emulator for tables, other than legacy / v2 Azurite, but it should be coming soon.  
We are giving it our best effort to support tables storage in the legacy branch until there is a new cross platform emulator for tables and cosmos.

**Comment by IdeaHunter** [comment]
@edwin-huber 
looking forward to it!

**Comment by BrainSlugs83** [comment]
So... what should we do if we need a portable Table Storage Emulator *today*? -- Because the latest 2.x branch doesn't appear to support basic operations (like a simple GET with a PartitionKey and a RowKey).

**Comment by atrauzzi** [comment]
Like all proprietary Azure technologies, we've had to take a "don't-adopt" stance. These kinds of situations have definitely contributed to this. Using Azure specific services adds so much uncertainty around our development flows and presents a risk to business continuity.

**Comment by edwin-huber** [comment]
I understand your frustration.  
For this reason we are working hard on getting batch in the table api implemented.  
As soon as the implementation is complete and working with the required samples across our other technologies, we shall release it.

**Comment by edwin-huber** [comment]
We have now released Azurite Table API support in preview.  
We are in the process of shoring up parity with the service, but we now support core scenarios around local development for Azure Table Storage, Azure Functions and Azure Logic Apps.
This addresses the scenario for which this issue was originally opened.  
If you hit anything in the new api, please do let us know. 😄
