### ISSUE TITLE
Storage Explorer Should Run Local Azurite exe on open to improve developer experience

### ISSUE THREAD

**Issue by MrAntix** [Azure/Azurite#2016]
### Which service(blob, file, queue, table) does this issue concern?
Storage Explorer

### Which version of the Azurite was used?
Storage Explorer 1.30

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio 2022

### What's the Node.js version?
n/a 

### What problem was encountered?
Storage explorer has a connected account but the emulator is not running
You open the node and it spins... and spins... then tells you to install Azurite

### Steps to reproduce the issue?
See above

### Have you found a mitigation/solution?
I can go to the directory where its installed and run it, but come on, so can you.
Please make an old developer a little happier and run the emulator ❤️

or, say why you can't if that's the case

Thanks 🤞

![image](https://github.com/Azure/Azurite/assets/873305/4b361b48-3e08-4371-927f-3a2b3b5676b0)

**Comment by blueww** [comment]
@EmmaZhu 
As we discussed, would you please help to look?

**Comment by EmmaZhu** [comment]
Hi @MrAntix ,  It's Storage Explorer's decision on whether emulator should be installed by default. Could you reach Storage Explorer about the requirement?

**Comment by MrAntix** [comment]
Apologies, I thought you were one and the same.

I have found them here https://github.com/microsoft/AzureStorageExplorer for anyone wondering.

Many thanks for the reply
