### ISSUE TITLE
ETag changed during DownloadStreaming.

### ISSUE THREAD

**Issue by NetGH** [Azure/Azurite#2034]
In a concurrent environment, we specified ETag in the BlobDownloadOptions. however, the ETag in the response is changed.

![image](https://github.com/Azure/Azurite/assets/13998151/1cf0d826-6cc6-49da-8ba4-e11b6e811691)

Is that by design in Azure Blob?  or a bug in Azurite? if so that means the client didn't get the version it expected.

**Comment by blueww** [comment]
@NetGH 
Would you please give the Azurite debug log?
We need it to continue invetigation.

**Comment by NetGH** [comment]
https://github.com/Azure/Azurite#scalability--performance 

"Azurite is not a scalable storage service and does not support many concurrent clients."
