### ISSUE TITLE
unexptected TCP RST from azurite side

### ISSUE THREAD

**Issue by Slach** [Azure/Azurite#2053]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
latest docker image
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
I created reproducible docker-compose
https://gist.github.com/Slach/043c85f759d4422a75fceab6dccb1f8d

### What problem was encountered?
TCP RST after make client requests
![image](https://github.com/Azure/Azurite/assets/105560/9bc9ecb2-f9b3-400d-898e-2017708c0118)
![image](https://github.com/Azure/Azurite/assets/105560/3b3a4876-6a26-433f-b120-c4e7b4ced836)

### Steps to reproduce the issue?
```
git clone https://gist.github.com/Slach/043c85f759d4422a75fceab6dccb1f8d
./reproduce.sh
```

### Have you found a mitigation/solution?
No

also look details https://github.com/ClickHouse/ClickHouse/issues/52088

**Comment by blueww** [comment]
@Slach 
Thanks for raising this issue!

Would you please share the Azurite debug log for this issue? 
And please point out in which step of reproduce.sh does this issue repro?

Besides that, just to confirm this kind of issue not happen on product Azure?

**Comment by parshimers** [comment]
I've experienced this issue as well in a different context. The debug log shows nothing, because the connection is immediately terminated by the RST. It happens immediately after the client connects. I can't reproduce it on MacOS but it happens easily on Linux.

**Comment by blueww** [comment]
@parshimers 

Do you use the same Azurite docker image version on linux and maxOS? (Docker image with version latest might be cached in local. IF so you might can clearup the local cached Azurite latest docker image, and try again to make sure you use latest docker image.)

As I also can't repro this issue locally, it will be very difficult for us to investigate. 
As you can't repro on MacOS but can repro on linux (I assume you use same docker image), it looks not an Azurite issue, but some issue related with your OS environment. 

Besides that, does the issue happen randomly, how frequently? If you add some retry logic on storage client side, can it workaround this issue?
