### ISSUE TITLE
Exception ever 5 seconds and excessive logging in Visual Studio

### ISSUE THREAD

**Issue by noontz** [Azure/Azurite#2060]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.22.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio

### What's the Node.js version?
v18.13.0

### What problem was encountered?
Excessive logging of an exception every 5 seconds

### Steps to reproduce the issue?
Open Visual Studio connected to Azurite (Service Dependency)

### Logging output extract from VS Debug:
13:46:31:375	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:31:375	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:31:375	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:31:375	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:31:640	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:36:437	The thread 0xc4c has exited with code 0 (0x0).
13:46:36:437	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:36:437	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:36:437	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:36:437	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:36:437	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:41:359	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:41:359	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:41:359	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:41:609	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:41:609	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:46:385	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:46:385	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:46:385	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:46:635	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:46:635	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:51:385	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:51:385	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:51:385	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll
13:46:51:635	Exception thrown: 'Azure.RequestFailedException' in Microsoft.Azure.WebJobs.Host.Storage.dll
13:46:51:635	Exception thrown: 'Azure.RequestFailedException' in System.Private.CoreLib.dll

### Logging output extract from VS Service Dependencies
ImageAccess: 127.0.0.1 - - [20/Jul/2023:11:46:31 +0000] "HEAD /devstoreaccount1/azure-webjobs-hosts/locks/desktopsteffen-1805179638/host HTTP/1.1" 400 -
ImageAccess: 127.0.0.1 - - [20/Jul/2023:11:46:36 +0000] "HEAD /devstoreaccount1/azure-webjobs-hosts/locks/desktopsteffen-1805179638/host HTTP/1.1" 400 -
ImageAccess: 127.0.0.1 - - [20/Jul/2023:11:46:41 +0000] "HEAD /devstoreaccount1/azure-webjobs-hosts/locks/desktopsteffen-1805179638/host HTTP/1.1" 400 -
ImageAccess: 127.0.0.1 - - [20/Jul/2023:11:46:46 +0000] "HEAD /devstoreaccount1/azure-webjobs-hosts/locks/desktopsteffen-1805179638/host HTTP/1.1" 400 -
ImageAccess: 127.0.0.1 - - [20/Jul/2023:11:46:51 +0000] "HEAD /devstoreaccount1/azure-webjobs-hosts/locks/desktopsteffen-1805179638/host HTTP/1.1" 400 -

### Have you found a mitigation/solution?
No

### Further information
I am not sure if this is related to Azurite or Microsoft.Azure.WebJobs.Host.Storage
I do NOT have any keep alive stuff or recurring triggered call in my code in the service ImageAccess running on 127.0.0.1

**Comment by blueww** [comment]
@noontz 

Would you please share the Azurite debug log for the 400 error?
We need this for continue the investigation.

**Comment by blueww** [comment]
@noontz 
The debug log you attached is on 2023-6-26. Not sure if this is the issue time.
If so, the 400 error is caused the send request account "imageaccount" is invalid, not in Azurite.

Else, Normally Azuite execution from VS is in C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe, and would you like to manually start it with "-debug [localDebugFilePath]", then repro this issue and share the debug log?

**Comment by noontz** [comment]
@blueww

I found the debug log in C:\Users\\####\\AppData\Local\.vstools\azurite\debug.log, and the exception cause is clear:
**_BlobSharedKeyAuthenticator:validate() Invalid storage account devstoreaccount1._**
This links the issue to #2018 as I am using customized storage accounts.
I have this setting in my local.settings.json values:  "AzureWebJobsStorage": "UseDevelopmentStorage=true" to make VS automatically start Azurite, and VS apparently insists on connecting to the non existent devstoreaccount1.
If I set "AzureWebJobsStorage": "UseDevelopmentStorage=**false**" Azurite will not start automatically with VS

So unless there is a setting I am unaware of, it seems customized storage accounts are not compatible with automatically starting Azurite from VS in an Azure Functions VS project

(if you can't tolerate the exception being logged every 5 seconds that is 😎)

**Comment by blueww** [comment]
@noontz 

I am confused. 
When you send request to Azurite, are you using account "devstoreaccount1" or other account name?

Azurite by default will support account name  "devstoreaccount1".
However, if you configure customized storage account name/key in Environment variable (see [link](https://github.com/Azure/Azurite#customized-storage-accounts--keys)) and then start Azurite, Azurite will only support the customized storage account.

I am not so familiar with  "AzureWebJobsStorage", however "UseDevelopmentStorage=true" normally means you will send request with default account "devstoreaccount1". So if you have configured customized account name/key in Environment variable, it's by nature the request will fail.

So would you please check if you have set the customized storage account name/key in Environment variable when start Azurite?
If so, you might should send request with customized account name.
Or remove the environment variable of customized storage account name/key, then start Azurite.

**Comment by noontz** [comment]
@blueww
Sorry for not being explicit enough.

- My code does not send requests to "devstoreaccount1"
- My code sends requests to two customized storage accounts.
- The only way (as far as I know) to start Azurite from VS automatically is setting "UseDevelopmentStorage=true"
- When starting Azurite from VS, VS apparently sends requests to the non existent "devstoreaccount1" every 5 seconds

My point is, that starting Azurite automatically from VS, with customized storage accounts, will trigger this issue.
Starting Azurite manually does not trigger the issue.

So the issue is most likely with VS, not Azurite, but I do not know what repo I should move this issue to. Please feel free to move it to the appropriate repo.

Hope this helps ;)

**Comment by blueww** [comment]
@noontz

As this looks a VS issue instead of Azurite issue, would you like to contact VS team for this issue?
This doc has the details on how to report a VS feedback issue : https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

Besides that, I will close this issue as this is not Azurite issue (Can't be resolved by Azurite code change).
Feel free to raise if you have any further comments/concern.

**Comment by noontz** [comment]
@blueww
I will report to VS and link to this issue.
