### ISSUE TITLE
Response to Blob Delete API call is missing the x-ms-deleted-type-permanent header

### ISSUE THREAD

**Issue by arsenvlad** [Azure/Azurite#2061]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.24

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
N/A

### What's the Node.js version?
N/A

### What problem was encountered?
Azure Blob Storage returns this header for api-version > 2017-07-29 https://learn.microsoft.com/en-us/rest/api/storageservices/delete-blob?tabs=azure-ad#response-headers

However, Azureite does not return this header.

Azure Storage Rust SDK is expecting the x-ms-deleted-type-permanent header and fails when this header is missing in the Azureite response.

Related issue https://github.com/Azure/azure-sdk-for-rust/issues/780

### Steps to reproduce the issue?

* Make a simple [Blob Delete API call](https://learn.microsoft.com/en-us/rest/api/storageservices/delete-blob) and check the response headers.
* x-ms-deleted-type-permanent header is missing.

**Comment by blueww** [comment]
Azurite API is generated from storage swagger, but storage swagger doesn’t define “x-ms-deleted-type-permanent” header in the [Blob_Delete](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fblob%2F4a4fcbb05758711473d337c48541d75ef9283fe3%2Fspecification%2Fstorage%2Fdata-plane%2FMicrosoft.BlobStorage%2Fpreview%2F2021-12-02%2Fblob.json%23L3624C25-L3624C36&data=05%7C01%7Cweiwei%40microsoft.com%7C7ec059634120415ced3008db89761cf8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638254912656399244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qxBi9FvB22NB4aDjhIwu0fdX%2BruNvYG64tfQbJaPrpc%3D&reserved=0) API responds.

I have opened [a swagger issue](https://github.com/Azure/azure-rest-api-specs/issues/24927) for this.

**Comment by blueww** [comment]
@arsenvlad  
I have raised PR https://github.com/Azure/Azurite/pull/2087 to fix this issue. 
Please note, the correct header name is "x-ms-delete-type-permanent" per my test and https://learn.microsoft.com/en-us/rest/api/storageservices/delete-blob?tabs=azure-ad#response-headers

**Comment by blueww** [comment]
The latest Azurite 3.26.0 contains the fix.
