### ISSUE TITLE
Wrong error code for forbidden request

### ISSUE THREAD

**Issue by volleyms** [Azure/Azurite#2064]
### Which service(blob, file, queue, table) does this issue concern?
queue

### Which version of the Azurite was used?
3.24.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Docker (ID: 0bf58610baaf)

### What's the Node.js version?
14.21.3

### What problem was encountered?
Accessing a queue using an SAS token which does not allow to do so, `403 Forbidden` is responded correctly. But the responded error code `AuthorizationFailure` is wrong and must be `AuthenticationFailed` according to the [official API documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes ).

### Steps to reproduce the issue?
Access a queue with an SAS token not sufficient to perform the requested operation.

### Have you found a mitigation/solution?
No.

**Comment by blueww** [comment]
@volleyms 

Would you please give the debug log for this issue, and if you care more than 1 API please give all the API name you care for this issue?
Then we can continue investigate it.

**Comment by volleyms** [comment]
@blueww 

Not much to investigate: `src\blob\generated\artifacts\models.ts` and `src\queue\generated\artifacts\models.ts` just contain an invalid constant in their `StorageErrorCode` enums. The [official API documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes) does not contain such a value, neither in the common area nor in the specific pages for BLOB or queue. Interestingly, the correct one (`AuthenticationFailed`) is defined there as well.

**Comment by blueww** [comment]
I have raised PR https://github.com/Azure/Azurite/pull/2087 to fix this issue.

**Comment by blueww** [comment]
The latest Azurite 3.26.0 contains the fix.
