### ISSUE TITLE
Set Queue ACL fails with Bad Request if Start is missing

### ISSUE THREAD

**Issue by volleyms** [Azure/Azurite#2065]
### Which service(blob, file, queue, table) does this issue concern?
queue

### Which version of the Azurite was used?
3.24.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Docker (ID: 0bf58610baaf)

### What's the Node.js version?
14.21.3

### What problem was encountered?
Setting a queue ACL (according to [the official documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/set-queue-acl)) with an empty `Start` property (which is what a .NET SDK does if not setting the start date), Azurite responds with a `400 Bad Request`, while the real Azure storage succeeds.

Most probably, this is down to the `src\queue\generated\artifacts\mappers.ts` which defines `AccessPolicy.Start` as required.

### Steps to reproduce the issue?
`PUT /devstoreaccount1/test?comp=acl` with an empty `<Start>` tag.

### Have you found a mitigation/solution?
Setting the ACL start to an arbitrary value in the past makes it work.

**Comment by blueww** [comment]
Thanks for reporting this issue!
Will look into it and update later.
