### ISSUE TITLE
Question -- Code Coverage of API implementation

### ISSUE THREAD

**Issue by anna-mazhar** [Azure/Azurite#2072]
Hey, I want to measure how comprehensively my script covers Azure Storage operations. I aim to cover as many paths (including error paths) for a certain operation, e.g., on a create_container request. Now my code coverage tool is giving me code coverage of the entire codebase, but I want to eliminate the code that is not relevant to API implementation, e.g., I can eliminate garbage collection-related code in the calculation. Can you point me to which directories I should target for code coverage calculation in my case? Much appreciated.

**Comment by XiaoningLiu** [comment]
@anna-mazhar Are you referring to the code coverage of Azurite?

**Comment by anna-mazhar** [comment]
@XiaoningLiu Yes!

**Comment by blueww** [comment]
@anna-mazhar 

I am not sure if it makes much sense to calculate Azurite code coverage to measure your script. 
Azurite has a large part of code is auto generated from swagger, and the manually written code are separated in different folders/files.  Besides, Azurite is an emulator, so the code of it has much difference than server and much simpler than server (like garbage collection-related code).

**Comment by anna-mazhar** [comment]
I totally understand that Azurite is a very simplified version of the real service. 

My goal is to assess how thoroughly my code covers Azurite, particularly the parts (of Azurite) that involve implementing REST APIs logic (all paths: valid and error paths). Hence, I do not want to cover the entire codebase of Azure in my coverage calculation. Could you point me to directories that contain Service API implementation logic or alternatively, point me to directories that I should remove from my code coverage calculations, considering my goal?

It's completely fine if this decoupling is hard to define. Any input would be much appreciated.

**Comment by blueww** [comment]
The "generated" folder is auto generated code, 
like in https://github.com/Azure/Azurite/tree/main/src/blob:
- except https://github.com/Azure/Azurite/tree/main/src/blob/generated, other code are mostly manually written (except some interface definition). 
- most API logic are in https://github.com/Azure/Azurite/tree/main/src/blob/handlers and https://github.com/Azure/Azurite/tree/main/src/blob/persistence

**Comment by blueww** [comment]
I will close this issue as this is not for Azurite issue, and the question is answered.
Feel free to container us again if need any further assistance on Azurite.
