### ISSUE TITLE
[ERR] The value "deflate" is invalid for option "encoding"

### ISSUE THREAD

**Issue by vohtaski** [Azure/Azurite#208]
We are using Azurite to emulate azure storage for local testing, however we get an error when we are using "encoding = deflate" setting. It works properly with Azure blob storage but Azurite is throwing an error. I can provide more details if needed.

```
contentSettings.contentEncoding = 'deflate';
```

![image](https://user-images.githubusercontent.com/158421/57193978-620bab00-6f41-11e9-9a93-1d6ed9df9dce.png)

**Comment by XiaoningLiu** [comment]
Hi @vohtaski We just released latest Azurite V3 based on new architecture and TypeScript. Welcome have a try!

**Comment by XiaoningLiu** [comment]
Close this for legacy Azurite V2. Please use Azurite V3.
