### ISSUE TITLE
Invalid "visibilitytimeout" parameters return no error code

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/Azurite#2083]
### Which service (blob, file, queue, table) does this issue concern?

Queue

### Which version of the Azurite was used?

3.2.4

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Visual Studio

### What's the Node.js version?

18.16.0

### What problem was encountered?

Passing a too-large `visibilitytimeout` parameter value to the "Receive Message" endpoint returns a 400 but no error code.

### Steps to reproduce the issue?

See log, which tries using visibility timeouts `0` and `691200`: [azurite.log](https://github.com/Azure/Azurite/files/12228394/azurite.log)

The former contains the header `x-ms-error-code: OutOfRangeQueryParameterValue`, the latter contains no `x-ms` headers. Compare lines 58-69 to 105-110.

### Have you found a mitigation/solution?

I suspect that we should remove the maximum checks here, or handle the errors differently: https://github.com/Azure/Azurite/blob/bb90e2595bf8cf5bd409ed8babdadb2794ea4910/src/queue/generated/artifacts/parameters.ts#L274
https://github.com/Azure/Azurite/blob/bb90e2595bf8cf5bd409ed8babdadb2794ea4910/src/queue/generated/artifacts/parameters.ts#L288

**Comment by blueww** [comment]
@Arithmomaniac 

From [Azure Storage Queue rest API doc](https://learn.microsoft.com/en-us/rest/api/storageservices/get-messages?source=recommendations#uri-parameters), you can see `visibilitytimeout` must "be larger than or equal to 1 second, and it can't be greater than 7 days".
And 604800 is just second of 7 days. 
As a storage rest API emulator, Azurite should be aligned with Storage rest API doc.
So the current azurite behavior is correct and aligned with Azure Storage rest API spec.

Would you please update your program to use a `visibilitytimeout` to a value between 1-604800 ?

**Comment by blueww** [comment]
Close as this is not Azurite issue. Azurite behavior is aligned with [Azure Storage Queue rest API doc](https://learn.microsoft.com/en-us/rest/api/storageservices/get-messages?source=recommendations#uri-parameters).

**Comment by Arithmomaniac** [comment]
I've attached a file of an actual Azure request and error.

[Uploading 210_Full.txt…]()

**Comment by Arithmomaniac** [comment]
Here's a payload from actual Azure storage for `visibilitytimeout=691200`.

[210_Full.txt](https://github.com/Azure/Azurite/files/12280692/210_Full.txt)

To get that error from Azurite, the request handling would have to get to here:
https://github.com/Azure/Azurite/blob/525f697c813da95c1327053cc6fac27032a436ce/src/queue/handlers/MessagesHandler.ts#L64-L77

But as you can see from L107 from [azurite.log](https://github.com/Azure/Azurite/files/12228394/azurite.log), that never happens. I believe the deserialization middleware sees the following from the generated specification for the GET operation:

https://github.com/Azure/Azurite/blob/525f697c813da95c1327053cc6fac27032a436ce/src/queue/generated/artifacts/specifications.ts#L406

Which has this constraint:
https://github.com/Azure/Azurite/blob/525f697c813da95c1327053cc6fac27032a436ce/src/queue/generated/artifacts/parameters.ts#L273-L276

Which is violated, throwing an exception and short-circuiting processing.

**Comment by blueww** [comment]
I have raised PR https://github.com/Azure/Azurite/pull/2087 to fix this issue.

**Comment by blueww** [comment]
The latest Azurite 3.26.0 contains the fix.
