### ISSUE TITLE
storage services authentication 

### ISSUE THREAD

**Issue by vitaly-goot** [Azure/Azurite#21]
I am playing with the emulator. Seems like it does not support authentication, 
https://docs.microsoft.com/en-us/rest/api/storageservices/authentication-for-the-azure-storage-services
The emulator provides static account and key.

AccountName =:: devstoreaccount1
AccountKey ::= Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==

My expectation that it should fail incoming API request with a wrong account and/or key, but it seems azurite does not care much about authentication. Perhaps I am missing some configuration option?

**Comment by edwin-huber** [comment]
@vitaly-goot many thanks for reporting this.

I'm working my way through quite a backlog at the moment, but as Azurite is not designed for production workloads, this doesn't surprise me.
However, as we want to emulate the API as  closely as possible, we should also appropriately respond to invalid credentials.

I'll add this to my Backlog and let you know when it's been addressed.
Kind regards,
Edwin

**Comment by vitaly-goot** [comment]
contributed my code here:
https://github.com/Azure/Azurite/pull/25

**Comment by edwin-huber** [comment]
#25 merged into dev
