### ISSUE TITLE
Guidance needed for running in GitHub actions on Windows

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/Azurite#2120]
### Which service(blob, file, queue, table) does this issue concern?
All, but principally Tables in this scenario

### Which version of the Azurite was used?
3.26.0, the latest as per npm install at the time of writing

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm via GitHub actions

### What's the Node.js version?
Don't know where to find this information

### What problem was encountered?
Running unit tests which access table storage via the well-known emulated connection strings fail with either 'The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.' or 'No connection could be made because the target machine actively refused it 127.0.0.1:10002'

Tried various permutations of:

mkcert as the documentation describes - doesn't work in GitHub as it shows an interactive prompt on `mkcert -install` that can't be answered. Using certutil to install the mkcert generated certificate instead makes no difference.

used powershell New-SelfSignedCertificate -DnsName localhost -CertStoreLocation "Cert:\CurrentUser\My" -KeyLength 2048 -KeyExportPolicy Exportable (example of how to do this was copied from https://github.com/potatoqualitee/azuright/tree/main) to generate the certificate

Using `start /b azurite` in case the issue was the process being shut down between steps didn't make any difference

used potatoqualitee/azuright directly - doesn't work - in this case appears to be an unsatisfactory TLS connection

### Steps to reproduce the issue?

Read everything one can find about how to use azurite, try every permutation described, find that none of them work

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

I don't know how to get this out of GitHub.

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?

No. I am essentially just looking for an example of how to set up Azurite in GitHub actions so that it works.

**Comment by blueww** [comment]
@TWolversonReply 

Would you please share：
1. How do you start Azurite? The command and parameter (hide credential if any)
2. Can you connect to Azurite with other tool/SDK, like Azure storage explorer.
3. We are not family with github Action. However, if you can connect to Azurite with other tool/SDK, this looks not Azurite issue, we might will need github action team support on this.
4. If you don't plan to use https or oauth, please don't use mkcert related stuff currently, to simplify the problem.

**Comment by TWolversonReply** [comment]
Doing some more searching, it appeared that the issue was most likely to do with the way the process was started, so changed the step to:

    - name: Start Azurite storage emulator
      shell: bash
      run: |
        npm install -g azurite
        azurite &

Running via bash (in Windows) and passing & solves the problem. I had tried using `start /B azurite`, which I understand is the Windows/cmd syntax for a background process, but this didn't work either.

I was under the impression that the storage SDKs would expect at least https, so I had various permutations of starting azurite with a self-signed certificate, which is ultimately unnecessary. It would be helpful to spell out what connection settings the `UseDevelopmentStorage=true` well-known connection string implies, since I would normally expect any implementation using storage to connect via https and use some mode of authorization.

**Comment by blueww** [comment]
@TWolversonReply 

You can find the connection string in https://github.com/Azure/Azurite#connection-strings

**Comment by blueww** [comment]
@TWolversonReply

I will close this issue since it looks the original issue is already resolved and not see new asks for a long time. 
Feel free to contact us again if need any further assistance on Azurite.
