### ISSUE TITLE
Cannot change access tier to Cold access tier for block blob

### ISSUE THREAD

**Issue by bcarthic** [Azure/Azurite#2130]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.26.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
V16.15.0

### What problem was encountered?

Receiving the following error when trying change access tier to cold access tier for block blob. As of August 10th, cold tier is GA. The same code works in actual storage account.

The same error is shown even in Azure Storage explorer.

<HTML>
<BODY>
<TABLE><TR><TD>The access tier is not supported for this blob type.<br>RequestId:528237ed-7c81-4604-af55-fdc029f6fe4e<br>Time:2023-08-22T03:00:28.834Z<br>Status: 400 (The access tier is not supported for this blob type.)<br>ErrorCode: AccessTierNotSupportedForBlobType<br><br>Content:<br>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;<br>&lt;Error&gt;<br> &nbsp;&lt;Code&gt;AccessTierNotSupportedForBlobType&lt;/Code&gt;<br> &nbsp;&lt;Message&gt;The access tier is not supported for this blob type.<br>RequestId:528237ed-7c81-4604-af55-fdc029f6fe4e<br>Time:2023-08-22T03:00:28.834Z&lt;/Message&gt;<br>&lt;/Error&gt;<br><br>Headers:<br>Server: Azurite-Blob/3.26.0<br>x-ms-error-code: AccessTierNotSupportedForBlobType<br>x-ms-request-id: 528237ed-7c81-4604-af55-fdc029f6fe4e<br>Date: Tue, 22 Aug 2023 03:00:28 GMT<br>Connection: keep-alive<br>Keep-Alive: REDACTED<br>Transfer-Encoding: chunked<br>Content-Type: application/xml<br></TD></TR></TABLE>

</BODY>
</HTML>

### Steps to reproduce the issue?
This is a sample code to reproduce the issue, the same can be reproduced in Azure Storage Explorer
```
class Program
{
	static async Task Main(string[] args)
	{
		string connectionString = "UseDevelopmentStorage=true"; 
		string containerName = "test";      
		string blobName = "example.jpg";    
		string filePath = "path_to_your_file\\example.jpg";

		BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
		BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);
		BlobClient blobClient = containerClient.GetBlobClient(blobName);

		using (FileStream fs = File.OpenRead(filePath))
		{
			await blobClient.UploadAsync(fs, true);
			fs.Close();
		}

		await blobClient.SetAccessTierAsync(AccessTier.Cold);
	}
}

```
Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
The PR to support cold tier is just merged : https://github.com/Azure/Azurite/pull/2112
Cold tier will be supported in the next Azurite release, which should be in 1-2 monthes.

**Comment by bcarthic** [comment]
Verified that the current version from main works.

**Comment by bcarthic** [comment]
@blueww, Its been more than 6 weeks, do you know when we will the release be available?

**Comment by blueww** [comment]
@bcarthic 
I believe we will have a new release  before end of Oct (normally should be in 2 weeks.)
Before the release is out, You can also run Azurite from latest code with steps in : https://github.com/Azure/Azurite#github

**Comment by bcarthic** [comment]
@blueww, It's almost end of October, there is still no new releases. We have to block few tests because of this delay. Could you let me know when this will be released.

**Comment by blueww** [comment]
@bcarthic 

We are working on the release. 
The latest Azurite 2.27.0 npm package should already include the change.
https://www.npmjs.com/package/azurite/v/3.27.0

**Comment by muhdammar** [comment]
does this issue already resolved? i also got this error today

**Comment by blueww** [comment]
@muhdammar 

Which version of Azurite do you use?
Do you use Azurite 3.27.0 or later?

If so, could you open a new issue with detail repro steps and Azurite debug log (and other info the issue template asked), then we most possibly will have the information we needed to investigate.

**Comment by muhdammar** [comment]
i use version 3.29.0, and im using C# language, i can set the tier in azure cloud storage, but not in azurite. later if i have time, i will try to reproduce again.

**Comment by blueww** [comment]
> i use version 3.29.0, and im using C# language, i can set the tier in azure cloud storage, but not in azurite. later if i have time, i will try to reproduce again. @blueww

I also use .net SDK, and I can set blob tier to cold with latest Azurite. 
Please share your repro code and the Azurite debug log, when you get it repro.
