### ISSUE TITLE
[Feature] Implement S3 persistance layer

### ISSUE THREAD

**Issue by jbpin** [Azure/Azurite#2134]
I'm currently running an Azurite instance to be able to speak Azure Storage SDK pattern between a Windows computer and the storage engine. Whoever, I'm curious if you got some documentation on how to implements an S3 persistant layer rather than Loki or SQL. 
Does it make sense ? 
We are already running S3 backend and have S3 provider with our cloud provider. Unfortunatly, for the job I have to do, the computer will only speak with an Azure Blob Storage endpoint, it is where Azurite does the job, but it is not compatible with S3.
The idea is to use Azurite as a "bridge to", for example, MinIO. I speak with Azurite but all the data come from a S3 bucket. 
If you give me some direction and challenges that is represented by this, I can try to implement something.

**Comment by blueww** [comment]
@jbpin 
Thank you for the suggestion! 
Azurite is an emulator for Azure Storage and we have no plans to offer S3 functionality in Azurite at this time.
