### ISSUE TITLE
Error when installing Azurite vscode extension

### ISSUE THREAD

**Issue by gcarvajal1222** [Azure/Azurite#2153]
vscode version: 

Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

### Steps to reproduce the issue?

Installing the extension, I get the error below: some of my teammates are able to see the same errors, while others can't

![image](https://github.com/Azure/Azurite/assets/36053537/830488b5-d2ef-4c1e-b302-c2e5a41ef1c7)

### Have you found a mitigation/solution?

No

**Comment by blueww** [comment]
@gcarvajal1222 

I see this issue also meet by other user with VS code 1.81.1 on when install other extension. 
https://stackoverflow.com/questions/41530269/error-end-of-central-directory-record-signature-not-found-while-installing-ion
And there's also a workaround in above link. Would you like to have a try?

**Comment by gcarvajal1222** [comment]
@blueww Thanks a lot for the response. 

I am using devcontainers and my workaournd was to install azurite as part of the docker build as root using npm:

`# Install npm and NodeJs
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs \
    npm

#azurite.azurite vscode extension not working properly
RUN npm install -g azurite`

and then in my postStartCommand, I check to see if I have the azurite.azurite installed and if not then start the services:

extension_name="azurite.azurite"
if code --list-extensions | grep -q "$extension_name"; then
    echo "Extension $extension_name is installed"
else
    echo "Extension $extension_name is not installed, so lets start it ourselves"
    azurite -s -l c:\azurite -d c:\azurite\debug.log
    echo "Successfully started all of Azurite Services"
fi

and this works just fine!

**Comment by blueww** [comment]
@gcarvajal1222 

Thanks for the update!

I will close this issue as it looks has been resolved on your side.
Feel free to contact us again if need any further assistance on Azurite.
