### ISSUE TITLE
'Content-Type' not found. Returning default encoding: JSON - when checking existance of non existing blob

### ISSUE THREAD

**Issue by luiswhatever** [Azure/Azurite#2157]
### Which service(blob, file, queue, table) does this issue concern?
BlobClientBase, SerializerEncoding
### Which version of the Azurite was used?
3.26.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub
### What's the Node.js version?
14.21.3
### What problem was encountered?

calling exists() method on a non existing Image/blob leads to a 404 response (OK) that contains no Content-Type header, which leads to unnecessary WARN log
2023-09-11 09:58:53.431  WARN 1 --- [or-http-epoll-2] c.a.c.u.serializer.SerializerEncoding    : 'Content-Type' not found. Returning default encoding: JSON

### Steps to reproduce the issue?

get blobClient, check existance of non existing blob through exists() method. Response contains no Content-Type header, unnecessary WARN is logged

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
@luiswhatever 

Would you please give the detail repro steps, include the SDK language/version, repro code (hide credential)?
And would you please give the Azurite debug log for this issue?
We need the info to see which API has the issue.

**Comment by blueww** [comment]
@luiswhatever 

I will close this issue as not hear from you for a long time.
Feel free to contact us again if need any further assistance on Azurite.
