### ISSUE TITLE
Running Azurite installed via NPM blocks CI on Travis

### ISSUE THREAD

**Issue by JimBobSquarePants** [Azure/Azurite#218]
Running via Travis Ci on Ubuntu 16.04 with the following config:

``` yaml
script:
  - git submodule -q update --init
  - npm install -g azurite
  - azurite --silent --location /home/travis/build/SixLabors/ --debug /home/travis/build/SixLabors/debug.log
  - dotnet restore
```
The console displays the following output.

```bash
$ azurite --silent --location /home/travis/build/SixLabors/ --debug /home/travis/build/SixLabors/debug.log
Azurite Blob service is starting on 127.0.0.1:10000
Azurite Blob service successfully listens on 127.0.0.1:10000
```

But the following command `dotnet restore` never runs. Removing the `azurite` code restores normal functionality.

**Comment by XiaoningLiu** [comment]
@JimBobSquarePants 

`silent` doesn't enforce a background execution, can you try `azurite &` in Linux, or  `start /B azurite` in Windows cmd to start azurite in background?

 We may need a background mode in the future.

**Comment by XiaoningLiu** [comment]
Will close this issue, as it's expected behavior, and background executation is supported by operation system.
