### ISSUE TITLE
non-existent X-Ms-Copy-Source behavior different from real azure storage

### ISSUE THREAD

**Issue by kahing** [Azure/Azurite#219]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

https://github.com/Azure/Azurite/commit/6e64127f22f0208701f0ba7cca82149fa9dbd648

### What problem was encountered?

When issuing a copy against a non-existent blob, azure storage returns 404 whereas Azurite returns 400

### Steps to reproduce the issue?

Send a `PUT` with a non-existent `X-Ms-Copy-Source`

### Have you found a mitigation/solution?

no

**Comment by XiaoningLiu** [comment]
Thanks @kahing , will update!
