### ISSUE TITLE
Docker: console not functioning

### ISSUE THREAD

**Issue by hlubovac** [Azure/Azurite#22]
When I attempt to connect to console, I get this error message:

`OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`

Maybe that's deliberate?

Thanks!

**Comment by edwin-huber** [comment]
Hi, yes, the Docker container is based on Alpine, and a minimal install.
See also: http://containertutorials.com/alpine/get_started.html
