### ISSUE TITLE
[Feature request] Allow disk-based persistence to be completely disabled

### ISSUE THREAD

**Issue by joelverhagen** [Azure/Azurite#2227]
### Which service(blob, file, queue, table) does this issue concern?

all

### Which version of the Azurite was used?

3.26.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

VS Code, npm

### What's the Node.js version?

18.18.2

### What problem was encountered?

Currently, there are two paths that are hard-coded to use disk-based persistence: LokiJS and extent storage. It would be great to enable an `--inMemoryPersistence` option that makes all data (including extents) stored only in memory.

### Steps to reproduce the issue?

All 3 service types (blob, queue, table) use LokiJS which periodically saves to disk. Queue and Blob use extent storage on disk.

### Have you found a mitigation/solution?

No

**Comment by joelverhagen** [comment]
I've started a draft PR here: https://github.com/Azure/Azurite/pull/2228. Let me know if this is something you'd be interested in accepting! Most of the code changes were related to plumbing and documenting configs :)

**Comment by blueww** [comment]
Close as PR @2228 is merged, will in the next Azurite release, which target early/middle of Dec.
