### ISSUE TITLE
Exporting interfaces in npm package to enable Azurite runtime control with code

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/Azurite#226]
Currently Azurite is exported as a command line tool. We can use global command `azurite` to start Azurite process.

I'm wondering if anyone needs to more customized control for Azurite. 
Such as adding more features to Azurite by inject into Azurite middlewares in the runtime, or even implement a different persistency layer.

We can do this by export interfaces in Azurite npm package. So everyone can take azurite as their dependency, and start/close and customize servers in their code directly.

Please vote or feedback if anyone has this requirement.

**Comment by edwin-huber** [comment]
no comments after almost 2 years, closing issue
