### ISSUE TITLE
Cannot Copy Blob OpenRead() Stream

### ISSUE THREAD

**Issue by Richyl2** [Azure/Azurite#227]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
Azurite v3.0.0-preview

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
NPM

### What's the Node.js version?
v8.1.0

### What problem was encountered?
Cannot copy open read blob stream to another stream.

### Steps to reproduce the issue?
1. Create a blob in blob storage
2. Open a read stream of the blob (OpenRead() or OpenReadAsync())
3. Attempt to copy the blob stream to a new stream (stream.CopyTo() or stream.CopyToAsync())

Sample code:
`var cloudBlob = _container.GetBlockBlobReference(blobName);`
`var memoryStream = new MemoryStream();`
`using (var stream = await cloudBlob.OpenReadAsync(cancellationToken)`
`{`
`await stream.CopyToAsync(memoryStream);`
`}`

### Have you found a mitigation/solution?
Use Azurite V2 (2.7.0)

**Comment by XiaoningLiu** [comment]
Hi @Richyl2 I cannot reproduce this issue when trying to download blob via stream. Below is my sample code. My Azure Storage .Net SDK is 9.3.3.

```C#
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage.RetryPolicies;
using System;
using System.IO;
using System.Threading.Tasks;

namespace Azurite
{
    class Program
    {
        static void Main(string[] args)
        {
            sample().Wait();
        }

        static async Task sample()
        {
            string containerName = Guid.NewGuid().ToString();

            CloudStorageAccount storageAccount = CloudStorageAccount.Parse("UseDevelopmentStorage=true;");
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

            Console.WriteLine("Creating Container");
            CloudBlobContainer container = blobClient.GetContainerReference(containerName);
            try
            {
                BlobRequestOptions requestOptions = new BlobRequestOptions() { RetryPolicy = new NoRetry() };
                await container.CreateIfNotExistsAsync(requestOptions, null);
            }
            catch (StorageException)
            {
                Console.WriteLine("If you are running with the default connection string, please make sure you have started the storage emulator. Press the Windows key and type Azure Storage to select and run it from the list of applications - then restart the sample.");
                Console.ReadLine();
                throw;
            }


            string file = "Git-2.16.2-64-bit.exe";
            CloudBlockBlob blockBlob = container.GetBlockBlobReference("blob.data");
            await blockBlob.UploadFromFileAsync(file);


            // Download blob to file system
            Console.WriteLine("Download Blob from {0}", blockBlob.Uri.AbsoluteUri);
            await blockBlob.DownloadToFileAsync(string.Format("./CopyOf{0}", "blob.downloaded.exe"), FileMode.Create);

            // Download blob into stream
            var memoryStream = new MemoryStream();
            using (var stream = await blockBlob.OpenReadAsync())
            {
                //await stream.CopyToAsync(memoryStream);
                string dest = string.Format("./blob.memorystream.exe");
                FileStream fileStream = new FileStream(dest, FileMode.OpenOrCreate);
                Console.WriteLine(dest);
                await stream.CopyToAsync(fileStream);
            }


            Console.WriteLine("Delete Container");
            await container.DeleteIfExistsAsync();
        }
    }
}
```

**Comment by Richyl2** [comment]
Still not working for me. However, the main difference here is I am using the 'Microsoft.Azure.Storage.Blob' SDK (v10.0.3) https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/10.0.3?_src=template . Here is a snippet of the code I am using (looks pretty similar).

`using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Azure.Storage;
using Microsoft.Azure.Storage.Blob;

namespace Azurite.Bug
{
    class Program
    {
        private static readonly byte[] SampleByteArray = new byte[] { 1, 2, 3 };

        static void Main(string[] args)
        {
            Sample().Wait();
        }

        static async Task<byte[]> Sample()
        {
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse("UseDevelopmentStorage=true;");
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

            CloudBlobContainer container = blobClient.GetContainerReference(Guid.NewGuid().ToString());
            await container.CreateIfNotExistsAsync();

            CloudBlockBlob cloudBlockBlob = container.GetBlockBlobReference(Guid.NewGuid().ToString());
            await cloudBlockBlob.UploadFromByteArrayAsync(SampleByteArray, 0, SampleByteArray.Length);

            using (var stream = await cloudBlockBlob.OpenReadAsync())
            {
                using (var memoryStream = new MemoryStream())
                {
                    await stream.CopyToAsync(memoryStream);
                    return memoryStream.ToArray();
                }
            }
        }
    }
}`

**Comment by XiaoningLiu** [comment]
@Richyl2  In your sample, MemoryStream already has data in it's inner _buffer, not sure why it doesn't convert to byte array.

![image](https://user-images.githubusercontent.com/6889160/58791675-3b669000-8625-11e9-9651-7068b1af8e25.png)

**Comment by Richyl2** [comment]
How strange! Thanks for your quick response and help with the issue 👍! Will stick to Azurite v2.7.0 for now as I need this for our build system.
