### ISSUE TITLE
`OperationBlobSASPermission` not requiring "r" permission for a number of operations

### ISSUE THREAD

**Issue by qc00** [Azure/Azurite#2299]
### Which service(blob, file, queue, table) does this issue concern?

blob (but others might also be wrong)

### Which version of the Azurite was used?

master

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

npm

### What's the Node.js version?

irrelevant

### What problem was encountered?

Per [Azure docs](https://learn.microsoft.com/en-us/rest/api/storageservices/get-container-properties?tabs=shared-access-signatures#account-sas) calling `GET` on a container requires the SAS token to have "r" permission; however, Azurite code does not enforce that:

https://github.com/Azure/Azurite/blob/caa3429f861c821882f17a31db4a6393dc162933/src/blob/authentication/OperationBlobSASPermission.ts#L62-L69

In fact, it's not enforcing the permission for a lot of operations.

### Have you found a mitigation/solution?

Patching the source code.

**Comment by blueww** [comment]
@qc00 

It looks this issue related with the code change in https://github.com/Azure/Azurite/commit/4209080ce250d8028687a4f27370e69511dc45b2.
The above code you mentioned is for blob SAS, and Blob SAS is not allowed to do container Get properties (container SAS also not allowed, only account sas allowed, see [link](https://learn.microsoft.com/en-us/rest/api/storageservices/get-container-properties?tabs=shared-access-signatures#:~:text=The%20Get%20Container%20Properties%20operation%20supports%20supports%20authorization%20using%20an%20account%20SAS.)), so there are no permission set, which mean this operation is not allowed with blob SAS.
However, with the above code change, the operation without permission will pass authentication validation. We will check this and see how to fix it.

**Comment by blueww** [comment]
This issue is already fixed by https://github.com/Azure/Azurite/pull/2305.
Close as the fix is already released in 3.28.0.
