### ISSUE TITLE
Start Azurite Blob Service error: Unexpected token '', ""... is not valid JSON

### ISSUE THREAD

**Issue by jayman-rhdhv** [Azure/Azurite#2301]

**Comment by blueww** [comment]
@jUddin-rhdhv 

We need more information to investigate this issue.
1. The Azurite debug log for this error. (see [link](https://github.com/Azure/Azurite#visual-studio-code-extension:~:text=by%20default%20false-,azurite.debug,-Output%20debug%20log))
2. The Azurite version (Does it repro after you install the latest Azurite VS code extension?)
3. Does this error happen just after you start Azurite blob service or after a while? 
5. OS information, OS, version, language
6. VS code version


Normally, by following the issue template, you can input most of the info that we needed to investigate the issue.

**Comment by lloydgeorge** [comment]
I had a similar issue while developing azure durable functions in VS Code using Azurite. Azurite blob service wouldn't start showing json error. I deleted the __azurite_db_blob__.json and similar azurite files from my solution(root folder) and that solved it.

**Comment by EmmaZhu** [comment]
Hi @lloydgeorge , 

Can you share more info to help us on investigation:

1. The Azurite debug log for this error.
2. The Azurite version (Does it repro after you install the latest Azurite VS code extension?)
3. Does this error happen just after you start Azurite blob service or after a while?
4. OS information, OS, version, language
5. VS code version
