### ISSUE TITLE
Unable to use DefaultAzureCredential on Azurite

### ISSUE THREAD

**Issue by phoebusm** [Azure/Azurite#2303]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
3.27.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
14.21.3
### What problem was encountered?
I have been trying to setup Azurite in some python unit tests with `DefaultAzureCredential`.  I have referred to a previous ticket https://github.com/Azure/Azurite/issues/1750 but it does not specify how to setup. And on https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#azure-blob-storage, 
```
var client = new BlobContainerClient(
    new Uri("https://127.0.0.1:10000/devstoreaccount1/container-name"), new DefaultAzureCredential()
  );
```
, it shows my idea is doable. My test code
```
from azure.storage.blob import BlobServiceClient
from azure.identity import DefaultAzureCredential

token_credential = DefaultAzureCredential()
blob_service_client = BlobServiceClient(
    account_url="https://127.0.0.1:10000/devstoreaccount1", credential=token_credential, connection_verify=False
)
azurite_container = "abc"
container_client = blob_service_client.get_container_client(container=azurite_container)
if not container_client.exists():
    blob_service_client.create_container(name=azurite_container)
```
My above test code never works with below errors
```
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

        AzurePowerShellCredential: PowerShell is not installed
        AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
```
 as the manual has never suggested what is the default `AZURE_TENANT_ID`, `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET` for Azurite. 

### Steps to reproduce the issue?
As above. No relevant log available on Azurite.
### Have you found a mitigation/solution?
Connections using using shared key and sas work fine.

**Comment by blueww** [comment]
@phoebusm 

Do you mean:
1. BlobContainerClient created from following code works well:
```
var client = new BlobContainerClient(
    new Uri("https://127.0.0.1:10000/devstoreaccount1/container-name"), new DefaultAzureCredential()
  );
  ```
2. BlobContainerClient created from following code not work :
```
token_credential = DefaultAzureCredential()
blob_service_client = BlobServiceClient(
    account_url="https://127.0.0.1:10000/devstoreaccount1", credential=token_credential, connection_verify=False
)
azurite_container = "abc"
container_client = blob_service_client.get_container_client(container=azurite_container)
```

If so, this looks the request send from SDK to Azurite should be different in the 2 scenarios (but they should be similar).
Would you please share Azurite debug log for request send from BlobContainerClient in above 2 scenarios, and we can have more idea on this.

**Comment by phoebusm** [comment]
@blueww Thanks for your prompt reply
1.
```
var client = new BlobContainerClient(
    new Uri("https://127.0.0.1:10000/devstoreaccount1/container-name"), new DefaultAzureCredential()
  );
```
is copied from https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#azure-blob-storage. I use it as an example to show `DefaultAzureCredential` authentication should be supported by `Azurite` but the manual lacks guidelines for setup, e.g. what is the default AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET for Azurite?
And  no log was captured on Azurite while trying `DefaultAzureCredential`.

2. With shared key credential, my python example will work:
```
blob_service_client = BlobServiceClient(
    account_url="https://127.0.0.1:10000/devstoreaccount1",
    credential=AzureNamedKeyCredential(
        "devstoreaccount1", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
    ),
    connection_verify=False,
)
azurite_container = "abc"
container_client = blob_service_client.get_container_client(container=azurite_container)
if not container_client.exists():
    blob_service_client.create_container(name=azurite_container)
```
3. I use below command for starting Azurite:
```
azurite --skipApiVersionCheck --blobPort 10000 --blobHost 127.0.0.1 -d debug.log --key server.key --cert server.pem
```

**Comment by blueww** [comment]
@phoebusm 

It looks you don't start Azurite with parameter `--oauth basic`.
By default, Azurite doesn't support OAuth and bearer token. Please see how to enable OAuth authentication in :  https://github.com/Azure/Azurite#oauth-configuration

**Comment by phoebusm** [comment]
@blueww 

I have tried adding parameter `--oauth basic` for starting Azurite. It doesn't change the test result.
Understand that the .net example works. Can you provide a working python example as well?

**Comment by blueww** [comment]
@phoebusm 

I will close this issue as not hear from you for a long time.
From the linked https://github.com/Azure/azure-sdk-for-python/issues/33297, it looks this is not Azurite issue, but some client code issue.

Feel free to contact us again if you need any further assistance on Azurite.

**Comment by jrichardsz** [comment]
Hi. I have the same error with nodejs

## Doesn't work using DefaultAzureCredential 

If I use the DefaultCredential example from official docs,it doesn't work

https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio%2Cblob-storage#azure-sdks

```js
const { DefaultAzureCredential } = require("@azure/identity");
const { BlobServiceClient } = require("@azure/storage-blob");
const defaultAzureCredential = new DefaultAzureCredential();

async function uploadBlob(url, containerName, blobName, blobContents) {
    const blobServiceClient = new BlobServiceClient(url, defaultAzureCredential);

    const containerClient = blobServiceClient.getContainerClient(containerName);

    try {
        await containerClient.createIfNotExists();
        const blockBlobClient = containerClient.getBlockBlobClient(blobName);
        const uploadBlobResponse = await blockBlobClient.upload(blobContents, blobContents.length);
        console.log(`Upload block blob ${blobName} successfully`, uploadBlobResponse.requestId);
    } catch (error) {
        console.log(error);
    }
}

uploadBlob("https://localhost:10000/devstoreaccount1", "container-name", "foo.txt", "bar");
```

<details>

<summary>Log</summary>

```
RestError: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
RequestId:689a0715-0dbc-482a-bb74-99a4373018e1
Time:2024-10-03T21:41:31.245Z
 {
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "url": "https://localhost:10000/devstoreaccount1/container-name?restype=REDACTED",
    "headers": {
      "x-ms-version": "REDACTED",
      "accept": "application/xml",
      "user-agent": "azsdk-js-azure-storage-blob/12.24.0 core-rest-pipeline/1.16.0 Node/22.9.0 OS/(x64-Windows_NT-10.0.19045)",
      "x-ms-client-request-id": "65e11060-f4f4-4c77-b237-01bc6f02c68c",
      "x-ms-date": "REDACTED",
      "authorization": "REDACTED"
    },
    "method": "PUT",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "65e11060-f4f4-4c77-b237-01bc6f02c68c",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "server": "Azurite-Blob/3.30.0",
    "x-ms-request-id": "689a0715-0dbc-482a-bb74-99a4373018e1",
    "content-type": "application/xml",
    "date": "Thu, 03 Oct 2024 21:41:31 GMT",
    "connection": "keep-alive",
    "keep-alive": "timeout=5",
    "transfer-encoding": "chunked",
    "message": "Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:689a0715-0dbc-482a-bb74-99a4373018e1\nTime:2024-10-03T21:41:31.245Z",
    "code": "AuthorizationFailure"
  },
  "message": "Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:689a0715-0dbc-482a-bb74-99a4373018e1\nTime:2024-10-03T21:41:31.245Z"
}
```

</details>


## It works using StorageSharedKeyCredential  instead DefaultCredential 

```js
const { DefaultAzureCredential } = require("@azure/identity");
const { BlobServiceClient } = require("@azure/storage-blob");
const { StorageSharedKeyCredential } = require("@azure/storage-blob");

async function uploadBlob(url, containerName, blobName, blobContents) {

    const AZURE_STORAGE_ACCOUNT = 'devstoreaccount1';
    const AZURE_STORAGE_ACCESS_KEY = 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==';
    const sharedKeyCredential = new StorageSharedKeyCredential(AZURE_STORAGE_ACCOUNT, AZURE_STORAGE_ACCESS_KEY);

    const blobServiceClient = new BlobServiceClient(url, sharedKeyCredential);

    const containerClient = blobServiceClient.getContainerClient(containerName);

    try {
        await containerClient.createIfNotExists();
        const blockBlobClient = containerClient.getBlockBlobClient(blobName);
        const uploadBlobResponse = await blockBlobClient.upload(blobContents, blobContents.length);
        console.log(`Upload block blob ${blobName} successfully`, uploadBlobResponse.requestId);
    } catch (error) {
        console.log(error);
    }
}

uploadBlob("https://localhost:10000/devstoreaccount1", "container-name", "foo.txt", "bar");
```

<details>

<summary>Log</summary>

```
Upload block blob foo.txt successfully aec8994d-217e-40b6-834b-d324bc76833a
```

</details>

## Contenxt

- Nodejs : v22.9.0
- Azurite: 3.30.0

## Additional

I detected this using c# trying to setup a EventProcessorClient with a checkpoint based on blob storage

**Comment by Alan-Hinton** [comment]
> [@phoebusm](https://github.com/phoebusm)
> 
> It looks you don't start Azurite with parameter `--oauth basic`. Azurite doesn't support OAuth and bearer token by default. Please see details for how to enable OAuth authentication in: https://github.com/Azure/Azurite#oauth-configuration

I am seeing similar problems when switching over to using `DefaultAzureCredential`.  I am using Visual Studio, which starts Azurite automatically in http mode and therefore doesn't support those credentials.  Do you know if there is any way to get Visual Studio to add the `--oauth basic` command line option when it start Azurite?
