### ISSUE TITLE
Blob: The API version 2023-11-03 is not supported by Azurite 

### ISSUE THREAD

**Issue by HerrDerb** [Azure/Azurite#2313]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
mcr.microsoft.com/azure-storage/azurite:latest

client library 'com.azure:azure-storage-blob:12.25.1'
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
dockerhub

### What problem was encountered?
The API version 2023-11-03 is not supported by Azurite

**Comment by jkonecki** [comment]
I'm experiencing the same issue while running Azurite that came with Microsoft Visual Studio Enterprise 2022 (64-bit) - Version 17.9.0 Preview 1.1

**Comment by blueww** [comment]
@jkonecki 

API version 2023-11-03 is already supported in Azurite 2.27.0 and later, see https://github.com/Azure/Azurite/blob/main/ChangeLog.md#202310-version-3270.

However, Visual studio need time to upgrade Azurite version in it, this is out of Azurite team control. This doc has the details on how to report a VS feedback issue : https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

Before Visual studio upgrade Azurite version, you can also run latest Azurite from npm/VS Code extension/docker. 
You can also run Azurite with parameter "--skipApiVersionCheck" to avoid this failure.

**Comment by HerrDerb** [comment]
🤦‍♂️I didn't use the latest image

**Comment by jackwoodward** [comment]
@blueww I think you mean 3.27.0, the link makes it clear but I didn't click on it for a while :)

**Comment by blueww** [comment]
> @blueww I think you mean 3.27.0, the link makes it clear but I didn't click on it for a while :)

Oh, yes. I mean 3.27.0.
