### ISSUE TITLE
Cannot start azurite table service

### ISSUE THREAD

**Issue by mscherotter** [Azure/Azurite#2329]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
3.29.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS Code Extension
### What's the Node.js version?
18.18.0
### What problem was encountered?
Restarting after power failure, table service will not start
![image](https://github.com/Azure/Azurite/assets/641702/18c3c11f-28fd-438a-acd6-47a54354cf54)
I have uninstalled azurite and reinstalled it.  Queue and blob startup fine.
### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by EmmaZhu** [comment]
Hi @mscherotter ,

Azurite as a simulator doesn't have protection on power failure, power failure may have caused Azurite data file corruption. Reinstallation won't clean up Azurite data files. Cleaning up these data files should be able to resolve the issue.

By default, Azurite puts data file in current working directory. You can use following setting in VS Extension to change the path: 
![image](https://github.com/Azure/Azurite/assets/6396650/78d0cd64-7e3b-4446-87d7-1311d592d511)

Azurite data file name starts with `__`: 
![image](https://github.com/Azure/Azurite/assets/6396650/c1f5cb16-9e49-47bf-8425-2e56f6087329)

**Comment by EmmaZhu** [comment]
No updates from customer for more than 2 weeks. Close this issue for now. Any further assistant required, please feel free to reopen it or open a new one.
