### ISSUE TITLE
functions host is not able to establish a connection to Azurite.

### ISSUE THREAD

**Issue by A30014424** [Azure/Azurite#2339]

**Comment by A30014424** [comment]
error:  Azure.Core: Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)). Azure.Core: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Http: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Sockets: No connection could be made because the target machine actively refused it.

**Comment by sm-palo** [comment]
I am also getting the same error, using Azurite v3.29.0, any help would be much appreciated.

**Comment by EmmaZhu** [comment]
Hi @A30014424 , @sm-palo , can you share more detail steps on how to reproduce the issue?

**Comment by A30014424** [comment]
@EmmaZhu, @sm-palo for me the issue is resolved now, downloading storage emulator did the trick, providing the steps, hope it helps

Step 1- Download the storage emulator - https://go.microsoft.com/fwlink/?linkid=717179&clcid=0x409
Step 2 - Once downloaded check the status by executing below command in cmd
"%programfiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" status
Step 3 - If it is not running then execute below command
"%programfiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" init
 "%programfiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start

Step-4 If port is conflicting  then change the port number in the file AzureStorageEmulator.exe.config

**Comment by blueww** [comment]
@A30014424 

It looks you are not using Azurite.
However, good to know your issue is resolved. I will close this issue.

Feel free to contact us again if you need any further assistance on Azurite.
