### ISSUE TITLE
Install Legacy version of azurite

### ISSUE THREAD

**Issue by Karthickeyanofficial** [Azure/Azurite#235]
Could you please let us know the steps to install the older(legacy V2) version of azurite?

**Comment by XiaoningLiu** [comment]
@Karthickeyanofficial You can install any Azurite versions by `npm install -g azurite@<version-number>`. And find 

We'd like to know for what reason blocking you moving to V3. Such as feature missing or issues? We will resolve this if any.

**Comment by XiaoningLiu** [comment]
Will close this issue.

**Comment by iamNoah1** [comment]
@XiaoningLiu at least for me the reason to use legacy version is that new versions don't include tablestorage

**Comment by XiaoningLiu** [comment]
@iamNoah1 Check Azurite v3 Table project https://github.com/Azure/Azurite/projects/2, open to contribution!
