### ISSUE TITLE
Unable upload directory structure into azurite blob storage

### ISSUE THREAD

**Issue by Ranjan-23** [Azure/Azurite#2351]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.29
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Dockerhub

### What's the Node.js version?
18.18

### What problem was encountered?
While uploading directory structure recursively to blob it is only uploading the file that also the lastest one , I want to upload the complete directory structure , is there any way to upload using SDK 

I am using java SDK 
### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by EmmaZhu** [comment]
Hi @Ranjan-23 ,

Azurite is an emulator which is following Azure Storage's behavior. In Azure Storage, blob directory is a virtual concept, there isn't a physical object to represent the directory, directory is only a segment in blob name string with '/' as separator. 

For example, for a blob with name `aa/bb/blob`, you can have an application to recognize `aa` and `bb` as a directory, but in Azure Storage, it doesn't have any physical stored object named with `aa` or `bb`.

Thanks
Emma

**Comment by blueww** [comment]
@Ranjan-23 

I will close this issue as you question is answered.

Feel free to contact us again if need any further assistance on Azurite.
