### ISSUE TITLE
Expect Azurite to fail when inserting doubles greater than MAX_VALUE but succeeds instead

### ISSUE THREAD

**Issue by richardMSFT** [Azure/Azurite#2387]
### Which service(blob, file, queue, table) does this issue concern?
Table storage

### Which version of the Azurite was used?
Azurite 3.29.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v18.15.0

### What problem was encountered?
When using azurite emulated table storage, entities that have a property of type `Edm.Double` who's value is greater than the `MAX_VALUE` can be  upserted successfully, whereas with Azure Table Storage this operation will fail with "InvalidInput: An error occurred while processing this request."

When inserted into emulated table storage, the value of the property in azurite will also be `null`.

This causes a problem when trying to query/list entities in the table. There will be an error when trying to parse the response body with something similar to:

```
Error "SyntaxError: Unexpected token 'I', ...","Property10":Infinity,""... is not valid JSON" occurred while parsing the response body
```

### Steps to reproduce the issue?
Create an entity with a property that has the type `Edm.Double` and a value of the string `13e7705`.

Try upserting the entity into Azurite table storage.

Expect the operation to fail, however it succeeds.

### Have you found a mitigation/solution?
Have azurite emulate the behavior of table storage and throw an error when trying to insert a number greater than `MAX_VALUE`.

**Comment by blueww** [comment]
@richardMSFT 

Thanks for raising this issue!
I have raised a PR to fix it: https://github.com/Azure/Azurite/pull/2388

**Comment by blueww** [comment]
The fix PR is merge. Normally will release in the next Azurite release.
