### ISSUE TITLE
Help request: How to setup Azurite HA?

### ISSUE THREAD

**Issue by olljanat** [Azure/Azurite#24]
I was wondering that how others have been solved high availability on their Azurite deployments?

Old skool way mapping storage from NAS to two nodes most probably works but then storage system it selves is SPOF.

On Azure they are using [data replication](https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy) but which is good/tested option for it wilt Azurite?

**Comment by edwin-huber** [comment]
Hi,
Please let me know if I have understood / answered your question in the way you expected...

Azurite is just the Azure storage emulator, and not designed for production workloads.
If you want to simulate multiple storage accounts for your offline application development, then you can start multiple instances of Azurite pointing to different folders on disk, and using different ports for the various storage services.

Cheers,

Edwin

**Comment by olljanat** [comment]
We are currently running all our applications on dedicated infrastructure but we want to develop our new applications on way that we are able to migrate them public cloud in future if we decide so.

We have consider to use Azurite as blob storage for our applications and run that even on our production Docker Swarm. But if we do so we need to make sure that storage is always available from applications point of view.

That why I was asking how others have solved that issue but it is interesting to also hear if anyone else is not doing like this so we know look some other solutions?

**Comment by edwin-huber** [comment]
For Docker  containers, if you do not currently use a Blob storage, you can mount disks or blob storage.
Check out the following as an option to use blob storage instead of file storage:
https://github.com/Azure/azure-storage-fuse

**Comment by edwin-huber** [comment]
I'm closing this issue for now, hit me up if anything is not clear.
Thanks,
Edwin
