### ISSUE TITLE
Is there a web portal to  check the received objects?

### ISSUE THREAD

**Issue by richard-leon-130524** [Azure/Azurite#2403]
### Which service(blob, file, queue, table) does this issue concern?

Queue

### Which version of the Azurite was used?

Azurite V3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub + https://mcr.microsoft.com/en-us/product/azure-messaging/eventhubs-emulator/about

### What's the Node.js version?

It is handled  by its Dockerfile

### What problem was encountered?

I cannot find an option to check or see the objects

I'm looking an option like Active MQ has

![Lz7YX](https://github.com/Azure/Azurite/assets/170019116/2f0e9156-ba55-4285-a096-360d4fdc4b31)

### Steps to reproduce the issue?

- There are not issues

### Have you found a mitigation/solution?

- I'm reviewing the nodejs code, specially the express configuration

**Comment by blueww** [comment]
@richard-leon-130524 

Azurite support rest API of Queue like product Azure does, so you can use any tool that support Queue rest API to list queue and see the result, like with PowerShell:
```
PS C:\> $ctx = New-AzStorageContext -ConnectionString $connectionstring

PS C:\> Get-AzStorageQueue -Context $ctx


   Storage Account Name: devstoreaccount1

Name  Uri                                           ApproximateMessageCount
----  ---                                           -----------------------
test  http://127.0.0.1:10001/devstoreaccount1/test  2                      
test2 http://127.0.0.1:10001/devstoreaccount1/test2 0       
```

Not sure how ActiveMQ works, however if it support configure storage account connection string, you should can use it to view Queue in Azurite.

**Comment by blueww** [comment]
@richard-leon-130524

I will close this issue as not hear from you for a long time.
Feel free to contact us again if need any further assistance on Azurite.
