### ISSUE TITLE
Update mysql2 version

### ISSUE THREAD

**Issue by nicholas-lockhart** [Azure/Azurite#2415]
### Which service(blob, file, queue, table) does this issue concern?
N/A

### Which version of the Azurite was used?
Azurite 3.30.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub
mcr.microsoft.com/azure-storage/azurite:3.30.0

### What's the Node.js version?
v20.10.0

### What problem was encountered?
I noticed that the version of mysql2 (3.7.0) being used is several months old. I know that there were a couple of significant CVEs that were resolved in 3.9.7, and there was a new version created not too long ago (3.10.0). 

When do we think that Azurite will be using a newer version of mysql2 for testing?

### Steps to reproduce the issue?
N/A

**Comment by blueww** [comment]
@nicholas-lockhart 

Thanks for raising the issue!
Could you please help to clarify which mysql2 version do you mean?

Do you mean mysql client, Azurite currently refer to `"mysql2": "^3.2.0"`, see [link](https://github.com/Azure/Azurite/blob/afa2c37579b9a8c9506ded4b6c545f9d5fb80812/package.json#L34C5-L34C24).

We are currently working on some other new features and improvements, so this might won't be our recent priority.

Azurite welcome contribution!
It would be great if you could raise a PR to update mysql2 version!

**Comment by nicholas-lockhart** [comment]
@blueww 

Yes, the mysql client is the dependency in question. You can see [here](https://github.com/Azure/Azurite/blob/afa2c37579b9a8c9506ded4b6c545f9d5fb80812/package-lock.json#L7335) that is resolves to 3.7.0 for this project. Looking at NPM's versions available, it can be seen that there is now a 3.10.1 version available which has been a popular download, assuming it fixed some security issues based on the download count trends.

**Comment by blueww** [comment]
Hi @nicholas-lockhart 

Azurite welcome contribution!
It would be great if you could raise a PR to update mysql2 version!

We are currently working on some other new features and improvements, so this might won't be our recent priority.

**Comment by nicholas-lockhart** [comment]
@blueww, PR opened https://github.com/Azure/Azurite/pull/2418
