### ISSUE TITLE
Docker container is not up-to-date

### ISSUE THREAD

**Issue by Rutgerdj** [Azure/Azurite#2435]
### Which service(blob, file, queue, table) does this issue concern?

All services (Blob, File, Queue, Table)
### Which version of the Azurite was used?

Not applicable (N/A)
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
 
DockerHub
### What's the Node.js version?

Not applicable (N/A)
### What problem was encountered?

The version of Azurite available on DockerHub is outdated.
### Steps to reproduce the issue?

N/A
### Have you found a mitigation/solution?

I build the Docker container myself and push it to my own account. This workaround is functional but not ideal.

I can also use the outdated container and pass the `--skipVersionCheck` parameter, but I just want to use the latest version

**Comment by blueww** [comment]
@EmmaZhu 
Would you please help to follow up?

@Rutgerdj 
We will update docker image in every Azurite release.
Why do you think the docker container is not updated? Do you use the local cached latest Azurite docker image? If so, try to delete it and redownload it, and see if it will be updated.

**Comment by Rutgerdj** [comment]
I do indeed think it has something to do with the cache being used. I can't reproduce the issue and I see that the latest tags (`3.30.0`) do exist in the container registry. My apologies for the confusion.
