### ISSUE TITLE
Port specification not working (docker, --blobPort)

### ISSUE THREAD

**Issue by hladnykokos** [Azure/Azurite#2439]
### Which service(blob, file, queue, table) does this issue concern?
All services: blob/queue/table

### Which version of the Azurite was used?
Very latest, hash: d9dc9980c4d032fc8bdd0dfa79e5a8a16dacb82269ec996e24a75c3de950e5b6

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
docker pull

### What problem was encountered?
The service TCP ports can't be specified.

### Steps to reproduce the issue?
This is the minimalistic version, skipping export ports etc., just to demostrate that the `--blobPort` is not taken:
`docker run mcr.microsoft.com/azure-storage/azurite --blobPort 777`

The command gives me this error:
`node: bad option: --blobPort`

Please notice, that the given command is really just a stripped-down demo: I'm aware of all the other port-options, naming container etc. - all the possible args combinations gave me exactly that error, regardless what I've tried.

### Have you found a mitigation/solution?
When specifying explicitely a sub-service, like `azurite-blob`, the `--blobPort` can be specified correctly. But I need to use all the services, like tables and queues: it seems that running with `azurite-blob` runs only that one service, blob - and the other services won't run.

For example, this runs fine, but it's useless, as it listens only for the blob-requests obviously; but the point is, the `--blobPort` is take here w/out issues:
`docker run mcr.microsoft.com/azure-storage/azurite azurite-blob --blobPort 777`

**Comment by blueww** [comment]
@hladnykokos 

If you would like to run Azurite blob service on a specific port, you should run `>docker run mcr.microsoft.com/azure-storage/azurite azurite --blobPort 777`. 
With "azurite", the "--blobPort" will be taken as Azurite parameter.
Without "azurite", the "--blobPort" will be taken as docker parameter. However docker doesn't has such a parameter so report error.

Besides that, the above command can start Azurite, but the Azurite can't be connected. You need add 2 more parameter as: `docker run -p 777:777 mcr.microsoft.com/azure-storage/azurite azurite --blobPort 777 --blobHost 0.0.0.0`. Then you can connect to Azurite with 777 port on you local machine. 

You can find all parameters and their usage in https://github.com/Azure/Azurite#customize-all-azurite-v3-supported-parameters-for-docker-image
