### ISSUE TITLE
Azurite not recognizing accounts other than default even though prerequisites are met.

### ISSUE THREAD

**Issue by jkempf42** [Azure/Azurite#2447]
### Which service(blob, file, queue, table) does this issue concern?

Blob service

### Which version of the Azurite was used?
3.31.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v20.16.0
### What problem was encountered?
Not recognizing nondefault accounts although they are set in the AZURE_ACCOUNTS environmen variable
### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.
[debug.log](https://github.com/user-attachments/files/16482625/debug.log)

### Have you found a mitigation/solution?
Use the default account but that is not ideal since I'd like to simulate multiple account names.

**Comment by blueww** [comment]
@jkempf42 

We have test case to cover this scenario, so this normally can't happen. 

Would you please share the detail repro steps, include but not limited to:
1. The repro OS
2. how you setup Azurite
3. how you set environment variable? User or system? With admin or other credential?
4. How you start Azurite? Command line? With admin or other credential?
5. Azurite debug log.

Please hide credential in all above sharing if any.

**Comment by jkempf42** [comment]
I found the problem. You can close the ticket, sorry for the confusion.

        jak
