### ISSUE TITLE
Consider removing '*' from Activation Events

### ISSUE THREAD

**Issue by JustinGrote** [Azure/Azurite#2467]
The extension is very heavyweight startup, 2s on my machine and a lot of cpu cycles each time even if I'm not using it.

Ideally your activation events would be the existing onCommand events, and a `workspaceContains` even that looks for the typical azurite cache files indicating azurite is in use in the workspace.

At worst, change `*` to `onStartupFinished` so that vscode startup time is not impacted by the extension loading.

Due to this behavior I generally have to disable it and only enable it in workspaces I use it, it would be nice for it to be more behaved.

**Comment by blueww** [comment]
@JustinGrote 

Thanks for the suggestion!
We will look into it.

Besides that, Azurite welcome contribution!
It would be great if you could raise a PR to fix it.
