### ISSUE TITLE
Getting the correct version of a Azurite

### ISSUE THREAD

**Issue by GrahamSnee** [Azure/Azurite#2479]
As a developer I wish to spend more time developing rather than patching tooling etc.
The latest version on Visual Studio is only support 3.30.0 which is not supporting the latest version of the storage API's
Version 3.31.0 is not event marked as the latest on the project front page but is obtainable as source code.
I have a couple of options in terms of either waiting for a VS update (V3.31.0 did not mark this version), or download the latest source and build etc.
When creating release's, it would be better if we could download the latest version of binaries and get on with dev rather than spending time patch.

**Comment by EmmaZhu** [comment]
I can quite understand your concern. Seems the delay on releasing Azurite on VS causes inconvenience in your project?
 
Our release on VS is to send package to VS team and VS team will update their repositories on their own schedule. 

Would you like to contact VS team for this the delay?
This doc has the details on how to report a VS feedback issue : https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

**Comment by blueww** [comment]
Close as the question is answered.
Feel free to contact us if need any further assistance on Azurite.
However, for Azurite release version in VS, this is controlled by VS team instead of Azurite team, please contact VS team with the link in above comment if need any support.
