### ISSUE TITLE
3.32.0 not listed on https://github.com/Azure/Azurite/releases

### ISSUE THREAD

**Issue by EklipZgit** [Azure/Azurite#2481]
version 3.32.0 isn't listed in the releases list here https://github.com/Azure/Azurite/releases

Would appear that here
https://mcr.microsoft.com/v2/azure-storage/azurite/tags/list

is the only place on the internet 3.32.0 can be found? DockerHub https://hub.docker.com/r/microsoft/azure-storage-azurite even says last updated 5 months ago, which makes it sound like there ISNT a new release that supports API Version 2024-11-04. I would never have thought to click the More History Tags link and find 3.32.0 mid-way in the list.

**Comment by blueww** [comment]
@EmmaZhu 

Would you please help to check if we have added 3.32.0 tag?

**Comment by EmmaZhu** [comment]
Added tag for 3.32.0
