### ISSUE TITLE
Add support for 02-02-2019 of service

### ISSUE THREAD

**Issue by amishra-dev** [Azure/Azurite#249]
### Which service(blob, file, queue, table) does this issue concern?
All of them
### Which version of the Azurite was used?
Feature request for the next version
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
https://github.com/Azure/azure-sdk-for-net/issues/7208
### What problem was encountered?
No support for 02-02-2019
### Steps to reproduce the issue?
Feature request
### Have you found a mitigation/solution?
no

**Comment by amishra-dev** [comment]
Request raised in .NET repo https://github.com/Azure/azure-sdk-for-net/issues/7208

**Comment by XiaoningLiu** [comment]
Hi Ashish, it's in the GA scope of Azurite. Should happen soon.

**Comment by XiaoningLiu** [comment]
2019-02-02 supported by 3.3.0-preview. Will close this issue.
