### ISSUE TITLE
SAS token is computed differently in azurite and azure-storage-blob(python sdk)

### ISSUE THREAD

**Issue by efiop** [Azure/Azurite#250]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.1.2-preview and 3.0.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
dockerhub and npm
### What's the Node.js version?
v8.10.0
### What problem was encountered?
403 Client Error: Forbidden for url. In debug logs I can see a more info:
[azurite.log](https://github.com/Azure/Azurite/files/3489464/azurite.log)
from which
```
debug: BlobSASAuthenticator:validate() Retrieved signature from URL parameter sig: sTkKbe5VNbkQYb24LjMjcM+xDRs78k3gJUoR1Jqbqis=
```
and
```
debug: BlobSASAuthenticator:validate() Calculated signature is: jmMm3MM4W5mNMS7ok3Tp0ESMDz/Hs9/s4+Hzi3LiEcQ=
```
led me to look if azure python sdk is generating the same token as azurite, and it turns out python sdk is using additional keys in `stringToSign` since version 1.5.0. `stringToSign` computed in azurite https://github.com/Azure/Azurite/blob/v3.1.2-preview/src/blob/authentication/IBlobSASSignatureValues.ts#L168 doesn't match the one in https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/sharedaccesssignature.py#L226 (e.g. see KEY_VERSION being added in python sdk). 
### Steps to reproduce the issue?
```
git clone https://github.com/iterative/dvc
cd dvc
git checkout 71ab380
pip install .[all,tests]
python -mtests 'tests/func/test_api.py::test_open[Azure]' -n0 --pdb
```
### Have you found a mitigation/solution?
Yes, using older azure-storage-blob==1.5.0 . Please see a better description up above.

Please correct me if I'm wrong, but I assume azure-storage-blob is reflecting the way SAS token is generated on Azure itself, so it looks like azurite needs to update the way it computes SAS token, right?

**Comment by XiaoningLiu** [comment]
Hi @efiop Yes. Azurite doesn't catch up with latest storage API Version features yet, including SAS generation. Please leverage legacy python SDK until Azurite updates.

**Comment by XiaoningLiu** [comment]
Please try with 3.3.0-preview. Will close this issue.

**Comment by efiop** [comment]
@XiaoningLiu Just tested it in https://github.com/iterative/dvc/pull/2785 Works like a charm! :fire:  Thank you so much! :pray:  Closing this issue.
