### ISSUE TITLE
Unable to launch azure function when starting azurite with HTTPS protocol

### ISSUE THREAD

**Issue by bingqiangxiang** [Azure/Azurite#2518]
**Which service(blob, file, queue, table) does this issue concern?**

Blob Storage

**Which version of the Azurite was used?**

3.32.0

**Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Extension)**

Visual Studio Extension

**What's the Visual Studio version?**

17.12.3

**What problem was encountered?**
I followed this doc [Use the Azurite emulator for local Azure Storage development](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=visual-studio%2Cblob-storage#oauth-configuration) to use the azurite as the storage emulator. But when I run the` .\azurite.exe --cert 127.0.0.1.pem --key 127.0.0.1-key.pem` command and launch the Azure function in Visual Studio. I got the following errors. 

![Image](https://github.com/user-attachments/assets/7ad8df43-a2a4-4a3c-828a-de17bae255d6)

How to resolve this issue?

**Comment by bingqiangxiang** [comment]
thanks @blueww , where can I get the Azurite debug log? Is the debug log recorded in any folder?

And I generated the certificate and saved it in the following folder. Does this satisfy the requirement?
![Image](https://github.com/user-attachments/assets/b9e4e2c2-b492-4a08-92b1-f5df26a9f844)

**Comment by blueww** [comment]
@bingqiangxiang 
As you have closed this issue, I believe you have found the root cause and resolved this issue.
Feel free to ping us again if you need any further assistance.

BTW, for Azurite debug log, you can find it by run Azurite with parameter like "-d c:\temp\debug.log"
