### ISSUE TITLE
CORS Errors?

### ISSUE THREAD

**Issue by sarink** [Azure/Azurite#254]
Is there a way to just completely disable CORS in development? That would be fine as well.

I was getting this error initially. Then I attempted to set a bunch of cors rules via `serviceURL.setServiceProperties` (from the `@azure/storage-blob` sdk), which appears to have succeeded, although it has had no effect on resolving the issue.

As you can see, I have set the cors rules appropriately
<img width="779" alt="Screen Shot 2019-08-28 at 9 06 13 PM" src="https://user-images.githubusercontent.com/1881761/63870711-1db48700-c9d8-11e9-8ee2-e57d82f6cf3c.png">

Yet when I attempt an upload from a browser
<img width="1497" alt="Screen Shot 2019-08-28 at 9 06 54 PM" src="https://user-images.githubusercontent.com/1881761/63870732-2ad17600-c9d8-11e9-9d6d-577f2f81507f.png">

Why?

**Comment by XiaoningLiu** [comment]
Hi @sarink V3 blob doesn't support prefligt requets right now. We will add this feature request into our backlog and triaging of next plan. We are currently busy with V3 Queue implementation  and next step will be with high priority newstorage features in V3 blob, such as unblocking the breaking change in SAS authentication. It may need more time before we get change for Preflight request supports for V3 blob. In the meantime, contribution are welcome!

**Comment by sarink** [comment]
I see.

For those interested, I solved this problem by setting up a proxy. In my case, I was using the webpack-dev-server, and did it like this: https://webpack.js.org/configuration/dev-server/#devserverproxy

**Comment by sarink** [comment]
I'll close this issue since it's known and on your roadmap.
