### ISSUE TITLE
list blobs does not return blobs in order

### ISSUE THREAD

**Issue by kahing** [Azure/Azurite#262]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

3.1.2-preview

### What problem was encountered?

azure blob is supposed to return blobs in alphabetical order, but azurite does not return blobs in that order. Because of this, it also does not support next marker and seems to never return a marker even if there are more than 5000 objects in result (the output is truncated to 5000 objects).

### Steps to reproduce the issue?

put 5001 objects, list

### Have you found a mitigation/solution?

no

**Comment by XiaoningLiu** [comment]
Thanks for reporting! V3 does support next marker, will investigate whether it's a bug. 

Does any Azure Storage doc has this description "azure blob is supposed to return blobs in alphabetical order"?

**Comment by timuralp** [comment]
Looks like there is an allusion to it [here](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs):
> Blobs are listed in alphabetical order in the response body, with upper-case letters listed first.

**Comment by XiaoningLiu** [comment]
Will update list order. Thanks!

**Comment by timuralp** [comment]
@XiaoningLiu I also noticed that containers are not listed in sorted order either. Should I open a separate issue for that?

Here is an example output I get using the Python SDK:
```
>>> [cont.name for cont in c.list_containers()]
[u'test-blob-\xc3\xaf', 'test', 'test2', 'a', 'z', 'e']
```

The behavior is documented [here](https://docs.microsoft.com/en-us/rest/api/storageservices/list-containers2):
> Containers are listed in alphabetical order in the response body.

**Comment by XiaoningLiu** [comment]
@timuralp Please open another issue for container order listing, thanks! Blob listing order will be updated in incoming release this week.
