### ISSUE TITLE
Support for Batch APIs in Table

### ISSUE THREAD

**Issue by preetriti1** [Azure/Azurite#264]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
legacy_V2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What problem was encountered?
We have a service in Azure which uses the current Azure Storage apis to do operations in Table and Blob. We are currently working on moving this to Linux containers and we need a storage emulator to work for linux machines (Ours is a dev box scenario).
We have lots of batch operations in table so we want to keep using the same service to point to Azure storage in cloud, emulator in dev box. When are the batch apis going to be implemented for tables?

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Hi preetriti1! Thanks for your feedback! However, supporting new features of Table service is not in our recent backlog. Cosmos DB team is working on an official cross-platform emualtor supporting both CosmosDB and Table API.

**Comment by bsoulier** [comment]
I see that this has been added to the 3.3 label then closed.
Microsoft is not doing anything on their side to provide a *nix based emulator (have a look [here](https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/17)).

I think providing batch operations would solve quite some issues for people trying to run their DOTNET core development using on Azure Table Storage locally
