### ISSUE TITLE
New Snapshot with Metadata (metadata is being ignored in the request)

### ISSUE THREAD

**Issue by apertusai** [Azure/Azurite#265]
### Which service(blob, file, queue, table) does this issue concern?
Blob (Block Blob) Snapshot

### Which version of the Azurite was used?
3.2.0 preview (i believe)

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
docker image mcr.microsoft.com/azure-storage/azurite

### What's the Node.js version?
12.11.0

### What problem was encountered?
Snapshot created without any change to the metadata

### Steps to reproduce the issue?
1) create a block blob with some metadata
2) use "@azure/storage-blob" BlockBlobURL.createSnapshot() API in node to create a new snapshot with metadata option (i.e. adding a different set of metadata)
3) End result - snapshot created successfully without any change to the metadata (expect: the newly created snapshot should contain a new set of metadata per Blob REST API spec. But the end result is the snapshot contains exactly the same metadata as the original block blob).

I also double-checked the HTTP request to the azurite process and it contains the correct HTTP metadata headers (see below, note the x-ms-meta-* are new metadata for the snapshot, which is not included in the snapshot created):

**Here is the JS code**
    console.log(
      await blockBlobURL.createSnapshot(aborter, {
        metadata: { test: "", haha: "my haha" }
      })
    );

**Request from my node client (note: the timestamp on this request is different from the response because run the code again to the proxy @ port 8080 to see the HTTP traffics from my node client)**

{ path: '/devstoreaccount1/sample/New.pdf',
  headers: 
   { 'x-ms-meta-test': '',
     'x-ms-meta-haha': 'my haha',
     'x-ms-version': '2019-02-02',
     'user-agent': 'Azure-Storage/10.5.0 (NODE-VERSION v12.11.0; Darwin 18.7.0)',
     'x-ms-client-request-id': '6b92adb2-4695-4690-9775-2a22c3401939',
     'x-ms-date': 'Fri, 04 Oct 2019 22:33:28 GMT',
     authorization: 'SharedKey devstoreaccount1:JcbjEiOsDy3ZIUxh4Oio4YKazqb/SmhGIQfW3oQHlkg=',
     cookie: '',
     accept: '*/*',
     'content-length': '0',
     'accept-encoding': 'gzip,deflate',
     connection: 'close',
     host: '127.0.0.1:8080' },
  method: 'PUT',
  body: '',
  cookies: undefined,
  fresh: false,
  hostname: '127.0.0.1',
  ip: '::ffff:172.17.0.1',
  ips: [],
  protocol: 'http',
  query: { comp: 'snapshot' },
  subdomains: [],
  xhr: false,
  os: { hostname: '28bc871b5300' } }
::ffff:172.17.0.1 - - [04/Oct/2019:22:33:28 +0000] "PUT /devstoreaccount1/sample/New.pdf?comp=snapshot HTTP/1.1" 200 884 "-" "Azure-Storage/10.5.0 (NODE-VERSION v12.11.0; Darwin 18.7.0)"

**Here is the response error from the server**

_edited: i copied the wrong output from the server. sorry_
{
  snapshot: '2019-10-04T22:29:19.796Z',
  eTag: '"d-PLQ46l/Q1+/+b9ZbOlcK4oND2TA"',
  lastModified: 2019-10-04T22:01:12.000Z,
  clientRequestId: undefined,
  requestId: '70eb4492-983f-4387-95ea-7f59c352d371',
  version: '2018-03-28',
  date: 2019-10-04T22:29:19.000Z,
  isServerEncrypted: undefined,
  encryptionKeySha256: undefined,
  errorCode: undefined,
  connection: 'close',
  'content-length': '0',
  server: 'Azurite-Blob/3.2.0-preview',
  body: undefined
}

### Have you found a mitigation/solution?
no

**Comment by XiaoningLiu** [comment]
Thanks @apertusai ! Will try to fix in next release.
