### ISSUE TITLE
Require Documentation Update for Legacy branch to indicate proper Docker usage

### ISSUE THREAD

**Issue by edwin-huber** [Azure/Azurite#266]
We need to update the ReadMe.md in the legacy-master branch to indicate the proper Docker usage.  
This is still pointing to **arafato/azurite** which is very outdated, and will cause issues.  

As we are unable to publish the legacy branch to the Microsoft Docker Container Registry, I would suggest that we provide instructions for users of Azurite to build their own image.  
This would both ensure that we do not again use a private repo to host the tool, and will ensure that they are always using at least the latest version of the legacy branch.

Thoughts? @XiaoningLiu @ms-vincent 

If we are in agreement, I shall make the change.

**Comment by XiaoningLiu** [comment]
Thanks @edwin-huber! Looks good.

**Comment by edwin-huber** [comment]
with latest release, legacy branch is no longer in focus
