### ISSUE TITLE
APINotImplemented error when creating blob through AppendBlobService azure python SDK

### ISSUE THREAD

**Issue by elembie** [Azure/Azurite#267]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
Azurite-Blob/3.2.0-preview

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
n/a - whatever is in the docker image

### What problem was encountered?
When attempting to create a blob using the AppendBlobService.create_blob method, I get a `APINotImplemented` error. From the log in the docker container, the request was;

`PUT /devstoreaccount1/1234/output_thing.csv HTTP/1.1 500`

Unsure if this is an error on my part - however I am using the python `azure` sdk to generate the requests, e.g.

```
self.blob_service.create_blob(
            destination['blob_container'],
            destination['file_name']
 )
```
where `self.blob_service` is an instance of `AppendBlobService` instantiated with a connection string containing the `Azurite` store details. I already have a container named `1234`.

I am using the same service to read a blob to stream and it seems to function properly, but errors when attempting to create a blob as described above.

### Steps to reproduce the issue?
Use Docker version and attempt same operation as described above.

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Hi, Append Blob is not supported by Azurite yet, that's why you got APINotImplemented error.

**Comment by elembie** [comment]
@XiaoningLiu thanks - apologies, I did have a read of the docs and this wasn't immediately obvious - thanks for clarifying :) I'll mark as closed.
