### ISSUE TITLE
Docker image does not bind to 0.0.0.0 when only running azurite-blob

### ISSUE THREAD

**Issue by sgerace** [Azure/Azurite#272]
### Which service(blob, file, queue, table) does this issue concern?

azurite-blob

### Which version of the Azurite was used?

Azurite v3.2.0-preview (docker image)

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What's the Node.js version?

N/A

### What problem was encountered?

When running the full Azurite server from Docker, I am simply able to run the following command:
```
docker run -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite
```
Which produce the following output:
```
Azurite Blob service is starting on 0.0.0.0:10000
Azurite Blob service successfully listens on 0.0.0.0:10000
Azurite Queue service is starting on 0.0.0.0:10001
Azurite Queue service successfully listens on 0.0.0.0:10001
```
Indicating that both the Azurite Blob service and Azurite Queue service are listening on 0.0.0.0 (which makes sense given that this is running in a Docker container).

However, if I try to run just the azurite-blob service with the following command that is listed in the Azurite README:
```
docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob
```
I get the following output:
```
Azurite Blob service is starting on 127.0.0.1:10000
Azurite Blob service successfully listens on 127.0.0.1:10000
```
Indicating that the Azurite Blob service is now listening on 127.0.0.1, which, because this is inside of a Docker container, rejects all connections from the host machine.

I had originally tried to run this using docker-compose, which resulted in a fair bit of confusion until I realized that the bind address had changed when running just the Azurite Blob service.

### Steps to reproduce the issue?

See above.

### Have you found a mitigation/solution?

Yes, I'm able to get this working by supplying the `blobHost` argument as follows:
```
docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost=0.0.0.0
```
It would be great if this was the default behavior when running within Docker (similar to the situation where you are running both the blob and queue service), however, if that isn't possible or easy, simply denoting this difference in behavior in the README would be very helpful.

**Comment by XiaoningLiu** [comment]
Thanks! When doesn't specific `azurite-blob` command to start the docker image, there is `--blobHost` defined in dockerfile. That's why it uses "0.0.0.0".

`azurite-blob` command basically cannot detect it's under docker container or not, it needs the parameter.

Will update the readme documentation.

**Comment by sgerace** [comment]
Sounds good, I figured it was probably something like that. Thanks for the info and reply.

**Comment by XiaoningLiu** [comment]
Updated description in readme, will close this issue, thanks!
