### ISSUE TITLE
Is this Project Dead?

### ISSUE THREAD

**Issue by SirensOfTitan** [Azure/Azurite#274]
Typically I hate to open such issues, but this repository is for use alongside a development environment that we all pay for: Azure storage.

There seems to be a lot of feature incompleteness here: I couldn't get SAS signatures to work, one cannot use or disable CORS (and I'd imagine it's pretty commonplace to run Azurite inside docker-compose on a different port, i.e. on a different CORS domain).

Additionally, this repository hasn't been active in months.  The other Azure storage emulator for use locally is windows only, leaving linux servers out in the cold presumably.  

Is development occurring internally or is this repository dead?

**Comment by SirensOfTitan** [comment]
Particularly talking about #250, which has been open for months, and is a pretty significant issue, and #254, which was closed but it's still a very real issue.

**Comment by XiaoningLiu** [comment]
Hi @SirensOfTitan We have a release planned this week. Release will update API version to 2019-02-02 which supports new SAS format mentioned in #250. CORS for queue is already there, CORS for blob is in our radar. Sorry for the inconvenience, and thanks for your patience.

**Comment by XiaoningLiu** [comment]
3.3.0-preview has been released to npm, docker and Visual Studio Code. Will close this issue, thanks for your support!
