### ISSUE TITLE
list_containers does not sort the results

### ISSUE THREAD

**Issue by timuralp** [Azure/Azurite#275]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Dockerhub

### What's the Node.js version?
10.15.3

### What problem was encountered?
list_blobs returns the response not sorted in order:
Here is an example output I get using the Python SDK:
```
>>> [cont.name for cont in c.list_containers()]
[u'test-blob-\xc3\xaf', 'test', 'test2', 'a', 'z', 'e']
```

The behavior is documented [here](https://docs.microsoft.com/en-us/rest/api/storageservices/list-containers2): Containers are listed in alphabetical order in the response body.

### Steps to reproduce the issue?
Create containers not in alphabetical order, e.g. container "foo" then container "bar", then list containers.

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Hi @timuralp Thanks! Will update for a fix.

**Comment by sangeetha5491** [comment]
Can i work on this?

**Comment by XiaoningLiu** [comment]
@sangeetha5491 Yes! As list blobs already have order, you can do this for containers to. Notice that, we have 2 metadata store implemntation, one based on loki and another for SQL. Please update them at the same time.

**Comment by sangeetha5491** [comment]
thanks! Im working on it

**Comment by sangeetha5491** [comment]
@XiaoningLiu https://github.com/Azure/Azurite/pull/280

**Comment by XiaoningLiu** [comment]
@sangeetha5491 Thanks! Few comments added.

**Comment by edwin-huber** [comment]
Fix was merged, closing issue.
