### ISSUE TITLE
Issue with uploading empty file

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/Azurite#277]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

3.3.0-preview

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

all

### What problem was encountered?

Uploading empty file will fail;
Commit empty block list will fail.

**Comment by sangeetha5491** [comment]
@XiaoningLiu  can I work on this?

**Comment by XiaoningLiu** [comment]
@sangeetha5491 Sure.

There are 2 issues cross 2 APIs. #1 Upload empty file/blob #2 Commit empty block list

**Comment by XiaoningLiu** [comment]
@sangeetha5491 I sent a PR for fix due to limited time schedule. Welcome to take a look~

**Comment by sangeetha5491** [comment]
@XiaoningLiu sure. I had a very busy last few weeks which is why I was not able to work on it immediately. Sorry about that. I'll take a look at other open issues when I get time.

**Comment by blueww** [comment]
Fixed
