### ISSUE TITLE
Microsoft.Azure.Cosmos.Table.StorageException: 'Not Implemented' | CreateIfNotExistsAsync

### ISSUE THREAD

**Issue by spottedmahn** [Azure/Azurite#278]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
2.7.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
8.11.2

### What problem was encountered?
>Microsoft.Azure.Cosmos.Table.StorageException: 'Not Implemented'

### Steps to reproduce the issue?
```c#
using Microsoft.Azure.Cosmos.Table;
var table = tableClient.GetTableReference("blah");
await table.CreateIfNotExistsAsync();
```

**Comment by XiaoningLiu** [comment]
Hi @edwin-huber Any comments here?

**Comment by edwin-huber** [comment]
Using Package Microsoft.Azure.Cosmos.Table from Nuget, v1.0.8
and following snippet, this is no longer an issue with the new release and table api support.
```csharp
            var tableClient = new CloudTableClient(new Uri("http://127.0.0.1:10002/devstoreaccount1/"), new StorageCredentials(storageAccount, accountKey));
            var table = tableClient.GetTableReference("blah");
            try
            {
                table.CreateIfNotExistsAsync().Wait();
            }
            catch (Exception e)
            {
                throw e;
            }
```

**Comment by spottedmahn** [comment]
🎉, thanks @edwin-huber

**Comment by bhuvaness** [comment]
Thanks, @edwin-huber. It is working

**Comment by TarekSalha** [comment]
I've got one more question: The above apporach works, but requires code changes, when moving to prod. Is there any possibility to test without changing the code later?

**Comment by edwin-huber** [comment]
Hi @TarekSalha 
I'm not sure I can answer you without being sure of the issue you face.  
Could you perhaps elaborate?

**Comment by TarekSalha** [comment]
Ok, I see, my question was not clearly formulated:
What needs to be set as URI, if I want to use a real table storage and not azurite emulator?
