### ISSUE TITLE
Incorrect listing after a blob with non-ASCII characters is uploaded

### ISSUE THREAD

**Issue by timuralp** [Azure/Azurite#282]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.2.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
10.15.3

### What problem was encountered?
After uploading a blob named `unicodé`, the listing returns a blob named `unicodÃ©` (which would be the same as `unicodé` if the underlying byte string for the original object (`unicod\xc3\xa9`) is itself treated as the unicode string. It seems like the object name should be decoded before being used in the XML response.

### Steps to reproduce the issue?
Here is a small(ish) Python script demonstrating the problem (use with azure-sdk-python >= 12.0.0):
```
import azure.core.exceptions
import azure.storage.blob
import logging


# change to your emulator endpoint
EMULATOR_ENDPOINT = 'http://localhost:10081'
CONTAINER = 'non-ascii-test'
BLOB = u'unicod\u00e9'

# Sets up wire logs to see the requests/responses
logger = logging.getLogger('azure.storage.blob')
logger.setLevel('INFO')  # change to DEBUG for wire logs
logger.addHandler(logging.StreamHandler())

# Upload a block blob with a non-ASCII character
blob_service = azure.storage.blob.BlobServiceClient.from_connection_string(
    'AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1O'
    'UzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;'
    'DefaultEndpointsProtocol=http;'
    'BlobEndpoint={}/devstoreaccount1'.format(EMULATOR_ENDPOINT),
    logging_enable=True)
cont = blob_service.get_container_client(CONTAINER)
try:
    cont.create_container()
except azure.core.exceptions.ResourceExistsError:
    pass
blob = cont.get_blob_client(BLOB.encode('utf-8'))
blob.stage_block(1, 'content')
blob.commit_block_list([azure.storage.blob.BlobBlock(
    1, azure.storage.blob.BlockState.Uncommitted)])
listing_name = next(cont.list_blobs()).name
print(u'LISTING: {}; UPLOADED: {}'.format(listing_name, BLOB))
assert listing_name == BLOB
```
The above test passes successfully against Microsoft Azure service (replace the credentials with valid Azure ones and remove the `BlobEndpont` and `DefaultEndpointsProtocol` lines to verify.

### Have you found a mitigation/solution?
Yes, but it's quite cumbersome (at least in Python):
```
>>> s = u'unicod\xc3\xa9'
>>> bytes([ord(char) for char in s]).decode('utf-8')
'unicodé'
```
Above blurb converts the string into a byte array and then decodes it using UTF-8 encoding to get back the original name. It would be great if the emulator would return the correct response (like Microsoft Azure Blob does).

**Comment by blueww** [comment]
@timuralp 
Thanks for reporting the issue!
We will consider to fix it in a future release.

**Comment by XiaoningLiu** [comment]
Hi @timuralp I added a case covering this scenario, but cannot reproduce. As I'm not Python expert, please comment from your point of view. If possible, please share your Azurite debug.log.

In the case, will try to create a blob with `é` inside, and then list blob and compare blob name.

Here is the request url to create blob. `é` is uri encoded to `%C3%A9` in the url.

```
http://127.0.0.1/devstoreaccount1/1container-with-dash157657024699703761/unicod%C3%A9157657024715802570
```

And here is the response XML body. `unicodé157657024715802570` is successfully returned.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<EnumerationResults ServiceEndpoint="http://127.0.0.1:11000/devstoreaccount1" ContainerName="1container-with-dash157657024699703761">
	<Prefix>
		unicodé157657024715802570
	</Prefix>
	<Marker />
	<MaxResults>
		5000
	</MaxResults>
	<Delimiter>
		$
	</Delimiter>
	<Blobs>
		<Blob>
			<Name>
				unicodé157657024715802570
			</Name>
			<Snapshot />
			<Properties>
				<Creation-Time>
					Tue, 17 Dec 2019 08:10:47 GMT
				</Creation-Time>
				<Last-Modified>
					Tue, 17 Dec 2019 08:10:47 GMT
				</Last-Modified>
				<Etag>
					"d-BLEI1cg2wK2fvlyl3jSAG8QCooo"
				</Etag>
				<Content-Length>
					1
				</Content-Length>
				<Content-Type>
					application/octet-stream
				</Content-Type>
				<Content-MD5>
					f8VicOenD6gaWTW3Lqy+KQ==
				</Content-MD5>
				<BlobType>
					BlockBlob
				</BlobType>
				<LeaseStatus>
					unlocked
				</LeaseStatus>
				<LeaseState>
					available
				</LeaseState>
				<ServerEncrypted>
					true
				</ServerEncrypted>
				<AccessTier>
					Hot
				</AccessTier>
				<AccessTierInferred>
					true
				</AccessTierInferred>
				<AccessTierChangeTime>
					Tue, 17 Dec 2019 08:10:47 GMT
				</AccessTierChangeTime>
			</Properties>
			<Metadata />
		</Blob>
	</Blobs>
	<NextMarker />
</EnumerationResults>

```

**Comment by timuralp** [comment]
@XiaoningLiu Thank you for adding the test and looking into it. This looks like a deficiency in the python libraries. I tracked these down to the following differences:
The response from Microsoft Azure is prepended with a unicode zero-width no-break space character U+FEFF (https://www.fileformat.info/info/unicode/char/feff/index.htm).

Here is what the response from Microsoft Azure Blob looks like:
```
'\xef\xbb\xbf<?xml version="1.0" encoding="utf-8"?><EnumerationResults ServiceEndpoint="https://onespace.blob.core.windows.net/" ContainerName="non-ascii-test"><Blobs><Blob><Name>unicod\xc3\xa9</Name><Properties><Creation-Time>Thu, 21 Nov 2019 21:49:31 GMT</Creation-Time><Last-Modified>Wed, 18 Dec 2019 01:11:17 GMT</Last-Modified><Etag>0x8D783572F558EA9</Etag><Content-Length>7</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-CRC64 /><Content-MD5 /><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier><AccessTierInferred>true</AccessTierInferred><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>'
```

The Azurite emulator response does not include this character. This should be fine for most clients, however, it is an issue in the Azure SDK for Python client. In Python the `chardet` library ends up being used to decode the response (since no encoding is passed) and without the leading U+FEFF character it considers the response as ISO-8859-1. At that point we end up with the results that I posted above.

I think this an issue with the python library and will pursue the issue there. They should pass the UTF-8 encoding when processing the response body.

For the record, this is what the Azurite response looks like:
```
'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><EnumerationResults ServiceEndpoint="http://localhost:10081/devstoreaccount1" ContainerName="non-ascii-test"><Prefix/><Marker/><MaxResults>5000</MaxResults><Delimiter/><Blobs><Blob><Name>unicod\xc3\xa9</Name><Snapshot/><Properties><Creation-Time>Tue, 17 Dec 2019 23:56:41 GMT</Creation-Time><Last-Modified>Tue, 17 Dec 2019 23:56:41 GMT</Last-Modified><Etag>"d-56tc90uNFJ7nLwOycwUlxF3ABk8"</Etag><Content-Length>7</Content-Length><Content-Type>application/xml; charset=utf-8</Content-Type><BlobType>BlockBlob</BlobType><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><AccessTier>Hot</AccessTier><AccessTierInferred>true</AccessTierInferred></Properties><Metadata/></Blob></Blobs><NextMarker/></EnumerationResults>'
```

Apologies for the mistaken report! I should have tracked down the exact issue beforehand. I don't think Azurite should prepend U+FEFF in its responses, as that is not documented anywhere as far as I can tell.

**Comment by xiafu-msft** [comment]
Hi @Imazuel I'm still confused about the issue, I will send you the snapshot on teams ^_^
