### ISSUE TITLE
Azure Blob default content-type should be application/octet-stream

### ISSUE THREAD

**Issue by timuralp** [Azure/Azurite#283]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.2.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
dockerhub

### What's the Node.js version?
10.15.3

### What problem was encountered?
After uploading a blob, the content-type is returned as `application/xml; charset=utf-8`, however, the Azure Blob default in this case is `application/octet-stream` (https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties).

### Steps to reproduce the issue?
1. Upload a blob with no `x-ms-blob-content-type` set
2. Call GetBlobProperties and examine the Content-Type

### Have you found a mitigation/solution?
No. The only workaround is to always explicitly set `x-ms-blob-content-type` to `application/octet-stream`.

**Comment by blueww** [comment]
@timuralp
Thanks for reporting the issue!
We will consider to fix it in a future release.

**Comment by blueww** [comment]
@timuralp 
We can't repro this issue on 3.3.0-preview.
We have tried to upload a small Block Blob(<4MB), a big Block blob(>500MB), and a page blob. all works well, and has default content type is `application/octet-stream`

And in code, you can see the default content type is also right: https://github.com/Azure/Azurite/blob/df5bf1dd57162f7722cc861124c9d7c6c9b71352/src/blob/handlers/BlockBlobHandler.ts#L37

In [Rest API](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob), there are 2 header can set Content-Type: `x-ms-blob-content-type` , `Content-Type`. Please check you have not set any of them. The created Blob only in default contenttype when you don't set any of the 2 hearders.

**Comment by timuralp** [comment]
@blueww I tried to reproduce again and wasn't successful. I went through a few versions of Azurite and checked the commit history -- I'm not sure how I encountered this error. Thanks for checking it and apologies for the invalid report!
