### ISSUE TITLE
XHR request cors issues

### ISSUE THREAD

**Issue by stefanolsenn** [Azure/Azurite#285]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
mcr.microsoft.com/azure-storage/azurite
### What's the Node.js version?
-
### What problem was encountered?
AuthorizationFailure
### Steps to reproduce the issue?
- Run the container
- Make a XHR request against it
### Have you found a mitigation/solution?
no

Hi.. I'm getting CORS issues when trying to do a XHR request from the browser trying to get it.
Connectionstring used:
`"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;TableEndpoint=http://storage:10002/devstoreaccount1;QueueEndpoint=http://storage:10001/devstoreaccount1"`

It works perfectly with uploading to the endpoint.
I've tried with a PUT request with payload:
`<Cors>
    <CorsRule>  
        <AllowedOrigins>*</AllowedOrigins>  
        <AllowedMethods>PUT,GET</AllowedMethods>  
        <AllowedHeaders>x-ms-meta-data*,x-ms-meta-target*,x-ms-meta-abc</AllowedHeaders>  
        <ExposedHeaders>x-ms-meta-*</ExposedHeaders>  
        <MaxAgeInSeconds>200</MaxAgeInSeconds>  
    </CorsRule>  
<Cors>  `
But I'm getting this error.
`<Error>
  <Code>AuthorizationFailure</Code>
  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
RequestId:8900ff37-e5b5-4dee-a0d1-187057ad4fe5
Time:2019-11-26T11:16:07.559Z</Message>
</Error>`
How to properly do authentication so set the allowed origins?

**Comment by XiaoningLiu** [comment]
Hi @stefanolsenn Azurite 3.3.0-preview supports CORS access from browsers for queue. Blob doesn't support CORS access from browser yet. It's expected you get some CORS related errors reported by your browser. We have already track this feature request as a p2 feature for future releases.

Out of curious, the error type you got is not expected. Can you share the debug log by Azurite? We can see what makes AuthorizationFailure.

**Comment by peter-bannerflow** [comment]
@XiaoningLiu about CORS on blob storage, do you have any estimate on when that will be available? Is it planned for any upcoming release?

**Comment by XiaoningLiu** [comment]
@peter-bannerflow blob cors supported added into dev branch and will be release soon
