### ISSUE TITLE
Add support for Blob Batch operations

### ISSUE THREAD

**Issue by garayx** [Azure/Azurite#287]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What problem was encountered?
500 Internal Server Error
### Steps to reproduce the issue?
Run following test (use emulator connection string): 
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample03a_Batching.cs#L26
### docs page: 
https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch

**Comment by XiaoningLiu** [comment]
Thanks @garayx! We will track blob batch into Azurite backlog and make plan in the future releases.

**Comment by SeanFeldman** [comment]
@XiaoningLiu, is this something that is planned? It's been a year and 3.9.0 still doesn't have support batched operations.

**Comment by XiaoningLiu** [comment]
Sorry forry that, Batch is not planned in near furture. Recently, we are ocurripted with Azurite Table support. I'll bring up the ask to internal team and do another triage in planning meetings.

**Comment by SeanFeldman** [comment]
Azurite Tables support is important, 100%.
This API is a challenge to test as the old emulator doesn't support either. Hence my ping. For now, I've worked around the test to execute conditionally and skip storage accounts that are emulated. Would be nice to run all the tests w/o skipping any though.

**Comment by netspark** [comment]
Totally agree, it is hard to test the whole flow without it!
Please help us in testing our code properly!

**Comment by cristiangiagante** [comment]
Seems to be like the repro steps section is outdated, Batching example is not anymore available. Nice way to avoid people to request the feature lol

**Comment by underthevalley** [comment]
This is much needed, please help us out!

**Comment by Dirler** [comment]
Will be useful for some critical test cases...

**Comment by AlexBar** [comment]
Please add this feature

**Comment by blueww** [comment]
A new issue for blob batch support: https://github.com/Azure/Azurite/issues/967

**Comment by fatih-celonis** [comment]
Azurite is critical for us to write integration tests. This missing feature is quite important to us. Is there any progress on it? it's been 2.5 years since the issue was opened.

**Comment by blueww** [comment]
@fatih-celonis 
Thanks for your responds!

We hear your voice.
We will try to plan blob batch soon.

**Comment by rodolforeinaperficient** [comment]
Please add this feature

**Comment by blueww** [comment]
@rodolforeinaperficient 
The blob batch PR is already merged.
We will have a release for it soon.

**Comment by blueww** [comment]
Blob Batch is already supported in Azurite 3.20.1.
