### ISSUE TITLE
Azurite should not allow block IDs longer than 64 characters

### ISSUE THREAD

**Issue by timuralp** [Azure/Azurite#289]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.2
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

Azurite should fail requests to create a new block with an ID longer than 64 bytes to match the Azure Blob documented restriction: https://docs.microsoft.com/en-us/rest/api/storageservices/put-block
> A valid Base64 string value that identifies the block. Prior to encoding, the string must be less than or equal to 64 bytes in size. For a given blob, the length of the value specified for the blockid parameter must be the same size for each block.

**Comment by XiaoningLiu** [comment]
Thanks @timuralp for reporting! Will check in following releases, in the meantime, welcome contribution!

**Comment by XiaoningLiu** [comment]
All block IDs should have same length.

**Comment by blueww** [comment]
Fixed
