### ISSUE TITLE
[blob-storage]BlobClient.getProperties not returning archiveStatus

### ISSUE THREAD

**Issue by ljian3377** [Azure/Azurite#292]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v12.13.0
### What problem was encountered?
Unit test failure:
`BlobClient.beginCopyFromURL with rehydrate priority`

```
  it.only("beginCopyFromURL with rehydrate priority", async () => {
    recorder.skip("browser");
    const newBlobURL = containerClient.getBlobClient(recorder.getUniqueName("copiedblobrehydrate"));
    const initialTier = BlockBlobTier.Archive;
    const result = await (await newBlobURL.beginCopyFromURL(blobClient.url, {
      tier: initialTier,
      rehydratePriority: "Standard"
    })).pollUntilDone();
    assert.ok(result.copyId);
    delay(1 * 1000);

    const properties1 = await blobClient.getProperties();
    const properties2 = await newBlobURL.getProperties();
    assert.deepStrictEqual(properties1.contentMD5, properties2.contentMD5);
    assert.deepStrictEqual(properties2.copyId, result.copyId);
    assert.deepStrictEqual(properties2.copySource, blobClient.url);
    assert.equal(properties2.accessTier, initialTier);

    await newBlobURL.setAccessTier(BlockBlobTier.Hot);
    const properties3 = await newBlobURL.getProperties();
    assert.equal(properties3.archiveStatus!.toLowerCase(), "rehydrate-pending-to-hot");
  });
```
`assert.equal(properties3.archiveStatus!.toLowerCase(), "rehydrate-pending-to-hot")` throw error because properties3.archiveStatus is undefined.

```
  /**
   * For blob storage LRS accounts, valid values are
   * rehydrate-pending-to-hot/rehydrate-pending-to-cool. If the blob is being rehydrated and is not
   * complete then this header is returned indicating that rehydrate is pending and also tells the
   * destination tier.
   */
  archiveStatus?: string;
```

Do we support LRS accounts?

### Steps to reproduce the issue?
Re-run the test-case.

### Have you found a mitigation/solution?
N/A

### debug.log
[debug.log](https://github.com/Azure/Azurite/files/3955464/debug.log)
### request_id
`b1b8441a-d563-496d-ba8a-a40650d74307`

**Comment by XiaoningLiu** [comment]
Should add "archiveStatus" for get properties options.

**Comment by blueww** [comment]
Per [rest doc](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties), valid values are rehydrate-pending-to-hot/rehydrate-pending-to-cool. Since Azurite don't have this pedning status won't fix it.

**Comment by blueww** [comment]
@XiaoningLiu 
Would you please help to close it?
