### ISSUE TITLE
Can’t set Cors to Blob Service properties without “ExposedHeaders”

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#294]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
Can’t set Cors to Blob Service properties without “ExposedHeaders” (product server allows):

> 2019-12-12T04:06:36.987Z 9853e2b2-c9f6-489a-9193-fecaed3f2834 error: ErrorMiddleware: ErrorName=DeserializationError ErrorMessage=StorageServiceProperties.Cors.ExposedHeaders cannot be null or undefined.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="Error: StorageServiceProperties.Cors.ExposedHeaders cannot be null or undefined.
> at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:105:13)\n    
> at serializeCompositeType (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:502:44)\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:134:19)\n    at serializeSequenceType (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:408:31)\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:130:19)\n    at serializeCompositeType (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:502:44)\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:134:19)\n    at Object.deserialize (C:\\code\\azurite\\src\\blob\\generated\\utils\\serializer.ts:171:21)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
> 2019-12-12T04:06:36.987Z 9853e2b2-c9f6-489a-9193-fecaed3f2834 error: ErrorMiddleware: Set HTTP code: 400
> 

### Steps to reproduce the issue?
Set cors rule without ExposedHeaders
### Have you found a mitigation/solution?
no

**Comment by blueww** [comment]
@XiaoningLiu 
As we discussed , you will take this.

**Comment by XiaoningLiu** [comment]
@blueww Fixed in https://github.com/Azure/Azurite/pull/299
