### ISSUE TITLE
[blob] should return 'APINotImplemented' for API that's not implemented 

### ISSUE THREAD

**Issue by ljian3377** [Azure/Azurite#300]
These APIs are not supported but do not return  `APINotImplemented`.
- BlobClient
   - undelete
   - syncCopyFromURL
- PageBlobClient
  - uploadPagesFromURL

**Comment by XiaoningLiu** [comment]
Some of these features reuses existing APIs which will not return not implemented error. Should triage if there others.

**Comment by XiaoningLiu** [comment]
Fixed. Also added strict mode to block unsupported headers.
