### ISSUE TITLE
Azurite Blob Service starts failed with error: EACCES: permission denied, mkdir '__blobstorage__' E

### ISSUE THREAD

**Issue by Whadup** [Azure/Azurite#302]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
most recent visual studio code extension
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio Code Extension on osx. (v.3.3.0)
Version 3.2.0 still works.
### What's the Node.js version?
node --version says v8.9.3
### What problem was encountered?
When I try to start the Blob Service, it immediately fails with `Azurite Blob Service starts failed with error: EACCES: permission denied, mkdir '__blobstorage__' Error: EACCES: permission denied, mkdir '__blobstorage__'`. Manually trying to create said directory does not fail, but also does not solve the issue. Queue service runs without problems.

### Steps to reproduce the issue?
Open Visual Studio Code -> Install Extension -> Start Blob Service

**Comment by XiaoningLiu** [comment]
Hi @Whadup It sounds very weird per your description queue works while blob fails with permission issue. I cannot reproduce in my Mac, or I need to try again.

In the mean time, you can try to customize another workspace for Azurite in Visual Studio Code extension settings to see if it works.

![image](https://user-images.githubusercontent.com/6889160/70874872-092fe500-1fef-11ea-8b79-9f6384146e71.png)

**Comment by yoadsn** [comment]
Setting the Location specifically to some folder under the user home directory does not change the outcome.
The queue succeeds and the blob fails with the weird EROFS problem.

**Comment by XiaoningLiu** [comment]
@yoadsn Confirmed it's a bug. Added a fix.
