### ISSUE TITLE
commitBlockList: run it on not exist blob, with empty block list, server will create a new empty blob, Azurite will report “The specified blob does not exist.”

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#304]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
commitBlockList: run it on not exist blob, with empty block list, server will create a new empty blob, Azurite will report “The specified blob does not exist.”
### Steps to reproduce the issue?
create a blob client object from container object (Blob not created)
commitBlockList an empty list with the blob object.
### Have you found a mitigation/solution?
No

Rest Doc:
Rest Doc not mention the behavior

Test Case: 

> Test Name:	ParallelDownloadToEmptyFileTest
> Test FullName:	Microsoft.Azure.Storage.Blob.BlobDownloadToFileParallelTests.ParallelDownloadToEmptyFileTest
> Test Source:	C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\BlobDownloadToFileParallelTests.cs : line 372
> Test Outcome:	Failed
> Test Duration:	0:00:33.2128724
> 
> Result StackTrace:	
> at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 274
>    at Microsoft.Azure.Storage.Blob.BlobWriteStream.CommitAsync() in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 396
>    at Microsoft.Azure.Storage.Blob.CloudBlockBlob.UploadFromStreamAsyncHelper(Stream source, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, AggregatingProgressIncrementer progressIncrementer, CancellationToken cancellationToken) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 868
>    at Microsoft.Azure.Storage.Blob.CloudBlockBlob.UploadFromFileAsync(String path, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, AggregatingProgressIncrementer progressIncrementer, CancellationToken cancellationToken) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 1087
>    at Microsoft.Azure.Storage.Blob.BlobDownloadToFileParallelTests.ParallelDownloadToEmptyFileTest() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\BlobDownloadToFileParallelTests.cs:line 389
> Result Message:	
> Test method Microsoft.Azure.Storage.Blob.BlobDownloadToFileParallelTests.ParallelDownloadToEmptyFileTest threw exception: 
> Microsoft.Azure.Storage.StorageException: The specified blob does not exist.
> 
> 
[debug.log](https://github.com/Azure/Azurite/files/3967081/debug.log)
Request ID: 8d638823-2bcb-46dc-8cf6-37a3ba905ddd

**Comment by XiaoningLiu** [comment]
Fix has been merged into dev branch.
