### ISSUE TITLE
Container_ListBlob*/GetProperties: on Container with “Blob” “OFF” Public Access, Azurite return 403, server returns 401 

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#305]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
The request return code is not aligned with server:

Azurite return 403, 
server returns 401 

> HTTP/1.1 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.

(Anyway, XSCL test expected return code 404)
### Steps to reproduce the issue?
Set Container with “Blob” “OFF” Public Access
Run ListBlob*/GetProperties on the container

### Have you found a mitigation/solution?
No

Rest Doc:
This is not mentioned in rest doc

Test Case: 

> Test Name:	CloudBlobContainerCreateWithBlobAccessType
> Test FullName:	Microsoft.Azure.Storage.Blob.CloudBlobContainerTest.CloudBlobContainerCreateWithBlobAccessType
> Test Source:	C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\CloudBlobContainerTest.cs : line 1693
> Test Outcome:	Failed
> Test Duration:	0:00:00.30207
> 
> Result StackTrace:	
> at Microsoft.Azure.Storage.TestHelper.ExpectedException(Action operation, String operationDescription, HttpStatusCode expectedStatusCode, String requestErrorCode) in C:\code\azure-storage-net\Test\ClassLibraryCommon\TestHelper.cs:line 46
>    at Microsoft.Azure.Storage.Blob.CloudBlobContainerTest.TestAccess(BlobContainerPublicAccessType accessType, CloudBlobContainer container, CloudBlob inputBlob) in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\CloudBlobContainerTest.cs:line 53
>    at Microsoft.Azure.Storage.Blob.CloudBlobContainerTest.CloudBlobContainerCreateWithBlobAccessType() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\CloudBlobContainerTest.cs:line 1705
> Result Message:	Assert.AreEqual failed. Expected:<404>. Actual:<403>. Http status code is unexpected.

**Comment by XiaoningLiu** [comment]
401 will be returned when bearer challenge enabled.
managed fe will return 404 without bearer challenge.
native fe will return 403.

Azurite cannot align with all scenarios and currently uses 403
