### ISSUE TITLE
Triage & Fix issues reported by CPP SDK

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/Azurite#337]
- [X] 1. When breaking a lease with a peroid, the lease is directly broken ignorant the period. 
@blueww has fixed this.

- [x] 2. Blob's Etag isn't updated after metadata is changed.
@blueww will fix in https://github.com/Azure/Azurite/issues/330

- [X] 3. Cannot put empty block list to craete an empty blob.
Fixed in https://github.com/Azure/Azurite/commit/6af3cc17dc194d3dc39147f73f1fc52f635ec782

- [x] 4. Content-Range in response header is missing
Fixed in https://github.com/Azure/Azurite/pull/350

- [x] 5. If-Match header doesn't work when creating(not overwriting) a new page blob. Actual server returns 412(The condition specified using HTTP conditional header(s) is not met), while Azurite returns 201(Created).
Azurite doesn't support conditional headers. After discussion, Azurite will block unsupported headers with 500 FeatureNotSupported error.

- [X] 6. SAS token cannot be parsed, returns 400(Value for one of the query parameters specified in the request URI is invalid).
GET /?comp=list&prefix=prefix&api-version=2019-02-02&se=2019-12-13T06%3A46%3A30Z&sig=UkGksQxbF%2FPTTcbxX6yVE1f96IjhhKx3YLiF1Yw%2BXU8%3D&sip=0.0.0.0-255.255.255.255&sp=racwudpl&spr=https%2Chttp&srt=sco&ss=bqtf&sv=2019-02-02 HTTP/1.1
Invalid path which should start with devstorageaccount1

- [x] 7. Allowed IP address in SAS token is ignored.
Azurite doesn't support IP region block for local network access.

- [X] 8. Result of list containers is not sorted.
Latest dev branch commit has sorted listed containers.

- [x] 9. SharedKeyLite is not supported.
By design, not support SharedKeyLite.

- [x] 10. x-ms-access-tier is not supported.
Azurite doesn't support premium page blob tiers. Will block them.

- [x] 11. Cannot download page blob that is not 512-byte aligned.
9f200791-540a-4d2b-8126-cbf362b7126f
Fixed in https://github.com/Azure/Azurite/pull/350

- [x] 12. rscc and stuff like this in SAS token aren't supported.
By design, Azurite doesn't support them. Will block them in strict mode.

- [X] 13. Deleting root blob with snapshots is supposed to fail. But not on Azurite.
Fixed.

- [x] 14. x-ms-source-if-match is ignored.
By design. Not support.

- [x] 15. "If-None-Match: *" should return error.
Azurite doesn't support conditional headers. After discussion, Azurite will block unsupported headers with 500 FeatureNotSupported error.

- [x] 16. x-ms-access-tier together with x-ms-copy-source is not supported.
Doesn't suppport set tier when copy page blob, where page blob tier is only avaiable in premium storage account. Azurite only supports standard storage account.

**Comment by hansmbakker** [comment]
@XiaoningLiu
> 15. "If-None-Match: *" should return error.
> After discussion, Azurite will block unsupported headers with 500 FeatureNotSupported error.

Can you link to the discussion about this? This is a functionality from Blob Storage that Azure Storage supports (see the [swagger file](https://github.com/Azure/Azurite/blob/6d444ef1ab6f2933d63ca5fffa07de3abffa8f12/swagger/blob-storage-2019-02-02.json)) and that is used by Microsoft NuGet packages (e.g. [`Microsoft.AspNetCore.DataProtection.AzureStorage`](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.AzureStorage/2.2.7) requires it).

Having to use the `--loose` parameter to make it work makes it feel as if we are using some deprecated/obsolete functionality while this conditional header functionality is builtin functionality in Azure Storage that is not going away I believe?

**Comment by Kant8** [comment]
New .NET Azure API throws exception on executing BlobClient.UploadAsync mentioning If-None-Match is not supported.
Event example from https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet doesn't work without loose mode.

**Comment by XiaoningLiu** [comment]
Hi @hansmbakker @Kant8 Thanks for bring up this discussion.

Conditional header support (such as if-match) is tracked as candidate work items for Azurite, but not supported by Azurite 3.4.0 yet. We have it in backlog. Every release we will triage backlog items and features Azurite will support.

Completely matching all Azure Storage features needs great efforts, with limited resources, we choose to support features with higher prioirty first and add more support for other features. Conditional header is one of them. To avoid potential misunderstanding for not supported features. We introduce strict mode and loose mode.

In strict mode (by default), Azurite will block requests with unsupported headers. In loose mode, Azurite will IGNORE these headers.

As long as Azurite supports more and more features in the future, we will see less and less FeatureNotSupported.

For most of the scenario, ignoring conditional header for read requests is harmless. While it depends for write requests.

**Comment by epicfaace** [comment]
> For most of the scenario, ignoring conditional header for read requests is harmless. While it depends for write requests. We can discuss for specific scenarios.

Hi @XiaoningLiu -- this isn't the case for my application, in which I redirect the user to an Azurite URL directly in their browser. It's important to set the right headers such as Content-Type, Content-Disposition, etc. on the fly so that users can properly view files such as images or text files inline. I know this is still in your backlog but just wanted to make sure you're aware of my use case!

**Comment by epicfaace** [comment]
https://github.com/Azure/Azurite/issues/997
