### ISSUE TITLE
[queue] getQueueClient QueueNotFound error detail doesn't align

### ISSUE THREAD

**Issue by ljian3377** [Azure/Azurite#339]
### Which service(blob, file, queue, table) does this issue concern?
queue
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v12.13.0
### What problem was encountered?
Unit test failure:
```
  QueueServiceClient
    × can create and delete a queue
      HeadlessChrome 79.0.3945 (Windows 10.0.0)
    AssertionError: Error does not contain details property
```

```
    // deletes the queue
    await queueServiceClient.deleteQueue(queueName);

    let err;
    try {
      await queueServiceClient.getQueueClient(queueName).getProperties();
    } catch (error) {
      err = error;
    }
    assert.equal(err.details.errorCode, "QueueNotFound", "Error does not contain details property");
    assert.ok(err.message.includes("QueueNotFound"), "Error doesn't say `QueueNotFound`");
  });
``` 

### Debug
Azurite puts `QueueNotFound` in `err.details.Code`.

**Comment by XiaoningLiu** [comment]
Latest dev branch doesn't have this issue. 
![image](https://user-images.githubusercontent.com/6889160/71430630-fc567400-2707-11ea-8698-51432abf0462.png)

√ can create and delete a queue (60ms)
