### ISSUE TITLE
Please tag dockerhub images with the release versions

### ISSUE THREAD

**Issue by timuralp** [Azure/Azurite#377]
Currently, I can only find the "latest" tag on dockerhub (https://hub.docker.com/_/microsoft-azure-storage-azurite). It would be great to be able to pin to a specific dockerhub image when working with Azurite, as breaking changes may appear in new images (e.g. the strict/loose mode added in the 3.4 preview).

**Comment by thisisthekap** [comment]
Tags can be found at https://mcr.microsoft.com/v2/azure-storage/azurite/tags/list

The current tag list:
`{
  "name": "azure-storage/azurite",
  "tags": [
    "3.1.0-preview",
    "3.1.1-preview",
    "3.1.2-preview",
    "3.2.0-preview",
    "3.3.0-preview",
    "3.4.0",
    "latest"
  ]
}`

**Comment by timuralp** [comment]
Great! I'll be able to pin to a specific version through this. Might be useful to add this to the readme.
