### ISSUE TITLE
Running Azurite as background process on Azure DevOps

### ISSUE THREAD

**Issue by chriswill** [Azure/Azurite#382]
### Which service(blob, file, queue, table) does this issue concern?
All
### Which version of the Azurite was used?
3.4
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
12.13.0 (https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md)
### What problem was encountered?
I want to run Azurite in order to run blob storage unit tests during an Azure DevOps build.  There apparently was a command line option of '&' that would run Azurite in the background (https://devkimchi.com/2019/10/16/azure-storage-emulator-on-azure-pipelines/) but this does not appear to work in V3.
### Steps to reproduce the issue?
* Create a DevOps build process.
* Add a step to install Azurite through npm
* Add a step to run a Command, such as 'azurite -s -l c:\azurite -d c:\azurite\debug.log;

Result: Build process stays stuck on Command step where Azurite was executed.
Desired: Azurite runs in the background so that later build steps can take place.
### Have you found a mitigation/solution?
None

**Comment by XiaoningLiu** [comment]
Hi @chriswill 

Please try `azurite &` in Linux, or `start /B azurite` in Windows cmd to start azurite in background

**Comment by chriswill** [comment]
Thanks, that's helpful.

**Comment by SeanFeldman** [comment]
Would be nice to have the [info](https://github.com/Azure/Azurite/issues/382#issuecomment-572409873) as part of the readme.md

**Comment by chatchathu199162** [comment]
> Hi @chriswill
> 
> Please try `azurite &` in Linux, or `start /B azurite` in Windows cmd to start azurite in background
worked successfully

**Comment by trailmax** [comment]
I'm sorry, but this is not a solution. If you go `Start /B azurite`, console still needs to be running, so might as well just have it running in the console. The problem is that nobody wants to have random console windows floating about all the time.

**Comment by esushilnikov** [comment]
@trailmax 
I figured out one way how you can achieve it - I added the Azurite to the Local Group Policy Editor as the Logon script. It starts silently without any application in the tray.


Script Name:
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`

Script Parameters:
`azurite --location c:\azurite -s`

![Image](https://github.com/user-attachments/assets/12eda997-c396-46e6-8bb4-3706f41f8922)
