### ISSUE TITLE
Document best approach to programmatically cleanup the persisted data

### ISSUE THREAD

**Issue by ayeltsov** [Azure/Azurite#384]
Planning to use Azurelite for some unit tests, and need to wipe persisted data between some tests in reliable manner.

I'd like that documentation was explicit about resetting the state. I would just extend documentation somewhere after this example:

azurite -s -l c:\azurite -d c:\azurite\debug.log

E.g. something like this: "to cleanup persisted data, we recommend to kill the process, delete content of the directory specified by -l / --location parameter, and restart azurite" (note: I'm not sure if this is actually the best way, it's just a suggestion on delivery)

**Comment by blueww** [comment]
@ayeltsov 
Thanks for the suggestion!
We will investigate how to improve that.

**Comment by XiaoningLiu** [comment]
Added a section describe Azurite workspace structure in readme.md, will close this.
