### ISSUE TITLE
Adoption blocker: Access control based on conditional headers

### ISSUE THREAD

**Issue by ayeltsov** [Azure/Azurite#385]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
3.4.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
n/a
### What problem was encountered?
SQL team would like to migrate unit tests of our "VFS" project from legacy emulator to Azurite since Azurite supports cross-plat.
However, our project relies on conditional headers.
These are the ones that are currently in use:

```
// 1
AccessCondition accessCondition = AccessCondition.GenerateIfMatchCondition(blobToDownload.Properties.ETag);

await blob.DownloadRangeToStreamAsync(largeDownloadStream, offset, length, accessCondition,
options: CustomExponentialRetry.BackgroundOptions, operationContext: null, progressHandler:null, cancellationToken: cts.Token);
// also await blob.DownloadRangeToByteArrayAsync(..., accessCondition, ...)

// 2
blob.UploadFromByteArrayAsync(buffer: _empty, index: 0, count: 0, accessCondition: AccessCondition.GenerateIfNotExistsCondition(), options: null, operationContext: null, cancellationToken: ct)

// 3
string leaseId = await blob.AcquireLeaseAsync(_config.RegionalCacheLeaseTime, _sessionId.ToString(), accessCondition: null, options: null, operationContext: null, ct);
AccessCondition leaseCondition = AccessCondition.GenerateLeaseCondition(leaseId);
//<check headers>
await blob.ReleaseLeaseAsync(leaseCondition, options: null, operationContext: null, ct);

```
### Steps to reproduce the issue?

Use aforementioned code patterns in strict mode, they should all work

### Have you found a mitigation/solution?

We're holding off on migration to new emulator.

**Comment by XiaoningLiu** [comment]
Hi @ayeltsov 

Sorry for the late response due to holiday. This is a feature request for conditional header, and I got your email too. Will sync with team for the Azurite next schedule and planning.

**Comment by ayeltsov** [comment]
Thanks guys. Per email conversation, the x-ms-sequence-number-action and x-ms-blob-sequence-number ([Set Blob Properties](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-properties)) are also in scope for this improvement.

**Comment by XiaoningLiu** [comment]
Conditional header is supported in v3.6.0. Will close this issue.
