### ISSUE TITLE
How to create queues?

### ISSUE THREAD

**Issue by tcfialho** [Azure/Azurite#392]
How to create queues?

**Comment by blueww** [comment]
@tcfialho 
You can use any SDK to create queue in Azurite. 
Please follow ReadMe for how to start Azurite and how to set storage credential. 
Do you meet any error when create queue?

**Comment by vinjiang** [comment]
Azurite is a Azure Storage emulator, you can use most of the ways of creating Azure Storage queue against Azurite. Like SDK mentioned, like tools, such as Storage Explorer which supports Azurite as well.
