### ISSUE TITLE
Get Blob Metadata operation missing required last-modified header

### ISSUE THREAD

**Issue by meinemitternacht** [Azure/Azurite#396]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.4.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v12.15.0

### What problem was encountered?
When executing the "get blob metadata" command against a blob in a container, the PHP SDK throws an exception because it expects the "last-modified" header to be present in the response.

According to [the Azure REST API documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-metadata), the `Last-Modified` header should be present in the response.  I did not check for other missing headers.

### Steps to reproduce the issue?
Perform a "get blob metadata" request (`GET http://192.168.1.2/aztest/container/blob_name?comp=metadata`) with the PHP SDK to get the exception, but any other client to see the missing header.

### Have you found a mitigation/solution?
I have patched the PHP SDK to provide a default value in case the last-modified header is not present, but this should probably be fixed in Azurite as well.

**Good response when getting container properties**
````
Response headers: Array
(
    [server] => Azurite-Blob/3.4.0
    [etag] => "d-fWwH8Z2SFUuaZAhbGL4lgVLnxPQ"
    [last-modified] => Fri, 07 Feb 2020 21:27:34 GMT
    [x-ms-lease-state] => available
    [x-ms-lease-status] => unlocked
    [x-ms-request-id] => 2910afb9-1bee-424d-8afc-b2d1503c18f8
    [x-ms-version] => 2019-02-02
    [x-ms-has-immutability-policy] => false
    [x-ms-has-legal-hold] => false
    [date] => Mon, 10 Feb 2020 18:43:50 GMT
    [connection] => keep-alive
    [content-length] => 0
    [x-ms-continuation-location-mode] => PrimaryOnly
)
````

**Bad response when getting blob metadata**
````
Response headers: Array
(
    [server] => Azurite-Blob/3.4.0
    [x-ms-meta-originalsize] => aToyNzYxOw==
    [etag] => "d-TEXTttzOwOnm1uRUe/9dULRa46w"
    [x-ms-request-id] => 8c667bb0-0d12-4d10-961d-8ee1611794a7
    [x-ms-version] => 2019-02-02
    [date] => Mon, 10 Feb 2020 18:43:50 GMT
    [connection] => keep-alive
    [x-ms-continuation-location-mode] => PrimaryOnly
)
````

**Comment by blueww** [comment]
@meinemitternacht  

Thanks for reporting this issue!
Will priority the fixing of it with other feature request.
