### ISSUE TITLE
Support custom, multiple storage accounts

### ISSUE THREAD

**Issue by seguler** [Azure/Azurite#40]
See the request here: https://feedback.azure.com/forums/217298-storage/suggestions/31802242-support-multiple-storage-accounts-in-azure-storage

**Comment by edwin-huber** [comment]
Hi,

We already support this by starting multiple instances pointing to separate local paths and by using different TCP ports.
i.e.
azurite -l /account1 --blobport 10000 --queuePort 10001 --tablePort 10002
azurite -l /account2 --blobport 10100 --queuePort 10101 --tablePort 10102

I'll add this to the documentation in a more obvious fashion.
