### ISSUE TITLE
Check if block blob exists should fail if blocks are all uncommitted

### ISSUE THREAD

**Issue by mattdurak** [Azure/Azurite#400]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
3.4.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v11.10.0
### What problem was encountered?
When testing with Azurite, if I upload blocks to a new block blob but do not upload a block list, I expect that when I check if the block exists with the c++ API, it will say the block does not exist (this is the behavior of the old emulator and the actual storage service). However, with Azurite, the blob is reported as existing.
### Steps to reproduce the issue?
Create a block blob using the API. Upload 1 or more blocks to it. Do not upload a block list. Check if the blob exists.
### Have you found a mitigation/solution?
Only disabling our test

**Comment by blueww** [comment]
@mattdurak 
Thanks for reporting this issue!
We will priority it with other Azurite feature request, and fix in future release.

BTW, If you could give the debug log for this issue, it could better help us to investigate this issue.

**Comment by XiaoningLiu** [comment]
Fixed in v3.6.0. Will close this issue.

**Comment by blueww** [comment]
This issue is fixed
