### ISSUE TITLE
Uploading blocks with different lengths of IDs to the same blob should fail

### ISSUE THREAD

**Issue by mattdurak** [Azure/Azurite#401]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
3.4.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v11.10.0
### What problem was encountered?
I expect that if I upload multiple blocks to a blob with different length ID's, then the request will fail with HTTP 400 (The specified blob or block content is invalid.). This is the behavior of the old emulator and the real service, but not Azurite.
### Steps to reproduce the issue?
Create a block blob. Upload a block with ID base64("blockid"). Upload a second block with ID base64("blockid2") (which has a longer string before the base 64 encoding. The second block upload should fail with HTTP 400, but it does not with Azurite.
### Have you found a mitigation/solution?
Disable test or use the old emulator.

**Comment by blueww** [comment]
@mattdurak 

Thanks for reporting this issue!
We will priority it with other Azurite feature request, and fix in future release.

**Comment by XiaoningLiu** [comment]
Fixed in v3.6.0. Will close this issue.
