### ISSUE TITLE
Docker v3.4.0 400 error

### ISSUE THREAD

**Issue by JDonaghy** [Azure/Azurite#405]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
v3
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
10.15.3

### What problem was encountered?
`An unhandled exception of type 'Azure.RequestFailedException' occurred in System.Private.CoreLib.dll: 'The value for one of the HTTP headers is not in the correct format.`

### Steps to reproduce the issue?
Using standard connection string, attempt to create a blob container

### Have you found a mitigation/solution?
Use v3.3.0-preview

**Comment by blueww** [comment]
@JDonaghy 
Thanks for reporting this issue!
Will do some investigating, and update you later.

**Comment by blueww** [comment]
@JDonaghy
Would you please share the debug log? We need it for detail investigation.
It seems the error is from client side.

**Comment by JDonaghy** [comment]
@blueww 
Sorry but it's working now and I have no idea what the problem was. Thanks anyway!

In case anyone is struggling with get docker-compose.yml logging working, here's the command I used:

 `command: 'azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 -l /workspace -d /workspace/debug.log'`

**Comment by blueww** [comment]
@JDonaghy 
Thanks for confirm it works now!
I will close this issue.
Feel free to contact us if need any further assistance.
