### ISSUE TITLE
if-match header on PUT request is not supported

### ISSUE THREAD

**Issue by danielk1977** [Azure/Azurite#406]
### Which service(blob, file, queue, table) does this issue concern?
Blob service.
### Which version of the Azurite was used?
3.5.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
From [npm install]
### What's the Node.js version?
v8.10.0
### What problem was encountered?
The "If-Match" header is not supported on a PUT request to upload a blob. But our app needs that. 
### Steps to reproduce the issue?
Attempt PUT request with If-Match header. In strict mode a 500 error, in loose mode the request always succeeds, but the If-Match header is ignored.
### Have you found a mitigation/solution?
Not so far.

**Comment by XiaoningLiu** [comment]
Hi @danielk1977 This is a feature request for supporting conditional headers. We are planning this in recent releases! Will update later. Thanks for voting this up!

**Comment by danielk1977** [comment]
@XiaoningLiu I think you can close this issue now. Using the latest sources the If-Match header seems to be working fine now. Thanks!

**Comment by XiaoningLiu** [comment]
Thanks @danielk1977 Glad to see Azurite helps!
