### ISSUE TITLE
Standalone windows executables

### ISSUE THREAD

**Issue by maf1024** [Azure/Azurite#41]
In the Nuget package: "Azurite is packaged into a single self-contained executable"
(Side note: Opening the .nupkg as an archive reveals it's actually 3 executables: blob.exe, queue.exe, and table.exe)

Is there any reason that those aren't being published outside of the Nuget package? It seems more convenient to me than having to install it to a particular VS solution. (And easier than messing with Node.js. And less memory intensive than using Docker.)

**Comment by arafato** [comment]
Hi @maf1024 are you saying you would like to have Azurite releases available as self-contained binaries as well?

**Comment by maf1024** [comment]
@arafato Yes.

**Comment by edwin-huber** [comment]
This should not be hard, as we can use pkg for this, in the same way that we make the nuget package.
We could maybe offer the binaries for download.
@seguler what do you think?

**Comment by JustinGrote** [comment]
@XiaoningLiu I have tested this with v3 and the pkg tool and node12 and it generates a functional exe. Would you like me to PR? I will also contribute a scoop manifest and a chocolatey update if you can provide info on how you publish to chocolatey (it does'nt appear to be in the azure pipelines yaml)

**Comment by maf1024** [comment]
@JustinGrote Even if not a PR, if you could update a fork with your tested changes, that would probably be appreciated by my team and myself (with our inexperience in node) so we can try to make our own executables.

(We've been simply relying on the ancient nuget Azurite for a long time, but we recently discovered that we apparently can't use it with the newer Azure.Storage.Blobs V12 dotnet core library)

**Comment by maf1024** [comment]
Finally figured out how to compile the exe files myself.
For anyone out there with a similar need, here's the exhaustive steps I took (in WSL ubuntu 20.04):
```
sudo apt-get install nodejs npm
sudo npm install -g pkg
git clone https://github.com/Azure/Azurite.git ~/Azurite
cd ~/Azurite
npm install
pkg -t node16-win --output blob -c package.json dist/src/blob/main.js
pkg -t node16-win --output queue -c package.json dist/src/queue/main.js
```
(took me a long time to figure out that I'm not supposed to pass main.**_ts_** directly into pkg)

**Comment by edwin-huber** [comment]
Thanks for the effort you put into this!  
We are finding that more people are using the docker containers.
@XiaoningLiu @blueww @vinjiang - Do we want to add this to the documentation, or do we have other plans for Windows exes?

**Comment by JustinGrote** [comment]
I personally have mostly switch to just using the vscode extension and that's good enough for me.

**Comment by maf1024** [comment]
Even though exe distributions don't seem to be _directly_ part of Azurite releases yet, it looks like at least VS2022 finally includes this (and [is now up to date](https://developercommunity.visualstudio.com/t/VS-2022-ships-outdated-Azurite-version/10026492)).

For those interested: The executable's location is `[VS 2022 dir]\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe`
(Note it runs Blob, Queue, _and_ Table emulation all as one process)
