### ISSUE TITLE
Inconsistent GET-blob behavior between Azure and Azurite

### ISSUE THREAD

**Issue by joe-maley** [Azure/Azurite#420]
On Azurite: After a successful PUT-block request to a non-existent blob, GET-blob returns an HTTP 200 with a 0-length blob.

On Azure: After a successful PUT-block request to a non-existent blob, GET-blob returns an HTTP 404.

Once I invoke a PUT-block-list request, both Azurite and Azure return an HTTP 200 from GET-blob with the expected non-zero length.

I don't know if this a bug on Azurite or Azure. The documentation here: https://docs.microsoft.com/en-us/rest/api/storageservices/put-block
states `If you call Put Block on a blob that does not yet exist, a new block blob is created with a content length of 0`. It seems Azurite is in-spec but Azure is not -- but is this considered a bug because the behavior does not match the production Azure that Azurite emulates?

### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
mcr.microsoft.com/azure-storage/azurite

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
mcr.microsoft.com/azure-storage/azurite

### What's the Node.js version?
mcr.microsoft.com/azure-storage/azurite

### What problem was encountered?
Today

### Steps to reproduce the issue?
1. PUT a non-zero length block to a non-existent blob
2. GET the blob, response returns an HTTP 200

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
@joe-maley Please try with v3.6.0 mcr.microsoft.com/azure-storage/azurite:3.6.0, @blueww should already fixed it.

**Comment by joe-maley** [comment]
Thank you @XiaoningLiu and @blueww, v3.6.0 fixed the issue.
