### ISSUE TITLE
Is table storage emulation ever coming?

### ISSUE THREAD

**Issue by onionhammer** [Azure/Azurite#428]
Its a pretty glaring hole, and it don't actually see anything in this repository tracking this issue. Can someone please reference the tracking issue? If there isn't one, there definitely should be.

Being able to develop things that depend on azure tables, like durable functions for example, on any Mac and Linux with a local storage emulator is currently not possible.

**Comment by kosmiq** [comment]
I'm hoping that table emulation will come around sooner rather than later.

However I have a solution for you @onionhammer , if you really need it, on a non Windows machine that allows you to dev locally. I'm a Mac user and this is my current setup allowing me to use Azure Storage Emulator running on VirtualBox with a Windows VM in it.

(As a bonus I'm also running the Cosmos DB emulator)

You'll need:
- VirtualBox
- A Windows 10 ISO
- A Windows 10 key if you want to use it for more than 30 days
- The Azure Storage Emulator stand-alone installer
- (Cosmos DB Emulator stand-alone installer [ https://docs.microsoft.com/sv-se/azure/cosmos-db/local-emulator ] + SQL Express installer)

Setup:
- Install VirtualBox
  - Configure Host Network Manager in VirtualBox as:
    - Name: vboxnet0
    - Adapter -> Configure Adapter Manually (below IP-address can of course be changed to whatever you prefer, just keep any changes in mind going forward)
      - IPv4 Address: 192.168.56.3
      - IPv4 Network Mask: 255.255.255.0
      - Leave IPv6 as default
    - DHCP Server
      - Server Address: 192.168.56.1
      - Server Mask: 255.255.255.0
      - Lower Address Bound: 192.168.56.3
      - Upper Address Bound: 192.168.56.254
  - Install Windows in it
  - Install Virtualbox Guest extensions in Windows 10
  - Setup Network for your Windows 10 in VirtualBox as:
    - Adapter 1: Host-only Adapter
      - Name: vboxnet0 (the one you configured above in Host Network Manager)
    - Adapter 2: NAT
  - Configure your first Ethernet card in Windows 10 (the one created as Adapter 1)
    - Set IPv4 Address manually as:
      - IP Address: 192.168.56.3
      - Subnet Mask: 255.255.255.0
      - Default Gateway: 192.168.56.1
      - You can leave DNS empty
  - Install SQL Express in Windows 10, default setup is fine.
  - Install Azure Storage Emulator in Windows 10
    - Run it once and let it init
    - Goto C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator
    - Edit AzureStorageEmulator.exe.config (Notepad must run with Administrator Privileges)
    - Change URL lines for Blob, Queue and Table from 127.0.0.1:[ports] to 192.168.56.3:[ports] and save the file
    - Start the Azure Storage Emulator using an elevated command prompt.
    - Open the ports 10000, 10001, 10002 in the Windows Firewall for Inbound Connections.
    - The Storage Emulator is now accessible from your MacOS machine on http://192.168.56.3:[servicePort]


(bonus round: Cosmos DB Emulator)
  - Install Cosmos DB Emulator in Windows 10
    - Follow the instructions on how to start the emulator with network access
    - Follow the instructions at https://docs.microsoft.com/sv-se/azure/cosmos-db/local-emulator#running-on-mac-or-linux to get the certificate that you need to import on your MacOS/Unix machine.
    - You must run Command Prompt as Administrator

**Comment by XiaoningLiu** [comment]
Thanks guys! Appreciated to hear from your guys. Currently our main focus is on catching up feature parities for blob & queue storage, there is no short term plan to add table support for Azurite V3. We are also internally discussing with team and PM about table, will update if there is any news. Please leverage CosmosDB or Azurite V2 for Table emualtion for the time being.

**Comment by onionhammer** [comment]
@kosmiq that sounds a lot more complex than my current `docker-compose up -d` to spin up a sql database and azure storage from inside msbuild locally.

**Comment by gunzip** [comment]
a little addendum:

> leverage CosmosDB
cosmosdb emulator runs on windows only. if you have windows you can use the azure storage emulator, you don't need azurite. I guess the main selling point of azurite is to have a cross platform emulator that enables non windows user to develop locally

> leverage ... Azurite V2 for Table emualtion
azure durable functions need table emulation. but it looks like it's broken on azurite v2, see

https://github.com/Azure/Azurite/issues/115
https://github.com/Azure/Azurite/issues/268

so by no chance today you can run azure functions without the windows version of azure storage emulator.

including table emulation in v3 and make durable functions work looks like an important feature

**Comment by atrauzzi** [comment]
These are the kinds of gotchas and limitations that keep cropping up when people are trying to use Azure related tools and services.

**Comment by kosmiq** [comment]
> @kosmiq that sounds a lot more complex than my current `docker-compose up -d` to spin up a sql database and azure storage from inside msbuild locally.

In my case I'm running MacOS and the docker image is only compatible with MacOS as far as I can tell.

**Comment by MatejQ** [comment]
From time to time, we need to copy all blobs from real Azure to local storage emulator. But it's not possible using azcopy which fails with nonsense exceptions. I have read somewhere that it's simply not possible because of the windows azure storage emulator which is legacy, but it is possible with Azurite which is the future.
Now I read that Table storage isn't supported at all in Azurite V3 and broken in V2.
Come on, MS - this is not the first time you deprecate something and don't have a usable replacement.

**Comment by ayeltsov** [comment]
Adding 2 cents on behalf of SQL team. 

One of our smaller projects only has 1.5 people working on it, mostly in free time (read evenings/weekends). 

Project uses legacy emulator for unit tests. Want to migrate unit tests to Azurite but lack of table support is blocking. 

We don't extra have time or desire to use multiple products to get unit tests to work. 

Something simple, lightweight, easy to install and upgrade is what such projects need.

**Comment by kosmiq** [comment]
What is the official way of doing local development since Azure Storage Emulator is going to be deprecated soon, Azurite v2 is old and marked as legacy, and Azurite v3 does not support Table as of yet (with no "short term plans to add it"). (https://github.com/Azure/Azurite/issues/253).

We are using blob, queue and table storage on our end and have a team running MacOS and Windows.

**Comment by ggirard07** [comment]
@kosmiq official solution is to use cosmosdb emulator as indicated [in this duplicated issue](https://github.com/Azure/Azurite/issues/253#issuecomment-621168367) (only Windows seemed to be supported at time of original posting)

**Comment by gabrieljoelc** [comment]
> Thanks guys! Appreciated to hear from your guys. Currently our main focus is on catching up feature parities for blob & queue storage, there is no short term plan to add table support for Azurite V3. We are also internally discussing with team and PM about table, will update if there is any news. Please leverage CosmosDB or Azurite V2 for Table emulation for the time being.

@XiaoningLiu this is unfortunate and makes it very difficult to develop Azure Functions locally on non-windows without a real resource, since all Azure Functions require table storage to run. I end up doing a bunch of the coding on my Mac and then running the app on my PC. :( 

See my other open issue #263 where I need blob and table storage in a similar scenario so I have to try and use V3 and V2 because the V2 blob has issues. 💫 

@XiaoningLiu Is there any way I could convince you to increase the priority of adding table storage to V3 (e.g. makes selling Azure Functions to non-Windows peeps much more appealing since there is no Docker image for Table Storage we can just use)? 😅

**Comment by SeanFeldman** [comment]
> @XiaoningLiu Is there any way I could convince you to increase the priority of adding table storage to V3 (e.g. makes selling Azure Functions to non-Windows peeps much more appealing since there is no Docker image for Table Storage we can use)? 😅

I'll ask perhaps a bit too direct question, but still - is Table Storage service deprecated?

If "yes", understandable why there's a push back to support it with Azurite.
If "no", then it's weird that it's not supported, no?

Fully understand the challenges of any emulator - it adds to the product/service team to technically own and support a parallel product. At the same time, if the emulator is _already_ there and service (Table Storage) is not deprecated, then it's putting customers in an awkwardly strange situation.

**Comment by onionhammer** [comment]
I really think the team needs to re-prioritize this effort. Table storage support is critical for a lot of different scenarios like durable funcitons

**Comment by hoshauch** [comment]
how should we test locally on linux?
Please do it :)

**Comment by XiaoningLiu** [comment]
> > @XiaoningLiu Is there any way I could convince you to increase the priority of adding table storage to V3 (e.g. makes selling Azure Functions to non-Windows peeps much more appealing since there is no Docker image for Table Storage we can use)? 😅
> 
> I'll ask perhaps a bit too direct question, but still - is Table Storage service deprecated?
> 
> If "yes", understandable why there's a push back to support it with Azurite.
> If "no", then it's weird that it's not supported, no?
> 
> Fully understand the challenges of any emulator - it adds to the product/service team to technically own and support a parallel product. At the same time, if the emulator is _already_ there and service (Table Storage) is not deprecated, then it's putting customers in an awkwardly strange situation.

Table Storage is not deprecated. It's branding movs from Azure Storage Table to Azure Table. We are internally discussing Table support in Azurite V3 with CosmosDB team. We know many are aksing Table support. The challenge is we need more resources for contribution to Azurite Table. Open source contributions are very welcome. If anyone wants to contribute to Azurite Table, like implementing some APIs, please leave message here : )

**Comment by onionhammer** [comment]
@XiaoningLiu maybe if the team at Microsoft could start a branch with table support and just stub out the method signatures with "TODO"s the rest could be filled in somewhat idiomatically by the community? Putting such a large task out to the community without guidance is an invitation to failure or duplication of effort

**Comment by hugoeustaquio** [comment]
Can you fix table storage support on V2?

**Comment by takekazuomi** [comment]
Is this story the same as the CosmosDB emulator's cross-platform support?

**Comment by XiaoningLiu** [comment]
> @XiaoningLiu maybe if the team at Microsoft could start a branch with table support and just stub out the method signatures with "TODO"s the rest could be filled in somewhat idiomatically by the community? Putting such a large task out to the community without guidance is an invitation to failure or duplication of effort

We will prepare guidelines, project skeletons and open details tasks. Each task will have detailed description and should be fine greained.

**Comment by XiaoningLiu** [comment]
> Can you fix table storage support on V2?

V2 table has different structure with v3. @edwin-huber is helping with V2 releasing and reviewing, Open source contribution to table v2 is also welcome.

**Comment by XiaoningLiu** [comment]
> Is this story the same as the CosmosDB emulator's cross-platform support?

What's the `CosmosDB emulator's cross-platform support` you are referring to? In my recent talk with CosmosDB team, they are generally agree to have Table in Azurite V3 for better cross-platform support.

**Comment by takekazuomi** [comment]
@XiaoningLiu CosmosDB Emulator is under development.  I have been waiting for more than 3 years. I'm tired of waiting. 
https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/18533509-add-documentdb-emulator-support-for-mac-os-x-and

**Comment by edwin-huber** [comment]
Hi,  
I appreciate your pain.  
Maintaining v2 table is not very practicable any more as I can't keep up with the number of features that need backporting to keep up with the current versions of our APIs.  
We are working out the details for v3 and will update as soon as we can with something more concrete.

**Comment by maartenba** [comment]
Would also like to see this supported, especially to be able to work with durable functions locally (without having to depend on connectivity to an actual storage account to do development). We have a lot of developers on macOS and taking the connectivity constraint into account, they currently have no option other than booting into Windows and using the "old" storage emulator

**Comment by oising** [comment]
Need to add the point that alongside azure functions, Orleans also requires table storage for some important scenarios... :/

**Comment by XiaoningLiu** [comment]
Hi guys, after serveral rounds of discussion and review. Azurite V3 is going to support Table. It's great if anyone likes to contribute to Azurite V3 Table. Use following queries for all opening TODO items:
- [Phase 1 Preview Features, All](https://github.com/azure/azurite/issues?q=is%3Aissue+label%3Anewarch+label%3Atable-storage+label%3Afeatureparity+milestone%3A%22Preview+-+Azurite+V3+Table%22+is%3Aopen)
- [Phase 1 Preview Features, Unassigned](https://github.com/azure/azurite/issues?q=is%3Aissue+label%3Anewarch+label%3Atable-storage+label%3Afeatureparity+milestone%3A%22Preview+-+Azurite+V3+Table%22+is%3Aopen+no%3Aassignee)
- [Phase 1 Preview Testing, All](https://github.com/azure/azurite/issues?q=is%3Aissue+label%3Anewarch+label%3Atable-storage+label%3ATDD+milestone%3A%22Preview+-+Azurite+V3+Table%22+is%3Aopen+)
- [Phase 1 Preview Testing, Unassigned](https://github.com/azure/azurite/issues?q=is%3Aissue+label%3Anewarch+label%3Atable-storage+label%3ATDD+milestone%3A%22Preview+-+Azurite+V3+Table%22+is%3Aopen+no%3Aassignee+) 

Other references:
Azurite V3 Table GitHub Branch: https://github.com/Azure/Azurite/tree/table
Azurite V3 Table GitHub Project: https://github.com/Azure/Azurite/projects/2
Azurite V3 Table Wiki (under development): https://github.com/Azure/Azurite/wiki/Azurite-V3-Table

**Comment by edwin-huber** [comment]
Table support added in preview.  
GA soon.
