### ISSUE TITLE
Fix blob copy support when using SQL metadata implementations

### ISSUE THREAD

**Issue by atrauzzi** [Azure/Azurite#443]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
`latest`
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub
### What's the Node.js version?
N/A
### What problem was encountered?
Can't perform simple copy operations.
### Steps to reproduce the issue?
Attempt to call copy using Azure Storage Explorer or your favourite SDK, you'll get a 500.
### Have you found a mitigation/solution?
No.

**Comment by atrauzzi** [comment]
Just as a note, I think this functionality is too essential to not be supported.  This was a landmine for me today.

**Comment by blueww** [comment]
@atrauzzi 
We do have Test case to cover the blob copy scenarios.
So pleases give the detail repro steps, like how to prepare the blob to copy, the parameter you use in copy, the detail error message, and better with Azurite debug log.  
These information can help us to better investigate this issue.

**Comment by atrauzzi** [comment]
Hey @blueww!

I'm not sure it's necessary as [you guys have already acknowledged that this is an issue](https://github.com/Azure/Azurite/commit/a75984b6ff2dc569b2c8c07d0446720a8067484d#diff-04c6e90faac2675aa89e2176d2eec7d8R363) in the readme.

![image](https://user-images.githubusercontent.com/115199/80663519-d0eae980-8a59-11ea-9b91-209311325ae6.png)

The repro steps are to enable SQL based metadata and to perform a copy using Azure Storage Explorer or an SDK.  I have used no special parameters.  It's just the most basic copy operation you can think of.

**Comment by blueww** [comment]
@atrauzzi 
Yes, we currently don't support copy page/append blob on SQL based metadata implementation.
This is in our track. we will prioritize it with other feature ask.

**Comment by atrauzzi** [comment]
Much appreciated! :smile:

**Comment by patrickcarnahan** [comment]
@atrauzzi which sql dialect are you using?

**Comment by atrauzzi** [comment]
Postgres.

**Comment by patrickcarnahan** [comment]
@atrauzzi #577 adds support for asynchronous copy using the `sql` metadata store. it's entirely possible that the UI makes use of the synchronous copy call, i'm not positive how it works. 

care to give it a spin and see if it resolves you issue?

**Comment by atrauzzi** [comment]
I'll definitely take a look next chance I get and report back!  Thank you! :smile:
