### ISSUE TITLE
How to configure anonymous access

### ISSUE THREAD

**Issue by tcfialho** [Azure/Azurite#447]
Anonymous access is also available when container is set to allow public access. 

How to configure that?

**Comment by blueww** [comment]
@tcfialho 

You can config it with storage SDK or tools, as you do for storage accounts in Azure Product regions.

Like with Azure Storage explorer:
You can get the connect string from https://github.com/Azure/Azurite#connection-strings
Then in Azure Storage Explorer, connect to azure storage with the connection string.
Then in Azure storage explorer, choose the new added storage account, and the container below it, choose "Set Public Access Level", choose the public access you need.
![image](https://user-images.githubusercontent.com/6926193/82281199-557ab900-99c3-11ea-8744-83c392adf27e.png)

Then you can access the container (or blob in it) anonymously.

**Comment by robertsundstrom** [comment]
Excuse my poor JSON... You can do it manually by editing ```__azurite_db_blob__.json```, by adding ```"publicAccess": "blob``` to the container config. You can also specify "container" as a level.

I'm not sure if a restart is required, but I think it is.

```json
{
            "name": "$CONTAINERS_COLLECTION$",
            "data": [
                {
                    "accountName": "devstoreaccount1",
                    "name": "images",
                    "properties": {
                        "etag": "\"0x1C839AE6CDF11F0\"",
                        "lastModified": "2021-05-14T15:08:51.726Z",
                        "leaseStatus": "unlocked",
                        "leaseState": "available",
                        "hasImmutabilityPolicy": false,
                        "hasLegalHold": false,
              --- >  "publicAccess": "blob" <---- 
                    },
                   // Omitted
        },
```

**Comment by edwin-huber** [comment]
Thanks @robertsundstrom :smile: Seems like this old issue is resolved.
Closing for now.
