### ISSUE TITLE
Running azurite for tests in a GitHub action

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/Azurite#451]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.7.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
11

### What problem was encountered?
Running azurite in a GitHub action to allow tests to run

### Steps to reproduce the issue?

I'm running the following in my action:
```yml
    - name: Install NPM
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install -g azurite
    - shell: cmd
      run: start /B azurite-blob
    - name: Run tests
      run: dotnet test ./src/ServiceBus.AttachmentPlugin.sln --configuration Release  --no-restore  --verbosity normal
```

Can see azurite is running, but tests are failing to connect.

![image](https://user-images.githubusercontent.com/1309622/83604433-6420ae80-a533-11ea-871d-f062bd11b95d.png)

Tests execution:
![image](https://user-images.githubusercontent.com/1309622/83604492-7b5f9c00-a533-11ea-84d3-3c522c5870cd.png)

Is this a correct way to run azurite when using GitHub actions? The [workflow](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/actions/runs/123354713/workflow) I'm using fails to execute tests that are connecting to the development storage account.

**Comment by atrauzzi** [comment]
I feel like steps are isolated from eachother in actions. So your service might not exist on subsequent steps as the entire process context is disposed.

**Comment by SeanFeldman** [comment]
Steps in the same job share the same runner and access the same file system. Process wise, not sure. Maybe @ethomson can clarify?

**Comment by ethomson** [comment]
_Jobs_ are run in separate environments.  _Steps_ are run sequentially on the same environment.  So it would be ok to start azurite and then test it in separate steps.

But what does `start /B` do?  Does it start this process in the background?  If so, you'll probably need some sort of delay before running the tests to ensure that the process is fully started and ready to receive requests, otherwise I suspect your subsequent test run is losing a race and trying to hit the service before it's actually started.

Does azurite have a health check that you can poll before you run the tests?

**Comment by atrauzzi** [comment]
Are you sure?  I've tried to set environment variables in the past to share between steps and had no luck.  Which lead me to doing this between _steps_:

```
echo "::set-env name=VARIABLE_FOR_FUTURE_STEPS::${VARIABLE_IN_CURRENT_CONTEXT}"
```

**Comment by SeanFeldman** [comment]
> But what does `start /B` do? Does it start this process in the background?

Run a process in the background. This is what Az DevOps is doing to keep the process running while tests are executed.

> If so, you'll probably need some sort of delay before running the tests to ensure that the process is fully started and ready to receive requests, otherwise I suspect your subsequent test run is losing a race and trying to hit the service before it's actually started.

From what I've seen, Azurite [starts listening](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/runs/733597968?check_suite_focus=true#step:7:7) _before_ tests step is executed but all tests are [failing to establish the connection](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/runs/733597968?check_suite_focus=true#step:8:3355). The tests are running for 12 mins while trying to connect. That's why I question the timing issue, @ethomson.

**Comment by ethomson** [comment]
> Are you sure?

Yes, I'm sure; you can see this by writing a file to disk in one step and read it in a second.

> I've tried to set environment variables in the past to share between steps and had no luck.

Right - you get a new shell each for each step, so environment variables would not be persisted.

> Which lead me to doing this between steps:

Yep, this is the right way to do this.  👍 

> From what I've seen, Azurite starts listening before tests step is executed but all tests are failing to establish the connection.

Yeah, looking at the logs, that makes sense.  It would be interesting to know if you can hit that port (the moral equivalent of `sleep 5 && curl http://localhost:10000/`).  That might help understand whether the problem is in the service listening on 10000 or the test bits calling it.

**Comment by atrauzzi** [comment]
Apologies :smile:, I was under the impression that the behaviour behind getting a new shell would also destroy any processes started under it.

**Comment by SeanFeldman** [comment]
> Yeah, looking at the logs, that makes sense. It would be interesting to know if you can hit that port (the moral equivalent of `sleep 5 && curl http://localhost:10000/`). That might help understand whether the problem is in the service listening on 10000 or the test bits calling it.

Hmm, the tests are trying to establish a connection to http://**127.0.0.1**:10000/ and not http://**localhost**:10000/. I wonder if that's the root of the problem.

**Comment by SeanFeldman** [comment]
From what I can see, there's something that is blocking the communication. I tried both, [http://localhost:10000](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/runs/741284470?check_suite_focus=true#step:8:12) as well as [http://127.0.0.1:10000](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/runs/741296982?check_suite_focus=true#step:8:11) and both failed with

> curl: (7) Failed to connect to 127.0.0.1 port 10000: Connection refused

This indicates the azurite process is either not running or not accessible.

@ethomson, is there anyone at GitHub Actions team that can look into this?

**Comment by ethomson** [comment]
> Apologies 😄, I was under the impression that the behaviour behind getting a new shell would also destroy any processes started under it.

No apology needed - I'm not sure of the precise mechanics around `start /B` behavior or background processes in Windows.  And I think that you're right, this does actually appear to be a somewhat different concept.

The [docs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start) say:

>  Starts an application without opening a new Command Prompt window. CTRL+C handling is ignored unless the application enables CTRL+C processing. Use CTRL+BREAK to interrupt the application.

It sounds like this doesn't really put something in the background - at least in the Unix sense - as much as it means that the new process just [has the I/O of the existing window](https://stackoverflow.com/questions/649634/how-do-i-run-a-bat-file-in-the-background-from-another-bat-file), and that this is [tied to the current console](https://superuser.com/a/1069983):

> Now the problem is that when a console window is closed, any process associated with this console will also be closed.

Changing this to bash and putting it in the background with `&` seems to [get the process running correctly](https://github.com/ethomson/ServiceBus.AttachmentPlugin/blob/develop/.github/workflows/dotnet-core.yml).

```yaml
- run: npm install -g azurite
- shell: bash
  run: azurite-blob &
```

> @ethomson, is there anyone at GitHub Actions team that can look into this?

The best place to get help is [github.community](https://github.community) - support, engineering and product members of the Actions team hang out there.

**Comment by SeanFeldman** [comment]
Switching to bash was a great find. I've also noticed that on another CI/CD platform I've used PowerShell [`Start-Process` cmdlet](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process). Which I assume would work for Actions as well. It's interesting that for Azure DevOps pipelines, `start /B` does work.

Anyhow, @ethomson, thank you so much 🙂

**Comment by ethomson** [comment]
Happy to help, it was nice to learn a little bit more about `cmd`, even if I left with more questions about it than answers.  😁

**Comment by LarsKemmann** [comment]
@ethomson I would love to see some guidance on this use case referenced in the readme for Azurite. I'm not sure it's the best place for that, but that was where I looked for help with this exact scenario (before I found this issue). I know the readme is already really long 😀 -- maybe breaking out a wiki page (and referencing it from the readme) would be better.

**Comment by HiroyukiSakoh** [comment]
In the SelfHosted Windows (W/O WSL) environment
This command works well.
```
- name: Run Azurite
   run: cmd /c "START azurite -s -l azuritedatadir"
   shell: cmd
```

**Comment by IGx89** [comment]
FYI there's an even simpler solution available now, by running Azurite in a Docker container as part of your job. Just add the following under your job, above steps:

```
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002
```

This follows the same approach recommended for Redis here: https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers
