### ISSUE TITLE
Unable to run Azurite on Windows

### ISSUE THREAD

**Issue by gmantri** [Azure/Azurite#473]
### Which service(blob, file, queue, table) does this issue concern?
All

### Which version of the Azurite was used?
3.8.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
8.12.0

### What problem was encountered?
I'm pretty sure I am missing something very trivial but not able to figure it out. For some unknown reasons, I'm not able to run Azurite on Windows. I am getting the following error: `'azurite' is not recognized as an internal or external command, operable program or batch file.`. Would really appreciate any help.

### Steps to reproduce the issue?

1. Installed azurite using the following command: `npm install -g azurite`. The command runs successfully and I see the following in the command prompt:

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
C:\Users\gauravmantri\AppData\Roaming\npm\azurite -> C:\Users\gauravmantri\AppData\Roaming\npm\node_modules\azurite\dist\src\azurite.js
C:\Users\gauravmantri\AppData\Roaming\npm\azurite-blob -> C:\Users\gauravmantri\AppData\Roaming\npm\node_modules\azurite\dist\src\blob\main.js
C:\Users\gauravmantri\AppData\Roaming\npm\azurite-queue -> C:\Users\gauravmantri\AppData\Roaming\npm\node_modules\azurite\dist\src\queue\main.js
+ azurite@3.8.0
updated 1 package in 24.834s
```

2. Next I try to run the azurite using the following command: `azurite -s -l c:\temp -d c:\temp\azurite-debug.log`. When I do that, I am getting the following error:

```
'azurite' is not recognized as an internal or external command,
operable program or batch file.
``` 

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Believe this is a general issue on your local npm environment. Install other npm packages globally should fail either. 

I don't have much comments here, maybe you can try uninstall then install Node.js again and see if it helps?

**Comment by PureKrome** [comment]
@gmantri Heya- do you have to grab Azurite _via npm_ ? Why not use it via Docker?

**Comment by StingyJack** [comment]
If you installed azurite with the `-g` switch, this will happen if you dont have your NPM folder in your `PATH`.  Add 

``` cmd
%USERPROFILE%\AppData\Roaming\npm
```
to your `PATH` Environment variable, then open a new cmd or powershell window.

**Comment by gmantri** [comment]
@StingyJack ... Thanks (and apologies for a really late response)! Setting the path did the trick.
