### ISSUE TITLE
[Table] Phase 1 Feature - Query Entities

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/Azurite#486]
Read through:
- https://docs.microsoft.com/en-us/rest/api/storageservices/query-entities
- [Azurite V3 Table wiki](https://github.com/Azure/Azurite/wiki/Azurite-V3-Table)

Implement following parts:
- [ ] Implement TableHandler::queryEntities()
- [ ] Implement TableHandler::queryEntitiesWithPartitionAndRowKey()
- [ ] Implement LokiTableMetadataStore::queryTableEntities()
- [ ] Implement LokiTableMetadataStore::queryTableEntitiesWithPartitionAndRowKey()
- [ ] Add test cases

Take Create Table implementation as example:
- [TableHandler::create()](https://github.com/Azure/Azurite/blob/table/src/table/handlers/TableHandler.ts#L22)
- [LokiTableMetadataStore::createTable()](https://github.com/Azure/Azurite/blob/table/src/table/persistence/LokiTableMetadataStore.ts#L37)
- [Create Table test cases](https://github.com/Azure/Azurite/blob/table/tests/table/apis/table.test.ts#L39)

**Comment by edwin-huber** [comment]
Hi @XiaoningLiu  @isabella0428 , 
sorry, don't want to come across as impatient ::innocent:: we are waiting on the queryEntitiesWithPartitionAndRowKey handler for our insert or merge and upsert handlers test cases.

It looks like it has not been implemented here.

I already had to implement on the Loki metadata handler to complete the upsert, would not be much more to add the externally facing API and tests.

Are you OK for @CodeUnicornMartha and myself to implement?

Thanks,
Edwin

**Comment by XiaoningLiu** [comment]
Already implemented.
