### ISSUE TITLE
[Table] Phase 1 Feature - SharedKey Authentication

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/Azurite#494]
Read through:

- https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#table-service-shared-key-authorization
- [Azurite V3 Table wiki](https://github.com/Azure/Azurite/wiki/Azurite-V3-Table)

Implement following parts:

- [ ] Add AuthenticationMiddlewareFactory.ts into src/table/middlewares. Refer to [Azurite Blob AuthenticationMiddlewareFactory](https://github.com/azure/azurite/blob/2395dec0eb8f235922ba34633bd81e3b33704caf/src/blob/middlewares/AuthenticationMiddlewareFactory.ts)
- [ ] Add IAuthenticator.ts into src/table/authentication. Refer to [Azurite Blob IAuthenticator.ts](https://github.com/azure/azurite/blob/3a0c73bb50ea7408ad5bfa79df542d6b8f879c36/src/blob/authentication/IAuthenticator.ts)
- [ ] Add IAuthenticationContext.ts into src/table/authentication. Refer to [Azurite Blob IAuthenticationContext.ts](https://github.com/azure/azurite/blob/3a0c73bb50ea7408ad5bfa79df542d6b8f879c36/src/blob/authentication/IAuthenticationContext.ts)
- [ ] Add and implement TableSharedKeyAuthenticator.ts into src/table/authentication. Refer to [Azurite Blob BlobSharedKeyAuthenticator.ts](https://github.com/azure/azurite/blob/66ee971f88fdb972bac5d25ca0ba871d781b4bbc/src/blob/authentication/BlobSharedKeyAuthenticator.ts)
- [ ] Add test cases. Refer to [Azurite Blob SharedKey authentication tests](https://github.com/azure/azurite/blob/b057f11cf3198d6a8f3f910b352a449a537a47f7/tests/blob/authentication.test.ts)

**Comment by ocdi** [comment]
This task overlaps #495 and is required to get the unit tests to pass after introducing authentication, so I am tackling this now also.
