### ISSUE TITLE
[Table] Phase 1 Feature - Service SAS Authentication

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/Azurite#495]
Read through:

- https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas
- [Azurite V3 Table wiki](https://github.com/Azure/Azurite/wiki/Azurite-V3-Table)

Implement following parts:

- [ ] Add AuthenticationMiddlewareFactory.ts into src/table/middlewares. Refer to [Azurite Blob AuthenticationMiddlewareFactory](https://github.com/azure/azurite/blob/2395dec0eb8f235922ba34633bd81e3b33704caf/src/blob/middlewares/AuthenticationMiddlewareFactory.ts)
- [ ] Add IAuthenticator.ts into src/table/authentication. Refer to [Azurite Blob IAuthenticator.ts](https://github.com/azure/azurite/blob/3a0c73bb50ea7408ad5bfa79df542d6b8f879c36/src/blob/authentication/IAuthenticator.ts)
- [ ] Add IAuthenticationContext.ts into src/table/authentication. Refer to [Azurite Blob IAuthenticationContext.ts](https://github.com/azure/azurite/blob/3a0c73bb50ea7408ad5bfa79df542d6b8f879c36/src/blob/authentication/IAuthenticationContext.ts)
- [ ] Add and implement TableSASAuthenticator.ts into src/table/authentication. Refer to [Azurite Blob BlobSASAuthenticator.ts](BlobSASAuthenticator.ts).
- [ ] Add test cases. Refer to [Azurite Blob SAS tests](https://github.com/azure/azurite/blob/efe4e9d123304715cb84499653e008cc425d15fd/tests/blob/sas.test.ts)

**Comment by ocdi** [comment]
I'm giving this one a go

**Comment by XiaoningLiu** [comment]
Thanks @ocdi!
