### ISSUE TITLE
[Table] Phase 1 Feature - Logging

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/Azurite#499]
Read through:

- [Azurite V3 Table wiki](https://github.com/Azure/Azurite/wiki/Azurite-V3-Table)

Implement following parts:

- [ ] Add debug log for handler or metadata layer implementations

**Comment by edwin-huber** [comment]
Table already has logging implementation 
- log module shared by blob/queue/table
- also has some debug log output 

This item is more about checking any missing parts of logging and making sure it works as expected.

**Comment by edwin-huber** [comment]
Validated logging in table middleware
