### ISSUE TITLE
Table: Support for Entity Group Transaction

### ISSUE THREAD

**Issue by arafato** [Azure/Azurite#5]
https://docs.microsoft.com/en-us/rest/api/storageservices/performing-entity-group-transactions

**Comment by tlycken** [comment]
What's the ETA on this feature? I have a use case for it ([Streamstone](https://github.com/yevhen/Streamstone/) needs it) 😄

**Comment by murraybauer** [comment]
I know the actual ETG message body encoding is not pretty, but it's critical it's get added. ETG is core to the table storage design constraints.

**Comment by edwin-huber** [comment]
Sorry, right now we have no ETA on this, as we are working on getting blob storage up to the right level of feature parity with Azure to be able to run the core samples and take over as emulator.
It's on our list, and we will revisit this when we start working out all the kinks in the table storage emulation

**Comment by edwin-huber** [comment]
Table Support added to v3, closing old issues.
