### ISSUE TITLE
Use Typescript

### ISSUE THREAD

**Issue by swissarmykirpan** [Azure/Azurite#50]
Strategy:

- [ ] Convert existing code to ES6 (require => import) - https://github.com/Azure/Azurite/pull/63
- [ ] Convert JS to TS - with minimal tsconfig and lint configuration

Each step should be merged separately, so that the git history does not look like a mess and it will be possible to track back cleanly.
This approach will also allow for "easier" PR reviews and put the codebase in a position where by we can start to nicer typescript features such as `async await`

**Comment by edwin-huber** [comment]
Azurite v3 was written from the ground up in TypeScript
