### ISSUE TITLE
Azure Queues - ApproximateMessageCount Bug

### ISSUE THREAD

**Issue by swissarmykirpan** [Azure/Azurite#51]
`queue.ApproximateMessageCount` always returns `null`

**Comment by XiaoningLiu** [comment]
@swissarmykirpan 

Cannot reproduce this issue. Can you share your steps? See following code example I have, based on azure-storage Node.js SDK.

![image](https://user-images.githubusercontent.com/6889160/42981669-e76bae0a-8c0f-11e8-876c-031795b1ff1d.png)

**Comment by edwin-huber** [comment]
@swissarmykirpan please reopen if this is still an issue.

The code that does this is here: 
```
.\lib\actions\queue\GetQueueMetadata.js
```
```javascript
response.addHttpProperty(N.APPROXIMATE_MESSAGES_COUNT, queueLength);
```

If you have repro steps, then we can reopen and use that to validate any failures in Azurite code.
