### ISSUE TITLE
Azure policy - enable soft delete audit/deployifexists is not working

### ISSUE THREAD

**Issue by balareddy2509** [Azure/Azurite#514]
### Which service(blob, file, queue, table) does this issue concern?
blob, fileshare
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
NuGet
### What problem was encountered?
Azure Policy is not working as expected
### Steps to reproduce the issue?
{
    "properties": {
      "displayName": "Audit Data Protection on Blobs - Storage Accounts",
      "policyType": "Custom",
      "mode": "All",
      "description": "Ensure that storage accounts created with soft delete for blobs and fileshares",
      "metadata": {
        "version": "1.0.0",
        "category": "Storage"
      },
      "parameters": {
        "effect": {
          "type": "String",
          "metadata": {
            "displayName": "Effect",
            "description": "The effect determines what happens when the policy rule is evaluated to match"
          },
          "allowedValues": [
            "Audit",
            "Deny",
            "Disabled"
          ],
          "defaultValue": "Audit"
        }
      },
      "policyRule": {
        "if": {
          "allOf": [
            {
              "field": "type",
              "equals": "Microsoft.Storage/storageAccounts"
            },
            {
                "field": "Microsoft.Storage/storageAccounts/blobServices/deleteRetentionPolicy.enabled",
                "exists": "true"
            }
          ]
        },
        "then": {
          "effect": "[parameters('effect')]"
        }
      }
    }
  }
### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
This issue is not related to Azurite, please double check proper repo for issues about Azure Policy.

**Comment by MrChief07** [comment]
deployifnotexists works but deny won't
