### ISSUE TITLE
Azure Table Query not working

### ISSUE THREAD

**Issue by swissarmykirpan** [Azure/Azurite#52]
I am doing a simple search on partitionkey and rowkey -> no data is being returned. If I remove all filters from the filter I get the data back.

I have tried this using `WindowsAzure.Storage` nuget package lib and also the Microsoft Azure Storage Explorer - both produce the same result

**Comment by XiaoningLiu** [comment]
Hi @swagatmishra2007 

Can you help providing samples code used to query?

**Comment by swagatmishra2007** [comment]
@XiaoningLiu sorry doesn't look related to anything i work on :)

**Comment by XiaoningLiu** [comment]
@swagatmishra2007 Sorry.. 

@swissarmykirpan Can you help providing samples code used to query?

**Comment by edwin-huber** [comment]
This "should" be solved in the latest release (current dev branch being promoted now)  
Please let us know in case we need to improve the test cases and associated table query code.

**Comment by cswendrowski** [comment]
@edwin-huber Thanks for fixing this!

I went looking for the latest release in hopes of testing it out and noticed that both NPM and Dockerhub only have 2.6.5 (5 months old). It looks like there should have been a 2.6.6 deployed 2 days ago: https://travis-ci.org/Azure/Azurite/builds/421433522

Is the deployment having issues, or is there just a mechanism for promoting that I'm not seeing?

**Comment by maciejgos** [comment]
Hi do you have any idea when v.2.6.6 will be available on npm? Thanks.

**Comment by cswendrowski** [comment]
I am temporarily building and hosting the Docker images of this repository until deployments start coming out of this repo again: https://hub.docker.com/r/ironmoosedevelopment/azurite/

I can look into deploying the NPM version as well

**Comment by XiaoningLiu** [comment]
Close this for long time noactive.
