### ISSUE TITLE
Use Azure-Storage-Node in Tests

### ISSUE THREAD

**Issue by swissarmykirpan** [Azure/Azurite#53]
Rather than having to recreate the wheel with Http requests, why not use 
https://github.com/Azure/azure-storage-node ?

**Comment by edwin-huber** [comment]
Hi @swissarmykirpan, many thanks for the suggestion.
That's a good idea.
Building out the TDD is on our list of things to do.
Right now we are using the .Net Storage SDK to validate the  functionality, but a Node version would make life easier.

**Comment by edwin-huber** [comment]
Hi @pmanlukas , can you see if we can incorporate this and update the documentation accordingly?

**Comment by pmanlukas** [comment]
Sure, i will investigate this week if we can switch to our SDK for that :)

**Comment by swissarmykirpan** [comment]
@edwin-huber @pmanlukas I am happy to do this work if that helps :)

**Comment by pmanlukas** [comment]
That would be a great suppport :) Then I would suggest you add the changes and make a pull request and we will review it than in time

**Comment by edwin-huber** [comment]
@pdressel maybe you can connect with @swissarmykirpan , as you have been looking at this as well?

**Comment by swissarmykirpan** [comment]
@edwin-huber @pmanlukas the problem with TDD is that effectively we would have the same tests that the node lib already does - or the c# client already does. Rather than re-implementing all of those tests, what if we forked some of the other client libs and then target a docker container with the tests?

**Comment by pdressel** [comment]
@swissarmykirpan @edwin-huber @pmanlukas I agree, and azure-storage-node already comes with an exhaustive test suite for free. I was able to make it work by including node-azure-storage as a git submodule and writing a small shim to run their tests directly against Azurite via ´npm test´. This works with the existing pipeline without extra integration, and locking and updating the test code via git submodule is also easy to do. 

This could nicely complement PR#58, where we could write additional tests specific to Azurite not covered by the external tests. What do you think?

**Comment by swissarmykirpan** [comment]
@pdressel where’s the branch/PR then? 😜

**Comment by pmanlukas** [comment]
@pdressel is currently debugging the last issues with the storage tests. It is actually working to use his approach, but running the new storage tests showed some new issues in the code :) we keep you updated

**Comment by pmanlukas** [comment]
@swissarmykirpan we just merged the first part of the implementation :)

**Comment by edwin-huber** [comment]
We now have Azure Storage Node use in the basic testing, and are using azure-storage-node as our external integration tests.
Closing this issue.
