### ISSUE TITLE
[blob]: enable cross account async copy (same server)

### ISSUE THREAD

**Issue by patrickcarnahan** [Azure/Azurite#530]
### Which service(blob, file, queue, table) does this issue concern?

Blob 

### Which version of the Azurite was used?

3.8.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What problem was encountered?

copying a blob which exists in a different storage account does not work and instead returns a 404. it turns out this is due to https://github.com/Azure/Azurite/blob/master/src/blob/handlers/BlobHandler.ts#L627, which explicitly returns `blobNotFound` in the case that the source storage account isn't the same as the destination storage account. as it appeared to handle this fine all the way down the stack (at least in the Loki provider), i removed the comparison and built a new local image. upon rerunning our local tests this worked fine, so this is more of a question.

is cross-account blob copy explicitly disabled? it appears to be handled in the backend. 

### Steps to reproduce the issue?

- setup 2 storage accounts
- create a blob on account 1
- attempt to copy the blob to account 2 using account 1 as the copy source

### Have you found a mitigation/solution?

locally i was able to just remove the offending line as described above. any reason this couldn't be included in master?

**Comment by XiaoningLiu** [comment]
Hi @patrickcarnahan

Copy Blob is a complex scenario where copy source may be internal resources inside Azurite (same account or different account), or copy source may be external resources. Current implementation only supports copy from same account hosted by Azurite. 

I think it's a valid point to support copy from another account hosted by Azurite. However, we couldn't do this by simpliy removing account name check in current implementation, though it seems working in your case. To copy from another storage account, copy source URL should include a valid SAS in order to access another account. Then trigger HTTP Get requests to download source blob from another account.

**Comment by patrickcarnahan** [comment]
@XiaoningLiu you are correct. In my haste I wasn't specific enough, so I updated the title accordingly. In our case we do have a valid SAS token for the source account, so it meets the criteria you have laid out. 

If I were to submit a PR that enables cross account async copy within the same server (no http requests involved here) would that be accepted as a standalone change? Ideally if the source cannot be found it would still return the `404` which I imagine is expected, whether or not the source URL is from the same server.

**Comment by patrickcarnahan** [comment]
Did more digging today and validated your concern that the `copySource` SAS token is not validated. Are there any other requirements besides that validation which are missing?

**Comment by XiaoningLiu** [comment]
Glad to see your contribution! There are some scenarios about copy blob.

Scenarios:
1. Copy blob from same account in same Azurite instance;
2. Copy blob from another account in same Azurite instance;
3. Copy blob from another account in another Azurite instance;
4. Copy blob from external accessable URL resource; e.g from publich downloadable resource

Current we only support scenario 1. And the goal here is to support scenario 2.

There are some potential ideas for the implementation.
1. Take scenario 2, 3 & 4 as the same. Azurite sends out HTTP GET request against copySourceURL to download from source. This will be a "real" data copy, while existing async copy blob implementation just copys the metadata reference. It's another topic to maintain the async copy status and scheduling the copy, handle the exceptions when download request aborted.
2. Only support scenario 2 as first step. Check the source blob is under same Azurite instance (by checking it's the same address and port?). Then send out a HEAD/GET request to copySourceURL to validate access without downloading any HTTP payload by checking HTTP status code should be 200. Then copy metadata reference like current implementation. When copying metadata reference some properties should be updated accordingly, such like account name.

Seems idea 2 is more easy to consume.

**Comment by patrickcarnahan** [comment]
I'm happy to do whatever is most helpful. It seems like going the extra mile isn't considerably more work, but I'll start with your suggestion and we can go from there. 

Thanks for this project! Our test runs are much more reliable.
