### ISSUE TITLE
Azurit works with npm cli but not in VS Code

### ISSUE THREAD

**Issue by vkuehn** [Azure/Azurite#542]
### Which service(blob, file, queue, table) does this issue concern?
tested with Blob, probably others too
### Which version of the Azurite was used?
3.8.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm and VS Code
### What's the Node.js version?
v12.18.3
### What problem was encountered?
Work with nmp install but not in VS Code for DOTNET Core. Might be related to issue 
Support using Azurite #1200
### Steps to reproduce the issue?
Dotnet core disconnects from azurite after a view seconds when azurit is installed in VS Code.
Using the same dotnetcore code with azurite installed through npm command  line BlobTrigger works fine fine without any disconnects so far
### Have you found a mitigation/solution?
don't use the VS Code version
FYI
Storage Explorer works with both versions

**Comment by blueww** [comment]
@vkuehn 

As the Storage Explorer works with both versions, it looks not like an Azurite problem.
Would you please share the DOTNET Core code (hide credential), and Azurite configuration?
And better with Azurite debug log when the issue happen.

**Comment by vkuehn** [comment]
@blueww 

here the donetcore code

`namespace WatchStorage
{
    #region Constructor
    public class WatchStorageFunctions
    {
        private ILogger Logger { get; set; }
       
        public WatchStorageFunctions(ILogger<WatchStorageFunctions> logger)
        {
            this.Logger = logger;
        }
        #endregion

        [FunctionName("TaskWatchWebjobs")]
        // Connection = "AzureWebJobsStorage" ist default connection und kann auch weggelassen werden
        public void RunTaskWatchWebjobs([BlobTrigger("azure-webjobs-hosts/{name}", Connection = "AzureWebJobsStorage")]Stream myBlob, string name)
        {
            this.Logger.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
        }
    }
}`

**Comment by blueww** [comment]
@vkuehn 
The program you shared doesn't contain the information need to investigate the issue. Like how you connect to Azurite:  connection string, Uri, port ...., and I also don't see any Storage API is called in the program.

Would you please share how you connected to storage, and the storage API you called. (are they in "BlobTrigger"?)

Besides that, please also share the Azurite configuration, and Azurite debug log for the issue.

**Comment by vkuehn** [comment]
you would config the connection in a config file which does not contain anything else but 

{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}

for the local azurit installation. Interchangeable you would replace the connection string if not in local.settings.json of you VS 2019 Project

**Comment by blueww** [comment]
@vkuehn 
Would you please share the debug log for Azurite when the issue happen?
For VS extension, you can enable "Debug" in the extension setting, then in "Output" tab, choose "Azurite Blob debug", and save the debug log to a file.

Besides that, to repro the issue, would you please share a project that can build and run to repro the issue?

**Comment by vkuehn** [comment]
@blueww I honestly tried to get a better log but failed badly. How to produce a proper log (link to right doc appreciated) !?

**Comment by blueww** [comment]
@vkuehn 
It should be a standard way to show debug log in VS code.
Like following picture:
1. Enable "Debug" in Azurite setting
2. start Azurite Blob service 
3. Choose "Azurite Blob debug" in "Output" Tab
4. Then you can see the debug log in output tab

Please try to repro the issue and share the debug log with us.
Besides that, would you please share a project that can build and run to repro the issue? (Please hide credential if any)

![image](https://user-images.githubusercontent.com/6926193/92444714-de716680-f1e5-11ea-9433-83a21637573e.png)

**Comment by vkuehn** [comment]
meantime it looks like I have no code to reproduce the issue anymore. Also I switched to visual studio and it's embedded storage emulator. 

Thanks for your effort. I will do propper debugging next time !
