### ISSUE TITLE
Debugging Blob Trigger requires starting Azurite Queue Service  

### ISSUE THREAD

**Issue by sjondavey** [Azure/Azurite#554]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
VSCode extension 3.8.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VSCode Extension

### What's the Node.js version?
Not sure

### What problem was encountered?
I have a function that only uses Blobs, no Queues. If I start the Azurite Blob Service only from VSCode (and not the Queue Service), then debugging the function fails with the error message "microsoft.windowsazure.storage: no connection could be made because the target machine actively refused it". If I start the Azurite Queue Service and the Azurite Blob Service then I am able to debug the function.

### Steps to reproduce the issue?
Create a Blob trigger Azure Function that does not make use of queues, from VSCode start the Azurite Blob Service only (not the queue service). Wait for a few seconds and the debug fails with the error above. 

### Have you found a mitigation/solution?
Start Azurite Queue Service even though I am not using queues

**Comment by XiaoningLiu** [comment]
Hi @sjondavey Can you post the question to Azure Function repo? It's not related to azurite.

**Comment by sjondavey** [comment]
Thanks @XiaoningLiu 

I have logged the same issue [here](https://github.com/Azure/Azure-Functions/issues/1716)

**Comment by sjondavey** [comment]
From the 'Functions' thread: 
The blob trigger uses a queue behind the scenes. The binding puts changes in the storage account into a queue, and functions are triggered from that queue.

Here’s a bit more info on this in the docs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=javascript#concurrency-and-memory-usage
