### ISSUE TITLE
use eslint and prettier

### ISSUE THREAD

**Issue by swissarmykirpan** [Azure/Azurite#59]

**Comment by edwin-huber** [comment]
Hi @swissarmykirpan ,
in the core team, we are using VSCode, and this has a JSHint plugin.
I'll add the jshint configuration to the project.

As far as prettier goes :
@pdressel / @pmanlukas / @XiaoningLiu 
Any reason you have not to specify a standard formatting to the code now, and run it through prettier?
So far I just used the vscode defaults, but we can be a bit more stringent wrt. function calls etc.

Thoughts?

**Comment by edwin-huber** [comment]
This is now applied and we are using jshint 😄
