### ISSUE TITLE
Server failed to authenticate the request

### ISSUE THREAD

**Issue by SonOfSardaar** [Azure/Azurite#598]
### Node 14.11

After starting azurite, I tried connecting to it with storage explorer with following options, when I got following response
![image](https://user-images.githubusercontent.com/9803499/96173919-76b6e580-0f20-11eb-9f19-408555abdd03.png)

> Unable to retrieve child resources.
> 
> Details:
> Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
> RequestId:36593d4f-4e5d-4dd5-92bd-e45dae93666d
> Time:2020-10-15T18:42:02.626Z

Here is version of storage emulator 
![image](https://user-images.githubusercontent.com/9803499/96173206-6f430c80-0f1f-11eb-91fd-4ef0b8e618a5.png)

Also, is there a **npm** release available for "table" branch for azurite ?

**Comment by XiaoningLiu** [comment]
Hi @SonOfSardaar, table branch is still under development. Entity querying is not supported yet. Can you enable Azurite debug log by parameter "--debug debug.log" and attached the debug log here?
