### ISSUE TITLE
Latest docker image no longer found

### ISSUE THREAD

**Issue by sindre-nistad** [Azure/Azurite#628]
### Which service(blob, file, queue, table) does this issue concern?
All?

### Which version of the Azurite was used?
`latest`

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
Unknown

### What problem was encountered?
Trying to pull the image from DockerHub, but the `latest` tag was not found.
My exact use-case is with docker-compose, where one of the services uses `mcr.microsoft.com/azure-storage/azureite` as aan image.

```
docker pull mcr.microsoft.com/azure-storage/azureite
Using default tag: latest
Error response from daemon: manifest for mcr.microsoft.com/azure-storage/azureite:latest not found: manifest unknown: manifest tagged by "latest" is not found
```

### Steps to reproduce the issue?
`docker pull mcr.microsoft.com/azure-storage/azureite`

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Typo in docker name. Should "azurite" instead of "azureite".

**Comment by sindre-nistad** [comment]
That solved the issue for me.

Though I thought I had the same problem, after copy/paste [the command in the documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite#install-and-run-the-azurite-docker-image), but that too (now) works as expected.
