### ISSUE TITLE
The response returned in azurite doesn't have requestId field in Append Block operation on append blob 

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/Azurite#631]
**Error Description:**
When use append block operation, the requestId of response returned in Azurite is undefined.

**To Reproduce**
Please run the demo code as following:
```
import {
  BlobServiceClient
} from "@azure/storage-blob";
import * as assert from "assert"

async function main() {
  const blobServiceClient = await BlobServiceClient.fromConnectionString("Azurite-https-connectionString");
  const containerClient = await blobServiceClient.getContainerClient("<container-name>");
  const appendBlobClient = await containerClient.getAppendBlobClient("blob-name");
  await appendBlobClient.create();
  const content = "hello, world";
  const response = await appendBlobClient.appendBlock(content, Buffer.byteLength(content));
  assert.ok(response.requestId);
}

main();
```

**Error track:**
The reason maybe is that the response doesn't include requestId field in Azurite. the response is shown as following:
[https://github.com/Azure/Azurite/blob/master/src/blob/handlers/AppendBlobHandler.ts#L200](https://github.com/Azure/Azurite/blob/master/src/blob/handlers/AppendBlobHandler.ts#L200)
![Screenshot 2020-11-18 152751](https://user-images.githubusercontent.com/20970631/99498566-a723f080-29b2-11eb-85ec-9bdb9e7b0345.png)

**Expected Behavior**
When use append block operation, the requestId of response returned in Azurite is not undefined or null.

@jongio for notification.

**Comment by blueww** [comment]
@zzhxiaofeng
Thanks for raising the issue!
We will evaluate it.

We welcome contribution to Azurite.
It would be great if you could contribute the the fix of this issue.

**Comment by v-xuto** [comment]
azsdk-azurite
