### ISSUE TITLE
Azurite doesn't support Set Access Tier operation on page blob

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/Azurite#642]
**Error Description:**
When use Set Access Tier operation on page blob, Azurite will return an error as following:
![Screenshot 2020-11-19 100127](https://user-images.githubusercontent.com/20970631/99611249-49dd7d00-2a4e-11eb-90b5-440579ad5899.png)

**To Reproduce**
```
import {
 BlobServiceClient, BlockBlobClient, PageBlobClient
} from "@azure/storage-blob";


async function main(){
  const blobServiceClient = await BlobServiceClient.fromConnectionString("DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=https://127.0.0.1:10001/devstoreaccount1;TableEndpoint=https://127.0.0.1:10002/devstoreaccount1;");
  const containerClient=await blobServiceClient.getContainerClient("mycontainer3");
  const pageBlobClient = containerClient.getPageBlobClient("pageblob");
  await pageBlobClient.setAccessTier("hot");
}

main();
```

@jongio for notification.

**Comment by blueww** [comment]
@zzhxiaofeng 
Thanks for raising this issue?
Set tier on page blob, is only supported on premium storage account , see https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-tier.

Azurite is a standard storage account, so it does not support set tier on page blob. (Premium account support page blob, does not support block blob, queue).
If you don't have other comments, would you like to close this issue?

**Comment by v-xuto** [comment]
azsdk-azurite
