### ISSUE TITLE
Support for `UserDelegationKey`

### ISSUE THREAD

**Issue by sanderaernouts** [Azure/Azurite#656]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.9.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v12.16.2
### What problem was encountered?
Trying to generate a SAS using a `TokenCredential` instead of a connection string fails because it requires a user delegation key. Azurit does not (yet) support retrieving a user delegation key.

```
Azure.RequestFailedException : Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues
RequestId:a6cae55a-8b72-48bd-8d2c-357d942bdb9b
Time:2020-12-10T14:15:41.547Z
Status: 500 (Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues)
ErrorCode: APINotImplemented

Headers:
Server: Azurite-Blob/3.9.0
x-ms-error-code: APINotImplemented
x-ms-request-id: a6cae55a-8b72-48bd-8d2c-357d942bdb9b
Date: Thu, 10 Dec 2020 14:15:41 GMT
Connection: keep-alive
Transfer-Encoding: chunked
Content-Type: application/xml
```
### Steps to reproduce the issue?
Invoke `BlobServiceClient.GetUserDelegationKeyAsync(...)`

### Have you found a mitigation/solution?
No, but if there is a different way to configure a static/fake user delegation key that would solve my issue as well.

**Comment by blueww** [comment]
@sanderaernouts

We still not support User delegation SAS in Azurite.
Will evaluate it.

And we welcome contribution to Azurite.

**Comment by kaylumah** [comment]
Any plans on supporting this?, been a while since this issue was raised

**Comment by blueww** [comment]
@kaylumah 

User delegation SAS is in our plan. 
The feature need not only support Get User delegation Key, but also update the SAS validation logic. It will need time.

Would you please share your scenario need this API, this will help our design?

**Comment by kaylumah** [comment]
```csharp
private async Task<Uri> GenerateSasToken(BlobBaseClient blobClient, TimeSpan expiresAfter)
        {
            var dateNow = DateTimeOffset.UtcNow;
            var dateExpiresOn = dateNow.Add(expiresAfter);
            var sasBuilder = new BlobSasBuilder
            {
                BlobContainerName = blobClient.BlobContainerName,
                BlobName = blobClient.Name,
                Resource = "b",
                StartsOn = dateNow,
                ExpiresOn = dateExpiresOn
            };
            sasBuilder.SetPermissions(BlobSasPermissions.Read);
            if (blobClient.CanGenerateSasUri)
            {
                return blobClient.GenerateSasUri(sasBuilder);
            }

            var userDelegationKey = await _blobServiceClient.GetUserDelegationKeyAsync(dateNow, dateExpiresOn);
            var blobUriBuilder = new BlobUriBuilder(blobClient.Uri)
            {
                Sas = sasBuilder.ToSasQueryParameters(userDelegationKey, _blobServiceClient.AccountName)
            };
            return blobUriBuilder.ToUri();
        }
```

I am using C# to generate a token url.

If you use the https connection string (default endpoint protocol etc) it goes in the If CanGenerateSasUri, but if you use token credential for example Azure CLI Credential, you need to get the user key t generate a sas url

**Comment by icottiero** [comment]
From the number of votes on this issue, I can conclude that this is not the most pressing issue, but I would very much appreciate it if this feature was implemented.

I am researching the usage of Managed Identity for accessing Blob Storage - this is something we want to implement on all of our services, but we want to keep the possibility of running our projects locally without the need to connect to the cloud while developing. 

Our currently running version of code that generates a SAS Url was working locally but did not work when deployed on Azure. After some investigation, I came across [this](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-user-delegation-sas-create-dotnet#get-a-user-delegation-sas-for-a-blob) solution from your documentation, which led me to this issue after trying it out locally.

The only solution that comes to mind is to have two different implementations that would run depending on the environment (local & deployed), but I don't want to develop and test locally on some code that will not run when deployed.

Honestly, the lack of possibility to perform this locally is a dealbreaker for our usage of Managed Identity, so it would be a great help to all of us if we can find a way to solve this issue, either by implementing the API or finding a way around this 🙏

**Comment by blueww** [comment]
We already have a PR for User delegation key https://github.com/Azure/Azurite/pull/1753, the PR is being review.

**Comment by blueww** [comment]
The feature is already released in https://github.com/Azure/Azurite/releases/tag/v3.21.0

**Comment by kaylumah** [comment]
Can confirm that this now works, thank you :D

**Comment by devlie** [comment]
@blueww , is there a certain prerequisite for using this API? I checked README and the PR and couldn't find any instruction on how to enable this API. Thanks.

```
Azure.RequestFailedException: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
RequestId:ffdeb1e3-75be-47ad-a9ff-bf2ae7e53b22
Time:2023-01-14T01:19:01.063Z
Status: 403 (Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed

Additional Information:
AuthenticationErrorDetail: Only authentication scheme Bearer is supported

Content:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>AuthenticationFailed</Code>
  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
RequestId:ffdeb1e3-75be-47ad-a9ff-bf2ae7e53b22
Time:2023-01-14T01:19:01.063Z</Message>
  <AuthenticationErrorDetail>Only authentication scheme Bearer is supported</AuthenticationErrorDetail>
</Error>

Headers:
Server: Azurite-Blob/3.21.0
x-ms-error-code: AuthenticationFailed
x-ms-request-id: ffdeb1e3-75be-47ad-a9ff-bf2ae7e53b22
Date: Sat, 14 Jan 2023 01:19:01 GMT
Connection: keep-alive
Keep-Alive: REDACTED
Transfer-Encoding: chunked
Content-Type: application/xml


  Stack Trace: 
ServiceRestClient.GetUserDelegationKeyAsync(KeyInfo keyInfo, Nullable`1 timeout, CancellationToken cancellationToken)
BlobServiceClient.GetUserDelegationKeyInternal(Nullable`1 startsOn, DateTimeOffset expiresOn, Boolean async, CancellationToken cancellationToken)
BlobServiceClient.GetUserDelegationKeyAsync(Nullable`1 startsOn, DateTimeOffset expiresOn, CancellationToken cancellationToken)
```

**Comment by blueww** [comment]
@devlie

This API is used to support Creating a user delegation SAS.  See [details](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas).
The API can only be run with Oauth credential. See how to configure oauth in Azurite: https://github.com/Azure/Azurite#oauth-configuration
