### ISSUE TITLE
Wrong class name in QueueSASAuthenticator.ts

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/Azurite#659]
1.
Section [link](https://github.com/Azure/Azurite/blob/master/src/queue/authentication/QueueSASAuthenticator.ts)
![Screenshot 2020-12-15 101132](https://user-images.githubusercontent.com/20970631/102159172-fe3bb900-3ebd-11eb-9be3-b2a030e2cb6a.png)

Reason:
Wrong class name in Azurite.

Suggestion:
Update to `QueueSASAuthenticator`.

@jongio for notification.

**Comment by XiaoningLiu** [comment]
Thanks for this. We should definitly fix the typo. In the same time, contribution is welcome for anyone here.

**Comment by v-xuto** [comment]
azsdk-azurite

**Comment by trupakufi** [comment]
It should be closed, the problem was already solved.

**Comment by blueww** [comment]
Thanks for the remind! Close as the issue is resolved.
