### ISSUE TITLE
Azurite doesn't support use table service with secondary endpoint to perform operation

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/Azurite#667]
**Error Description:**
Azurite doesn't support use table service with secondary endpoint to perform operation.

**Error Track:**
Azurite lacks process code for the table service with secondary endpoint. Therefore, it doesn't use table service with secondary endpoint to perform operation in Azurite. The process code is shown as following:
[https://github.com/Azure/Azurite/blob/table/src/table/middleware/tableStorageContext.middleware.ts#L188](https://github.com/Azure/Azurite/blob/table/src/table/middleware/tableStorageContext.middleware.ts#L188)
![Screenshot 2021-01-05 093153](https://user-images.githubusercontent.com/20970631/103596418-e1ccf280-4f38-11eb-8a8f-b7ac6dd4b079.png)
The process code for the blob service with secondary endpoint is shown as following:
[https://github.com/Azure/Azurite/blob/master/src/blob/middlewares/blobStorageContext.middleware.ts#L156](https://github.com/Azure/Azurite/blob/master/src/blob/middlewares/blobStorageContext.middleware.ts#L156)
![Screenshot 2021-01-05 093520](https://user-images.githubusercontent.com/20970631/103596691-746d9180-4f39-11eb-8102-e454ab830fd3.png)

**Expected Behavior:**
Azurite support use table service with secondary endpoint to perform operation.

@jongio for notification.

**Comment by XiaoningLiu** [comment]
Thanks @zzhxiaofeng for bringing this up! Added this into Table backlog and do further plan after Batch.

**Comment by v-xuto** [comment]
azsdk-azurite

**Comment by blueww** [comment]
@zzhxiaofeng 
We recently has a fix for secondary in Azurite 3.15.0.
Does the issue still repro with 3.15.0?
If not, would you please close it.

**Comment by zzhxiaofeng** [comment]
@blueww Yeah, the issue has been resolved. I will close the issue right now.
