### ISSUE TITLE
Batch - It will return an error when use submit batch operation on table in Azurite

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/Azurite#677]
**Error Description:**
In Azurite, It will return an error when use submit batch operation on table.
The error is shown as following:
![Screenshot 2021-01-15 181053](https://user-images.githubusercontent.com/20970631/104714541-47eb1e00-5760-11eb-8d38-e2e31c6b9e36.png)

**To Reproduce:**
The demo code is shown as following:
```
import { TableClient } from "@azure/data-tables";

interface Entity {
  partitionKey: string;
  rowKey: string;
  name: string;
  price: number;
  quantity: number;
}

async function main() {
  const tableName = "batch";
  const client = TableClient.fromConnectionString("<Azurite-https-connection-string>", tableName);
  const partitionKey = "somPartition";
  const entities: Entity[] = [
    {
      partitionKey,
      rowKey: "A1",
      name: "Marker Set",
      price: 5.0,
      quantity: 21
    },
    {
      partitionKey,
      rowKey: "A2",
      name: "Pen Set",
      price: 2.0,
      quantity: 6
    },
    {
      partitionKey,
      rowKey: "A3",
      name: "Pencil",
      price: 1.5,
      quantity: 100
    }
  ];
  const batch = await client.createBatch(partitionKey);
  await batch.createEntities(entities);
  const response = await batch.submitBatch();
  console.log(response.subResponses);
}

main();
```

**Error Track:**
In Azurite, the response returned in Azurite doesn't have contentType field. When Azure Sdk handles the response, it will return error.
In Azurite, the response returned in Azurite doesn't have contentType field. 
[https://github.com/Azure/Azurite/blob/table/src/table/handlers/TableHandler.ts#L662](https://github.com/Azure/Azurite/blob/table/src/table/handlers/TableHandler.ts#L662)
![Screenshot 2021-01-15 182518](https://user-images.githubusercontent.com/20970631/104715078-ff803000-5760-11eb-9e70-27649bbc4f3f.png)
When Azure Sdk handles the response returned in Azurite, it will return error without the contentType field.
[https://github.com/Azure/azure-sdk-for-js/blob/46a342ee298ae4b7a213827699bf4f289ed1d9fc/sdk/core/core-http/src/policies/deserializationPolicy.ts#L346](https://github.com/Azure/azure-sdk-for-js/blob/46a342ee298ae4b7a213827699bf4f289ed1d9fc/sdk/core/core-http/src/policies/deserializationPolicy.ts#L346)
![Screenshot 2021-01-15 182929](https://user-images.githubusercontent.com/20970631/104714120-c5faf500-575f-11eb-85d4-82d71977f61d.png)

**Expected Behavior:**
In Azurite, it can submit batch on table successfully.

@jongio for notification.

**Comment by XiaoningLiu** [comment]
Thanks for reporting this! Batch operation is under implementation by @edwin-huber.

**Comment by XiaoningLiu** [comment]
Close this in favor of #493

**Comment by v-xuto** [comment]
azsdk-azurite
