### ISSUE TITLE
Is latest dockerHub tag really a latest version?

### ISSUE THREAD

**Issue by shoter** [Azure/Azurite#679]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
latest image
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub
### What's the Node.js version?
v12.18.3
### What problem was encountered?
I think `mcr.microsoft.com/azure-storage/azurite` does not represent latest version. 
I had bug in my code where `containerClient.ExistsAsync()` was throwing exception when running on old version Azurite when container was empty. After update error was gone.
i was thinking that I was using always latest version of Azurite by specifying image to use as `FROM mcr.microsoft.com/azure-storage/azurite`. But docker's latest azurite branch was not working with my code while local code with updated azurite was.

I used `mcr.microsoft.com/azure-storage/azurite:3.10.0` which seems to be [latest version](https://mcrflowprodcentralus.data.mcr.microsoft.com/mcrprod/azure-storage/azurite?P1=1611085810&P2=1&P3=1&P4=Go%2FwwswIF0zJz4rGBIsjJdXGEXACkMFziOq1rkQ84dM%3D&se=2021-01-19T19%3A50%3A10Z&sig=EA15dcPOtM7wgwOpa3a%2Bi%2B4iHI8wBQ1DIF06HkULZ%2F0%3D&sp=r&sr=b&sv=2015-02-21) and after that it worked flawlessly.

Could you check if latest tag is latest version of Azurite (3.10.0?)?

### Steps to reproduce the issue?

Use `mcr.microsoft.com/azure-storage/azurite` - it is probably not latest image.

### Have you found a mitigation/solution?
Use `mcr.microsoft.com/azure-storage/azurite:3.10.0` instead of default `mcr.microsoft.com/azure-storage/azurite`

**Comment by blueww** [comment]
@shoter 

I just run "docker run -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite"  on a clean machine, and see the latest (3.10.0) will be run.
It might be cause your machine has some cached image. If you clean up the old image, or run with the version number, you can ensure to run the latest image version.

**Comment by shoter** [comment]
@blueww You are completely right.
I always thought that by specifying `:latest` i will always get the latest image. What a weird design choice imo of Docker.

Thank you.
