### ISSUE TITLE
TableStorage returns HTTP 409 instead of 404 when entity not found

### ISSUE THREAD

**Issue by mstrejczek** [Azure/Azurite#687]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.9.0-table-alpha.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
NPM

### What's the Node.js version?
v14.15.4

### What problem was encountered?
When querying for a non-existing entity:
`myCloudTable.execute(TableOperation.retrieve(myEntity.partitionKey, myEntity.rowKey, MyEntity.class))` 

TableStorageException (409 Conflict) is thrown instead of returning a TableResult instance with 404 status code.
The underlying problem is that Azurite returns HTTP 409 instead of HTTP 404.

### Steps to reproduce the issue?
Query for a non-existing entity in an existing table.

### Have you found a mitigation/solution?
Handle TableStorageException(409 Conflict) similarly to 404 result.
It will get problematic if HTTP status codes for other operations diverge from codes returned by Azure Table Storage.

**Comment by blueww** [comment]
@mstrejczek 
We have go through the Azurite table code, not find why 409 is reported.
Would you please give the debug log of Azurite issue on this issue, so we can get more details to investigate this issue?

**Comment by mstrejczek** [comment]
I've updated https://github.com/mstrejczek/azurite-table-test repo to also allow reproducing this issue.
Azurite debug.log attached.
[debug.log](https://github.com/Azure/Azurite/files/5903396/debug.log)

**Comment by blueww** [comment]
@mstrejczek 
Thanks for the details!
The issue has been fixed in PR: https://github.com/Azure/Azurite/pull/622
It should be included in the next Azurite release for table.
