### ISSUE TITLE
TableStorage returns enparseable etag for Insert operation

### ISSUE THREAD

**Issue by mstrejczek** [Azure/Azurite#688]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.9.0-table-alpha.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
NPM

### What's the Node.js version?
v14.15.4

### What problem was encountered?
Insert entity operation fails when using Azure Storage java library.
IllegalArgumentException is thrown from `TableResult.parseETagForTimestamp(String etag)`
Debugger indicates that etag value returned by Azurite was "0x205B6F86DEB6480".

### Steps to reproduce the issue?
Fails every time for me whenever I add an entity to a table.
I use `com.microsoft.azure:azure-storage:8.6.5` library - works fine with Azure Table Storage in the cloud.

### Have you found a mitigation/solution?
Nope

**Comment by blueww** [comment]
@mstrejczek 
Currently the Etag generated from Azurite is a string that only matches etag format, it doesn't contain timestamp.
see code https://github.com/Azure/Azurite/blob/aa6cba7904e0c6e147bf1f932981776a09d7d059/src/common/utils/utils.ts#L50

We welcome contribution.
It would be great if you could help to fix the generate etag function!

**Comment by mstrejczek** [comment]
I've just checked how etag returned by Azure Table Storage looks like and it is something like
`W/"datetime'2021-02-01T10%3A58%3A01.2219993Z'"`
Basically a constant 
`W/"datetime'`
followed by ISO8601 datetime and then followed by another constant:
`"'`
I'll try to put together a PR when I have some time.

**Comment by mstrejczek** [comment]
This ticket can be reproduced with this test app: https://github.com/mstrejczek/azurite-table-test

**Comment by blueww** [comment]
@mstrejczek 
Thanks for the reply!
It would be great if you can raise a PR to fix it.
Please note, as the currently newEtag() if also used by Blob storage in Azurite, would you please write a new function to create etag for table request, and update table APIs to use your new function.
