### ISSUE TITLE
Anyone has experience using Table Storage in Azurite Legacy?

### ISSUE THREAD

**Issue by pghdeveloper** [Azure/Azurite#708]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub
### What problem was encountered?
I recently started looking into Azurite as a local emulator for Cosmos since I have a Mac.  I would like to know what everyone's experience with using Azurite and whenever data gets stored to Cosmos locally, how do you retrieve the data?  I've tried using Azure Data Studio, and DataGrip but there are no Cosmos drivers.

**Comment by edwin-huber** [comment]
Hi,  
Azure Table Storage support is now added to v3, but Azurite is not a Cosmos DB emulator.  
You need to look elsewhere for Cosmos DB.
