### ISSUE TITLE
XMLException on download

### ISSUE THREAD

**Issue by bigpod98** [Azure/Azurite#714]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.11.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
dockerhub
### What's the Node.js version?
unknown should be the one baked in docker image
### What problem was encountered?
System.Xml.XmlException: 'Root element is missing.' on download
### Steps to reproduce the issue?
Download in c# code
### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
@bigpod98 

Please see my comments in https://github.com/Azure/Azurite/issues/718
I can't repro this issue with Azurite 3.11.0 in docker and Azure Storage Explorer 1.18.1.
Please give the debug log, and the detail step to repro it.

**Comment by blueww** [comment]
Close this issue as #718 is also closed, and not Azurite code issue.
