### ISSUE TITLE
Split The README Into Smaller Files

### ISSUE THREAD

**Issue by opticyclic** [Azure/Azurite#716]
The README is nearly 1000 lines long, which makes it very hard to read.

Split it out into separate files for different sections or at the very least add a table of contents.

**Comment by blueww** [comment]
@opticyclic 

Thanks for the suggestion!
We will evaluate it.

**Comment by blueww** [comment]
Raise https://github.com/Azure/Azurite/pull/1064 to add table content for readme.

**Comment by blueww** [comment]
PR https://github.com/Azure/Azurite/pull/1064  is already merged, to add table contents to Readme.
