### ISSUE TITLE
How Do I Create A Container?

### ISSUE THREAD

**Issue by opticyclic** [Azure/Azurite#717]
It doesn't _appear_ to be possible to create a container.

The README talks about using Azure Storage Explorer and a REST API and says that it can create Containers.

If I connect Azure Storage Explorer to Azurite (started with VSCode) there is no right-click option to create a container.
However, if I connect to an Azure Subscription, the storage accounts have the "Create Blob Container" option.

I thought maybe this was a limitation of the Azure Storage Explorer so I thought I would try to do it with the REST API.

There is a big list of supported APIs in the README but no information on how to actually use them.

Please document the process for creating a container, adding blobs etc etc using the Storage Explorer and the REST API.

**Comment by blueww** [comment]
@opticyclic 

It seems the Azure Storage Explorer in VS code doesn't support to connect to a storage account without login Azure account now.

You can use the installed Azure Storage Explorer , you can install it from https://azure.microsoft.com/en-us/features/storage-explorer/

1. After install, choose "Toggle Explorer" -> "Local & Attached" -> "Storage Account", right click on it, and choose "Connect to Azure Storage" as below picture.

![image](https://user-images.githubusercontent.com/6926193/110585354-9f7b9800-81ab-11eb-8ea0-05f2be021b8b.png)

2. in the pops up window, choose "Local storage emulator" in the bottom:
![image](https://user-images.githubusercontent.com/6926193/110585486-d356bd80-81ab-11eb-96a1-3a7fdff3abc5.png)

3. Finish the wizard, normally you don't need to change anything. 

4. You will see a storage account with name like "local-1" under "Storage Account", and expand it, you can see "Blob Container", then right click on "Blob Container" , you can choose "Create Blob container". Input the container name, the container will be created.
![image](https://user-images.githubusercontent.com/6926193/110585908-4f510580-81ac-11eb-994b-1062b61d686c.png)


See more details for Azure Storage explorer https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=windows.

**Comment by opticyclic** [comment]
I think the key info here in the Azure Storage Explorer application, is to right-click on the Blob Containers under "local-1" in "Storage Accounts" and not on the  Blob Containers in "(Attached Containers)".

I probably will end up creating the containers in Azure using Terraform and locally as above, but can you also explain how to do it with the REST API?

Is there an OpenAPI definition?

**Comment by blueww** [comment]
@opticyclic 
You can see the details on create container rest API in https://docs.microsoft.com/en-us/rest/api/storageservices/create-container

As create container already work on your side, I would like to close this issue. Do you have any concern?

**Comment by blueww** [comment]
Close this issue as not get further question from customer.
