### ISSUE TITLE
The query result is incomplete when use Storage Table query entities by page operation in Azurite

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/Azurite#722]
**Error Description:**
The query result is incomplete when use Storage Table query entities by page operation in Azurite.
For example, in following demo, the count of table entities is 20 but actual query result is just 12. The running result is shown as following:
![image](https://user-images.githubusercontent.com/20970631/111589923-72109900-8800-11eb-9b11-a58c0d1c4ada.png)

**To Reproduce:**
The demo code is shown as following:
```
import { odata, TableClient, TableEntity } from "@azure/data-tables"
import { assert } from "chai";

async function main() {
  const client = TableClient.fromConnectionString("<Azurite-https-connectionString>", "test");
  await client.create();
  const listPartitionKey = "listEntitiesTest";

  for (let i = 0; i < 20; i++) {
    await client.createEntity({
      partitionKey: listPartitionKey,
      rowKey: `${i}`,
      foo: "testEntity"
    });
  }

  const totalItems = 20;
  const maxPageSize = 5;
  const entities = client.listEntities<TableEntity<String>>({
    queryOptions: { filter: odata`PartitionKey eq ${listPartitionKey}` }
  });
  let all: TableEntity<String>[] = [];
  for await (const entity of entities.byPage({
    maxPageSize
  })) {
    all = [...all, ...entity];
  }
  assert.lengthOf(all, totalItems);
}

main().catch((err) => {
  console.log(err);
});
```

**Error Track:**
It will receive the maximal row key as the `nextRowKey` in every query by page. The code is shown [here](https://github.com/Azure/Azurite/blob/table/src/table/persistence/LokiTableMetadataStore.ts#L474)
![Screenshot 2021-03-31 155658](https://user-images.githubusercontent.com/20970631/113110570-d0466e80-9239-11eb-8cef-b669bb009169.png)
then, the next query will use `nextRowKey` received from last query as filter to query entities whose row key is more than `nextRowKey`. the process code is shown [here](https://github.com/Azure/Azurite/blob/table/src/table/persistence/LokiTableMetadataStore.ts#L441)
![image](https://user-images.githubusercontent.com/20970631/113113041-76937380-923c-11eb-8f4e-e81de40ece09.png)
Therefore, it can't query entity whose row key is less than `nextRowKey` in next query.

**Expected Behavior:**
The query result is complete when use Storage Table query entities by page operation in Azurite. 

@jongio for notification.

**Comment by edwin-huber** [comment]
Thanks for the issue and repro, I shall take a look.

**Comment by v-xuto** [comment]
azsdk-azurite
