### ISSUE TITLE
Unable to set CORS rules programatically

### ISSUE THREAD

**Issue by kuba-lilz** [Azure/Azurite#731]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.11.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
N/A

### What problem was encountered?
CORS settings are accepted by Azurite with 
`"PUT /devstoreaccount1/?restype=service&comp=properties HTTP/1.1" 202`
message, but when blobs are accessed through browser, then browser fails to display blob and show following error messages

```
Access to image at 'http://localhost:10000/devstoreaccount1/....' from origin 'http://0.0.0.0:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
localhost:10000/devstoreaccount1/... net::ERR_FAILED
```

### Steps to reproduce the issue?
Set blob service properties e.g. with this python code:
```python
cors_rule = azure.storage.common.models.CorsRule(
        allowed_origins=application.config["AZURE_STORAGE"]["APPROVED_CORS_DOMAINS"], allowed_headers="*",
        allowed_methods=["GET"], exposed_headers="*", max_age_in_seconds=100)

access_blob_storage.set_blob_service_properties(
        cors=[cors_rule])
```

then access image blob in browser, loading it into canvas object (or accessing blob with javascript on the browser in in any way)

### Have you found a mitigation/solution?
arafato/azurite:2.6.5 works correctly, so perhaps it could be used as a reference.
arafato/azurite:2.6.5 is badly outdated now, and doesn't work with any recent azure-storage-blob python packages
(see https://github.com/Azure/azure-sdk-for-python/issues/17231), so we really want to switch to recent Azurite container, but can't until this problem is resolved.
This is for development environment of a product that runs on Azure in production, and it's really frustrating that we can't reproduce such a basic functionality in development.

On a side note - this issue was already raised in https://github.com/Azure/Azurite/issues/55, but it was closed with maintainer saying it was resolved.
Well, it wasn't.

![Screen Shot 2021-03-25 at 9 56 51](https://user-images.githubusercontent.com/30581417/112402764-7254eb00-8d50-11eb-8e7c-05242c61e655.png)

**Comment by blueww** [comment]
@kuba-lilz 
Legacy Azurite 2.* won't check CORS rule, so you won't meet this kind of error.

For your error, it looks like the `allowed_origins` is not set correctly in the CORS rule. Would like change it to "*" and see if it works. If it still not work, please share the debug log for Azurite.

**Comment by kuba-lilz** [comment]
@blueww 
Thank you for the suggestion
Using "*" works! So hey, that solves my immediate problem and I can move forward.

Just for reference - in local environment I access my site on "http://0.0.0.0:5000", but neither "http://0.0.0.0:*" nor "0.0.0.0:*" worked for CORS rule with mcr.microsoft.com/azure-storage/azurite:3.11.0.
I would think these are correct inputs, am I wrong?

**Comment by blueww** [comment]
@kuba-lilz 
You might can try replace 0.0.0.0 with127.0.0.1 in allowed_origins.

Besides that, as your scenarios works now, I would like to close this issue. 
Feel free to contact us again if you need any further support for Azurite.
