### ISSUE TITLE
The table batch entity response returned in Azurite doesn't have the property rowkey

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/Azurite#738]
**Error Description:**
The table batch entity response returned in Azurite doesn't have the property `rowkey`.

**To Reproduce:**
The demo code is shown as following:
```
import { TableClient, TablesSharedKeyCredential } from "@azure/data-tables"
import * as assert from "assert"

const partitionKey = "batchTest";
const testEntities = [
  { partitionKey, rowKey: "1", name: "first" },
  { partitionKey, rowKey: "2", name: "second" },
  { partitionKey, rowKey: "3", name: "third" }
];

async function main() {
  const tableClient = new TableClient(
    "<Azurite-table-endpoint>",
    "<table-name>",
    new TablesSharedKeyCredential("<Azurite-account-name>", "<Azurite-account-key>")
  );
  await tableClient.create();
  const batch = tableClient.createBatch(partitionKey);
  await batch.createEntities(testEntities);
  const result = await batch.submitBatch();
  assert.ok(result.subResponses[0].rowKey);
  await tableClient.delete();
}

main().catch((err) => {
  console.log(err);
});
```

**Error Track:**
The `rowkey` of table batch entity response returned in Azurite can't be handled by Azure SDK.
The table batch entity response use `%27` instead of `'` to wrap the `rowkey`, then the Azure SDK can't handle this. So the response dealt with by Azure SDK doesn't have property `rowkey`.
The code about table batch entity response  use `%27` to wrap the `rowkey` in Azurite is [here](https://github.com/Azure/Azurite/blob/table/src/table/batch/TableBatchSerialization.ts#L549)
![Screenshot 2021-03-31 110558](https://user-images.githubusercontent.com/20970631/113084734-2e129080-9211-11eb-8f1c-be296386a3a8.png)
The code about response process code in Azure SDK is [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/tables/data-tables/src/TableBatch.ts#L214)
![Screenshot 2021-03-31 134216](https://user-images.githubusercontent.com/20970631/113095933-f9a9cf00-9226-11eb-84a3-3edb4cb15907.png)

**Expected Behavior:**
The table batch entity response returned in Azurite have the property `rowkey`.

@jongio for notification.

**Comment by edwin-huber** [comment]
need to add tests that also use @azure\data-tables

**Comment by v-xuto** [comment]
azsdk-azurite
