### ISSUE TITLE
It can't catch the error "TableNotFound" returned in Azurite when use a non-existing table to perform batch operation

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/Azurite#739]
**Error Description:**
In Azure, it will return error `TableNotFound` when use a non-existing table to perform batch operation.
But in Azurite, the error can't be caught.
Azure error is shown as following:
![image](https://user-images.githubusercontent.com/20970631/113099287-4cd25080-922c-11eb-82f0-2c74b097c13c.png)

**To Reproduce:**
The demo code is shown as following:
```
import { TableClient, TablesSharedKeyCredential } from "@azure/data-tables"

const partitionKey = "batchTest";
const testEntities = [
  { partitionKey, rowKey: "1", name: "first" },
  { partitionKey, rowKey: "2", name: "second" },
  { partitionKey, rowKey: "3", name: "third" }
];

async function main() {
  const tableClient = new TableClient(
    "<Azurite-table-endpoint>",
    "noExistingTable",
    new TablesSharedKeyCredential("<Azurite-account-name>", "<Azurite-account-key>")
  );
  const batch = tableClient.createBatch(partitionKey);
  await batch.createEntities(testEntities);
  try {
    await batch.submitBatch();
  } catch (err) {
    console.log(err);
  }
}

main();
```

**Error Track:**
The error response of method `submitBatch` returned in Azurite can't be handled by Azure SDK.
Azure SDK process code is [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/tables/data-tables/src/TableBatch.ts#L185)
![Screenshot 2021-03-31 143804](https://user-images.githubusercontent.com/20970631/113101022-c66b3e00-922e-11eb-95ad-ca0cec6758de.png)
The `subResponses` is null array because `batchResponse.bodyAsText` just have the error without other response body. It is shown as following:
![Screenshot 2021-03-31 145453](https://user-images.githubusercontent.com/20970631/113102848-24008a00-9231-11eb-88dd-b05204214faa.jpg)
In Azure, the `batchResponse.bodyAsText` is shown as following:
![image](https://user-images.githubusercontent.com/20970631/113102662-e8fe5680-9230-11eb-8223-33bfde229ddd.png)

**Expected Behavior:**
It can catch the error "TableNotFound" returned in Azurite when use a non-existing table to perform batch operation.

@jongio for notification.

**Comment by edwin-huber** [comment]
resolved with preview of table api

**Comment by v-xuto** [comment]
azsdk-azurite
