### ISSUE TITLE
[Logic Apps] Format of eTag returned in PUT entity API is different than Azure storage

### ISSUE THREAD

**Issue by laveeshb** [Azure/Azurite#743]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
Latest from `table` branch (b188272ed79f711f40fbc6f39d3defb8ecc1ec19)

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Local `npm` build. Please see above.

### What's the Node.js version?
v14.16.0

### What problem was encountered?
The eTag returned by the API to create or update an entity in table is different than storage.

I am skipping the request content for brevity.

`Azure storage`
```
Request
PUT https://laveeshbazurite01.table.core.windows.net/testjobdefinitions(PartitionKey='EF800',RowKey='SequencerJobsCIT_5939B31DE58743EB9C92531A0980AFE4-A')?sv=2018-03-28&sig=*sanitized*

Response
HTTP/1.1 204 No Content
Cache-Control: no-cache
Content-Length: 0
ETag: W/"datetime'2021-04-06T21%3A03%3A31.9231271Z'"
Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: b6d10273-9002-003d-3628-2b91da000000
x-ms-version: 2018-03-28
X-Content-Type-Options: nosniff
Date: Tue, 06 Apr 2021 21:03:31 GMT
```

`Azurite`

```
Request
PUT http://127.0.0.1:10002/devstoreaccount1/testjobdefinitions(PartitionKey='EF800',RowKey='SequencerJobsCIT_2BF96E88A1E048F5AF1323F7768400CE-system%3A2Efirst')?sv=2018-03-28&sig=*sanitized*

Response
HTTP/1.1 204 No Content
Server: Azurite-Table/3.9.0-table-alpha.1
x-ms-request-id: 3ba01a85-2f66-4972-a9de-a28aa1f5e6aa
x-ms-version: 2019-12-12
date: Tue, 06 Apr 2021 21:23:08 GMT
etag: W/"datetime'2021-04-06T21:23:08.1040000Z'"
Connection: keep-alive
Keep-Alive: timeout=5
```

eTag returned by Azure storage is `W/"datetime'2021-04-06T21%3A03%3A31.9231271Z'"`. However, eTag returned by Azurite is `W/"datetime'2021-04-06T21:23:08.1040000Z'"`
Azure storage is escaping the separator in the timestamp.

I haven't tested POST API; when you fix this one, could you check that as well?

### Steps to reproduce the issue?
Please see above.

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
Raise a PR to fix it: https://github.com/Azure/Azurite/pull/744
