### ISSUE TITLE
Table query on Int64 field using 'L' suffix does not find entity

### ISSUE THREAD

**Issue by tmcgannon** [Azure/Azurite#755]
### Which service(blob, file, queue, table) does this issue concern?

Table

### Which version of the Azurite was used?

3.11.0-table-alpha.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Cloned repo from Github

### What's the Node.js version?

14.15.4

### What problem was encountered?

Table query on Int64 property using L suffix does not find rows.

### Steps to reproduce the issue?

1. In Storage Explorer, insert entity with Int64 field ('Int64Field')

<img width="702" alt="image" src="https://user-images.githubusercontent.com/2172012/115098951-a5614900-9ece-11eb-976b-59feffd001e4.png">

2. In Storage Explorer, use query tool to create a query that includes Int64Field using the 'L' suffix.  Entity will not be found.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/2172012/115099019-10128480-9ecf-11eb-980f-694cdabfad66.png">

3. In Storage Explorer, use query tool to create a query. This time, query the Int64Value field as if it were a string.  Entity is found.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/2172012/115099038-291b3580-9ecf-11eb-93cd-6c0231bdf0b3.png">

This works in Azure Table Services.

### Have you found a mitigation/solution?

No

**Comment by edwin-huber** [comment]
Pending PR to address this.
