### ISSUE TITLE
Unable to access the blob storage files from Apache spark. 

### ISSUE THREAD

**Issue by rkworkzone** [Azure/Azurite#757]
### Which version of the Azurite was used?
latest version 3.x.x
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Docker
### What's the Node.js version?
Trying to access it from Apache spark
### What problem was encountered?
Unable to read the files
### Steps to reproduce the issue?

Step 1: Set up anaconda databricks environment. (spark 3.0) 
           conda env list
           conda create --name databricks python=3.7
           conda activate databricks
           pip install pyspark
Step 2: 
          install docker
         docker pull mcr.microsoft.com/azure-storage/azurite
         docker run -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite
         docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0
          

Step 3: Run the following in pyspark shell. 
   spark = SparkSession.Builder().appName("abc").master("local[4]").getOrCreate()
    conf = spark.sparkContext._jsc.hadoopConfiguration()
    conf.set("fs.wasbs.impl", "org.apache.hadoop.fs.azure.NativeAzureFileSystem")
    spark.conf.set('fs.azure.account.key.jimtestdiag924.blob.core.windows.net', '')
    # AccountName=devstoreaccount1;AccountKey=Eby8vdM01OUzFT50uSRZ6IFsuFq2UVErtq/K1SZFOtr/KBHBeksMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
    blob_account_name = "devstoreaccount1"
    blob_container_name = "input"
    blob_relative_path = ""
    blob_sas_token = ""

    wasbs_path = 'http://127.0.0.1:10000/devstoreaccount1'
    #wasbs_path = 'wasb://127.0.0.1:10000/devstoreaccount1'
    spark.conf.set('fs.azure.sas.%s.%s.blob.core.windows.net' % (blob_container_name, blob_account_name), blob_sas_token)
    print('Remote blob path: ' + wasbs_path)

    df = spark.read.csv(wasbs_path+"/input/ProductListPriceHistory.csv", inferSchema=True, header=True)
    print('Register the DataFrame as a SQL temporary view: source')
    df.show()

    # COMMAND ----------

### Have you found a mitigation/solution?
NO

**Comment by blueww** [comment]
@rkworkzone 
I can successfully connect to the Azurite start with the same way as you, with other SDK.

I am not so family with Python SDK, but from your code, there seems at least 2 issues:
1. the Blob endpoint should be "http://127.0.0.1:10000/devstoreaccount1", I see your code has "blob.core.windows.net'" which will not work.
2. the account key is not correct (if you have not changed it in Azurite), see the correct key in: https://github.com/Azure/Azurite#default-storage-account

**Comment by blueww** [comment]
@rkworkzone
I will close the issue since not get responds from you for a long time.
Feel free to contact us again if need any further assistance for Azurite.
