### ISSUE TITLE
Python BlobStorage V12 SDK Bad Request for list_containers

### ISSUE THREAD

**Issue by Exitare** [Azure/Azurite#760]
### Which service(blob, file, queue, table) does this issue concern?
I am using the blob storage functionality.

### Which version of the Azurite was used?
V. 3.11

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Azurite globally installed using npm.

### What's the Node.js version?
Node.js version v14.16.1

### What problem was encountered?
Using the [library](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python) provided by microsoft, one can use the function list_containers() to list all available containers in azure. Calling the same function with azurite results in a Bad Request error.

I am using the default devaccount1. No modifications whatsoever. 

Azurite Console Output:
`127.0.0.1 - - [20/Apr/2021:00:56:55 +0000] "GET /devstoreaccount1/?comp=list&include= HTTP/1.1" 400 -`

On the python side, I get this error:

`azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'`

I checked other functionality using the provided connection string, and everything checks out. For example creating containers. 
It's just this function which errors out.

### Steps to reproduce the issue?

The bare minimum would be:

```
from azure.storage.blob import BlobServiceClient

 connection_string = "yourconnectionstringhere"
 blob_service_client = BlobServiceClient.from_connection_string(connection_string)

 for container in blob_service_client.list_containers():
        print(container.name)


```

### Have you found a mitigation/solution?
No solutions so far.

**Comment by blueww** [comment]
@Exitare 
Would you please share the debug log for Azurite, we need it to investigate the issue?

**Comment by Exitare** [comment]
[debug.log](https://github.com/Azure/Azurite/files/6344548/debug.log)

**Comment by blueww** [comment]
@Exitare 

For the debug log, we see "Error:  is not a valid value for include."
And the request URI is "http://127.0.0.1/devstoreaccount1/?comp=list&include= ", there are no value for the include query parameter.

Per https://docs.microsoft.com/en-us/rest/api/storageservices/list-containers2, "Include" is used by "Specifies one or more datasets to include in the response:" But your request specify no dataset.

Would you please please add a value to include like "include=metadata", or remove "include=", and see if your request will success?

**Comment by Exitare** [comment]
I am not sure how to do that, as the function "list_containers()" works as is for the azure cloud instance. It returns all containers associated to the connection string (Blob storage)

**Comment by blueww** [comment]
@Exitare
Per the following doc, you can just list container with `blob_service_client.list_containers(include_metadata=True)`, to include metadata.
https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobserviceclient?view=azure-python#list-containers-name-starts-with-none--include-metadata-false----kwargs-

**Comment by Exitare** [comment]
Oh yeah... 
I am sorry. Yes this fixed the issue. My bad :/

**Comment by campbellr** [comment]
I'm running into this same issue (although I'm using `azure-storage-blob-go`) and stumbled upon this ticket.

While the workaround *technically* works, it's not great, because the behaviour of azurite isn't consistent with the behaviour of azure blob storage, since `include=` works just fine against a real storage account.

**Comment by blueww** [comment]
@campbellr 

We will use https://github.com/Azure/Azurite/issues/813 to follow up this issue. 
"include=" with no include option is not aligned with [rest API doc](https://docs.microsoft.com/en-us/rest/api/storageservices/list-containers2), so would you like to open an issue for Go SDK and see if Go SDK can fix it.

**Comment by campbellr** [comment]
Oh, I'm not sure how I missed that other issue, thanks.

> so would you like to open an issue for Go SDK and see if Go SDK can fix it.

I'll do that, thanks.

**Comment by blueww** [comment]
Thanks @campbellr !
Please add the Go SDK issue link to this issue or #813 after you open it.
