### ISSUE TITLE
CPU OVER LOAD

### ISSUE THREAD

**Issue by Darkstar1t** [Azure/Azurite#762]

**Comment by Darkstar1t** [comment]
[](url)

**Comment by blueww** [comment]
@Darkstar1t

Please give more details for how you repro this, by follow up the issue template.
It's better can also share Azurite debug log with the issue.

**Comment by blueww** [comment]
@Darkstar1t
We don't receive your responds for this incident for > 7 days.
So close it.

Feel free to contact us again if you need any further assistance on Azurite.
