### ISSUE TITLE
[Table] Insert duplicate entity returns 'EntityAlreadyExist' code. Should be 'EntityAlreadyExists'.

### ISSUE THREAD

**Issue by tmcgannon** [Azure/Azurite#764]
### Which service(blob, file, queue, table) does this issue concern?

Table

### Which version of the Azurite was used?

3.11.0-table-alpha.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Cloned repo from Github

### What's the Node.js version?

14.15.4

### What problem was encountered?

When inserting a duplicate entity, the HTTP result code is 409 but the Azure error code is 'EntityAlreadyExist' as constructed in src/table/errors/StorageErrorFactory.ts getEntityAlreadyExist().  However, in the Azure Table Service documentation https://docs.microsoft.com/en-us/rest/api/storageservices/table-service-error-codes, it clearly states that the error code should be 'EntityAlreadyExists'

### Steps to reproduce the issue?

Insert same row twice

### Have you found a mitigation/solution?

no.

**Comment by edwin-huber** [comment]
thanks for the heads up.
Merge is pending.
