### ISSUE TITLE
[Logic Apps] Azurite VS code extension does not start table service

### ISSUE THREAD

**Issue by laveeshb** [Azure/Azurite#772]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
3.12.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code extension

### What's the Node.js version?
v14.15.0

### What problem was encountered?
On starting Azurite from VS code extension, only blob and queue service get started, not table.
In v3.12.0, support for table service has been added at runtime. Could you make sure VS code extension also starts all the services?

### Steps to reproduce the issue?
Please see above.

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
I can start Azurite from the cmd line.

**Comment by blueww** [comment]
The fix has released in Azurite 3.13.0
