### ISSUE TITLE
XML Parsing Error

### ISSUE THREAD

**Issue by HjalmarAtBMW** [Azure/Azurite#773]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
latest docker container as of 30-Apr-2021

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
Not sure, it's in the container

### What problem was encountered?
.NET SDK BlobContainerClient.Exists() throws an exception System.Xml.XmlException: 'Reference to undeclared entity 'nbsp'. Line 5, position 18.'

### Steps to reproduce the issue?
call BlobContainerClient.Exists() with any container name, non-existing or existing.
Strangely, this worked with the same container and code a couple of days ago. No change related to this as far as I can recall.

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
StackTrace:

  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at System.Xml.XmlTextReaderImpl.Throw(Exception e)\r\n   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)\r\n   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)\r\n   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)\r\n   at System.Xml.XmlTextReaderImpl.ParseText()\r\n   at System.Xml.XmlTextReaderImpl.ParseElementContent()\r\n   at System.Xml.XmlTextReaderImpl.Read()\r\n   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)\r\n   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)\r\n   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)\r\n   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)\r\n   at Azure.Storage.Blobs.BlobRestClient.Container.GetPropertiesAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)\r\n   at Azure.Storage.Blobs.BlobRestClient.Container.<GetPropertiesAsync>d__3.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()\r\n   at Azure.Storage.Blobs.BlobContainerClient.<ExistsInternal>d__70.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)\r\n   at Azure.Storage.Blobs.BlobContainerClient.Exists(CancellationToken cancellationToken)\r\n   at FileProvider.AzureBlob.FileProviderAzureBlob.ConnectIfNecessary(String path, Boolean createContainerIfNotExist, CancellationToken cancellationToken) in...

```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
Nope

**Comment by HjalmarAtBMW** [comment]
One more note: This issue is specific to the .NET Nuget Package Azure.Storage.Blobs v12.8.3.
Azurite works fine using the Storage Emulator 1.19.1
I have not tried it in other languages.

**Comment by HjalmarAtBMW** [comment]
BTW, the reason for opening the issue here is because with the 'real' Azure Storage Account Blobs this issue is not present

**Comment by edwin-huber** [comment]
Hi,  
thanks for raising the issue.  
Could you perhaps provide a debug log of the issue occurring?

**Comment by HjalmarAtBMW** [comment]
Apologies for never getting the logs to you.
I retested this with the 3.13.1 image and the issue has been resolved.
Many thanks !
