### ISSUE TITLE
azurite 3.12.0: No connection could be made because the target machine actively refused it (127.0.0.1:50210)

### ISSUE THREAD

**Issue by sanderaernouts** [Azure/Azurite#777]
### Which service(blob, file, queue, table) does this issue concern?
`blob`
### Which version of the Azurite was used?
`3.12.0`
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
`npm`
### What's the Node.js version?
`v12.16.2`
### What problem was encountered?
We use azurite in our unit tests, after updating to `3.12.0` tests started to fail with this error:
Error Message:
   System.AggregateException : Retry failed after 6 tries. (No connection could be made because the target machine actively refused it. (127.0.0.1:50210)) (No connection could be made because the target machine actively refused it. (127.0.0.1:50210)) (No connection could be made because the target machine actively refused it. (127.0.0.1:50210)) (No connection could be made because the target machine actively refused it. (127.0.0.1:50210)) (No connection could be made because the target machine actively refused it. (127.0.0.1:50210)) (No connection could be made because the target machine actively refused it. (127.0.0.1:50210))
  ----> Azure.RequestFailedException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> Azure.RequestFailedException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> Azure.RequestFailedException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> Azure.RequestFailedException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> Azure.RequestFailedException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> Azure.RequestFailedException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
  ----> System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
  ----> System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
  ----> System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
  ----> System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
  ----> System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (127.0.0.1:50210)
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.

### Steps to reproduce the issue?
1. upgrade to `3.12.0`
2. run tests

### Have you found a mitigation/solution?
Pin version to `3.11.0`

**Comment by edwin-huber** [comment]
Hi,
I notice that you are trying to connect to a non-standard tcp port:
```
127.0.0.1:50210
```
Could you perhaps share a little more information about how your tests are configured?
Thanks!

**Comment by sanderaernouts** [comment]
We start Azurite from C# using the following parameters `<azurite> --oauth basic -l <tempdirectory> --blobPort 0 --queuePort 0 --cert cert.pem --key cert.pem --skipApiVersionCheck`. If I remember correctly this will make Azurite pick the next free port. Our tests can run in parallel so we can have multiple Azurite processes running side by side each on a separate set of ports and using a separate temp directory.

**Comment by edwin-huber** [comment]
As the latest release includes table API, you might need to add ```--tablePort 0``` to your configuration, as otherwise multiple instances of Azurite will conflict.

**Comment by XiaoningLiu** [comment]
Thanks @edwin-huber!

**Comment by sanderaernouts** [comment]
Thanks @edwin-huber , adding `--tablePort 0` fixed it.
