### ISSUE TITLE
HTTP headers not in the correct format when using Azure.Storage.Blobs v12.8.x

### ISSUE THREAD

**Issue by lyallguiney** [Azure/Azurite#797]
### Which service(blob, file, queue, table) does this issue concern?

Blob.

### Which version of the Azurite was used?

Pulled from master on 2021-05-31, version 3.9.0.

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Run with npm having pulled from Github.

### What's the Node.js version?

v10.15.3

### What problem was encountered?

When I try to connect to a Blob storage container, an exception is thrown (below). This only occurs when using Azure.Storage.Blobs nuget package greater than v12.7.0. The issue does not occur with v12.7.0.

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (The value for one of the HTTP headers is not in the correct format.
RequestId:25352f9e-abaf-44bd-bdc7-eb538bc842f8
Time:2021-05-31T12:28:36.521Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Additional Information:
HeaderName: x-ms-version
HeaderValue: 2020-04-08

Headers:
Server: Azurite-Blob/3.9.0
x-ms-error-code: InvalidHeaderValue
x-ms-request-id: 25352f9e-abaf-44bd-bdc7-eb538bc842f8
Date: Mon, 31 May 2021 12:28:36 GMT
Connection: keep-alive
Transfer-Encoding: chunked
Content-Type: application/xml
)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at OddsFactory.Propaganda.Infrastructure.Blob.DelayedMessageArchive..ctor(ILogger logger, IStorageAccountConfiguration config, IBlobSerializer serializer) in C:\Code\OddsFactory.Propaganda\src\OddsFactory.Propaganda.Infrastructure.Blob\DelayedMessageArchive.cs:line 44

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
RequestFailedException: The value for one of the HTTP headers is not in the correct format.
RequestId:25352f9e-abaf-44bd-bdc7-eb538bc842f8
Time:2021-05-31T12:28:36.521Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Additional Information:
HeaderName: x-ms-version
HeaderValue: 2020-04-08

Headers:
Server: Azurite-Blob/3.9.0
x-ms-error-code: InvalidHeaderValue
x-ms-request-id: 25352f9e-abaf-44bd-bdc7-eb538bc842f8
Date: Mon, 31 May 2021 12:28:36 GMT
Connection: keep-alive
Transfer-Encoding: chunked
Content-Type: application/xml

### Steps to reproduce the issue?

Install Azure.Storage.Blobs v12.8.x, and write any code that tries to write to access the blob emulator.

Example:

```
var blobClient = new BlobServiceClient(/* connection string */);
var container = blobClient.GetBlobContainerClient(/* container name */);
container.CreateIfNotExistsAsync().Wait(); // throws exception
```

### Have you found a mitigation/solution?

Lock the Azure.Storage.Blobs package to v12.7.0

**Comment by blueww** [comment]
@lyallguiney 
Would you please share the Azurite debug log for this failed request?
It looks some new header in 12.8.0 is still not supported by Azurite, but we need the debug log to get the details.

**Comment by lyallguiney** [comment]
Ah, apologies. Yes, updating to the latest Azurite version works. I thought I had pulled and re-built the code, but evidently not. :(

All good, thanks! :)

**Comment by blueww** [comment]
@lyallguiney 

It's good to know your issue is resolved.
I will close the issue.

Feel free to contact us again if you need any further assistance of Azurite.
