### ISSUE TITLE
Blob Storage: Add support for Account SAS

### ISSUE THREAD

**Issue by arafato** [Azure/Azurite#8]
See https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-an-account-sas for specification.

**Comment by edwin-huber** [comment]
This is also required for supporting the .Net storage samples.
Currently some of the later SAS storage calls are failing, still needs debugging and resolving.

**Comment by XiaoningLiu** [comment]
Close this as this has been supported in V3.
