### ISSUE TITLE
Multi-storage account clarification

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/Azurite#837]
### Which version of the Azurite was used?

Version 3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What problem was encountered?

The [documentation](https://github.com/Azure/Azurite#customized-storage-accounts--keys-1) does not elaborate on details when multi-storage accounts are used. It shows how to define Azurite accounts and keys and then [later states](https://github.com/Azure/Azurite#storage-accounts)
> Please reach to us or open issues if you need multi storage account support.

I'd like to understand the following - given the following configuration
> set AZURITE_ACCOUNTS="account1:key1:key2;account2:key1:key2"

1. What will be the connection strings generated for those accounts?
1. Can those be hosted using the same docker container? And if yes, how would that work, given the same port number/host.

**Comment by XiaoningLiu** [comment]
1. One account one connection string. Replace account name and key from the default connection string.
2. Multi storage accounts can be hosted in same docker container, same port and host.

**Comment by SeanFeldman** [comment]
To clarify, for a single docker container with the following environment variable set

> set AZURITE_ACCOUNTS="account1:key1:key2;account2:key1:key2"

The two connection strings will be 

> DefaultEndpointsProtocol=http;AccountName=account1;AccountKey=key1;
BlobEndpoint=http://127.0.0.1:10000/account1;QueueEndpoint=http://127.0.0.1:10001/account1;TableEndpoint=http://127.0.0.1:10002/account1;

and 

> DefaultEndpointsProtocol=http;AccountName=account2;AccountKey=key2;
BlobEndpoint=http://127.0.0.1:10000/account2;QueueEndpoint=http://127.0.0.1:10001/account2;TableEndpoint=http://127.0.0.1:10002/account2;

Correct?

**Comment by SeanFeldman** [comment]
@XiaoningLiu I've tried to run the container using

> docker run -d -p 10010:10000 -p 10011:10001 -p 10002:10002 -e AZURITE_ACCOUNTS="account1:key1:key2;account2:key1:key2" -v c:/azurite-multi:/data --name azurite_multi-account mcr.microsoft.com/azure-storage/azurite

And while can connect to the emulated storage accounts using Storage Explorar, any attempt to create a container fails with the following error:

> Failed to create blob container 'test': Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Comment by XiaoningLiu** [comment]
Please enable azurite debug log and share here, we can take a look.

**Comment by SeanFeldman** [comment]
Please see [debug.log](https://github.com/Azure/Azurite/files/6675203/debug.log)

**Comment by SeanFeldman** [comment]
@XiaoningLiu, were you able to determine anything from the log file?

I was looking for any information on setting up a multi-storage account Azurite and couldn't find anything (except the already mentioned information in the README.md).

**Comment by XiaoningLiu** [comment]
Hi @SeanFeldman The request to Azurite is using account devstoreaccount1 instead of account 1


RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1?restype=account&comp=properties RequestHeaders:{"x-ms-version":"2019-07-07","user-agent":"Microsoft Azure Storage Explorer, 1.19.1, win32 azsdk-js-storageblob/12.4.1 (NODE-VERSION v12.16.3; Windows_NT 10.0.19043)","x-ms-client-request-id":"7a0503b0-a6e5-45b9-93ee-259830762dbc","x-ms-date":"Fri, 18 Jun 2021 07:01:50 GMT","authorization":"SharedKey devstoreaccount1:FeqZr7Wg3Aec/cIUnuxV2BhsdNSbNhqrN2BN7DCPHRo=","cookie":"","accept":"*/*","host":"127.0.0.1:10000","connection":"keep-alive"} ClientIP=192.168.80.1 Protocol=http HTTPVersion=1.1

**Comment by SeanFeldman** [comment]
@XiaoningLiu, yes. And that's while the Storage Explorer was explicitly instructed to connect to account1/key1 account. Was my [connection string](https://github.com/Azure/Azurite/issues/837#issuecomment-863804749) incorrect?

**Comment by SeanFeldman** [comment]
I've double-checked how the container is created and can't see anything different from the instructions.

Here's my `docker-compose.yml` I've used to create the container:

```yml
version: '3.4'

services:
  azurite_multi-account:
    environment:
      - AZURITE_ACCOUNTS=account1:key1:key2;account2:key1:key2
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite_multi-account
    volumes:
      - "c:/azurite-multi:/workspace"
    command: "azurite --location /workspace --debug /workspace/debug.log --loose --skipApiVersionCheck --silent --blobPort 10000 --blobHost 0.0.0.0 --queuePort 10001 --queueHost 0.0.0.0 --tablePort 10002 --tableHost 0.0.0.0"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
```

While the Azurite container starts up, I cannot access either of the accounts from Storage Explorer. The container has the necessary `AZURITE_ACCOUNTS` environment variable set, and yet the log contains `info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1?restype=account&comp=properties` when trying to access it from the Storage Explorer.

I've also tried the latest Storage .NET SDK using the connection string I've shared [earlier](https://github.com/Azure/Azurite/issues/837#issuecomment-863774312)
```c#
var client = new BlobServiceClient("DefaultEndpointsProtocol=http;AccountName=account1;AccountKey=key1;BlobEndpoint = http://127.0.0.1:10000/account1;QueueEndpoint=http://127.0.0.1:10001/account1;TableEndpoint=http://127.0.0.1:10002/account1;");
await client.CreateBlobContainerAsync("test");
```

and that also throws:
```
No valid combination of account information found.<br>
  at Azure.Storage.StorageConnectionString.<>c.<Parse>b__67_0(String err)
  at Azure.Storage.StorageConnectionString.ParseCore(String connectionString, StorageConnectionString&amp; accountInformation, Action`1 error)
  at Azure.Storage.StorageConnectionString.Parse(String connectionString)
  at Azure.Storage.Blobs.BlobServiceClient..ctor(String connectionString, BlobClientOptions options)
  at Azure.Storage.Blobs.BlobServiceClient..ctor(String connectionString)
```

@XiaoningLiu, is there a sample project on GitHub that executes multi-account Azurite I could use as a reference? At this point, I'm not sure if I'm doing something wrong or it's just not working OOTB. Thank you.

**Comment by SeanFeldman** [comment]
Quick update -- I have pulled an updated Docker image with Azurite version 13.3.1 and this issue is gone. The previous image had 13.0.1. Looking at the [releases](https://github.com/Azure/Azurite/releases), [13.3.0](https://github.com/Azure/Azurite/releases/tag/v3.13.0) is the last release made 20 days ago. The Docker image with 13.3.1 was released 19 days ago. So whatever was done in 13.3.1 has fixed the issue except I can't see the changelog as it's not public. I can't roll back the image to the 13.3.0 tag as it seems to be not available in order to confirm that 13.3.1 has addressed the issue. From the log file, I've seen that the issue was handling a request with a dollar sign in a container name made by the Storage Explorer and Azurite failing on that. @XiaoningLiu I'd love you to confirm or clarify what has changed and wherever that was the blocking issue or not. Thank you.

**Comment by SeanFeldman** [comment]
Officially, 13.3.1 got released today https://github.com/Azure/Azurite/releases/tag/v3.13.1

Somewhat frustrating TBH to waste so much time and see no confirmation of what happened. Glad to see multi-account working now.

**Comment by Cogax** [comment]
This issue again exists in `3.14.3`. I was able to reproduce it with that version. When I use `3.13.1` as mentioned from @SeanFeldman, it works.

**Comment by SeanFeldman** [comment]
Thank you for posting here, @Cogax. This is quite frustrating, especially when it's a regression bug.
