### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by JCARLOSRP** [Azure/Azurite#841]
- Issue Type: `Performance`
- Extension Name: `azurite`
- Extension Version: `3.12.0`
- OS Version: `Windows_NT ia32 10.0.19042`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\carlo\AppData\Local\Temp\Azurite.azurite-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by edwin-huber** [comment]
Hi,
can you attach the text file to this issue?
You can usually do this by dragging the file to the comment area in GitHub on this issue.

thanks!

**Comment by edwin-huber** [comment]
Hi,
as there has been no response after 23 Days, I shall close this for now.
Please feel free to re-open if you still need assistance.
