### ISSUE TITLE
Unable to start in HTTPS in docker container

### ISSUE THREAD

**Issue by bendanye** [Azure/Azurite#843]
### Which version of the Azurite was used?
Latest version found in DockerHub

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
Trying to use HTTPS and the cert and key generated using mkcert mentioned in the readme.md. When execute with --cert and --key, encounter the following error:

`Exit due to unhandled error: ENOENT: no such file or directory, open '127.0.0.1.pem'`

When try to run with only --cert param, it can start the container.

### Steps to reproduce the issue?

Executing the command:

`docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --cert "127.0.0.1.pem" --key "127.0.0.1-key.pem"`

### Have you found a mitigation/solution?
No

**Comment by edwin-huber** [comment]
Hi, 
what operating system are you using docker in, and what is the location of your cert and key files?

**Comment by bendanye** [comment]
Hi,
I am using Mac and the location of my cert and key files are in the download directory. I make sure i was in the download directory when i run the docker run command

**Comment by blueww** [comment]
@bendanye 

The cert file is on you local machine, to make docker can access the cert file, you need to map the folder contains the files to docker. (in following sample, I map local folder  `c:/azurite` to `/workspace` on docker )

The command work for on my machine is ("c:/azurite" contains the cert file): 
```
docker run -p 10000:10000 -v c:/azurite:/workspace   mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0  --cert /workspace/127.0.0.1.pem --key /workspace/127.0.0.1-key.pem 
```

**Comment by blueww** [comment]
@bendanye

I will close the issue as not receive your responds for 7+ days.
Feel free to contact us again if you need any further assistance on Azurite.
