### ISSUE TITLE
StorageServiceProperties is null when it shouldn't be

### ISSUE THREAD

**Issue by xt0rted** [Azure/Azurite#86]
This was found with version 1.4.0 and 1.4.1 of the Storage Explorer. When trying to delete a blob nothing happens (this does however work with the .net client since my webjobs are running just fine).

More discussion on this can be found in the following issues
https://github.com/Microsoft/AzureStorageExplorer/issues/60#issuecomment-417809216
https://github.com/Azure/azure-storage-node/issues/511

**Comment by edwin-huber** [comment]
This is now resolved in the dev branch...  
The next release should not be next week.

**Comment by XiaoningLiu** [comment]
Close this for legacy Azurite V2. Please use Azurite V3.
