### ISSUE TITLE
Missing error status codes according to MS Azure reference

### ISSUE THREAD

**Issue by MartinMikita** [Azure/Azurite#88]
Azurite is now missing error responses according to [the reference](https://docs.microsoft.com/en-us/rest/api/storageservices/status-and-error-codes2).

For example, if the requested container is missing (was not created), the `PUT BLOB` API requests fails only with the response code `404 Not found`, but it should be another error message:

PUT BLOB REST API: https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob
Common REST API Error codes: https://docs.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes

```
ContainerNotFound | Not Found (404) | The specified container does not exist.
```

Instead, it returns only
```
Response 404 Not Found
```

This response is hard to decode, that the Container does not exist.

**Comment by edwin-huber** [comment]
I think I fixed this a while back in the dev branch... if not, we should not have too much effort to correct it.

**Comment by edwin-huber** [comment]
resolved in v3
