### ISSUE TITLE
Support for Data Lake Storage Gen2 API

### ISSUE THREAD

**Issue by prasantakumar82** [Azure/Azurite#909]
### Which service(blob, file, queue, table) does this issue concern?
Blob Service

### Which version of the Azurite was used?
V3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
NA

### What problem was encountered?
Data Lake Storage Gen2 is built on top Blob Storage. What's the plan for supporting Data Lake Storage Gen2 API? 

### Steps to reproduce the issue?

NA

### Have you found a mitigation/solution?

NA

**Comment by blueww** [comment]
@prasantakumar82 

Thanks for raising the request!

We already have other issue to track datalake gen2 API, https://github.com/Azure/Azurite/issues/910.
I would like to link the 2 issues, and close this issue. Do you have any concern?

Besides that, if possible, please try to leverage your contacts with Azure, and reach to Azure AdlsGen2 team for your asks directly. We have once talked this ask with AdlsGen2 team, it's better they can get more direct feedbacks to better understand the scenario and importance.
