### ISSUE TITLE
List pagination is broken

### ISSUE THREAD

**Issue by ncabatoff** [Azure/Azurite#910]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
mcr.microsoft.com/azure-storage/azurite:latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
No idea

### What problem was encountered?
When using ListBlobsFlatSegment to list blobs and there are more blobs than MaxResults, we must do further requests so long as the returned NextMarker is NotDone.  I create 110 blobs, named 0..109.  I do a list with MaxResults=100, and get back blobs 0..99 and a NextMarker of 99.  I do another list using that marker, and get back no results, instead of the remaining 10 results.

### Steps to reproduce the issue?

I have an open PR which demonstrates the problem: https://github.com/hashicorp/vault/pull/12057
TestAzureBackend_ListPaging works with Azure, when I set the environment variables AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY.  It fails when running against Azurite, as described above, and as seen here: https://app.circleci.com/pipelines/github/hashicorp/vault/19003/workflows/775ca893-c275-474e-b32b-f6c4071671dc/jobs/240755
[azurite-debug-logs.txt.gz](https://github.com/Azure/Azurite/files/6810725/azurite-debug-logs.txt.gz)

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
@ncabatoff 
I can't repro the issue on Azurite 3.13.1, with API ListBlobFlatSegment from container. 
I also create 110 blobs, and list maxcount as 100, the returned continuation token is the last listout blob name. Then list with the continuation token， the rest 10 blobs will return. 

Would you please:
1. Confirm the Azurite version you are using. You can start docker with specific Azurite version.
2. Please attach the Azurite debug log.

**Comment by ncabatoff** [comment]
> Before we fix it, would you like to workaround it by adding some prefix like "blob" to the blob name to make it not only number.

Thanks for the suggestion.  But I don't want to modify Vault's prod behaviour just so that it can test using Azurite.

**Comment by blueww** [comment]
@ncabatoff 

The fix PR has been merged. So this should be fixed in the next release.

**Comment by ncabatoff** [comment]
Thanks @blueww!  I guess since one just came out that'll be a month or two from now?

**Comment by blueww** [comment]
@ncabatoff 
We can't give the exact date now. Might be 1-2 weeks but can't make sure.

**Comment by ncabatoff** [comment]
Perfectly understandable.  I realized that I can use your workaround to modify my test just fine, without impacting prod, so thanks again for that.

**Comment by blueww** [comment]
Azurite 3.14.0 is already released with the fix.
