### ISSUE TITLE
[Table] Phase 3 Feature - HTTPS

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/Azurite#947]

**Comment by brandonh-msft** [comment]
Any ETA on this? As our team migrates to Managed Identity for all connections which support it, Azurite's lack of HTTPS cramps the local developer experience.

**Comment by blueww** [comment]
@brandonh-msft 

Azure Table service already supported https protocol.  
Please try it with latest Azurite version, and feel free to let us know if you see any issue.

**Comment by brandonh-msft** [comment]
Hm, what about HTTPS for blobs & queues then? I am using the Azurite which ships inside VS (Preview, 17.6); not a separate install. Reports it is 3.21.0.

When I tried yesterday to use https endpoints for blob, queue, table the local MI endpoint said it was getting 404s back and Azurite wasn't logging any hits.

**Comment by blueww** [comment]
@brandonh-msft 

Blob/Queue/Table should all work with https on 3.21.0.

As you see "404s back and Azurite wasn't logging any hits" , it looks the request is not sent to Azurite. 
Please check the connection string you use is correct (refer [link](https://github.com/Azure/Azurite#https-connection-strings)), and only Azurite list on the specific port.

**Comment by brandonh-msft** [comment]
> Please check the connection string you use is correct

I want to make sure my ask is clear - I'm _not_ using connection strings. I'm using Managed Identity which takes URLs (so am doing `https://localhost...`)

Is the expectations that these should all work as well?

**Comment by blueww** [comment]
@brandonh-msft 

If you are using Oauth, please make sure you are using correct table endpoint.

So which Table endpoint are your using?
And what's the command you start Azurite? (hide credential if any)

I can connect to Azurite with Oauth credential successfully when start Azurite with `azurite --cert 127.0.0.1.pem --key 127.0.0.1-key.pem --oauth basic`, and connect to it with table endpoint as "https://127.0.0.1:10002/devstoreaccount1".

**Comment by brandonh-msft** [comment]
core problem here is Visual Studio's the one launching azurite - not me directly. And it doesn't allow customization of the parameters. So appears I need to do the config and launch azurite outside VS in order for the scenario to work.

**Comment by blueww** [comment]
@brandonh-msft 
Feel free to let us know if you still see any problem when launch Azurite with the specific parameter outside Visual Studio.

BTW, if you need assistance from visual studio team, this doc has the details on how to report a VS feedback issue : [https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fide%2Fhow-to-report-a-problem-with-visual-studio%3Fview%3Dvs-2022&data=05%7C01%7Cweiwei%40microsoft.com%7C018bab47753441a4efbc08da37aa53e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883501988809333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O8MtF%2Ft%2B5s7xXFJPiRAQzI7qYU9B3lWj0rXclmmUvXE%3D&reserved=0)

**Comment by brandonh-msft** [comment]
yup i gave feedback for them on this. thanks!
