### ISSUE TITLE
Exception parsing ETag of Azurite response

### ISSUE THREAD

**Issue by capoitas** [Azure/Azurite#95]
We are using the latest version of the Docker Azurite. We can access it through the Azure Explorer but...

Azurite is returning a 200 response with: 
{ETag: W/"75-mAoh3qooM6Mzsi98Dku2rmIXONw"}

As opposed to the same response coming from the real Azure with the format: 
{ETag: W/"datetime'2018-09-07T14%3A42%3A56.757613Z'"}

Is this a know issue, a new issue or are we doing something wrong?

**Comment by GSingha** [comment]
I am facing the same issue. When the change will be released?

**Comment by edwin-huber** [comment]
eTag checking and formatting now in v3
