### ISSUE TITLE
Internal error when copying blobs from Azure Storage to Azurite

### ISSUE THREAD

**Issue by tdwright** [Azure/Azurite#96]
Hi - big fan of Azurite. I'm on Windows, but for me Azurite > Storage Emulator.

The only problem I'm having is when I want to copy files from a real Azure Storage account to my local Azurite instance using Storage Explorer.

I can download / upload files without problem, but when I try to copy / paste files directly I get:

> \*Internal Azurite Error\*: Request: x-ms-copy-source was not in the expected format

![Screenshot showing that copy fails, but upload succeeds](https://user-images.githubusercontent.com/95890/46053321-9b975f00-c185-11e8-8c96-ca817025600c.png)

Any idea what's going on here?

**Comment by tdwright** [comment]
Ah, I see. Thanks for clarifying @XiaoningLiu 😄

**Comment by marshallpenn** [comment]
So how can we copy the blobs into Azurite to do some testing?

**Comment by XiaoningLiu** [comment]
@marshallpenn You mean copy from external resources into Azurite? Azurite V3 currently doesn't support that, but it maybe a valid scenario. Can you describe your usage pattern with that?

**Comment by marshallpenn** [comment]
In the same way you can copy files into Azure Storage Manager, like copying into another file folder.
