### ISSUE TITLE
azurite.location -> ENOENT: no such file or directory, access

### ISSUE THREAD

**Issue by Sti2nd** [Azure/Azurite#962]
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

VS Code extension

### What's the Node.js version?

14.17.0

### What problem was encountered?

```txt
Start Azurite Blob Service error: ENOENT: no such file or directory, access 'C:\Users\USERNAME\AppData\Local\Programs\Microsoft VS Code\.azurite'
```

### Steps to reproduce the issue?

1. In the "azurite.location" setting in VS Code, specify a folder location relative to the workspace.
2. Run the command `Azurite: Start` from the command palette.

### Have you found a mitigation/solution?

The solution is to support specifying a location relative to the workspace, which is apparently not supported. So this is a feature request.

Related: #756 , #391

**Comment by blueww** [comment]
@Sti2nd 
 Thanks for reporting the issue!
As the request is already tracked in the 2 issues you mentioned, do you mind to link this issue with the 2 existing issue, and close this one? 
Feel free to let us know if you have any concern.
