### ISSUE TITLE
Add support for BlobBatch operations

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/Azurite#967]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
13.3.1

### What problem was encountered?
No support for `BlobBatch` operations

### Steps to reproduce the issue?

```c#
BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
    BlobBatchClient batchClient = new BlobBatchClient(blobServiceClient);
    
    List<string> blobNames = new List<string>()
    {
        "blob1"
        "blob2
    };
    BlobBatch batch = new BlobBatch(batchClient);
    foreach (var blobName in blobNames)
    {
        batch.DeleteBlob(containerName, blobName, DeleteSnapshotsOption.IncludeSnapshots);
    }

    await batchClient.SubmitBatchAsync(batch);
```

### Have you found a mitigation/solution?

Only to use a real storage account

**Comment by blueww** [comment]
@SeanFeldman 
Thanks for raising the issue!
We already have the request tracking in https://github.com/Azure/Azurite/issues/287.

I would like to link this issue to the original one, and close this.
Do you have any concern?

Besides that, Azurite welcome contribution!
It would be great if you can raise PR to adding the blob batch support.
