### ISSUE TITLE
Not able to create queue from storage explorer

### ISSUE THREAD

**Issue by an-prog** [Azure/Azurite#969]
### Which service(blob, file, queue, table) does this issue concern?
queue
### Which version of the Azurite was used?
Latest
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub
### What's the Node.js version?
7.13.0
### What problem was encountered?
Not able to create queue
### Steps to reproduce the issue?
Run docker container for azurite and then from storage explorer trying to create the queue in local 
If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10001/devstoreaccount1/test1?timeout=30 failed, reason: socket hang up",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET",
  "stack": "FetchError: request to http://127.0.0.1:10001/devstoreaccount1/test1?timeout=30 failed, reason: socket hang up\n    at ClientRequest.<anonymous> (/private/var/folders/sc/thl48_69397738nwd1phphhw0000gn/T/AppTranslocation/EE90A0FF-9572-4386-963A-7AD4EC539A53/d/Microsoft Azure Storage Explorer 2.app/Contents/Resources/app/node_modules/node-fetch/lib/index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketOnEnd (_http_client.js:453:9)\n    at Socket.emit (events.js:322:22)\n    at endReadableNT (_stream_readable.js:1187:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
not yet

**Comment by blueww** [comment]
@an-prog 
I can't repro this issue with latest Azurite.

Would you please share:
1. the debug log of Azurite. The above log is from client side, not from Azurite. We need debug log to investigate the issue.
2. The command to start Azurite with docker 
3. Can you run other API with Azurite, like list queue, list blob container ?

**Comment by an-prog** [comment]
hello
I am able to run the other 2 services successfully.

Command used to start docker:
docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 -v
~/Documents/tmp/azurite:/workspace mcr.microsoft.com/azure-storage/azurite
azurite -l /workspace -d /workspace/debug.log --blobPort 10000 --blobHost
0.0.0.0 --queuePort 10001 --queueHost 0.0.0.0 --tablePort 10002 --tableHost
0.0.0.0 --loose --skipApiVersionCheck

Azurite Blob service is starting at http://0.0.0.0:10000
Azurite Blob service is successfully listening at http://0.0.0.0:10000
Azurite Queue service is starting at http://0.0.0.0:10001
Azurite Queue service is successfully listening at http://0.0.0.0:10001
Azurite Table service is starting at http://0.0.0.0:10002
Azurite Table service is successfully listening at http://0.0.0.0:10002
172.17.0.1 - - [28/Jul/2021:04:33:27 +0000] "GET
/devstoreaccount1?restype=account&comp=properties HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:35:46 +0000] "GET
/devstoreaccount1?restype=service&comp=properties HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:35:52 +0000] "GET
/devstoreaccount1/?comp=properties&restype=service&_=1627446952861
HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:37:12 +0000] "GET
/devstoreaccount1?include=metadata&comp=list HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:37:12 +0000] "GET
/devstoreaccount1/%24logs?restype=container HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:37:16 +0000] "PUT
/devstoreaccount1/devstoreaccount1?restype=container HTTP/1.1" 201 -
172.17.0.1 - - [28/Jul/2021:04:37:16 +0000] "GET
/devstoreaccount1/devstoreaccount1?restype=container HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:37:16 +0000] "GET
/devstoreaccount1?where=%22fakeTagKey%22%3D%27fakeTagValue%27&comp=blobs
HTTP/1.1" 400 -
172.17.0.1 - - [28/Jul/2021:04:37:16 +0000] "GET
/devstoreaccount1/devstoreaccount1?restype=account&comp=properties
HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:37:16 +0000] "GET
/devstoreaccount1?where=%22fakeTagKey%22%3D%27fakeTagValue%27&comp=blobs
HTTP/1.1" 400 -
172.17.0.1 - - [28/Jul/2021:04:37:17 +0000] "GET
/devstoreaccount1/devstoreaccount1?delimiter=%2F&maxresults=1000&include=metadata&restype=container&comp=list
HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:50:05 +0000] "GET
/devstoreaccount1?restype=account&comp=properties HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:51:24 +0000] "GET
/devstoreaccount1?restype=account&comp=properties HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:51:50 +0000] "GET
/devstoreaccount1?include=metadata&comp=list HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:51:50 +0000] "GET
/devstoreaccount1/%24logs?restype=container HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:51:50 +0000] "GET
/devstoreaccount1/devstoreaccount1?restype=container HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:51:50 +0000] "GET
/devstoreaccount1?restype=service&comp=properties HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:55:59 +0000] "GET
/devstoreaccount1?include=metadata&comp=list HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:55:59 +0000] "GET
/devstoreaccount1/%24logs?restype=container HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:55:59 +0000] "GET
/devstoreaccount1/devstoreaccount1?restype=container HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:56:00 +0000] "GET
/devstoreaccount1?restype=service&comp=properties HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:56:02 +0000] "GET
/devstoreaccount1/devstoreaccount1?restype=account&comp=properties
HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:56:02 +0000] "GET
/devstoreaccount1?where=%22fakeTagKey%22%3D%27fakeTagValue%27&comp=blobs
HTTP/1.1" 400 -
172.17.0.1 - - [28/Jul/2021:04:56:05 +0000] "DELETE
/devstoreaccount1/devstoreaccount1?restype=container HTTP/1.1" 202 -
172.17.0.1 - - [28/Jul/2021:04:56:14 +0000] "GET
/devstoreaccount1?restype=account&comp=properties HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables?%24top=25&_=1627448178833 HTTP/1.1" 200 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsHourSecondaryTransactionsTable%27)?_=1627448178854
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsHourPrimaryTransactionsQueue%27)?_=1627448178848
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsMinutePrimaryTransactionsBlob%27)?_=1627448178849
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsMinutePrimaryTransactionsFile%27)?_=1627448178849
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsHourPrimaryTransactionsTable%27)?_=1627448178848
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsHourPrimaryTransactionsBlob%27)?_=1627448178846
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsHourPrimaryTransactionsFile%27)?_=1627448178847
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsMinutePrimaryTransactionsTable%27)?_=1627448178852
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsMinutePrimaryTransactionsQueue%27)?_=1627448178853
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsHourSecondaryTransactionsQueue%27)?_=1627448178855
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsHourSecondaryTransactionsBlob%27)?_=1627448178853
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsMinuteSecondaryTransactionsBlob%27)?_=1627448178855
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsHourSecondaryTransactionsFile%27)?_=1627448178854
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsCapacityBlob%27)?_=1627448178858
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsMinuteSecondaryTransactionsFile%27)?_=1627448178856
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsMinuteSecondaryTransactionsQueue%27)?_=1627448178858
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:18 +0000] "GET
/devstoreaccount1/Tables(%27$MetricsMinuteSecondaryTransactionsTable%27)?_=1627448178856
HTTP/1.1" 404 -
172.17.0.1 - - [28/Jul/2021:04:56:23 +0000] "POST /devstoreaccount1/Tables
HTTP/1.1" 204 -
172.17.0.1 - - [28/Jul/2021:04:56:25 +0000] "GET
/devstoreaccount1/test?%24top=1000 HTTP/1.1" 200 -

**Comment by blueww** [comment]
@an-prog
The above log is not debug log. 
The debug log should be the file specified by  "-d /workspace/debug.log".

Besides that, seems there are no request to Queue endpoint in the above log (still need debug log to confirm.)
If so, would you please check the Queue Endpoint you specified in the client is correct, and the port 10001 on you machine is not occupied by other process.

**Comment by blueww** [comment]
@an-prog 
Since not receive message from you for a long time, I will close this  issue.
Feel free to contact us again if need any more assistance on Azurite.
