### ISSUE TITLE
Forbidden when accessing in Azure Storage Explorer

### ISSUE THREAD

**Issue by cocowalla** [Azure/Azurite#97]
I'm trying to use Azure Storage Explorer with Azurite, but when it tries to load blobs, queues or tables it pops up a dialog with:

```
Unable to retrieve child resources.

Details: Forbidden
```

When connecting in Storage Explorer, I've tried both using the [hardcoded connection string](https://github.com/Azure/Azurite/blob/9413bd7af4da7ffe24457180541ad1c6d2da8d10/doc/azure-storage-node_tdd.md), and using the `Attach to a local emulator` option.

**Comment by edwin-huber** [comment]
hi,

this will be fixed in the next release.
You can get it to work now by switching to the dev branch of Azurite.

**Comment by edwin-huber** [comment]
now resolved in current release of master branch on v3
