### ISSUE TITLE
copy blob status never changes from pending to success

### ISSUE THREAD

**Issue by kuba-lilz** [Azure/Azurite#98]
When trying to copy a blob from one container to another, the copy property status never changes from `pending` to `success`, even though blob gets correctly copied.

I'm using `arafato/azurite:2.6.5` docker container, and here's a simple Python script illustrating the problem:

```python
import time

import azure.storage.blob


def main():

    azure_blob_config = {
        "account_name": "devstoreaccount1",
        "is_emulated": True,
        "account_key": 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='
    }

    block_blob_service = azure.storage.blob.BlockBlobService(**azure_blob_config)

    source_container = "source"
    destination_container = "destination"
    blob_name = "some_blob.txt"

    block_blob_service.create_container(source_container)
    block_blob_service.create_container(destination_container)

    block_blob_service.create_blob_from_text(
        container_name="source", blob_name=blob_name, text="foo")

    source_blob_url = block_blob_service.make_blob_url(source_container, blob_name)
    copy_property = block_blob_service.copy_blob(destination_container, blob_name, source_blob_url)

    time.sleep(1)

    while copy_property.status != "success":

        print("Waiting for blob {} copy to finish...".format(blob_name))
        copy_property = block_blob_service.copy_blob(destination_container, blob_name, source_blob_url)
        time.sleep(1)

        print(copy_property.status)

    print(copy_property.status)


if __name__ == "__main__":
    main()
```

This code outputs a continuous stream of
```
Waiting for blob some_blob.txt copy to finish...
pending
Waiting for blob some_blob.txt copy to finish...
pending
Waiting for blob some_blob.txt copy to finish...
pending
Waiting for blob some_blob.txt copy to finish...
pending
```
when used with Azurite. The same code works without problems when changing `azure_blob_config` to point to a real azure storage container.

Here's a sample Azurite's output when running above code:
```
PUT /devstoreaccount1/destination/some_blob.txt 202 3.806 ms - 0
PUT /devstoreaccount1/destination/some_blob.txt 202 2.168 ms - 0
PUT /devstoreaccount1/destination/some_blob.txt 202 1.181 ms - 0
PUT /devstoreaccount1/destination/some_blob.txt 202 3.024 ms - 0
PUT /devstoreaccount1/destination/some_blob.txt 202 2.798 ms - 0
PUT /devstoreaccount1/destination/some_blob.txt 202 2.576 ms - 0
PUT /devstoreaccount1/destination/some_blob.txt 202 2.749 ms - 0
```

Is there some problem with my approach? Am I running into a limitation of the emulator?

**Comment by edwin-huber** [comment]
hi @kuba-lilz ,

thanks for reporting!
There are still some features of the APIs which we have not implemented.
We are currently looking at better options to address the API coverage.

I'll mark this as an issue which we will hopefully get around to addressing.

**Comment by edwin-huber** [comment]
Sorry, I also noticed that you are using the docker container... but sadly this issue is not resolved in the latest release (not yet dockerized).
That said, we are hoping to release Azurite to a different container registry soon.
@pdressel would you maybe have time to look at this?

**Comment by pdressel** [comment]
Sure, I will get back to you on this 😄

**Comment by XiaoningLiu** [comment]
Close this for legacy Azurite V2. Please use Azurite V3.
