### ISSUE TITLE
Azurite doesn't copy blob when using putBlobFromUrl API

### ISSUE THREAD

**Issue by stingster** [Azure/Azurite#991]
### Service
* Blob Service

### Version
* Azurite V3.14.0

### Azurite source
* mcr.microsoft.com/azure-storage/azurite:3.14.0

### Environment
* Java API  V12.13.0

### Symptom
* The destination blob is an empty String

### Steps to reproduce the issue
* use Azure Blob Store Client V12.13.0 for Java
* run azurite in a container, in secure mode, from mcr.microsoft.com/azure-storage/azurite:3.14.0
* deposit blob using [Put Blob Api](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob)
* copy blob using [Put Blob from Url Api](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url)
* retrieve destination blob using [Get Blob Api](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob)

### Have you found a mitigation/solution
Although it works if [Copy From Url Api](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) is used it is not an option for us because that has higher latency.

**Comment by blueww** [comment]
@stingster 

Would you please share the Azurite debug log for investigation?

**Comment by blueww** [comment]
@stingster 
Thanks for the update!

`Put Blob From URL` is still not supported by Azurite, see detail in https://github.com/Azure/Azurite#support-matrix
As we already has issue to follow up it as https://github.com/Azure/Azurite/issues/852, so would you like to close this issue.

**Comment by blueww** [comment]
@stingster

I closed this issue as we already have an issue to track `Put Blob From URL`, and not hear from you for a long time.
Feel free to contact us again if you need any further assistance on azurite
