### ISSUE TITLE
Are rscc, rscd, rsce, etc. in SAS tokens supported by Azurite?

### ISSUE THREAD

**Issue by epicfaace** [Azure/Azurite#997]
### Which service(blob, file, queue, table) does this issue concern?

Blob 

### Which version of the Azurite was used?

3.14.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Docker

### What's the Node.js version?

10

### What problem was encountered?

The feature I'm trying to use is rscc, rscd, rsce, etc. in SAS tokens to set headers dynamically -- see https://docs.microsoft.com/en-us/rest/api/storageservices/service-sas-examples -- it doesn't seem to work with Azurite, though, is this feature currently supported?

**Comment by blueww** [comment]
The fix already released in Azurite 3.14.2.

**Comment by epicfaace** [comment]
Thank you!
